#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

namespace System { class String; }

#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_CREATE_OFFSET UNITYSDK_OFFSET(0xC9A38D0)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ENTERTIPSTEXTID_OFFSET UNITYSDK_OFFSET(0xC9A5640)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ERRORTIPSTEXTID_OFFSET UNITYSDK_OFFSET(0xC9A5680)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_FLUTEID_OFFSET UNITYSDK_OFFSET(0xC9A55C0)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ICONPATHENTERTIPS_OFFSET UNITYSDK_OFFSET(0xC9A55E0)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ICONPATHERRORTIPS_OFFSET UNITYSDK_OFFSET(0xC9A5620)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ICONPATHINPUTTIPS_OFFSET UNITYSDK_OFFSET(0xC9A5600)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_INPUTTIPSTEXTID_OFFSET UNITYSDK_OFFSET(0xC9A5660)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ENTERTIPSTEXTID_OFFSET UNITYSDK_OFFSET(0xC9A5650)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ERRORTIPSTEXTID_OFFSET UNITYSDK_OFFSET(0xC9A5690)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_FLUTEID_OFFSET UNITYSDK_OFFSET(0xC9A55D0)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ICONPATHENTERTIPS_OFFSET UNITYSDK_OFFSET(0xC9A55F0)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ICONPATHERRORTIPS_OFFSET UNITYSDK_OFFSET(0xC9A5630)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ICONPATHINPUTTIPS_OFFSET UNITYSDK_OFFSET(0xC9A5610)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_INPUTTIPSTEXTID_OFFSET UNITYSDK_OFFSET(0xC9A5670)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xC9A5510)
#define RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA__INIT_OFFSET UNITYSDK_OFFSET(0xC9A5520)

namespace RPG::Client::LittleGame::FiveDim
{
	inline static constexpr unsigned int FiveDimFluteNewGuideData_TypeDefinitionIndex = 73269;

	class FiveDimFluteNewGuideData : public ::System::Object
	{
	public:
		::System::String* _IconPathEnterTips_k__BackingField; // 0x10
		::System::String* _IconPathInputTips_k__BackingField; // 0x18
		::System::String* _IconPathErrorTips_k__BackingField; // 0x20
		::RPG::Client::TextID _ErrorTipsTextID_k__BackingField; // 0x28
		::System::UInt32 _FluteID_k__BackingField; // 0x38
		::RPG::Client::TextID _InputTipsTextID_k__BackingField; // 0x40
		::RPG::Client::TextID _EnterTipsTextID_k__BackingField; // 0x50

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::LittleGame::FiveDim::FiveDimFluteNewGuideData* Create(::System::UInt32 a1)
		{
			return ((::RPG::Client::LittleGame::FiveDim::FiveDimFluteNewGuideData*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_CREATE_OFFSET))(a1);
		}

		::System::Void _Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA__INIT_OFFSET))(this);
		}

		::System::UInt32 get_FluteID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_FLUTEID_OFFSET))(this);
		}

		::System::Void set_FluteID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_FLUTEID_OFFSET))(this, a1);
		}

		::System::String* get_IconPathEnterTips()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ICONPATHENTERTIPS_OFFSET))(this);
		}

		::System::Void set_IconPathEnterTips(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ICONPATHENTERTIPS_OFFSET))(this, a1);
		}

		::System::String* get_IconPathInputTips()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ICONPATHINPUTTIPS_OFFSET))(this);
		}

		::System::Void set_IconPathInputTips(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ICONPATHINPUTTIPS_OFFSET))(this, a1);
		}

		::System::String* get_IconPathErrorTips()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ICONPATHERRORTIPS_OFFSET))(this);
		}

		::System::Void set_IconPathErrorTips(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ICONPATHERRORTIPS_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_EnterTipsTextID()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ENTERTIPSTEXTID_OFFSET))(this);
		}

		::System::Void set_EnterTipsTextID(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ENTERTIPSTEXTID_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_InputTipsTextID()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_INPUTTIPSTEXTID_OFFSET))(this);
		}

		::System::Void set_InputTipsTextID(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_INPUTTIPSTEXTID_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_ErrorTipsTextID()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_GET_ERRORTIPSTEXTID_OFFSET))(this);
		}

		::System::Void set_ErrorTipsTextID(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LITTLEGAME_FIVEDIM_FIVEDIMFLUTENEWGUIDEDATA_SET_ERRORTIPSTEXTID_OFFSET))(this, a1);
		}
	};
}
