#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_4608E37A1B3D374A_23.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/Client/TransitionMode.h"
#include "unitysdk/RPG/GameCore/AdvEnterBattleSelectTargetType.h"
#include "unitysdk/RPG/GameCore/AdventureAnimStateType.h"
#include "unitysdk/RPG/GameCore/AdventureModifierBehaviorFlag.h"
#include "unitysdk/RPG/GameCore/AdventureSkillType.h"
#include "unitysdk/RPG/GameCore/BattlePostureType.h"
#include "unitysdk/RPG/GameCore/EntityType.h"
#include "unitysdk/RPG/GameCore/FixPoint.h"
#include "unitysdk/RPG/GameCore/FloorType.h"
#include "unitysdk/RPG/GameCore/GameModeType.h"
#include "unitysdk/RPG/GameCore/MapCameraType.h"
#include "unitysdk/RPG/GameCore/MazeBuffType.h"
#include "unitysdk/RPG/GameCore/MonsterRank.h"
#include "unitysdk/RPG/GameCore/PlaneType.h"
#include "unitysdk/RPG/GameCore/PropType.h"
#include "unitysdk/RPG/GameCore/PropertyModifyFunction.h"
#include "unitysdk/RPG/GameCore/StageType.h"
#include "unitysdk/Struct_2_591DD46947F040CB.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/System/Object.h"
#include "unitysdk/UnityEngine/Quaternion.h"
#include "unitysdk/UnityEngine/Vector2.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_380;
class Class_1_0AD6129525BF5F86;
class Class_1_0F1ECB28664B98E3;
class Class_1_1826B7898EFE06BA;
class Class_1_4CEDF380BFE8D93F;
class Class_1_64D890C466F37235;
class Class_1_72FF3C03F0F06A80;
class Class_1_A2D8E5AB4B623162;
class Class_1_AFC3C7A272BDF32C;
class Class_1_CC76D1702CC17C09_5;
class Class_2_A171F95E026CBAD1;
class Class_3_07C3C4D2990C49EE;
namespace Proto { class SceneEntityInfo; }
namespace RPG::Client { class AdventurePhase; }
namespace RPG::Client { class EraFlipperManager; }
namespace RPG::Client { class FMSystem; }
namespace RPG::Client { class MapDef; }
namespace RPG::Client { class MapEntityDef; }
namespace RPG::Client { class MapNpc; }
namespace RPG::Client { class MapNpcDef; }
namespace RPG::Client { class MapPropDef; }
namespace RPG::Client { class MapRotationInfo; }
namespace RPG::Client { class RuntimeGroupManager; }
namespace RPG::Client { class TeamManager; }
namespace RPG::GameCore { class AdventureAnimationMoveRange; }
namespace RPG::GameCore { class AdventureAttackDetectShapeConfig; }
namespace RPG::GameCore { class AdventureAttackDetectSummonUnitTriggerConfig; }
namespace RPG::GameCore { class AdventureBehaviorConfig; }
namespace RPG::GameCore { class AdventureBuffEvent; }
namespace RPG::GameCore { class AdventureDyingParam; }
namespace RPG::GameCore { class AdventureHitConfig; }
namespace RPG::GameCore { class AdventureModifierInstance; }
namespace RPG::GameCore { class AdventurePlayerRow_AdventurePlayerCommonRowWrap; }
namespace RPG::GameCore { class AdventureStatic_WallDetectParams; }
namespace RPG::GameCore { class AnchorInfo; }
namespace RPG::GameCore { class AvatarSkillRow; }
namespace RPG::GameCore { class CharacterModelScaleEventParam; }
namespace RPG::GameCore { class CustomMazeBattleTransitionConfig; }
namespace RPG::GameCore { class DynamicString; }
namespace RPG::GameCore { class EntityManager; }
namespace RPG::GameCore { class EntitySpawnConfig; }
namespace RPG::GameCore { class GameEntity; }
namespace RPG::GameCore { class GameEntityList; }
namespace RPG::GameCore { class GameWorld; }
namespace RPG::GameCore { class HoyoTagContainer; }
namespace RPG::GameCore { class LevelCurveInfo; }
namespace RPG::GameCore { class LevelCurveInstance; }
namespace RPG::GameCore { class LevelEntityVCameraConfig; }
namespace RPG::GameCore { class LevelNPCInfo; }
namespace RPG::GameCore { class NPCComponent; }
namespace RPG::GameCore { class PlayerLockTargetComponent; }
namespace RPG::GameCore { class PostureTypeTasksConfig; }
namespace RPG::GameCore { class PropComponent; }
namespace RPG::GameCore { class RuntimeGroupInfo; }
namespace RPG::GameCore { class StageRow; }
namespace RPG::GameCore { class TargetEvaluator; }
namespace RPG::GameCore { class TaskConfig; }
namespace RPG::GameCore { class TaskContext; }
namespace System { class String; }
namespace System { class Type; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class IEnumerable_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class Collider; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Transform; }

#define RPG_GAMECORE_ADVENTURESTATIC_ACQUIREADVSKILLSERVERRSPCHECKRECORDS_OFFSET UNITYSDK_OFFSET(0xD9890F0)
#define RPG_GAMECORE_ADVENTURESTATIC_ADDADVSKILLSERVERRSPCHECKRECORDS_OFFSET UNITYSDK_OFFSET(0xD9891D0)
#define RPG_GAMECORE_ADVENTURESTATIC_APPLYLEVELCURVE_OFFSET UNITYSDK_OFFSET(0xD9792B0)
#define RPG_GAMECORE_ADVENTURESTATIC_CALCEFFECTIVEHITENTITYLIST_OFFSET UNITYSDK_OFFSET(0xD988090)
#define RPG_GAMECORE_ADVENTURESTATIC_CALCTARGETLISTENTERSUMMONUNITTRIGGER_OFFSET UNITYSDK_OFFSET(0xD987F10)
#define RPG_GAMECORE_ADVENTURESTATIC_CALCULATEATTACKRANGEENEMYLIST_OFFSET UNITYSDK_OFFSET(0xD98AF80)
#define RPG_GAMECORE_ADVENTURESTATIC_CANPUTMAPPOSESWITCHER_OFFSET UNITYSDK_OFFSET(0xD986AD0)
#define RPG_GAMECORE_ADVENTURESTATIC_CANSHOWENTITYICON_OFFSET UNITYSDK_OFFSET(0xD98E030)
#define RPG_GAMECORE_ADVENTURESTATIC_CANSTARTLEVELGRAPH_OFFSET UNITYSDK_OFFSET(0xD980CA0)
#define RPG_GAMECORE_ADVENTURESTATIC_CHECKLOCALPLAYERCANINTERACTOPTION_OFFSET UNITYSDK_OFFSET(0xD98CCB0)
#define RPG_GAMECORE_ADVENTURESTATIC_COMMONPROCESSBEFORETRIGGERBATTLE_OFFSET UNITYSDK_OFFSET(0xD97E120)
#define RPG_GAMECORE_ADVENTURESTATIC_CONVERTPLANETYPETOGAMEMODETYPE_OFFSET UNITYSDK_OFFSET(0xD981E00)
#define RPG_GAMECORE_ADVENTURESTATIC_CREATELEVELCURVE_OFFSET UNITYSDK_OFFSET(0xD978EF0)
#define RPG_GAMECORE_ADVENTURESTATIC_DISABLEALLMONSTERAI_OFFSET UNITYSDK_OFFSET(0xD97C520)
#define RPG_GAMECORE_ADVENTURESTATIC_ENTITYENTERAVAILABLE_OFFSET UNITYSDK_OFFSET(0xD98E790)
#define RPG_GAMECORE_ADVENTURESTATIC_ENTITYLEAVEAVAILABLE_OFFSET UNITYSDK_OFFSET(0xD98E510)
#define RPG_GAMECORE_ADVENTURESTATIC_EVALUATEMAZEBUFFDESCPARAM_OFFSET UNITYSDK_OFFSET(0xD980160)
#define RPG_GAMECORE_ADVENTURESTATIC_FILLNPCLISTBYGROUP_OFFSET UNITYSDK_OFFSET(0xD97B870)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDENTITYBYGROUPENTITYID_OFFSET UNITYSDK_OFFSET(0xD979DA0)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDENTITYBYSERVERENTITYID_OFFSET UNITYSDK_OFFSET(0xD979C30)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDLEVELCURVEINFO_OFFSET UNITYSDK_OFFSET(0xD979030)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDMAZESKILLABILITYBYAVATARID_OFFSET UNITYSDK_OFFSET(0xD93CDB0)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDPROPBYGROUPID_OFFSET UNITYSDK_OFFSET(0xD97A390)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDPROPENTITYBYGROUPID_OFFSET UNITYSDK_OFFSET(0xD97A2E0)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDPROP_OFFSET UNITYSDK_OFFSET(0xD979EA0)
#define RPG_GAMECORE_ADVENTURESTATIC_FINDSKILLABILITYBYSERVERENTITYID_OFFSET UNITYSDK_OFFSET(0xD93CB50)
#define RPG_GAMECORE_ADVENTURESTATIC_GENERATEDYNAMICBUFFPARAMS_OFFSET UNITYSDK_OFFSET(0xD991100)
#define RPG_GAMECORE_ADVENTURESTATIC_GET2DPOSITIONINMAPBACKGROUND_OFFSET UNITYSDK_OFFSET(0xD980AB0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETABILITYTARGETSERVERENTITYID_1_OFFSET UNITYSDK_OFFSET(0xD97C1B0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETABILITYTARGETSERVERENTITYID_OFFSET UNITYSDK_OFFSET(0xD97C060)
#define RPG_GAMECORE_ADVENTURESTATIC_GETACTUALTEAMLEADERSERVERENTITYID_OFFSET UNITYSDK_OFFSET(0xD980430)
#define RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREBASICINFO_OFFSET UNITYSDK_OFFSET(0xD990930)
#define RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREMAPDEF_OFFSET UNITYSDK_OFFSET(0xD984ED0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREMAPRUNTIMEID_OFFSET UNITYSDK_OFFSET(0xD985CC0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREPHASE_OFFSET UNITYSDK_OFFSET(0xD980F00)
#define RPG_GAMECORE_ADVENTURESTATIC_GETANCHORINFOBYCUSTOMSTRING_OFFSET UNITYSDK_OFFSET(0xD978710)
#define RPG_GAMECORE_ADVENTURESTATIC_GETAREAANCHORNAME_OFFSET UNITYSDK_OFFSET(0xD983D30)
#define RPG_GAMECORE_ADVENTURESTATIC_GETAREABYNAVMESHMASK_OFFSET UNITYSDK_OFFSET(0xD982780)
#define RPG_GAMECORE_ADVENTURESTATIC_GETATTACHPOINTTRANSFORM_OFFSET UNITYSDK_OFFSET(0xD981B20)
#define RPG_GAMECORE_ADVENTURESTATIC_GETAVATARBATTLETRANSITIONCONFIG_OFFSET UNITYSDK_OFFSET(0xD97E5A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETAVATARNAMEINDEXFROMJSONPATH_OFFSET UNITYSDK_OFFSET(0xD9915F0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETBATTLEAREANAMEBYROWID_OFFSET UNITYSDK_OFFSET(0xD9836A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETBATTLEASSISTMONSTERLIST_OFFSET UNITYSDK_OFFSET(0xD97C260)
#define RPG_GAMECORE_ADVENTURESTATIC_GETBEHAVIORCONFIG_OFFSET UNITYSDK_OFFSET(0xD98D380)
#define RPG_GAMECORE_ADVENTURESTATIC_GETBELONGINGADVSKILLTYPE_OFFSET UNITYSDK_OFFSET(0xD989540)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCOLLIDERCENTER_OFFSET UNITYSDK_OFFSET(0xD981960)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCOLLIDERHEIGHT_OFFSET UNITYSDK_OFFSET(0xD981850)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTADVENTUREMAPINFO_1_OFFSET UNITYSDK_OFFSET(0xD98D860)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTADVENTUREMAPINFO_OFFSET UNITYSDK_OFFSET(0xD98D630)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTFASTDELIVERAIMFINISH_OFFSET UNITYSDK_OFFSET(0xD98E390)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTFASTDELIVERFINISHSTATE_OFFSET UNITYSDK_OFFSET(0xD98E250)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTFASTDELIVERFOCUSTARGET_OFFSET UNITYSDK_OFFSET(0xD98E2B0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTGAMEMODETYPE_OFFSET UNITYSDK_OFFSET(0xD981F80)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTMAPNAME_OFFSET UNITYSDK_OFFSET(0xD9820A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTMAZEMPVALUEFORDISPLAY_OFFSET UNITYSDK_OFFSET(0xD97BBA0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTMAZEMPVALUE_OFFSET UNITYSDK_OFFSET(0xD9737A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTSKILLINDEX_OFFSET UNITYSDK_OFFSET(0xD98AEA0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETCURVERIFYSERVERENTITYID_OFFSET UNITYSDK_OFFSET(0xD986600)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITIESBYGROUP_OFFSET UNITYSDK_OFFSET(0xD97A5E0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITYBYRUNTIMEID_OFFSET UNITYSDK_OFFSET(0xD97AAC0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITYBYUNIQUENAME_OFFSET UNITYSDK_OFFSET(0xD97A930)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITYGOBYGROUPENTITYID_OFFSET UNITYSDK_OFFSET(0xD97AF00)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITYMANAGER_OFFSET UNITYSDK_OFFSET(0xD96F6E0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITYSPAWNCONFIG_OFFSET UNITYSDK_OFFSET(0xD98CE60)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENTITYSPAWNPOSITION_OFFSET UNITYSDK_OFFSET(0xD98D290)
#define RPG_GAMECORE_ADVENTURESTATIC_GETENUMTYPENAMES_OFFSET UNITYSDK_OFFSET(0xD9836F0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETERAFLIPPERMANAGER_OFFSET UNITYSDK_OFFSET(0xD986880)
#define RPG_GAMECORE_ADVENTURESTATIC_GETESPLAYERPOS_OFFSET UNITYSDK_OFFSET(0xD985830)
#define RPG_GAMECORE_ADVENTURESTATIC_GETFLOORMISSIONIDS_OFFSET UNITYSDK_OFFSET(0xD985E50)
#define RPG_GAMECORE_ADVENTURESTATIC_GETFLOORMISSIONINFO_OFFSET UNITYSDK_OFFSET(0xD985DA0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETFMSYSTEM_OFFSET UNITYSDK_OFFSET(0xD985B50)
#define RPG_GAMECORE_ADVENTURESTATIC_GETGROUPIDANDINSTANCEIDBYENTITY_OFFSET UNITYSDK_OFFSET(0xD984110)
#define RPG_GAMECORE_ADVENTURESTATIC_GETGROUPIDBYENTITY_OFFSET UNITYSDK_OFFSET(0xD983F20)
#define RPG_GAMECORE_ADVENTURESTATIC_GETINSTANCEIDBYENTITY_OFFSET UNITYSDK_OFFSET(0xD984020)
#define RPG_GAMECORE_ADVENTURESTATIC_GETISINPERFORMANCE_OFFSET UNITYSDK_OFFSET(0xD9866A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETISTEXTPASSEDFILTERKEYWORDS_OFFSET UNITYSDK_OFFSET(0xD983E00)
#define RPG_GAMECORE_ADVENTURESTATIC_GETLEVELENTITYVCAMERACONFIGFROMENTITY_OFFSET UNITYSDK_OFFSET(0xD97ADE0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETLOCALPLAYERINCLUDESTORYPLAYER_OFFSET UNITYSDK_OFFSET(0xD97B680)
#define RPG_GAMECORE_ADVENTURESTATIC_GETLOCALPLAYERNAMEINDEXFROMJSONPATH_OFFSET UNITYSDK_OFFSET(0xD9916A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETLOCALPLAYER_OFFSET UNITYSDK_OFFSET(0xD93A510)
#define RPG_GAMECORE_ADVENTURESTATIC_GETLOCKTARGETINCAMERA_OFFSET UNITYSDK_OFFSET(0xD97F570)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAINWORLDTIMESCALE_OFFSET UNITYSDK_OFFSET(0xD979AA0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAINWORLD_OFFSET UNITYSDK_OFFSET(0xD979970)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPCAMERACONFIGPATHBYTYPE_OFFSET UNITYSDK_OFFSET(0xD9809A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPNPC_OFFSET UNITYSDK_OFFSET(0xD97A420)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONCURRENTENERGY_OFFSET UNITYSDK_OFFSET(0xD986A40)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONINFO_OFFSET UNITYSDK_OFFSET(0xD981010)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONMANAGER_OFFSET UNITYSDK_OFFSET(0xD986750)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONMAXENERGY_OFFSET UNITYSDK_OFFSET(0xD9869B0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONPROPANCHOR_OFFSET UNITYSDK_OFFSET(0xD978BE0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAZEBUFFTYPE_OFFSET UNITYSDK_OFFSET(0xD980A40)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAZEFLOORCOMMENT_OFFSET UNITYSDK_OFFSET(0xD9835B0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAZEMPMAXVALUE_OFFSET UNITYSDK_OFFSET(0xD97BCD0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMAZESKILLRELATEDAVATARSKILL_OFFSET UNITYSDK_OFFSET(0xD9802B0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMONSTERNAMEINDEXFROMTEMPLATEPREFABPATH_OFFSET UNITYSDK_OFFSET(0xD991750)
#define RPG_GAMECORE_ADVENTURESTATIC_GETMONSTERRANKBYCHARACTERID_OFFSET UNITYSDK_OFFSET(0xD97BFF0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETNAMEBYENTITY_OFFSET UNITYSDK_OFFSET(0xD9856E0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETNPCBORNTRANSFORM_OFFSET UNITYSDK_OFFSET(0xD98DE20)
#define RPG_GAMECORE_ADVENTURESTATIC_GETNPCMONSTERHARDCONFIG_OFFSET UNITYSDK_OFFSET(0xD986520)
#define RPG_GAMECORE_ADVENTURESTATIC_GETNPCMONSTERSTAGETYPE_OFFSET UNITYSDK_OFFSET(0xD988CB0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETNPCMONSTERWARNINGRATIO_OFFSET UNITYSDK_OFFSET(0xD986470)
#define RPG_GAMECORE_ADVENTURESTATIC_GETNPCTAGS_OFFSET UNITYSDK_OFFSET(0xD991470)
#define RPG_GAMECORE_ADVENTURESTATIC_GETONENTERBATTLESEQ_OFFSET UNITYSDK_OFFSET(0xD97EF80)
#define RPG_GAMECORE_ADVENTURESTATIC_GETONLOADBATTLESEQ_OFFSET UNITYSDK_OFFSET(0xD97ED80)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPERFORMANCEREPLAYINFO_OFFSET UNITYSDK_OFFSET(0xD990DD0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPLAYERANIMSTATE_OFFSET UNITYSDK_OFFSET(0xD9833C0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPOSITIONBYGROUPIDANDINSTANCEID_OFFSET UNITYSDK_OFFSET(0xD984FA0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPOSTURETYPETASKCONFIG_1_OFFSET UNITYSDK_OFFSET(0xD97E4B0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPOSTURETYPETASKCONFIG_OFFSET UNITYSDK_OFFSET(0xD97E3D0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPROPANCHOR_OFFSET UNITYSDK_OFFSET(0xD978850)
#define RPG_GAMECORE_ADVENTURESTATIC_GETPROPMANAGER_OFFSET UNITYSDK_OFFSET(0xD979FE0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETQATESTPLAYERS_OFFSET UNITYSDK_OFFSET(0xD9822A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETREALLOCALPLAYER_OFFSET UNITYSDK_OFFSET(0xD97B330)
#define RPG_GAMECORE_ADVENTURESTATIC_GETRUNTIMEGROUPINFO_OFFSET UNITYSDK_OFFSET(0xD980D90)
#define RPG_GAMECORE_ADVENTURESTATIC_GETRUNTIMEGROUPMANAGER_OFFSET UNITYSDK_OFFSET(0xD985AE0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETSKILLUSEIDBYSKILLCONTEXT_OFFSET UNITYSDK_OFFSET(0xD97C6A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETSTAGEIDBYEVENTID_OFFSET UNITYSDK_OFFSET(0xD97F3E0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETSTAGEIDFROMNPC_OFFSET UNITYSDK_OFFSET(0xD97F4D0)
#define RPG_GAMECORE_ADVENTURESTATIC_GETSUMMONUNITMANAGER_OFFSET UNITYSDK_OFFSET(0xD960480)
#define RPG_GAMECORE_ADVENTURESTATIC_GET_CURRENTBATTLEPOSTURETYPE_OFFSET UNITYSDK_OFFSET(0xD97E340)
#define RPG_GAMECORE_ADVENTURESTATIC_GET_CURRENTBATTLESKILLTYPE_OFFSET UNITYSDK_OFFSET(0xD97E3A0)
#define RPG_GAMECORE_ADVENTURESTATIC_GET_INITALREADY_OFFSET UNITYSDK_OFFSET(0xD94DEC0)
#define RPG_GAMECORE_ADVENTURESTATIC_HASSTATICAIPATHWAY_OFFSET UNITYSDK_OFFSET(0xD986C00)
#define RPG_GAMECORE_ADVENTURESTATIC_HASUNFINISHEDMAPOBJECTREFRESHTASK_OFFSET UNITYSDK_OFFSET(0xD98DEE0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISADVENTUREMAZESKILL_OFFSET UNITYSDK_OFFSET(0xD989660)
#define RPG_GAMECORE_ADVENTURESTATIC_ISADVENTUREWEAKTYPEACTIVE_OFFSET UNITYSDK_OFFSET(0xD97C820)
#define RPG_GAMECORE_ADVENTURESTATIC_ISANYFASTDELIVERPUZZLEPLAYING_OFFSET UNITYSDK_OFFSET(0xD98E470)
#define RPG_GAMECORE_ADVENTURESTATIC_ISENTERBATTLEBLOCKPOSTURE_OFFSET UNITYSDK_OFFSET(0xD97D380)
#define RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_1_OFFSET UNITYSDK_OFFSET(0xD984780)
#define RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_2_OFFSET UNITYSDK_OFFSET(0xD984980)
#define RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_3_OFFSET UNITYSDK_OFFSET(0xD984B60)
#define RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_OFFSET UNITYSDK_OFFSET(0xD984580)
#define RPG_GAMECORE_ADVENTURESTATIC_ISENTITYINMAP_OFFSET UNITYSDK_OFFSET(0xD98D510)
#define RPG_GAMECORE_ADVENTURESTATIC_ISFORCEENTERBATTLEADVANTAGE_OFFSET UNITYSDK_OFFSET(0xD97D080)
#define RPG_GAMECORE_ADVENTURESTATIC_ISGROUPATMOSPHERE_OFFSET UNITYSDK_OFFSET(0xD9843B0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISINCONTENTDIMENSION_OFFSET UNITYSDK_OFFSET(0xD984E10)
#define RPG_GAMECORE_ADVENTURESTATIC_ISINSWITCHTEAMLEADER_OFFSET UNITYSDK_OFFSET(0xD97B560)
#define RPG_GAMECORE_ADVENTURESTATIC_ISLOCALPLAYER_OFFSET UNITYSDK_OFFSET(0xD97B1D0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISMAINSTORYLINE_OFFSET UNITYSDK_OFFSET(0xD984D40)
#define RPG_GAMECORE_ADVENTURESTATIC_ISMISSIONENTITY_OFFSET UNITYSDK_OFFSET(0xD983560)
#define RPG_GAMECORE_ADVENTURESTATIC_ISNPCBELONGTOGROUP_OFFSET UNITYSDK_OFFSET(0xD97D520)
#define RPG_GAMECORE_ADVENTURESTATIC_ISPERFORMANCEREPLAYING_OFFSET UNITYSDK_OFFSET(0xD990D40)
#define RPG_GAMECORE_ADVENTURESTATIC_ISPLAYERMOVING_OFFSET UNITYSDK_OFFSET(0xD983210)
#define RPG_GAMECORE_ADVENTURESTATIC_ISPLAYINGFAKEAVATAR_OFFSET UNITYSDK_OFFSET(0xD9803B0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISPROPBELONGTOGROUP_OFFSET UNITYSDK_OFFSET(0xD97D420)
#define RPG_GAMECORE_ADVENTURESTATIC_ISPROPSTATIC_OFFSET UNITYSDK_OFFSET(0xD982BE0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISRESHAMODULEACTIVE_OFFSET UNITYSDK_OFFSET(0xD9918A0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISRUNTIMEGROUPLOADED_OFFSET UNITYSDK_OFFSET(0xD985BF0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISSAMEFLOOR_OFFSET UNITYSDK_OFFSET(0xD98D480)
#define RPG_GAMECORE_ADVENTURESTATIC_ISSTILLNPC_OFFSET UNITYSDK_OFFSET(0xD97D620)
#define RPG_GAMECORE_ADVENTURESTATIC_ISTARGETHOLYSHIELD_OFFSET UNITYSDK_OFFSET(0xD97CB00)
#define RPG_GAMECORE_ADVENTURESTATIC_ISTARGETINMAINCAMERA_OFFSET UNITYSDK_OFFSET(0xD981CA0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISTARGETNOTRIGGERBATTLE_OFFSET UNITYSDK_OFFSET(0xD97D3E0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISTARGETSTEALTH_OFFSET UNITYSDK_OFFSET(0xD97CDC0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISTEAMCONTAINMODIFIERBEHAVIOR_OFFSET UNITYSDK_OFFSET(0xD97D0E0)
#define RPG_GAMECORE_ADVENTURESTATIC_ISVALIDTRIGGERBATTLEENTITYTYPE_OFFSET UNITYSDK_OFFSET(0xD988D70)
#define RPG_GAMECORE_ADVENTURESTATIC_MODIFYMAXMAZEMPVALUE_OFFSET UNITYSDK_OFFSET(0xD97B9B0)
#define RPG_GAMECORE_ADVENTURESTATIC_MODIFYMAZEMPVALUE_OFFSET UNITYSDK_OFFSET(0xD975F00)
#define RPG_GAMECORE_ADVENTURESTATIC_NOTIFYENTITYUISCALE_OFFSET UNITYSDK_OFFSET(0xD98A150)
#define RPG_GAMECORE_ADVENTURESTATIC_ONENTERADVENTUREPERFORM_OFFSET UNITYSDK_OFFSET(0xD97B450)
#define RPG_GAMECORE_ADVENTURESTATIC_PROCESSATTACKRESULTDIRECTKILL_OFFSET UNITYSDK_OFFSET(0xD988DC0)
#define RPG_GAMECORE_ADVENTURESTATIC_PROCESSHITANIMANDEFFECT_OFFSET UNITYSDK_OFFSET(0xD98A430)
#define RPG_GAMECORE_ADVENTURESTATIC_PROCESSHOLYSHIELD_OFFSET UNITYSDK_OFFSET(0xD97D6D0)
#define RPG_GAMECORE_ADVENTURESTATIC_PROCESSNPCONHITEFFECT_OFFSET UNITYSDK_OFFSET(0xD98A1D0)
#define RPG_GAMECORE_ADVENTURESTATIC_PROCESSONHITEFFECT_1_OFFSET UNITYSDK_OFFSET(0xD989810)
#define RPG_GAMECORE_ADVENTURESTATIC_PROCESSONHITEFFECT_OFFSET UNITYSDK_OFFSET(0xD989730)
#define RPG_GAMECORE_ADVENTURESTATIC_RANDOMWIGHTEDINDEX_OFFSET UNITYSDK_OFFSET(0xD982640)
#define RPG_GAMECORE_ADVENTURESTATIC_SAFEGETMONSTERRANKBYCHARACTERID_OFFSET UNITYSDK_OFFSET(0xD97C460)
#define RPG_GAMECORE_ADVENTURESTATIC_SETMONSTERAIENABLE_OFFSET UNITYSDK_OFFSET(0xD97E180)
#define RPG_GAMECORE_ADVENTURESTATIC_SETUPENTITYMOVEMENT_OFFSET UNITYSDK_OFFSET(0xD97F7B0)
#define RPG_GAMECORE_ADVENTURESTATIC_SET_CURRENTBATTLEPOSTURETYPE_OFFSET UNITYSDK_OFFSET(0xD97E310)
#define RPG_GAMECORE_ADVENTURESTATIC_SET_CURRENTBATTLESKILLTYPE_OFFSET UNITYSDK_OFFSET(0xD97E370)
#define RPG_GAMECORE_ADVENTURESTATIC_SYNCPLAYERTEAMMEMBERSERVERENTITYINFO_OFFSET UNITYSDK_OFFSET(0xD980730)
#define RPG_GAMECORE_ADVENTURESTATIC_TARGETALLOWINSTANTKILL_OFFSET UNITYSDK_OFFSET(0xD97BDB0)
#define RPG_GAMECORE_ADVENTURESTATIC_TASKGETVALIDTARGET_OFFSET UNITYSDK_OFFSET(0xD98DA20)
#define RPG_GAMECORE_ADVENTURESTATIC_TRIGGERENTITYONBEFOREBATTLE_OFFSET UNITYSDK_OFFSET(0xD987E70)
#define RPG_GAMECORE_ADVENTURESTATIC_TRIGGERMODIFIERONBEFOREBATTLE_OFFSET UNITYSDK_OFFSET(0xD9875C0)
#define RPG_GAMECORE_ADVENTURESTATIC_TRIGGERWATERINTERACTBYATTACK_OFFSET UNITYSDK_OFFSET(0xD98C170)
#define RPG_GAMECORE_ADVENTURESTATIC_TRYATTACKENTITYBYLEVEL_OFFSET UNITYSDK_OFFSET(0xD986C90)
#define RPG_GAMECORE_ADVENTURESTATIC_TRYGETCAMERAROOT_OFFSET UNITYSDK_OFFSET(0xD97AC40)
#define RPG_GAMECORE_ADVENTURESTATIC_TRYGETFARMELEMENTID_1_OFFSET UNITYSDK_OFFSET(0xD982F20)
#define RPG_GAMECORE_ADVENTURESTATIC_TRYGETFARMELEMENTID_OFFSET UNITYSDK_OFFSET(0xD982C30)
#define RPG_GAMECORE_ADVENTURESTATIC_TRYGETSKILLPOINTCOLLIDER_OFFSET UNITYSDK_OFFSET(0xD98E0D0)
#define RPG_GAMECORE_ADVENTURESTATIC_TRYNOTIFYUIMAZEREFRESHBUFF_OFFSET UNITYSDK_OFFSET(0xD939590)
#define RPG_GAMECORE_ADVENTURESTATIC_WALLDETECT_OFFSET UNITYSDK_OFFSET(0xD9810E0)
#define RPG_GAMECORE_ADVENTURESTATIC__APPENDATTACKOCCLUSIONEXCLUDELIST_OFFSET UNITYSDK_OFFSET(0xD9905F0)
#define RPG_GAMECORE_ADVENTURESTATIC__ATTACKDETECTBYBOXCONFIG_OFFSET UNITYSDK_OFFSET(0xD98B1F0)
#define RPG_GAMECORE_ADVENTURESTATIC__ATTACKDETECTBYCIRCLECONFIG_OFFSET UNITYSDK_OFFSET(0xD98B730)
#define RPG_GAMECORE_ADVENTURESTATIC__ATTACKDETECTBYSPHERECONFIG_OFFSET UNITYSDK_OFFSET(0xD98B4F0)
#define RPG_GAMECORE_ADVENTURESTATIC__ATTACKOCCLUSION_OFFSET UNITYSDK_OFFSET(0xD98F3F0)
#define RPG_GAMECORE_ADVENTURESTATIC__CCTOR_OFFSET UNITYSDK_OFFSET(0xD991A20)
#define RPG_GAMECORE_ADVENTURESTATIC__CHECKISCHILDOFANY_OFFSET UNITYSDK_OFFSET(0xD990720)
#define RPG_GAMECORE_ADVENTURESTATIC__COMPARECOLLSIONRESULTCONFLICT_OFFSET UNITYSDK_OFFSET(0xD990560)
#define RPG_GAMECORE_ADVENTURESTATIC__CTOR_OFFSET UNITYSDK_OFFSET(0xD991A10)
#define RPG_GAMECORE_ADVENTURESTATIC__FACEHITTARGETTOATTACK_OFFSET UNITYSDK_OFFSET(0xD9892D0)
#define RPG_GAMECORE_ADVENTURESTATIC__FILTEREDATTACKDETECT_OFFSET UNITYSDK_OFFSET(0xD98E980)
#define RPG_GAMECORE_ADVENTURESTATIC__GETAVATARBATTLETRANSITIONCONFIG_OFFSET UNITYSDK_OFFSET(0xD97E930)
#define RPG_GAMECORE_ADVENTURESTATIC__SEARCHHIGHESTPRIORITYHOLYSHIELD_OFFSET UNITYSDK_OFFSET(0xD97DE90)

namespace RPG::GameCore
{
	inline static constexpr unsigned int AdventureStatic_TypeDefinitionIndex = 56380;

	class AdventureStatic : public ::System::Object
	{
	public:
		static ::System::String** StaticGet_AvatarNameIndexTrimStart()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DBF0);
		}
		static ::System::String** StaticGet_MazeBuffParamPrefix()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DBF8);
		}
		static ::System::String** StaticGet_MonsterNameIndexTrimEnd()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DC00);
		}
		static ::System::String** StaticGet_AvatarNameIndexTrimEnd()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DC08);
		}
		static ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>** StaticGet__entitiesCache()
		{
			return (::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DC10);
		}
		static ::System::String** StaticGet_LocalPlayerNameIndexTrimStart()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DC18);
		}
		static ::System::String** StaticGet_LocalPlayerNameIndexTrimEnd()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DC20);
		}
		static ::System::String** StaticGet_MonsterNameIndexTrimStart()
		{
			return (::System::String**)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x1DC28);
		}
		static ::System::Boolean* StaticGet__CurrentFastDeliverFinish()
		{
			return (::System::Boolean*)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x68A0);
		}
		static ::System::Boolean* StaticGet_EnableModelDitherWithPlayer()
		{
			return (::System::Boolean*)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x68A1);
		}
		static ::System::Boolean* StaticGet_OpenFollowPlatformMove()
		{
			return (::System::Boolean*)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x68A2);
		}
		static ::RPG::GameCore::BattlePostureType* StaticGet__CurrentBattlePostureType_k__BackingField()
		{
			return (::RPG::GameCore::BattlePostureType*)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x68A4);
		}
		static ::RPG::GameCore::AdventureSkillType* StaticGet__CurrentBattleSkillType_k__BackingField()
		{
			return (::RPG::GameCore::AdventureSkillType*)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x68A8);
		}
		static ::System::Single* StaticGet_EnableNPCDitherDistance()
		{
			return (::System::Single*)Il2CppClass::FromTypeDefinitionIndex(AdventureStatic_TypeDefinitionIndex)->GetStaticField(0x68AC);
		}
		// static const ::System::UInt32 s_InvalidMissionID = 0x0; // 0x0
		// static const ::System::String* AREA_ANCHOR_NAME; // 0x0
		// static const ::System::String* PROP_PREFIX; // 0x0
		// static const ::System::String* NPCMONSTER_PREFIX; // 0x0
		// static const ::System::String* UNTAGGED_TAG; // 0x0
		// static const ::System::String* MOVE_IGNORE_COLLIDER_TAG; // 0x0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__CCTOR_OFFSET))();
		}

		static ::System::Boolean get_InitAlready()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GET_INITALREADY_OFFSET))();
		}

		static ::RPG::GameCore::AnchorInfo* GetAnchorInfoByCustomString(::RPG::GameCore::TaskContext* a1, ::RPG::GameCore::DynamicString* a2)
		{
			return ((::RPG::GameCore::AnchorInfo*(*)(::RPG::GameCore::TaskContext*, ::RPG::GameCore::DynamicString*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETANCHORINFOBYCUSTOMSTRING_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::AnchorInfo* GetPropAnchor(::RPG::GameCore::TaskContext* a1, ::System::String* a2, ::System::String* a3, ::UnityEngine::Vector3& a4, ::UnityEngine::Quaternion& a5)
		{
			return ((::RPG::GameCore::AnchorInfo*(*)(::RPG::GameCore::TaskContext*, ::System::String*, ::System::String*, ::UnityEngine::Vector3&, ::UnityEngine::Quaternion&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPROPANCHOR_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::RPG::GameCore::AnchorInfo* GetMapRotationPropAnchor(::System::String* a1, ::UnityEngine::Vector3& a2, ::UnityEngine::Quaternion& a3)
		{
			return ((::RPG::GameCore::AnchorInfo*(*)(::System::String*, ::UnityEngine::Vector3&, ::UnityEngine::Quaternion&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONPROPANCHOR_OFFSET))(a1, a2, a3);
		}

		static ::RPG::GameCore::LevelCurveInstance* CreateLevelCurve(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::RPG::GameCore::LevelCurveInstance*(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CREATELEVELCURVE_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::LevelCurveInfo* FindLevelCurveInfo(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::RPG::GameCore::LevelCurveInfo*(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDLEVELCURVEINFO_OFFSET))(a1, a2);
		}

		static ::System::Void ApplyLevelCurve(::UnityEngine::GameObject* a1, ::System::UInt32 a2, ::System::UInt32 a3)
		{
			return ((::System::Void(*)(::UnityEngine::GameObject*, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_APPLYLEVELCURVE_OFFSET))(a1, a2, a3);
		}

		static ::RPG::GameCore::GameWorld* GetMainWorld()
		{
			return ((::RPG::GameCore::GameWorld*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAINWORLD_OFFSET))();
		}

		static ::System::Single GetMainWorldTimeScale()
		{
			return ((::System::Single(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAINWORLDTIMESCALE_OFFSET))();
		}

		static ::RPG::GameCore::EntityManager* GetEntityManager()
		{
			return ((::RPG::GameCore::EntityManager*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITYMANAGER_OFFSET))();
		}

		static ::RPG::GameCore::GameEntity* FindEntityByServerEntityID(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDENTITYBYSERVERENTITYID_OFFSET))(a1);
		}

		static ::RPG::GameCore::GameEntity* FindEntityByGroupEntityID(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDENTITYBYGROUPENTITYID_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::PropComponent* FindProp(::RPG::GameCore::TaskContext* a1, ::System::String* a2, ::System::Boolean a3)
		{
			return ((::RPG::GameCore::PropComponent*(*)(::RPG::GameCore::TaskContext*, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDPROP_OFFSET))(a1, a2, a3);
		}

		static ::Class_1_AFC3C7A272BDF32C* GetPropManager()
		{
			return ((::Class_1_AFC3C7A272BDF32C*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPROPMANAGER_OFFSET))();
		}

		static ::Class_1_72FF3C03F0F06A80* GetSummonUnitManager()
		{
			return ((::Class_1_72FF3C03F0F06A80*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETSUMMONUNITMANAGER_OFFSET))();
		}

		static ::RPG::GameCore::GameEntity* FindPropEntityByGroupID(::System::UInt32 a1, ::System::UInt32 a2, ::System::Boolean a3)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::System::UInt32, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDPROPENTITYBYGROUPID_OFFSET))(a1, a2, a3);
		}

		static ::RPG::GameCore::PropComponent* FindPropByGroupID(::System::UInt32 a1, ::System::UInt32 a2, ::System::Boolean a3)
		{
			return ((::RPG::GameCore::PropComponent*(*)(::System::UInt32, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDPROPBYGROUPID_OFFSET))(a1, a2, a3);
		}

		static ::RPG::Client::MapNpc* GetMapNpc(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::RPG::Client::MapNpc*(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPNPC_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::GameEntityList* GetEntitiesByGroup(::System::UInt32 a1, ::System::Collections::Generic::HashSet_1<::System::UInt32>* a2)
		{
			return ((::RPG::GameCore::GameEntityList*(*)(::System::UInt32, ::System::Collections::Generic::HashSet_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITIESBYGROUP_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::GameEntity* GetEntityByUniqueName(::System::String* a1)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITYBYUNIQUENAME_OFFSET))(a1);
		}

		static ::RPG::GameCore::GameEntity* GetEntityByRuntimeID(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITYBYRUNTIMEID_OFFSET))(a1);
		}

		static ::UnityEngine::GameObject* TryGetCameraRoot(::UnityEngine::GameObject* a1, ::System::String* a2)
		{
			return ((::UnityEngine::GameObject*(*)(::UnityEngine::GameObject*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRYGETCAMERAROOT_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::LevelEntityVCameraConfig* GetLevelEntityVCameraConfigFromEntity(::RPG::GameCore::GameEntity* a1)
		{
			return ((::RPG::GameCore::LevelEntityVCameraConfig*(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETLEVELENTITYVCAMERACONFIGFROMENTITY_OFFSET))(a1);
		}

		static ::UnityEngine::GameObject* GetEntityGoByGroupEntityID(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::UnityEngine::GameObject*(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITYGOBYGROUPENTITYID_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsLocalPlayer(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISLOCALPLAYER_OFFSET))(a1);
		}

		static ::RPG::GameCore::GameEntity* GetLocalPlayer()
		{
			return ((::RPG::GameCore::GameEntity*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETLOCALPLAYER_OFFSET))();
		}

		static ::RPG::GameCore::GameEntity* GetRealLocalPlayer()
		{
			return ((::RPG::GameCore::GameEntity*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETREALLOCALPLAYER_OFFSET))();
		}

		static ::System::Void OnEnterAdventurePerform()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ONENTERADVENTUREPERFORM_OFFSET))();
		}

		static ::System::Boolean IsInSwitchTeamLeader()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISINSWITCHTEAMLEADER_OFFSET))();
		}

		static ::RPG::GameCore::GameEntity* GetLocalPlayerIncludeStoryPlayer(::System::Boolean a1)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETLOCALPLAYERINCLUDESTORYPLAYER_OFFSET))(a1);
		}

		static ::System::Void FillNpcListByGroup(::System::UInt32 a1, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a2)
		{
			return ((::System::Void(*)(::System::UInt32, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FILLNPCLISTBYGROUP_OFFSET))(a1, a2);
		}

		static ::System::Void ModifyMazeMPValue(::RPG::GameCore::PropertyModifyFunction a1, ::RPG::GameCore::FixPoint a2, ::System::Boolean a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::RPG::GameCore::PropertyModifyFunction, ::RPG::GameCore::FixPoint, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_MODIFYMAZEMPVALUE_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Void ModifyMaxMazeMPValue(::RPG::GameCore::PropertyModifyFunction a1, ::RPG::GameCore::FixPoint a2)
		{
			return ((::System::Void(*)(::RPG::GameCore::PropertyModifyFunction, ::RPG::GameCore::FixPoint))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_MODIFYMAXMAZEMPVALUE_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::FixPoint GetCurrentMazeMPValue()
		{
			return ((::RPG::GameCore::FixPoint(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTMAZEMPVALUE_OFFSET))();
		}

		static ::RPG::GameCore::FixPoint GetCurrentMazeMPValueForDisplay()
		{
			return ((::RPG::GameCore::FixPoint(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTMAZEMPVALUEFORDISPLAY_OFFSET))();
		}

		static ::RPG::GameCore::FixPoint GetMazeMPMaxValue()
		{
			return ((::RPG::GameCore::FixPoint(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAZEMPMAXVALUE_OFFSET))();
		}

		static ::System::Boolean TargetAllowInstantKill(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TARGETALLOWINSTANTKILL_OFFSET))(a1);
		}

		static ::System::Void GetAbilityTargetServerEntityID(::RPG::GameCore::TaskContext* a1, ::System::Collections::Generic::List_1<::System::UInt32>* a2)
		{
			return ((::System::Void(*)(::RPG::GameCore::TaskContext*, ::System::Collections::Generic::List_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETABILITYTARGETSERVERENTITYID_OFFSET))(a1, a2);
		}

		static ::System::Void GetAbilityTargetServerEntityID_1(::Class_2_A171F95E026CBAD1* a1, ::System::Collections::Generic::List_1<::System::UInt32>* a2)
		{
			return ((::System::Void(*)(::Class_2_A171F95E026CBAD1*, ::System::Collections::Generic::List_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETABILITYTARGETSERVERENTITYID_1_OFFSET))(a1, a2);
		}

		static ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* GetBattleAssistMonsterList(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETBATTLEASSISTMONSTERLIST_OFFSET))(a1);
		}

		static ::RPG::GameCore::MonsterRank GetMonsterRankByCharacterID(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::MonsterRank(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMONSTERRANKBYCHARACTERID_OFFSET))(a1);
		}

		static ::System::Boolean SafeGetMonsterRankByCharacterID(::System::UInt32 a1, ::RPG::GameCore::MonsterRank& a2)
		{
			return ((::System::Boolean(*)(::System::UInt32, ::RPG::GameCore::MonsterRank&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_SAFEGETMONSTERRANKBYCHARACTERID_OFFSET))(a1, a2);
		}

		static ::System::Void DisableAllMonsterAI(::RPG::GameCore::GameWorld* a1)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameWorld*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_DISABLEALLMONSTERAI_OFFSET))(a1);
		}

		static ::System::UInt32 GetSkillUseIdBySkillContext(::RPG::GameCore::TaskContext* a1)
		{
			return ((::System::UInt32(*)(::RPG::GameCore::TaskContext*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETSKILLUSEIDBYSKILLCONTEXT_OFFSET))(a1);
		}

		static ::System::Boolean IsAdventureWeakTypeActive(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::TaskContext* a3)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TaskContext*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISADVENTUREWEAKTYPEACTIVE_OFFSET))(a1, a2, a3);
		}

		static ::System::Boolean IsTargetHolyShield(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISTARGETHOLYSHIELD_OFFSET))(a1);
		}

		static ::System::Boolean IsTargetStealth(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISTARGETSTEALTH_OFFSET))(a1);
		}

		static ::System::Boolean IsForceEnterBattleAdvantage(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISFORCEENTERBATTLEADVANTAGE_OFFSET))(a1);
		}

		static ::System::Boolean IsEnterBattleBlockPosture(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISENTERBATTLEBLOCKPOSTURE_OFFSET))(a1);
		}

		static ::System::Boolean IsTeamContainModifierBehavior(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::AdventureModifierBehaviorFlag a2)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureModifierBehaviorFlag))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISTEAMCONTAINMODIFIERBEHAVIOR_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsTargetNoTriggerBattle(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISTARGETNOTRIGGERBATTLE_OFFSET))(a1);
		}

		static ::System::Boolean IsPropBelongToGroup(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISPROPBELONGTOGROUP_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsNpcBelongToGroup(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISNPCBELONGTOGROUP_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsStillNPC(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISSTILLNPC_OFFSET))(a1);
		}

		static ::System::Void ProcessHolyShield(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::AdventureHitConfig* a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureHitConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_PROCESSHOLYSHIELD_OFFSET))(a1, a2, a3);
		}

		static ::System::Void _SearchHighestPriorityHolyShield(::System::Collections::Generic::List_1<::Class_0_16E4307DCC419505_380*>* a1, ::RPG::GameCore::AdventureModifierInstance*& a2)
		{
			return ((::System::Void(*)(::System::Collections::Generic::List_1<::Class_0_16E4307DCC419505_380*>*, ::RPG::GameCore::AdventureModifierInstance*&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__SEARCHHIGHESTPRIORITYHOLYSHIELD_OFFSET))(a1, a2);
		}

		static ::System::Void CommonProcessBeforeTriggerBattle(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::Class_1_0AD6129525BF5F86* a3, ::System::Single a4)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::Class_1_0AD6129525BF5F86*, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_COMMONPROCESSBEFORETRIGGERBATTLE_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Void SetMonsterAIEnable(::RPG::GameCore::GameWorld* a1, ::System::Boolean a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameWorld*, ::System::Boolean, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_SETMONSTERAIENABLE_OFFSET))(a1, a2, a3);
		}

		static ::System::Void set_CurrentBattlePostureType(::RPG::GameCore::BattlePostureType a1)
		{
			return ((::System::Void(*)(::RPG::GameCore::BattlePostureType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_SET_CURRENTBATTLEPOSTURETYPE_OFFSET))(a1);
		}

		static ::RPG::GameCore::BattlePostureType get_CurrentBattlePostureType()
		{
			return ((::RPG::GameCore::BattlePostureType(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GET_CURRENTBATTLEPOSTURETYPE_OFFSET))();
		}

		static ::System::Void set_CurrentBattleSkillType(::RPG::GameCore::AdventureSkillType a1)
		{
			return ((::System::Void(*)(::RPG::GameCore::AdventureSkillType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_SET_CURRENTBATTLESKILLTYPE_OFFSET))(a1);
		}

		static ::RPG::GameCore::AdventureSkillType get_CurrentBattleSkillType()
		{
			return ((::RPG::GameCore::AdventureSkillType(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GET_CURRENTBATTLESKILLTYPE_OFFSET))();
		}

		static ::Il2CppArray<::RPG::GameCore::TaskConfig*>* GetPostureTypeTaskConfig(::Il2CppArray<::RPG::GameCore::PostureTypeTasksConfig*>* a1)
		{
			return ((::Il2CppArray<::RPG::GameCore::TaskConfig*>*(*)(::Il2CppArray<::RPG::GameCore::PostureTypeTasksConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPOSTURETYPETASKCONFIG_OFFSET))(a1);
		}

		static ::Il2CppArray<::RPG::GameCore::TaskConfig*>* GetPostureTypeTaskConfig_1(::Il2CppArray<::RPG::GameCore::TaskConfig*>* a1, ::Il2CppArray<::RPG::GameCore::PostureTypeTasksConfig*>* a2)
		{
			return ((::Il2CppArray<::RPG::GameCore::TaskConfig*>*(*)(::Il2CppArray<::RPG::GameCore::TaskConfig*>*, ::Il2CppArray<::RPG::GameCore::PostureTypeTasksConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPOSTURETYPETASKCONFIG_1_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::CustomMazeBattleTransitionConfig* GetAvatarBattleTransitionConfig(::RPG::GameCore::GameEntity*& a1)
		{
			return ((::RPG::GameCore::CustomMazeBattleTransitionConfig*(*)(::RPG::GameCore::GameEntity*&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETAVATARBATTLETRANSITIONCONFIG_OFFSET))(a1);
		}

		static ::RPG::GameCore::CustomMazeBattleTransitionConfig* _GetAvatarBattleTransitionConfig(::RPG::GameCore::GameEntity* a1)
		{
			return ((::RPG::GameCore::CustomMazeBattleTransitionConfig*(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__GETAVATARBATTLETRANSITIONCONFIG_OFFSET))(a1);
		}

		static ::Class_3_07C3C4D2990C49EE* GetOnLoadBattleSeq(::RPG::Client::TransitionMode a1)
		{
			return ((::Class_3_07C3C4D2990C49EE*(*)(::RPG::Client::TransitionMode))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETONLOADBATTLESEQ_OFFSET))(a1);
		}

		static ::Class_3_07C3C4D2990C49EE* GetOnEnterBattleSeq(::RPG::Client::TransitionMode a1, ::System::Boolean& a2, ::System::Boolean a3)
		{
			return ((::Class_3_07C3C4D2990C49EE*(*)(::RPG::Client::TransitionMode, ::System::Boolean&, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETONENTERBATTLESEQ_OFFSET))(a1, a2, a3);
		}

		static ::System::UInt32 GetStageIDByEventID(::System::UInt32 a1, ::System::Nullable_1<::System::UInt32> a2)
		{
			return ((::System::UInt32(*)(::System::UInt32, ::System::Nullable_1<::System::UInt32>))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETSTAGEIDBYEVENTID_OFFSET))(a1, a2);
		}

		static ::System::UInt32 GetStageIDFromNPC(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::UInt32(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETSTAGEIDFROMNPC_OFFSET))(a1);
		}

		static ::RPG::GameCore::GameEntity* GetLockTargetInCamera(::RPG::GameCore::PlayerLockTargetComponent* a1)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::RPG::GameCore::PlayerLockTargetComponent*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETLOCKTARGETINCAMERA_OFFSET))(a1);
		}

		static ::System::Void SetupEntityMovement(::RPG::GameCore::TaskContext* a1, ::RPG::GameCore::GameEntity* a2, ::Il2CppArray<::RPG::GameCore::AdventureAnimationMoveRange*>* a3, ::System::Int32 a4, ::System::Boolean a5)
		{
			return ((::System::Void(*)(::RPG::GameCore::TaskContext*, ::RPG::GameCore::GameEntity*, ::Il2CppArray<::RPG::GameCore::AdventureAnimationMoveRange*>*, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_SETUPENTITYMOVEMENT_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Void TryNotifyUIMazeRefreshBuff(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::AdventureBuffEvent* a2)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureBuffEvent*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRYNOTIFYUIMAZEREFRESHBUFF_OFFSET))(a1, a2);
		}

		static ::Il2CppArray<::RPG::GameCore::FixPoint>* EvaluateMazeBuffDescParam(::RPG::GameCore::AdventureModifierInstance* a1)
		{
			return ((::Il2CppArray<::RPG::GameCore::FixPoint>*(*)(::RPG::GameCore::AdventureModifierInstance*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_EVALUATEMAZEBUFFDESCPARAM_OFFSET))(a1);
		}

		static ::RPG::GameCore::AvatarSkillRow* GetMazeSkillRelatedAvatarSkill(::RPG::GameCore::GameEntity* a1, ::System::UInt32 a2)
		{
			return ((::RPG::GameCore::AvatarSkillRow*(*)(::RPG::GameCore::GameEntity*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAZESKILLRELATEDAVATARSKILL_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsPlayingFakeAvatar()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISPLAYINGFAKEAVATAR_OFFSET))();
		}

		static ::System::UInt32 GetActualTeamLeaderServerEntityID()
		{
			return ((::System::UInt32(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETACTUALTEAMLEADERSERVERENTITYID_OFFSET))();
		}

		static ::System::Void SyncPlayerTeammemberServerEntityInfo(::RPG::Client::TeamManager* a1, ::Proto::SceneEntityInfo* a2)
		{
			return ((::System::Void(*)(::RPG::Client::TeamManager*, ::Proto::SceneEntityInfo*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_SYNCPLAYERTEAMMEMBERSERVERENTITYINFO_OFFSET))(a1, a2);
		}

		static ::System::String* GetMapCameraConfigPathByType(::RPG::GameCore::MapCameraType a1)
		{
			return ((::System::String*(*)(::RPG::GameCore::MapCameraType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPCAMERACONFIGPATHBYTYPE_OFFSET))(a1);
		}

		static ::Class_2_A171F95E026CBAD1* FindMazeSkillAbilityByAvatarID(::System::UInt32 a1)
		{
			return ((::Class_2_A171F95E026CBAD1*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDMAZESKILLABILITYBYAVATARID_OFFSET))(a1);
		}

		static ::Class_2_A171F95E026CBAD1* FindSkillAbilityByServerEntityID(::System::UInt32 a1)
		{
			return ((::Class_2_A171F95E026CBAD1*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_FINDSKILLABILITYBYSERVERENTITYID_OFFSET))(a1);
		}

		static ::RPG::GameCore::MazeBuffType GetMazeBuffType(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::RPG::GameCore::MazeBuffType(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAZEBUFFTYPE_OFFSET))(a1, a2);
		}

		static ::UnityEngine::Vector2 Get2dPositionInMapBackground(::UnityEngine::Vector3 a1)
		{
			return ((::UnityEngine::Vector2(*)(::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GET2DPOSITIONINMAPBACKGROUND_OFFSET))(a1);
		}

		static ::System::Boolean CanStartLevelGraph()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CANSTARTLEVELGRAPH_OFFSET))();
		}

		static ::RPG::GameCore::RuntimeGroupInfo* GetRuntimeGroupInfo(::RPG::Client::MapEntityDef* a1)
		{
			return ((::RPG::GameCore::RuntimeGroupInfo*(*)(::RPG::Client::MapEntityDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETRUNTIMEGROUPINFO_OFFSET))(a1);
		}

		static ::RPG::Client::MapRotationInfo* GetMapRotationInfo()
		{
			return ((::RPG::Client::MapRotationInfo*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONINFO_OFFSET))();
		}

		static ::System::Boolean WallDetect(::UnityEngine::Vector3 a1, ::UnityEngine::Vector3 a2, ::System::Int32 a3, ::RPG::GameCore::AdventureStatic_WallDetectParams* a4, ::UnityEngine::Vector3& a5, ::System::Boolean& a6)
		{
			return ((::System::Boolean(*)(::UnityEngine::Vector3, ::UnityEngine::Vector3, ::System::Int32, ::RPG::GameCore::AdventureStatic_WallDetectParams*, ::UnityEngine::Vector3&, ::System::Boolean&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_WALLDETECT_OFFSET))(a1, a2, a3, a4, a5, a6);
		}

		static ::System::Single GetColliderHeight(::UnityEngine::Collider* a1)
		{
			return ((::System::Single(*)(::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCOLLIDERHEIGHT_OFFSET))(a1);
		}

		static ::UnityEngine::Vector3 GetColliderCenter(::UnityEngine::Collider* a1)
		{
			return ((::UnityEngine::Vector3(*)(::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCOLLIDERCENTER_OFFSET))(a1);
		}

		static ::UnityEngine::Transform* GetAttachPointTransform(::RPG::GameCore::GameEntity* a1, ::System::String* a2)
		{
			return ((::UnityEngine::Transform*(*)(::RPG::GameCore::GameEntity*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETATTACHPOINTTRANSFORM_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsTargetInMainCamera(::UnityEngine::Vector3 a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISTARGETINMAINCAMERA_OFFSET))(a1);
		}

		static ::RPG::GameCore::GameModeType ConvertPlaneTypeToGameModeType(::RPG::GameCore::PlaneType a1, ::System::UInt32 a2, ::RPG::GameCore::FloorType a3)
		{
			return ((::RPG::GameCore::GameModeType(*)(::RPG::GameCore::PlaneType, ::System::UInt32, ::RPG::GameCore::FloorType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CONVERTPLANETYPETOGAMEMODETYPE_OFFSET))(a1, a2, a3);
		}

		static ::RPG::GameCore::GameModeType GetCurrentGameModeType()
		{
			return ((::RPG::GameCore::GameModeType(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTGAMEMODETYPE_OFFSET))();
		}

		static ::RPG::Client::TextID GetCurrentMapName()
		{
			return ((::RPG::Client::TextID(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTMAPNAME_OFFSET))();
		}

		static ::System::Collections::Generic::List_1<::RPG::GameCore::AdventurePlayerRow_AdventurePlayerCommonRowWrap*>* GetQATestPlayers()
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::AdventurePlayerRow_AdventurePlayerCommonRowWrap*>*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETQATESTPLAYERS_OFFSET))();
		}

		static ::System::Int32 RandomWightedIndex(::Il2CppArray<::System::Single>* a1)
		{
			return ((::System::Int32(*)(::Il2CppArray<::System::Single>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_RANDOMWIGHTEDINDEX_OFFSET))(a1);
		}

		static ::System::Int32 GetAreaByNavMeshMask(::System::Int32 a1)
		{
			return ((::System::Int32(*)(::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETAREABYNAVMESHMASK_OFFSET))(a1);
		}

		static ::System::Boolean IsPropStatic(::RPG::GameCore::PropType a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::PropType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISPROPSTATIC_OFFSET))(a1);
		}

		static ::System::Boolean TryGetFarmElementID(::System::UInt32 a1, ::System::UInt32& a2)
		{
			return ((::System::Boolean(*)(::System::UInt32, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRYGETFARMELEMENTID_OFFSET))(a1, a2);
		}

		static ::System::Boolean TryGetFarmElementID_1(::RPG::GameCore::GameEntity* a1, ::System::UInt32& a2)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRYGETFARMELEMENTID_1_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsPlayerMoving()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISPLAYERMOVING_OFFSET))();
		}

		static ::RPG::GameCore::AdventureAnimStateType GetPlayerAnimState()
		{
			return ((::RPG::GameCore::AdventureAnimStateType(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPLAYERANIMSTATE_OFFSET))();
		}

		static ::System::Boolean IsMissionEntity(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISMISSIONENTITY_OFFSET))(a1);
		}

		static ::System::String* GetMazeFloorComment(::System::UInt32 a1)
		{
			return ((::System::String*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAZEFLOORCOMMENT_OFFSET))(a1);
		}

		static ::System::String* GetBattleAreaNameByRowID(::System::UInt32 a1)
		{
			return ((::System::String*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETBATTLEAREANAMEBYROWID_OFFSET))(a1);
		}

		static ::System::Collections::Generic::List_1<::System::String*>* GetEnumTypeNames(::System::Type* a1)
		{
			return ((::System::Collections::Generic::List_1<::System::String*>*(*)(::System::Type*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENUMTYPENAMES_OFFSET))(a1);
		}

		static ::System::String* GetAreaAnchorName(::System::UInt32 a1, ::System::UInt32 a2, ::System::UInt32 a3)
		{
			return ((::System::String*(*)(::System::UInt32, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETAREAANCHORNAME_OFFSET))(a1, a2, a3);
		}

		static ::System::Boolean GetIsTextPassedFilterKeywords(::System::String* a1, ::System::String* a2)
		{
			return ((::System::Boolean(*)(::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETISTEXTPASSEDFILTERKEYWORDS_OFFSET))(a1, a2);
		}

		static ::System::UInt32 GetGroupIDByEntity(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::UInt32(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETGROUPIDBYENTITY_OFFSET))(a1);
		}

		static ::System::UInt32 GetInstanceIDByEntity(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::UInt32(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETINSTANCEIDBYENTITY_OFFSET))(a1);
		}

		static ::System::Void GetGroupIDAndInstanceIDByEntity(::RPG::GameCore::GameEntity* a1, ::System::UInt32& a2, ::System::UInt32& a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::System::UInt32&, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETGROUPIDANDINSTANCEIDBYENTITY_OFFSET))(a1, a2, a3);
		}

		static ::System::Boolean IsGroupAtmosphere(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISGROUPATMOSPHERE_OFFSET))(a1);
		}

		static ::System::Boolean IsEntityAtomosphere(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_OFFSET))(a1);
		}

		static ::System::Boolean IsEntityAtomosphere_1(::RPG::GameCore::PropComponent* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::PropComponent*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_1_OFFSET))(a1);
		}

		static ::System::Boolean IsEntityAtomosphere_2(::RPG::Client::MapPropDef* a1)
		{
			return ((::System::Boolean(*)(::RPG::Client::MapPropDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_2_OFFSET))(a1);
		}

		static ::System::Boolean IsEntityAtomosphere_3(::RPG::Client::MapNpcDef* a1)
		{
			return ((::System::Boolean(*)(::RPG::Client::MapNpcDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISENTITYATOMOSPHERE_3_OFFSET))(a1);
		}

		static ::System::Boolean IsMainStoryLine()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISMAINSTORYLINE_OFFSET))();
		}

		static ::System::Boolean IsInContentDimension()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISINCONTENTDIMENSION_OFFSET))();
		}

		static ::UnityEngine::Vector3 GetPositionByGroupIDAndInstanceID(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::UnityEngine::Vector3(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPOSITIONBYGROUPIDANDINSTANCEID_OFFSET))(a1, a2);
		}

		static ::RPG::Client::TextID GetNameByEntity(::RPG::GameCore::GameEntity* a1)
		{
			return ((::RPG::Client::TextID(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETNAMEBYENTITY_OFFSET))(a1);
		}

		static ::System::Boolean GetESPlayerPos(::UnityEngine::Vector3& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETESPLAYERPOS_OFFSET))(a1);
		}

		static ::RPG::Client::AdventurePhase* GetAdventurePhase()
		{
			return ((::RPG::Client::AdventurePhase*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREPHASE_OFFSET))();
		}

		static ::RPG::Client::RuntimeGroupManager* GetRuntimeGroupManager()
		{
			return ((::RPG::Client::RuntimeGroupManager*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETRUNTIMEGROUPMANAGER_OFFSET))();
		}

		static ::RPG::Client::FMSystem* GetFMSystem()
		{
			return ((::RPG::Client::FMSystem*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETFMSYSTEM_OFFSET))();
		}

		static ::System::Boolean IsRuntimeGroupLoaded(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISRUNTIMEGROUPLOADED_OFFSET))(a1);
		}

		static ::System::UInt64 GetAdventureMapRuntimeID()
		{
			return ((::System::UInt64(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREMAPRUNTIMEID_OFFSET))();
		}

		static ::RPG::Client::MapDef* GetAdventureMapDef()
		{
			return ((::RPG::Client::MapDef*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREMAPDEF_OFFSET))();
		}

		static ::System::Collections::Generic::List_1<::Class_1_4CEDF380BFE8D93F*>* GetFloorMissionInfo(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::Class_1_4CEDF380BFE8D93F*>*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETFLOORMISSIONINFO_OFFSET))(a1);
		}

		static ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::System::UInt32>*>* GetFloorMissionIDs(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::Collections::Generic::List_1<::System::UInt32>*>*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETFLOORMISSIONIDS_OFFSET))(a1);
		}

		static ::System::Single GetNPCMonsterWarningRatio(::RPG::GameCore::StageRow* a1)
		{
			return ((::System::Single(*)(::RPG::GameCore::StageRow*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETNPCMONSTERWARNINGRATIO_OFFSET))(a1);
		}

		static ::System::Void GetNPCMonsterHardConfig(::RPG::GameCore::NPCComponent* a1, ::System::UInt32& a2, ::System::UInt32& a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::NPCComponent*, ::System::UInt32&, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETNPCMONSTERHARDCONFIG_OFFSET))(a1, a2, a3);
		}

		static ::System::UInt32 GetCurVerifyServerEntityID()
		{
			return ((::System::UInt32(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURVERIFYSERVERENTITYID_OFFSET))();
		}

		static ::System::Boolean GetIsInPerformance()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETISINPERFORMANCE_OFFSET))();
		}

		static ::Class_1_64D890C466F37235* GetMapRotationManager()
		{
			return ((::Class_1_64D890C466F37235*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONMANAGER_OFFSET))();
		}

		static ::RPG::Client::EraFlipperManager* GetEraFlipperManager()
		{
			return ((::RPG::Client::EraFlipperManager*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETERAFLIPPERMANAGER_OFFSET))();
		}

		static ::System::Int32 GetMapRotationMaxEnergy()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONMAXENERGY_OFFSET))();
		}

		static ::System::Int32 GetMapRotationCurrentEnergy()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMAPROTATIONCURRENTENERGY_OFFSET))();
		}

		static ::System::Boolean CanPutMapPoseSwitcher()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CANPUTMAPPOSESWITCHER_OFFSET))();
		}

		static ::System::Boolean HasStaticAIPathway(::RPG::Client::MapNpcDef* a1)
		{
			return ((::System::Boolean(*)(::RPG::Client::MapNpcDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_HASSTATICAIPATHWAY_OFFSET))(a1);
		}

		static ::System::Void TryAttackEntityByLevel(::RPG::GameCore::GameEntity* a1, ::System::Collections::Generic::IEnumerable_1<::RPG::GameCore::GameEntity*>* a2, ::Enum_3_4608E37A1B3D374A_23 a3, ::System::Int32& a4, ::System::Int32& a5)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::System::Collections::Generic::IEnumerable_1<::RPG::GameCore::GameEntity*>*, ::Enum_3_4608E37A1B3D374A_23, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRYATTACKENTITYBYLEVEL_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Void TriggerModifierOnBeforeBattle(::RPG::GameCore::GameEntity* a1, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a2, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntityList*>* a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntityList*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRIGGERMODIFIERONBEFOREBATTLE_OFFSET))(a1, a2, a3);
		}

		static ::System::Void TriggerEntityOnBeforeBattle(::RPG::GameCore::GameEntity* a1, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a2)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRIGGERENTITYONBEFOREBATTLE_OFFSET))(a1, a2);
		}

		static ::System::Void CalcTargetListEnterSummonUnitTrigger(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::AdventureAttackDetectSummonUnitTriggerConfig* a2, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureAttackDetectSummonUnitTriggerConfig*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CALCTARGETLISTENTERSUMMONUNITTRIGGER_OFFSET))(a1, a2, a3);
		}

		static ::System::Void CalcEffectiveHitEntityList(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::AdventureHitConfig* a2, ::System::Boolean a3, ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* a4, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a5, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a6, ::RPG::GameCore::AdvEnterBattleSelectTargetType a7)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureHitConfig*, ::System::Boolean, ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*, ::RPG::GameCore::AdvEnterBattleSelectTargetType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CALCEFFECTIVEHITENTITYLIST_OFFSET))(a1, a2, a3, a4, a5, a6, a7);
		}

		static ::RPG::GameCore::StageType GetNpcMonsterStageType(::RPG::GameCore::NPCComponent* a1)
		{
			return ((::RPG::GameCore::StageType(*)(::RPG::GameCore::NPCComponent*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETNPCMONSTERSTAGETYPE_OFFSET))(a1);
		}

		static ::System::Boolean IsValidTriggerBattleEntityType(::RPG::GameCore::EntityType a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::EntityType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISVALIDTRIGGERBATTLEENTITYTYPE_OFFSET))(a1);
		}

		static ::System::Void ProcessAttackResultDirectKill(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::AdventureDyingParam* a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureDyingParam*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_PROCESSATTACKRESULTDIRECTKILL_OFFSET))(a1, a2, a3);
		}

		static ::Class_1_1826B7898EFE06BA* AcquireAdvSkillServerRspCheckRecords()
		{
			return ((::Class_1_1826B7898EFE06BA*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ACQUIREADVSKILLSERVERRSPCHECKRECORDS_OFFSET))();
		}

		static ::System::Void AddAdvSkillServerRspCheckRecords(::System::UInt32 a1, ::Class_1_1826B7898EFE06BA* a2)
		{
			return ((::System::Void(*)(::System::UInt32, ::Class_1_1826B7898EFE06BA*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ADDADVSKILLSERVERRSPCHECKRECORDS_OFFSET))(a1, a2);
		}

		static ::System::Void _FaceHitTargetToAttack(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__FACEHITTARGETTOATTACK_OFFSET))(a1, a2, a3);
		}

		static ::RPG::GameCore::AdventureSkillType GetBelongingAdvSkillType(::Class_1_A2D8E5AB4B623162* a1)
		{
			return ((::RPG::GameCore::AdventureSkillType(*)(::Class_1_A2D8E5AB4B623162*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETBELONGINGADVSKILLTYPE_OFFSET))(a1);
		}

		static ::System::Boolean IsAdventureMazeSkill(::Class_1_A2D8E5AB4B623162* a1)
		{
			return ((::System::Boolean(*)(::Class_1_A2D8E5AB4B623162*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISADVENTUREMAZESKILL_OFFSET))(a1);
		}

		static ::System::Void ProcessOnHitEffect(::RPG::GameCore::GameEntity* a1, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a2, ::RPG::GameCore::AdventureHitConfig* a3, ::Class_1_0F1ECB28664B98E3* a4)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*, ::RPG::GameCore::AdventureHitConfig*, ::Class_1_0F1ECB28664B98E3*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_PROCESSONHITEFFECT_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Void ProcessOnHitEffect_1(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::AdventureHitConfig* a3, ::Class_1_0F1ECB28664B98E3* a4)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureHitConfig*, ::Class_1_0F1ECB28664B98E3*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_PROCESSONHITEFFECT_1_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Void NotifyEntityUIScale(::RPG::GameCore::GameEntity* a1, ::System::Single a2, ::RPG::GameCore::CharacterModelScaleEventParam* a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::System::Single, ::RPG::GameCore::CharacterModelScaleEventParam*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_NOTIFYENTITYUISCALE_OFFSET))(a1, a2, a3);
		}

		static ::System::Void ProcessNPCOnHitEffect(::UnityEngine::Vector3 a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::AdventureHitConfig* a3, ::Class_1_CC76D1702CC17C09_5* a4)
		{
			return ((::System::Void(*)(::UnityEngine::Vector3, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureHitConfig*, ::Class_1_CC76D1702CC17C09_5*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_PROCESSNPCONHITEFFECT_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Void ProcessHitAnimAndEffect(::UnityEngine::Vector3 a1, ::RPG::GameCore::GameEntity* a2, ::System::Boolean a3, ::System::String* a4, ::System::String* a5, ::System::Single a6, ::System::Single a7, ::System::Single a8, ::UnityEngine::Vector3& a9, ::Class_1_CC76D1702CC17C09_5* a10)
		{
			return ((::System::Void(*)(::UnityEngine::Vector3, ::RPG::GameCore::GameEntity*, ::System::Boolean, ::System::String*, ::System::String*, ::System::Single, ::System::Single, ::System::Single, ::UnityEngine::Vector3&, ::Class_1_CC76D1702CC17C09_5*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_PROCESSHITANIMANDEFFECT_OFFSET))(a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
		}

		static ::System::Int32 GetCurrentSkillIndex(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Int32(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTSKILLINDEX_OFFSET))(a1);
		}

		static ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* CalculateAttackRangeEnemyList(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::UnityEngine::Collider* a3, ::RPG::GameCore::AdventureAttackDetectShapeConfig* a4, ::System::Boolean a5)
		{
			return ((::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::UnityEngine::Collider*, ::RPG::GameCore::AdventureAttackDetectShapeConfig*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CALCULATEATTACKRANGEENEMYLIST_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Void TriggerWaterInteractByAttack(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::AdventureAttackDetectShapeConfig* a3)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::AdventureAttackDetectShapeConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRIGGERWATERINTERACTBYATTACK_OFFSET))(a1, a2, a3);
		}

		static ::System::Boolean CheckLocalPlayerCanInteractOption()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CHECKLOCALPLAYERCANINTERACTOPTION_OFFSET))();
		}

		static ::RPG::GameCore::EntitySpawnConfig* GetEntitySpawnConfig(::RPG::Client::MapEntityDef* a1)
		{
			return ((::RPG::GameCore::EntitySpawnConfig*(*)(::RPG::Client::MapEntityDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITYSPAWNCONFIG_OFFSET))(a1);
		}

		static ::UnityEngine::Vector3 GetEntitySpawnPosition(::RPG::Client::MapEntityDef* a1)
		{
			return ((::UnityEngine::Vector3(*)(::RPG::Client::MapEntityDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETENTITYSPAWNPOSITION_OFFSET))(a1);
		}

		static ::RPG::GameCore::AdventureBehaviorConfig* GetBehaviorConfig(::RPG::GameCore::AdventureModifierBehaviorFlag a1)
		{
			return ((::RPG::GameCore::AdventureBehaviorConfig*(*)(::RPG::GameCore::AdventureModifierBehaviorFlag))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETBEHAVIORCONFIG_OFFSET))(a1);
		}

		static ::System::Boolean IsSameFloor(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISSAMEFLOOR_OFFSET))(a1, a2);
		}

		static ::System::Boolean IsEntityInMap(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISENTITYINMAP_OFFSET))(a1, a2);
		}

		static ::System::String* GetCurrentAdventureMapInfo()
		{
			return ((::System::String*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTADVENTUREMAPINFO_OFFSET))();
		}

		static ::System::Boolean GetCurrentAdventureMapInfo_1(::System::UInt32& a1, ::System::UInt32& a2)
		{
			return ((::System::Boolean(*)(::System::UInt32&, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTADVENTUREMAPINFO_1_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::GameEntity* TaskGetValidTarget(::RPG::GameCore::TaskContext* a1, ::RPG::GameCore::TargetEvaluator* a2)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::RPG::GameCore::TaskContext*, ::RPG::GameCore::TargetEvaluator*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TASKGETVALIDTARGET_OFFSET))(a1, a2);
		}

		static ::System::Void GetNpcBornTransform(::RPG::Client::MapNpcDef* a1, ::UnityEngine::Vector3& a2, ::UnityEngine::Quaternion& a3)
		{
			return ((::System::Void(*)(::RPG::Client::MapNpcDef*, ::UnityEngine::Vector3&, ::UnityEngine::Quaternion&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETNPCBORNTRANSFORM_OFFSET))(a1, a2, a3);
		}

		static ::System::Boolean HasUnfinishedMapObjectRefreshTask()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_HASUNFINISHEDMAPOBJECTREFRESHTASK_OFFSET))();
		}

		static ::System::Boolean CanShowEntityIcon(::RPG::Client::MapEntityDef* a1)
		{
			return ((::System::Boolean(*)(::RPG::Client::MapEntityDef*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_CANSHOWENTITYICON_OFFSET))(a1);
		}

		static ::UnityEngine::Collider* TryGetSkillPointCollider(::RPG::GameCore::GameEntity* a1, ::UnityEngine::Transform* a2)
		{
			return ((::UnityEngine::Collider*(*)(::RPG::GameCore::GameEntity*, ::UnityEngine::Transform*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_TRYGETSKILLPOINTCOLLIDER_OFFSET))(a1, a2);
		}

		static ::System::Boolean GetCurrentFastDeliverFinishState()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTFASTDELIVERFINISHSTATE_OFFSET))();
		}

		static ::System::Boolean GetCurrentFastDeliverFocusTarget()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTFASTDELIVERFOCUSTARGET_OFFSET))();
		}

		static ::System::Boolean GetCurrentFastDeliverAimFinish()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETCURRENTFASTDELIVERAIMFINISH_OFFSET))();
		}

		static ::System::Boolean IsAnyFastDeliverPuzzlePlaying()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISANYFASTDELIVERPUZZLEPLAYING_OFFSET))();
		}

		static ::System::Void EntityLeaveAvailable(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ENTITYLEAVEAVAILABLE_OFFSET))(a1);
		}

		static ::System::Void EntityEnterAvailable(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ENTITYENTERAVAILABLE_OFFSET))(a1);
		}

		static ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* _FilteredAttackDetect(::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::GameEntity* a3, ::UnityEngine::Collider* a4, ::System::Boolean a5)
		{
			return ((::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*(*)(::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::UnityEngine::Collider*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__FILTEREDATTACKDETECT_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Boolean _CompareCollsionResultConflict(::Struct_2_591DD46947F040CB& a1, ::Struct_2_591DD46947F040CB& a2)
		{
			return ((::System::Boolean(*)(::Struct_2_591DD46947F040CB&, ::Struct_2_591DD46947F040CB&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__COMPARECOLLSIONRESULTCONFLICT_OFFSET))(a1, a2);
		}

		static ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* _AttackDetectByBoxConfig(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::UnityEngine::Collider* a3, ::RPG::GameCore::AdventureAttackDetectShapeConfig* a4, ::System::Boolean a5)
		{
			return ((::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::UnityEngine::Collider*, ::RPG::GameCore::AdventureAttackDetectShapeConfig*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__ATTACKDETECTBYBOXCONFIG_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* _AttackDetectBySphereConfig(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::UnityEngine::Collider* a3, ::RPG::GameCore::AdventureAttackDetectShapeConfig* a4, ::System::Boolean a5)
		{
			return ((::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::UnityEngine::Collider*, ::RPG::GameCore::AdventureAttackDetectShapeConfig*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__ATTACKDETECTBYSPHERECONFIG_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* _AttackDetectByCircleConfig(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::UnityEngine::Collider* a3, ::RPG::GameCore::AdventureAttackDetectShapeConfig* a4, ::System::Boolean a5)
		{
			return ((::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::UnityEngine::Collider*, ::RPG::GameCore::AdventureAttackDetectShapeConfig*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__ATTACKDETECTBYCIRCLECONFIG_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Void _AppendAttackOcclusionExcludeList(::System::Collections::Generic::List_1<::UnityEngine::Transform*>* a1, ::RPG::GameCore::GameEntity* a2)
		{
			return ((::System::Void(*)(::System::Collections::Generic::List_1<::UnityEngine::Transform*>*, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__APPENDATTACKOCCLUSIONEXCLUDELIST_OFFSET))(a1, a2);
		}

		static ::System::Boolean _AttackOcclusion(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::GameEntity* a2, ::Struct_2_591DD46947F040CB a3, ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* a4)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::GameEntity*, ::RPG::GameCore::GameEntity*, ::Struct_2_591DD46947F040CB, ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__ATTACKOCCLUSION_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Boolean _CheckIsChildOfAny(::UnityEngine::Transform* a1, ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>* a2)
		{
			return ((::System::Boolean(*)(::UnityEngine::Transform*, ::System::Collections::Generic::List_1<::Struct_2_591DD46947F040CB>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC__CHECKISCHILDOFANY_OFFSET))(a1, a2);
		}

		static ::System::Collections::Generic::Dictionary_2<::System::String*, ::System::String*>* GetAdventureBasicInfo()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::String*, ::System::String*>*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETADVENTUREBASICINFO_OFFSET))();
		}

		static ::System::Boolean IsPerformanceReplaying()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISPERFORMANCEREPLAYING_OFFSET))();
		}

		static ::System::Collections::Generic::Dictionary_2<::System::String*, ::System::String*>* GetPerformanceReplayInfo()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::String*, ::System::String*>*(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETPERFORMANCEREPLAYINFO_OFFSET))();
		}

		static ::Il2CppArray<::RPG::GameCore::FixPoint>* GenerateDynamicBuffParams(::RPG::GameCore::AdventureModifierInstance* a1, ::Il2CppArray<::RPG::GameCore::FixPoint>* a2)
		{
			return ((::Il2CppArray<::RPG::GameCore::FixPoint>*(*)(::RPG::GameCore::AdventureModifierInstance*, ::Il2CppArray<::RPG::GameCore::FixPoint>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GENERATEDYNAMICBUFFPARAMS_OFFSET))(a1, a2);
		}

		static ::RPG::GameCore::HoyoTagContainer* GetNPCTags(::RPG::GameCore::LevelNPCInfo* a1)
		{
			return ((::RPG::GameCore::HoyoTagContainer*(*)(::RPG::GameCore::LevelNPCInfo*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETNPCTAGS_OFFSET))(a1);
		}

		static ::System::String* GetAvatarNameIndexFromJsonPath(::System::String* a1)
		{
			return ((::System::String*(*)(::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETAVATARNAMEINDEXFROMJSONPATH_OFFSET))(a1);
		}

		static ::System::String* GetLocalPlayerNameIndexFromJsonPath(::System::String* a1)
		{
			return ((::System::String*(*)(::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETLOCALPLAYERNAMEINDEXFROMJSONPATH_OFFSET))(a1);
		}

		static ::System::String* GetMonsterNameIndexFromTemplatePrefabPath(::System::String* a1)
		{
			return ((::System::String*(*)(::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_GETMONSTERNAMEINDEXFROMTEMPLATEPREFABPATH_OFFSET))(a1);
		}

		static ::System::Boolean IsReShaModuleActive()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_ADVENTURESTATIC_ISRESHAMODULEACTIVE_OFFSET))();
		}
	};
}
