#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/DitherSourcePriority.h"
#include "unitysdk/RPG/Client/ReasonBool_1.h"
#include "unitysdk/RPG/GameCore/CharacterForceVisibleReason.h"
#include "unitysdk/RPG/GameCore/CharacterVisibilityFollowState.h"
#include "unitysdk/RPG/GameCore/CharacterVisibleComponent_AttachmentVisibilityInfo.h"
#include "unitysdk/RPG/GameCore/CharacterVisibleComponent_ShadowVisibleSource.h"
#include "unitysdk/RPG/GameCore/CharacterVisibleReason.h"
#include "unitysdk/RPG/GameCore/CharacterVisiblityFollowFlag.h"
#include "unitysdk/RPG/GameCore/ColliderEnableReason.h"
#include "unitysdk/RPG/GameCore/GameComponentBase.h"
#include "unitysdk/RPG/GameCore/HitboxEnableReason.h"
#include "unitysdk/Struct_2_6E7CE7203DFFA724.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_573;
class Class_0_16E4307DCC419505_575;
class Class_1_0DD2EC99154A46F0;
class Class_1_B68CA618BEA3A2C8;
namespace RPG::Client { class EntityCollisionBodyParts; }
namespace RPG::CustomRP { class CapsuleOcclusion; }
namespace RPG::GameCore { class CharacterVisibleComponent_HideAttachPointInfo; }
namespace RPG::GameCore { class ColliderGroup; }
namespace RPG::GameCore { class GameEntity; }
namespace RPG::GameCore { class GroupedColliderConfig; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class IEnumerable_1; }
namespace System::Collections::Generic { template <typename T> class IEnumerator_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class Animator; }
namespace UnityEngine { class Collider; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class ParticleSystem; }
namespace UnityEngine { class Renderer; }
namespace UnityEngine { class SkinnedMeshRenderer; }
namespace UnityEngine { class Transform; }

#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ALIGNHITBOXTOROOTPOINT_OFFSET UNITYSDK_OFFSET(0xD9FE990)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_DECINVISIBLECOUNTER_OFFSET UNITYSDK_OFFSET(0xDA04190)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_DISPOSE_OFFSET UNITYSDK_OFFSET(0xDA00FC0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLEARTNODECOLLIDERS_OFFSET UNITYSDK_OFFSET(0xD9FDC70)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLECOLLIDERSBYGROUP_OFFSET UNITYSDK_OFFSET(0xD9FC2B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLECOLLIDERSBYLAYER_OFFSET UNITYSDK_OFFSET(0xD9FDA00)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLEHITBOX_OFFSET UNITYSDK_OFFSET(0xD9FE130)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLESETSTENCILREFANDFACE_OFFSET UNITYSDK_OFFSET(0xDA061E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_FORCESETSTENCILINDEX_OFFSET UNITYSDK_OFFSET(0xDA05C20)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWERSRECUSIVELY_OFFSET UNITYSDK_OFFSET(0xD9FB020)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWERS_OFFSET UNITYSDK_OFFSET(0xD9FAFA0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWTARGETSRECUSIVELY_OFFSET UNITYSDK_OFFSET(0xD9FB080)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWTARGET_OFFSET UNITYSDK_OFFSET(0xD9FAED0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETHEADFOLLOWTARGET_OFFSET UNITYSDK_OFFSET(0xD9FAF30)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETISMUTE_OFFSET UNITYSDK_OFFSET(0xDA097A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETMAINCOLLIDERENABLEEXCEPTREASON_OFFSET UNITYSDK_OFFSET(0xDA09460)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETMAINCOLLIDERENABLE_OFFSET UNITYSDK_OFFSET(0xDA08430)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETMAINCOLLIDER_OFFSET UNITYSDK_OFFSET(0xDA09410)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETPROTOTYPERENDERERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA026D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETRENDERBOUNDSHEIGHT_OFFSET UNITYSDK_OFFSET(0xDA053C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETSTENCILEYE_OFFSET UNITYSDK_OFFSET(0xDA05D40)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ACTIVEGROUPNAME_OFFSET UNITYSDK_OFFSET(0xD9FD9A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ATTACHMENTVISIBILITYLIST_OFFSET UNITYSDK_OFFSET(0xDA093C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_CHARACTERMATERIALEFFECTVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA09360)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_CHARACTERSTEALTHSTATE_OFFSET UNITYSDK_OFFSET(0xDA09380)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_COLLISIONBODYPARTSCOMPT_OFFSET UNITYSDK_OFFSET(0xDA093D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_DITHERALPHAVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA09320)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_DITHERHIDEREASON_OFFSET UNITYSDK_OFFSET(0xDA09340)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_EFFECTLOADINGHIDECOUNT_OFFSET UNITYSDK_OFFSET(0xDA093F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_GROUPEDCOLLIDERHIERACHYFLAG_OFFSET UNITYSDK_OFFSET(0xD9FCEC0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_HITBOXENABLE_OFFSET UNITYSDK_OFFSET(0xD9FE2B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ISFORBIDCAMERADITHER_OFFSET UNITYSDK_OFFSET(0xDA092A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ISONLYINVISIBLEBYCAMERADITHER_OFFSET UNITYSDK_OFFSET(0xDA090F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ISRAWRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA09290)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_RENDERERCOUNT_OFFSET UNITYSDK_OFFSET(0xDA092C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_RENDERVISIBLEIGNOREDITHER_OFFSET UNITYSDK_OFFSET(0xDA091C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_RENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA06BC0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_SHADOWVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA093A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_VISIBILITYFOLLOWFLAG_OFFSET UNITYSDK_OFFSET(0xD9FB5B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_VISIBLEFOLLOWOPTVERSION_OFFSET UNITYSDK_OFFSET(0xD9FB5C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET__FORCERENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA090D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET__RAWRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA090E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_HASRENDERINGLAYERMASK_OFFSET UNITYSDK_OFFSET(0xDA032E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_INCINVISIBLECOUNTER_OFFSET UNITYSDK_OFFSET(0xDA04130)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_INITCOMPONENT_OFFSET UNITYSDK_OFFSET(0xDA013B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISHITBOXACTIVE_OFFSET UNITYSDK_OFFSET(0xD9FE930)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISINVISIBLEBYREASONS_OFFSET UNITYSDK_OFFSET(0xDA05B80)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISNOSHADOWCASTER_OFFSET UNITYSDK_OFFSET(0xDA030D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISVISIBLEIGNOREREASONS_OFFSET UNITYSDK_OFFSET(0xDA05630)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_LOCKSTENCILINDEX_OFFSET UNITYSDK_OFFSET(0xDA06260)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_MUTEAUDIO_OFFSET UNITYSDK_OFFSET(0xDA09020)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELARTLOADED_OFFSET UNITYSDK_OFFSET(0xDA01430)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELARTUNLOADED_OFFSET UNITYSDK_OFFSET(0xDA029E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELREBUILD_OFFSET UNITYSDK_OFFSET(0xD9EACA0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELROOTLOADED_OFFSET UNITYSDK_OFFSET(0xDA02CD0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELROOTUNLOADED_OFFSET UNITYSDK_OFFSET(0xDA02DA0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_POPEFFECTLOADINGHIDE_OFFSET UNITYSDK_OFFSET(0xDA04260)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_PUSHEFFECTLOADINGHIDE_OFFSET UNITYSDK_OFFSET(0xDA041F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_REFRESHFOLLOWVISIBILITYFORDATAVIEW_OFFSET UNITYSDK_OFFSET(0xD9FAD90)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_RELEASECHARACTERHUDVISIBLECONTROL_OFFSET UNITYSDK_OFFSET(0xDA052A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_RELEASESTENCIL_OFFSET UNITYSDK_OFFSET(0xDA05CE0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_RESETTODEFAULT_OFFSET UNITYSDK_OFFSET(0xDA097F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETALLCOLLIDERENABLE_OFFSET UNITYSDK_OFFSET(0xDA09710)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETATTACHMENTVISIBILITY_OFFSET UNITYSDK_OFFSET(0xDA049F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETATTACHPOINTVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA03D10)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETCHARACTERHUDVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA051C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETCOLLIDERENABLEBYRELATIVEPATH_OFFSET UNITYSDK_OFFSET(0xDA002E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETDITHERALPHAVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA03A00)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETENTITYVISIBLEPARAM_OFFSET UNITYSDK_OFFSET(0xDA042C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETFOLLOWTARGETVISIBILITY_OFFSET UNITYSDK_OFFSET(0xD9FAA30)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETFORCEVISIBLE_OFFSET UNITYSDK_OFFSET(0xD9FADF0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETMAINCOLLIDERENABLE_OFFSET UNITYSDK_OFFSET(0xDA09510)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETNOSHADOWCASTER_OFFSET UNITYSDK_OFFSET(0xDA03120)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETPARTICLESYSTEMOPEN_OFFSET UNITYSDK_OFFSET(0xDA038D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETPROTOTYPERENDERERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA04580)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETRENDERINGLAYERMASK_OFFSET UNITYSDK_OFFSET(0xDA033E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSHADOWCASTINGMODE_OFFSET UNITYSDK_OFFSET(0xDA03550)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSHADOWVISIBLE_OFFSET UNITYSDK_OFFSET(0xD9E33F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSKINABLE_OFFSET UNITYSDK_OFFSET(0xDA048D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSKINNINGENABLE_OFFSET UNITYSDK_OFFSET(0xDA03740)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSTENCILINDEX_OFFSET UNITYSDK_OFFSET(0xDA05C80)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA03A70)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_CHARACTERMATERIALEFFECTVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA09370)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_CHARACTERSTEALTHSTATE_OFFSET UNITYSDK_OFFSET(0xDA09390)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_COLLISIONBODYPARTSCOMPT_OFFSET UNITYSDK_OFFSET(0xDA093E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_DITHERALPHAVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA09330)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_DITHERHIDEREASON_OFFSET UNITYSDK_OFFSET(0xDA09350)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_EFFECTLOADINGHIDECOUNT_OFFSET UNITYSDK_OFFSET(0xDA09400)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_ISFORBIDCAMERADITHER_OFFSET UNITYSDK_OFFSET(0xDA092B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_VISIBLEFOLLOWOPTVERSION_OFFSET UNITYSDK_OFFSET(0xD9FB5D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SYNCBODYPARTSANIMATORS_OFFSET UNITYSDK_OFFSET(0xD9FE6F0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TEAMLEADERCHANGESWAPVISIBLEANDPHYSICSATTRIBUTE_OFFSET UNITYSDK_OFFSET(0xDA081A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TEMPSETMODELVISBLE_OFFSET UNITYSDK_OFFSET(0xDA062B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TICK_OFFSET UNITYSDK_OFFSET(0xDA02E90)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TRYREFRESHRENDERLIST_OFFSET UNITYSDK_OFFSET(0xDA05320)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_UNMUTEAUDIO_OFFSET UNITYSDK_OFFSET(0xDA08F70)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_UPDATEBOUNDS_OFFSET UNITYSDK_OFFSET(0xDA076E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CCTOR_OFFSET UNITYSDK_OFFSET(0xDA0A2E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CHECKISFOLLOWINGRECUSIVELY_OFFSET UNITYSDK_OFFSET(0xD9FAC90)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CHECKVISIBLITYFOLLOW_OFFSET UNITYSDK_OFFSET(0xD9FB100)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__COLLECTARTNODECOLLIDERS_OFFSET UNITYSDK_OFFSET(0xD9FC680)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CTOR_OFFSET UNITYSDK_OFFSET(0xDA09D00)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__DISPOSEFOLLOWINFOS_OFFSET UNITYSDK_OFFSET(0xD9FB4E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETMAINCOLLIDERENABLE_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FCED0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETMAINCOLLIDERENABLE_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FF080)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETRENDERERINDEX_OFFSET UNITYSDK_OFFSET(0xDA07F40)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETVISIBILITYTRANSMITIONSTATE_OFFSET UNITYSDK_OFFSET(0xD9FB3C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITATTACHMENTVISIBILITY_OFFSET UNITYSDK_OFFSET(0xDA02790)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITCOLLIDERGROUPS_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FC200)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITDEFAULTARTCOLLIDERENABLEFLAG_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FFE00)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITDEFAULTLAYERSTATE_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FB810)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITHIERACHYFLAG_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FB5E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITHITBOXCOLLIDER_OFFSET UNITYSDK_OFFSET(0xD9FD0B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITMAINCOLLIDER_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FB750)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITMAINCOLLIDER_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FEE00)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITOTHERCOLLIDERSUNDERROOT_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FB940)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__ISAUDIONPC_OFFSET UNITYSDK_OFFSET(0xD9FA780)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__ISAUDIOPROP_OFFSET UNITYSDK_OFFSET(0xD9FA830)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__ONINITOWNERREF_OFFSET UNITYSDK_OFFSET(0xDA00F60)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__POSTINVISIBLEAUDIOEVENT_OFFSET UNITYSDK_OFFSET(0xD9FA8E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__POSTVISIBLEAUDIOEVENT_OFFSET UNITYSDK_OFFSET(0xD9FA4B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTLOAD_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FC630)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTLOAD_LEGACY_OFFSET UNITYSDK_OFFSET(0xDA00BE0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTUNLOAD_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FCD40)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTUNLOAD_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FFD10)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTLOADED_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FB6C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTLOADED_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FF3B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTUNLOAD_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FC5C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTUNLOAD_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FF2C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSSHADOWVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA03170)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__RECOVERARTNODECOLLIDERSDEFAULTSTATE_OFFSET UNITYSDK_OFFSET(0xD9FCD90)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__RECOVERHITBOXCOLLIDER_OFFSET UNITYSDK_OFFSET(0xD9FE2C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__RECOVERMODELPROPERTYONARTUNLOAD_OFFSET UNITYSDK_OFFSET(0xDA08660)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHARTNODECOLLIDERSSTATE_OFFSET UNITYSDK_OFFSET(0xD9FCC30)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHATTACHPOINTVISIBLERENDERERINDEX_OFFSET UNITYSDK_OFFSET(0xDA07CE0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHFORCEVISIBLEREASONINDEX_OFFSET UNITYSDK_OFFSET(0xDA03BF0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHGROUPEDCOLLIDERSSTATE_OFFSET UNITYSDK_OFFSET(0xD9FD6A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHMODELPROPERTYONARTLOAD_OFFSET UNITYSDK_OFFSET(0xDA084D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHRELATEDFOLLOWVISIBILITYSTATES_OFFSET UNITYSDK_OFFSET(0xD9FAD10)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHSELFANDFOLLOWERVISIBILITY_OFFSET UNITYSDK_OFFSET(0xD9FB300)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHSELFFOLLOWVISIBLESTATE_OFFSET UNITYSDK_OFFSET(0xD9FB440)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHSELFVISIBILITYTRANSMITION_OFFSET UNITYSDK_OFFSET(0xD9FB170)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHVISIBLEPROCESS_OFFSET UNITYSDK_OFFSET(0xDA07290)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHVISIBLEREASONINDEX_OFFSET UNITYSDK_OFFSET(0xDA03C80)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLCOLLIDERENABLE_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FDD00)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLCOLLIDERENABLE_LEGACY_OFFSET UNITYSDK_OFFSET(0xDA006D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLNONERENDERCOMPONENTSVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA068C0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA06300)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETATTACHMENTVISIBILITYIMPL_OFFSET UNITYSDK_OFFSET(0xDA04C50)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETCHARACTERHUBWITHVISIBLEWHENBATTLE_OFFSET UNITYSDK_OFFSET(0xDA06FB0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETCHARACTERMODELVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA066A0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETCOLLIDERWITHVISIBLEWHENADVENTURE_OFFSET UNITYSDK_OFFSET(0xDA06C80)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETMAINCOLLIDERENABLE_GROUPED_OFFSET UNITYSDK_OFFSET(0xD9FCF30)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETMAINCOLLIDERENABLE_LEGACY_OFFSET UNITYSDK_OFFSET(0xD9FF0E0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETMAINCOLLIDERENABLE_OFFSET UNITYSDK_OFFSET(0xDA06DA0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETRENDERINGACTORSHADOWFLAG_OFFSET UNITYSDK_OFFSET(0xDA03220)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETRENDERINGLAYERMASK_OFFSET UNITYSDK_OFFSET(0xDA02870)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xDA070D0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETUPENTITYVISIBLEPARAM_OFFSET UNITYSDK_OFFSET(0xDA08990)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETUPEXTRAHITBOXANCHOR_OFFSET UNITYSDK_OFFSET(0xD9FE5B0)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SOLVESETALLCOLLIDERENABLE_LEGACY_OFFSET UNITYSDK_OFFSET(0xDA00A40)
#define RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SWAPVISIBLEINDEX_OFFSET UNITYSDK_OFFSET(0xDA080A0)

namespace RPG::GameCore
{
	inline static constexpr unsigned int CharacterVisibleComponent_TypeDefinitionIndex = 54658;

	class CharacterVisibleComponent : public ::RPG::GameCore::GameComponentBase
	{
	public:
		static ::System::Collections::Generic::List_1<::UnityEngine::Renderer*>** StaticGet__TmpRenderers()
		{
			return (::System::Collections::Generic::List_1<::UnityEngine::Renderer*>**)Il2CppClass::FromTypeDefinitionIndex(CharacterVisibleComponent_TypeDefinitionIndex)->GetStaticField(0x60160);
		}
		static ::Il2CppArray<::System::Int32>** StaticGet__SupportedOtherColliderLayer()
		{
			return (::Il2CppArray<::System::Int32>**)Il2CppClass::FromTypeDefinitionIndex(CharacterVisibleComponent_TypeDefinitionIndex)->GetStaticField(0x60168);
		}
		::System::Collections::Generic::List_1<::UnityEngine::Renderer*>* _ShadowOnlyRenderer; // 0x18
		::RPG::CustomRP::CapsuleOcclusion* _aoCompt; // 0x20
		::System::Collections::Generic::List_1<::System::Int32>* _ProtoTypeRendererEnableFlagList; // 0x28
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _AllOtherCollidersManagedByGroupConfig_Grouped; // 0x30
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _AllOtherCollidersUnderRoot_Grouped; // 0x38
		::System::Collections::Generic::List_1<::UnityEngine::ParticleSystem*>* _CacheParticleSystemCmpts; // 0x40
		::System::Collections::Generic::List_1<::System::Boolean>* _ArtCollidersDefaultState_Grouped; // 0x48
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _HitboxCollider; // 0x50
		::System::Collections::Generic::Dictionary_2<::System::String*, ::Struct_2_6E7CE7203DFFA724>* _VisibleParams; // 0x58
		::System::Collections::Generic::List_1<::UnityEngine::Vector3>* _DefaultHitboxPositions; // 0x60
		::System::Collections::Generic::List_1<::System::UInt32>* _RenderOriginalLayerMask; // 0x68
		::UnityEngine::GameObject* _RootModel; // 0x70
		::Class_1_0DD2EC99154A46F0* _ShadowVisibleSet; // 0x78
		::System::Collections::Generic::List_1<::RPG::GameCore::CharacterVisibleComponent*>* _VisibilityFollowers; // 0x80
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _ExtraBodyPartHitBoxs; // 0x88
		::RPG::GameCore::GroupedColliderConfig* _GroupedColliderConfig; // 0x90
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _ColliderList_Legacy; // 0x98
		::System::Collections::Generic::List_1<::UnityEngine::Transform*>* _ExtraBodyPartAnchor; // 0xA0
		::UnityEngine::Collider* _MainCollider; // 0xA8
		::System::Collections::Generic::List_1<::UnityEngine::Vector3>* _HitboxCenterOffset; // 0xB0
		::System::Collections::Generic::List_1<::UnityEngine::SkinnedMeshRenderer*>* _skinnedMeshRenderers; // 0xB8
		::System::Collections::Generic::List_1<::System::Boolean>* _DefaultColliderEnableFlagList_Legacy; // 0xC0
		::System::Collections::Generic::List_1<::UnityEngine::Renderer*>* _RendererList; // 0xC8
		::RPG::GameCore::ColliderGroup* _ActiveGroup; // 0xD0
		::System::Collections::Generic::Dictionary_2<::System::String*, ::System::Boolean>* _RelatePathColliderEnableAfterModified_Legacy; // 0xD8
		::System::Collections::Generic::List_1<::UnityEngine::SkinnedMeshRenderer*>* _UpdateWhenOffScreenSkinnedMesh; // 0xE0
		::System::Collections::Generic::Dictionary_2<::System::Int32, ::RPG::Client::ReasonBool_1<::RPG::GameCore::ColliderEnableReason>>* _LayerState_Grouped; // 0xE8
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _ArtColliders_Grouped; // 0xF0
		::System::Collections::Generic::List_1<::RPG::GameCore::CharacterVisibleComponent_AttachmentVisibilityInfo>* _AttachmentVisibilityList; // 0xF8
		::System::Collections::Generic::List_1<::System::Boolean>* _DefaultArtColliderEnableFlagList_Legacy; // 0x100
		::Il2CppArray<::Class_0_16E4307DCC419505_575*>* _NoneRenderVisibleComponents; // 0x108
		::System::Collections::Generic::List_1<::UnityEngine::Collider*>* _ArtColliderList_Legacy; // 0x110
		::Class_1_B68CA618BEA3A2C8* _materialGroupContainer; // 0x118
		::System::Collections::Generic::List_1<::UnityEngine::Renderer*>* _ShadowOnRenderer; // 0x120
		::System::Collections::Generic::Dictionary_2<::System::String*, ::RPG::GameCore::CharacterVisibleComponent_HideAttachPointInfo*>* _AttachPointHideReason; // 0x128
		::Class_0_16E4307DCC419505_573* _ModelRef; // 0x130
		::System::Collections::Generic::Dictionary_2<::System::String*, ::System::Boolean>* _RendererEnableStateByPath; // 0x138
		::RPG::GameCore::CharacterVisibleComponent* _FollowVisibilityTargetCmpt; // 0x140
		::System::Collections::Generic::List_1<::System::Int32>* _DefaultProtoTypeRendererEnableFlagList; // 0x148
		::RPG::Client::EntityCollisionBodyParts* _CollisionBodyPartsCompt_k__BackingField; // 0x150
		::System::UInt64 _ReasonRenderVisibleIndex; // 0x158
		::System::UInt64 _HitboxEnableBitset; // 0x160
		::System::Int32 _EffectLoadingHideCount_k__BackingField; // 0x168
		::System::Int32 _boundUpdateGapFrame; // 0x16C
		::System::UInt64 _ReasonMainColliderDisableIndex; // 0x170
		::UnityEngine::Vector3 _DefaultHitboxPosition; // 0x178
		::System::Int32 _boundUpdateFrameIndex; // 0x184
		::RPG::Client::ReasonBool_1<::RPG::GameCore::ColliderEnableReason> _MainColliderEnableAfterModified_GroupedCollider; // 0x188
		::RPG::Client::DitherSourcePriority _DitherHideReason_k__BackingField; // 0x190
		::System::Int32 _RendererVisibilityFlipRemainedDelay; // 0x194
		::System::UInt64 _ReasonRenderForceVisibleIndex; // 0x198
		::RPG::GameCore::CharacterVisibilityFollowState _TransmitVisibilityState; // 0x1A0
		::RPG::GameCore::CharacterVisibilityFollowState _FollowVisibilityState; // 0x1A4
		::System::Nullable_1<::RPG::Client::ReasonBool_1<::RPG::GameCore::ColliderEnableReason>> _AllColliderEnableAfterModified_Legacy; // 0x1A8
		::RPG::GameCore::CharacterVisiblityFollowFlag _VisibilityFollowFlag; // 0x1B8
		::System::Boolean _CharacterStealthState_k__BackingField; // 0x1BA
		::System::Boolean _LockStencilIndex; // 0x1BB
		::System::Boolean _NoShadowCaster; // 0x1BC
		::System::Boolean _MainColliderDefaultEnable; // 0x1BD
		::System::Boolean _DefaultHitboxEnable; // 0x1BE
		::System::Boolean _InvalidMainCollider; // 0x1BF
		::System::Boolean _GroupedColliderHierachyFlag; // 0x1C0
		::System::Boolean _IsForbidCameraDither_k__BackingField; // 0x1C1
		::System::Boolean _needUpdateBounds; // 0x1C2
		::System::Boolean _DitherAlphaVisible_k__BackingField; // 0x1C3
		::System::Int32 _VisibleFollowOptVersion_k__BackingField; // 0x1C4
		::System::Int32 _CustomInvisibleCounter; // 0x1C8
		::System::Nullable_1<::System::UInt32> _RendererLayerMask; // 0x1CC
		::RPG::Client::ReasonBool_1<::RPG::GameCore::ColliderEnableReason> _ArtCollidersEnable_Grouped; // 0x1D8
		::System::Nullable_1<::System::Boolean> _EnableUpdateOffScreen; // 0x1E0
		::System::Boolean _CharacterMaterialEffectVisible_k__BackingField; // 0x1E2
		::System::Nullable_1<::System::Boolean> _EnableSkinning; // 0x1E3
		::System::Nullable_1<::System::Boolean> _ShadowCastingModeVisible; // 0x1E5
		::System::Boolean _IsMute; // 0x1E7
		::System::Boolean _Skinable; // 0x1E8
		::System::Nullable_1<::RPG::Client::ReasonBool_1<::RPG::GameCore::ColliderEnableReason>> _MainColliderEnableAfterModified_Legacy; // 0x1F0

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CCTOR_OFFSET))();
		}

		::System::Void _PostVisibleAudioEvent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__POSTVISIBLEAUDIOEVENT_OFFSET))(this);
		}

		::System::Void _PostInvisibleAudioEvent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__POSTINVISIBLEAUDIOEVENT_OFFSET))(this);
		}

		::System::Boolean _IsAudioNPC()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__ISAUDIONPC_OFFSET))(this);
		}

		::System::Boolean _IsAudioProp()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__ISAUDIOPROP_OFFSET))(this);
		}

		::System::Void SetFollowTargetVisibility(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::CharacterVisiblityFollowFlag a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::CharacterVisiblityFollowFlag))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETFOLLOWTARGETVISIBILITY_OFFSET))(this, a1, a2);
		}

		::System::Void RefreshFollowVisibilityForDataView(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_REFRESHFOLLOWVISIBILITYFORDATAVIEW_OFFSET))(this, a1);
		}

		::RPG::GameCore::GameEntity* GetFollowTarget()
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWTARGET_OFFSET))(this);
		}

		::RPG::GameCore::GameEntity* GetHeadFollowTarget()
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETHEADFOLLOWTARGET_OFFSET))(this);
		}

		::System::Collections::Generic::IEnumerator_1<::RPG::GameCore::CharacterVisibleComponent*>* GetFollowers()
		{
			return ((::System::Collections::Generic::IEnumerator_1<::RPG::GameCore::CharacterVisibleComponent*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWERS_OFFSET))(this);
		}

		::System::Collections::Generic::IEnumerator_1<::RPG::GameCore::CharacterVisibleComponent*>* GetFollowersRecusively()
		{
			return ((::System::Collections::Generic::IEnumerator_1<::RPG::GameCore::CharacterVisibleComponent*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWERSRECUSIVELY_OFFSET))(this);
		}

		::System::Collections::Generic::IEnumerator_1<::RPG::GameCore::CharacterVisibleComponent*>* GetFollowTargetsRecusively()
		{
			return ((::System::Collections::Generic::IEnumerator_1<::RPG::GameCore::CharacterVisibleComponent*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETFOLLOWTARGETSRECUSIVELY_OFFSET))(this);
		}

		::System::Boolean _CheckVisiblityFollow(::System::Boolean& a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CHECKVISIBLITYFOLLOW_OFFSET))(this, a1);
		}

		::System::Boolean _CheckIsFollowingRecusively(::RPG::GameCore::CharacterVisibleComponent* a1, ::RPG::GameCore::CharacterVisibleComponent*& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::CharacterVisibleComponent*, ::RPG::GameCore::CharacterVisibleComponent*&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__CHECKISFOLLOWINGRECUSIVELY_OFFSET))(this, a1, a2);
		}

		::System::Void _RefreshRelatedFollowVisibilityStates()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHRELATEDFOLLOWVISIBILITYSTATES_OFFSET))(this);
		}

		::System::Boolean _RefreshSelfVisibilityTransmition()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHSELFVISIBILITYTRANSMITION_OFFSET))(this);
		}

		::RPG::GameCore::CharacterVisibilityFollowState _GetVisibilityTransmitionState()
		{
			return ((::RPG::GameCore::CharacterVisibilityFollowState(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETVISIBILITYTRANSMITIONSTATE_OFFSET))(this);
		}

		::System::Boolean _RefreshSelfFollowVisibleState()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHSELFFOLLOWVISIBLESTATE_OFFSET))(this);
		}

		::System::Void _RefreshSelfAndFollowerVisibility()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHSELFANDFOLLOWERVISIBILITY_OFFSET))(this);
		}

		::System::Void _DisposeFollowInfos()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__DISPOSEFOLLOWINFOS_OFFSET))(this);
		}

		::RPG::GameCore::CharacterVisiblityFollowFlag get_VisibilityFollowFlag()
		{
			return ((::RPG::GameCore::CharacterVisiblityFollowFlag(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_VISIBILITYFOLLOWFLAG_OFFSET))(this);
		}

		::System::Int32 get_VisibleFollowOptVersion()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_VISIBLEFOLLOWOPTVERSION_OFFSET))(this);
		}

		::System::Void set_VisibleFollowOptVersion(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_VISIBLEFOLLOWOPTVERSION_OFFSET))(this, a1);
		}

		::System::Void _InitHierachyFlag_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITHIERACHYFLAG_GROUPED_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnRootLoaded_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTLOADED_GROUPED_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnRootUnload_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTUNLOAD_GROUPED_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnArtLoad_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTLOAD_GROUPED_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnArtUnLoad_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTUNLOAD_GROUPED_OFFSET))(this);
		}

		::System::Boolean get_GroupedColliderHierachyFlag()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_GROUPEDCOLLIDERHIERACHYFLAG_OFFSET))(this);
		}

		::System::Void _InitMainCollider_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITMAINCOLLIDER_GROUPED_OFFSET))(this);
		}

		::System::Boolean _GetMainColliderEnable_Grouped()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETMAINCOLLIDERENABLE_GROUPED_OFFSET))(this);
		}

		::System::Void _SetMainColliderEnable_Grouped(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETMAINCOLLIDERENABLE_GROUPED_OFFSET))(this, a1, a2);
		}

		::System::Void _InitDefaultLayerState_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITDEFAULTLAYERSTATE_GROUPED_OFFSET))(this);
		}

		::System::Void _InitColliderGroups_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITCOLLIDERGROUPS_GROUPED_OFFSET))(this);
		}

		::System::Void _InitOtherCollidersUnderRoot_Grouped()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITOTHERCOLLIDERSUNDERROOT_GROUPED_OFFSET))(this);
		}

		::System::Void _RefreshGroupedCollidersState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHGROUPEDCOLLIDERSSTATE_OFFSET))(this);
		}

		::System::String* get_ActiveGroupName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ACTIVEGROUPNAME_OFFSET))(this);
		}

		::System::Void EnableCollidersByGroup(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLECOLLIDERSBYGROUP_OFFSET))(this, a1);
		}

		::System::Void EnableCollidersByLayer(::System::Int32 a1, ::System::Boolean a2, ::RPG::GameCore::ColliderEnableReason a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLECOLLIDERSBYLAYER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _CollectArtNodeColliders()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__COLLECTARTNODECOLLIDERS_OFFSET))(this);
		}

		::System::Void _RecoverArtNodeCollidersDefaultState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__RECOVERARTNODECOLLIDERSDEFAULTSTATE_OFFSET))(this);
		}

		::System::Void EnableArtNodeColliders(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLEARTNODECOLLIDERS_OFFSET))(this, a1, a2);
		}

		::System::Void _RefreshArtNodeCollidersState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHARTNODECOLLIDERSSTATE_OFFSET))(this);
		}

		::System::Void _SetAllColliderEnable_Grouped(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLCOLLIDERENABLE_GROUPED_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _InitHitboxCollider(::UnityEngine::Collider* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Collider*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITHITBOXCOLLIDER_OFFSET))(this, a1);
		}

		::System::Void _RecoverHitboxCollider()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__RECOVERHITBOXCOLLIDER_OFFSET))(this);
		}

		::System::Void _SetupExtraHitboxAnchor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETUPEXTRAHITBOXANCHOR_OFFSET))(this);
		}

		::System::Void SyncBodyPartsAnimators(::Il2CppArray<::UnityEngine::Animator*>*& a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::UnityEngine::Animator*>*&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SYNCBODYPARTSANIMATORS_OFFSET))(this, a1);
		}

		::System::Void EnableHitbox(::System::Boolean a1, ::RPG::GameCore::HitboxEnableReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::HitboxEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLEHITBOX_OFFSET))(this, a1, a2);
		}

		::System::Boolean IsHitBoxActive()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISHITBOXACTIVE_OFFSET))(this);
		}

		::System::Void AlignHitBoxToRootPoint()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ALIGNHITBOXTOROOTPOINT_OFFSET))(this);
		}

		::System::Boolean get_HitboxEnable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_HITBOXENABLE_OFFSET))(this);
		}

		::System::Void _InitMainCollider_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITMAINCOLLIDER_LEGACY_OFFSET))(this);
		}

		::System::Boolean _GetMainColliderEnable_Legacy()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETMAINCOLLIDERENABLE_LEGACY_OFFSET))(this);
		}

		::System::Void _SetMainColliderEnable_Legacy(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETMAINCOLLIDERENABLE_LEGACY_OFFSET))(this, a1, a2);
		}

		::System::Void _ProcessCollidersOnRootUnload_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTUNLOAD_LEGACY_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnRootLoaded_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONROOTLOADED_LEGACY_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnArtUnLoad_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTUNLOAD_LEGACY_OFFSET))(this);
		}

		::System::Void _InitDefaultArtColliderEnableFlag_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITDEFAULTARTCOLLIDERENABLEFLAG_LEGACY_OFFSET))(this);
		}

		::System::Void SetColliderEnableByRelativePath(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETCOLLIDERENABLEBYRELATIVEPATH_OFFSET))(this, a1, a2);
		}

		::System::Void _SetAllColliderEnable_Legacy(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLCOLLIDERENABLE_LEGACY_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _SolveSetAllColliderEnable_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SOLVESETALLCOLLIDERENABLE_LEGACY_OFFSET))(this);
		}

		::System::Void _ProcessCollidersOnArtLoad_Legacy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSCOLLIDERSONARTLOAD_LEGACY_OFFSET))(this);
		}

		::System::Void _OnInitOwnerRef()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__ONINITOWNERREF_OFFSET))(this);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_DISPOSE_OFFSET))(this);
		}

		::System::Void InitComponent(::Class_0_16E4307DCC419505_573* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_573*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_INITCOMPONENT_OFFSET))(this, a1);
		}

		::System::Void OnModelArtLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELARTLOADED_OFFSET))(this);
		}

		::System::Void OnModelArtUnloaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELARTUNLOADED_OFFSET))(this);
		}

		::System::Void OnModelRootLoaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELROOTLOADED_OFFSET))(this);
		}

		::System::Void OnModelRootUnloaded()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELROOTUNLOADED_OFFSET))(this);
		}

		::System::Void OnModelRebuild()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ONMODELREBUILD_OFFSET))(this);
		}

		::System::Void Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TICK_OFFSET))(this, a1);
		}

		::System::Boolean IsNoShadowCaster()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISNOSHADOWCASTER_OFFSET))(this);
		}

		::System::Void SetNoShadowCaster()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETNOSHADOWCASTER_OFFSET))(this);
		}

		::System::Void SetShadowVisible(::System::Boolean a1, ::RPG::GameCore::CharacterVisibleComponent_ShadowVisibleSource a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::CharacterVisibleComponent_ShadowVisibleSource, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSHADOWVISIBLE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _ProcessShadowVisible()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__PROCESSSHADOWVISIBLE_OFFSET))(this);
		}

		::System::Void _SetRenderingActorShadowFlag(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETRENDERINGACTORSHADOWFLAG_OFFSET))(this, a1);
		}

		::System::Boolean HasRenderingLayerMask(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_HASRENDERINGLAYERMASK_OFFSET))(this, a1);
		}

		::System::Void SetRenderingLayerMask(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETRENDERINGLAYERMASK_OFFSET))(this, a1, a2);
		}

		::System::Void _SetRenderingLayerMask(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETRENDERINGLAYERMASK_OFFSET))(this, a1, a2);
		}

		::System::Void SetShadowCastingMode(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSHADOWCASTINGMODE_OFFSET))(this, a1);
		}

		::System::Void SetSkinningEnable(::System::Boolean a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSKINNINGENABLE_OFFSET))(this, a1, a2);
		}

		::System::Void SetParticleSystemOpen(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETPARTICLESYSTEMOPEN_OFFSET))(this, a1);
		}

		::System::Void SetDitherAlphaVisible(::System::Boolean a1, ::RPG::Client::DitherSourcePriority a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::Client::DitherSourcePriority))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETDITHERALPHAVISIBLE_OFFSET))(this, a1, a2);
		}

		::System::Boolean _RefreshForceVisibleReasonIndex(::System::Boolean a1, ::RPG::GameCore::CharacterForceVisibleReason a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::CharacterForceVisibleReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHFORCEVISIBLEREASONINDEX_OFFSET))(this, a1, a2);
		}

		::System::Boolean _RefreshVisibleReasonIndex(::System::Boolean a1, ::RPG::GameCore::CharacterVisibleReason a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::CharacterVisibleReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHVISIBLEREASONINDEX_OFFSET))(this, a1, a2);
		}

		::System::Void SetAttachPointVisible(::System::Collections::Generic::List_1<::System::String*>* a1, ::System::Boolean a2, ::RPG::GameCore::CharacterVisibleReason a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::String*>*, ::System::Boolean, ::RPG::GameCore::CharacterVisibleReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETATTACHPOINTVISIBLE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetVisible(::System::Boolean a1, ::System::Boolean a2, ::RPG::GameCore::CharacterVisibleReason a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean, ::RPG::GameCore::CharacterVisibleReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETVISIBLE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetForceVisible(::System::Boolean a1, ::RPG::GameCore::CharacterForceVisibleReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::CharacterForceVisibleReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETFORCEVISIBLE_OFFSET))(this, a1, a2);
		}

		::System::Void IncInvisibleCounter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_INCINVISIBLECOUNTER_OFFSET))(this);
		}

		::System::Void DecInvisibleCounter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_DECINVISIBLECOUNTER_OFFSET))(this);
		}

		::System::Void PushEffectLoadingHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_PUSHEFFECTLOADINGHIDE_OFFSET))(this);
		}

		::System::Void PopEffectLoadingHide()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_POPEFFECTLOADINGHIDE_OFFSET))(this);
		}

		::System::Void SetEntityVisibleParam(::System::Boolean a1, ::Struct_2_6E7CE7203DFFA724& a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::Struct_2_6E7CE7203DFFA724&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETENTITYVISIBLEPARAM_OFFSET))(this, a1, a2);
		}

		::System::Boolean GetProtoTypeRendererVisible(::UnityEngine::Renderer* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::UnityEngine::Renderer*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETPROTOTYPERENDERERVISIBLE_OFFSET))(this, a1);
		}

		::System::Void SetProtoTypeRendererVisible(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETPROTOTYPERENDERERVISIBLE_OFFSET))(this, a1, a2);
		}

		::System::Void SetSkinable(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSKINABLE_OFFSET))(this, a1);
		}

		::System::Boolean SetAttachmentVisibility(::System::String* a1, ::System::Boolean a2, ::System::Int32 a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*, ::System::Boolean, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETATTACHMENTVISIBILITY_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean _SetAttachmentVisibilityImpl(::System::String* a1, ::System::Boolean a2, ::System::Int32 a3, ::System::Boolean a4)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*, ::System::Boolean, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETATTACHMENTVISIBILITYIMPL_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void _InitAttachmentVisibility()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__INITATTACHMENTVISIBILITY_OFFSET))(this);
		}

		::System::Void SetCharacterHUDVisible(::System::Boolean a1, ::System::Boolean a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETCHARACTERHUDVISIBLE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ReleaseCharacterHUDVisibleControl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_RELEASECHARACTERHUDVISIBLECONTROL_OFFSET))(this);
		}

		::System::Void TryRefreshRenderList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TRYREFRESHRENDERLIST_OFFSET))(this);
		}

		::System::Single GetRenderBoundsHeight()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETRENDERBOUNDSHEIGHT_OFFSET))(this);
		}

		::System::Boolean IsVisibleIgnoreReasons(::System::Collections::Generic::IEnumerable_1<::RPG::GameCore::CharacterVisibleReason>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Collections::Generic::IEnumerable_1<::RPG::GameCore::CharacterVisibleReason>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISVISIBLEIGNOREREASONS_OFFSET))(this, a1);
		}

		::System::Boolean IsInvisibleByReasons(::Il2CppArray<::RPG::GameCore::CharacterVisibleReason>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::CharacterVisibleReason>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ISINVISIBLEBYREASONS_OFFSET))(this, a1);
		}

		::System::Void ForceSetStencilIndex(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_FORCESETSTENCILINDEX_OFFSET))(this, a1);
		}

		::System::Void SetStencilIndex()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETSTENCILINDEX_OFFSET))(this);
		}

		::System::Void ReleaseStencil(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_RELEASESTENCIL_OFFSET))(this, a1);
		}

		::System::Int32 GetStencilEye()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETSTENCILEYE_OFFSET))(this);
		}

		::System::Void EnableSetStencilRefAndFace()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_ENABLESETSTENCILREFANDFACE_OFFSET))(this);
		}

		::System::Void LockStencilIndex(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_LOCKSTENCILINDEX_OFFSET))(this, a1);
		}

		::System::Void TempSetModelVisble(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TEMPSETMODELVISBLE_OFFSET))(this, a1);
		}

		::System::Void _SetCharacterModelVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETCHARACTERMODELVISIBLE_OFFSET))(this, a1);
		}

		::System::Void _SetAllRenderVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLRENDERVISIBLE_OFFSET))(this, a1);
		}

		::System::Void _SetAllNoneRenderComponentsVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETALLNONERENDERCOMPONENTSVISIBLE_OFFSET))(this, a1);
		}

		::System::Void _SetColliderWithVisibleWhenAdventure(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETCOLLIDERWITHVISIBLEWHENADVENTURE_OFFSET))(this, a1);
		}

		::System::Void _SetCharacterHubWithVisibleWhenBattle(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETCHARACTERHUBWITHVISIBLEWHENBATTLE_OFFSET))(this, a1);
		}

		::System::Void _SetRenderVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETRENDERVISIBLE_OFFSET))(this, a1);
		}

		::System::Void _RefreshVisibleProcess()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHVISIBLEPROCESS_OFFSET))(this);
		}

		::System::Void UpdateBounds()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_UPDATEBOUNDS_OFFSET))(this);
		}

		::System::Void _RefreshAttachPointVisibleRendererIndex()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHATTACHPOINTVISIBLERENDERERINDEX_OFFSET))(this);
		}

		::System::Int32 _GetRendererIndex(::UnityEngine::Transform* a1)
		{
			return ((::System::Int32(*)(::PVOID, ::UnityEngine::Transform*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__GETRENDERERINDEX_OFFSET))(this, a1);
		}

		::System::Void _SwapVisibleIndex(::RPG::GameCore::CharacterVisibleComponent* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::CharacterVisibleComponent*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SWAPVISIBLEINDEX_OFFSET))(this, a1);
		}

		::System::Void TeamLeaderChangeSwapVisibleAndPhysicsAttribute(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_TEAMLEADERCHANGESWAPVISIBLEANDPHYSICSATTRIBUTE_OFFSET))(this, a1);
		}

		::System::Void _RefreshModelPropertyOnArtLoad()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__REFRESHMODELPROPERTYONARTLOAD_OFFSET))(this);
		}

		::System::Void _RecoverModelPropertyOnArtUnload()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__RECOVERMODELPROPERTYONARTUNLOAD_OFFSET))(this);
		}

		::System::Void _SetupEntityVisibleParam(::Struct_2_6E7CE7203DFFA724& a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_6E7CE7203DFFA724&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETUPENTITYVISIBLEPARAM_OFFSET))(this, a1);
		}

		::System::Boolean get_RenderVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_RENDERVISIBLE_OFFSET))(this);
		}

		::System::Boolean get_IsOnlyInvisibleByCameraDither()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ISONLYINVISIBLEBYCAMERADITHER_OFFSET))(this);
		}

		::System::Boolean get_RenderVisibleIgnoreDither()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_RENDERVISIBLEIGNOREDITHER_OFFSET))(this);
		}

		::System::Boolean get_IsRawRenderVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ISRAWRENDERVISIBLE_OFFSET))(this);
		}

		::System::Boolean get_IsForbidCameraDither()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ISFORBIDCAMERADITHER_OFFSET))(this);
		}

		::System::Void set_IsForbidCameraDither(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_ISFORBIDCAMERADITHER_OFFSET))(this, a1);
		}

		::System::Int32 get_RendererCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_RENDERERCOUNT_OFFSET))(this);
		}

		::System::Boolean get_DitherAlphaVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_DITHERALPHAVISIBLE_OFFSET))(this);
		}

		::System::Void set_DitherAlphaVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_DITHERALPHAVISIBLE_OFFSET))(this, a1);
		}

		::RPG::Client::DitherSourcePriority get_DitherHideReason()
		{
			return ((::RPG::Client::DitherSourcePriority(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_DITHERHIDEREASON_OFFSET))(this);
		}

		::System::Void set_DitherHideReason(::RPG::Client::DitherSourcePriority a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::DitherSourcePriority))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_DITHERHIDEREASON_OFFSET))(this, a1);
		}

		::System::Boolean get_CharacterMaterialEffectVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_CHARACTERMATERIALEFFECTVISIBLE_OFFSET))(this);
		}

		::System::Void set_CharacterMaterialEffectVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_CHARACTERMATERIALEFFECTVISIBLE_OFFSET))(this, a1);
		}

		::System::Boolean get_CharacterStealthState()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_CHARACTERSTEALTHSTATE_OFFSET))(this);
		}

		::System::Void set_CharacterStealthState(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_CHARACTERSTEALTHSTATE_OFFSET))(this, a1);
		}

		::System::Boolean get_ShadowVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_SHADOWVISIBLE_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::CharacterVisibleComponent_AttachmentVisibilityInfo>* get_AttachmentVisibilityList()
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::CharacterVisibleComponent_AttachmentVisibilityInfo>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_ATTACHMENTVISIBILITYLIST_OFFSET))(this);
		}

		::RPG::Client::EntityCollisionBodyParts* get_CollisionBodyPartsCompt()
		{
			return ((::RPG::Client::EntityCollisionBodyParts*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_COLLISIONBODYPARTSCOMPT_OFFSET))(this);
		}

		::System::Void set_CollisionBodyPartsCompt(::RPG::Client::EntityCollisionBodyParts* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::EntityCollisionBodyParts*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_COLLISIONBODYPARTSCOMPT_OFFSET))(this, a1);
		}

		::System::Int32 get_EffectLoadingHideCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET_EFFECTLOADINGHIDECOUNT_OFFSET))(this);
		}

		::System::Void set_EffectLoadingHideCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SET_EFFECTLOADINGHIDECOUNT_OFFSET))(this, a1);
		}

		::System::Boolean get__ForceRenderVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET__FORCERENDERVISIBLE_OFFSET))(this);
		}

		::System::Boolean get__RawRenderVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GET__RAWRENDERVISIBLE_OFFSET))(this);
		}

		::UnityEngine::Collider* GetMainCollider()
		{
			return ((::UnityEngine::Collider*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETMAINCOLLIDER_OFFSET))(this);
		}

		::System::Boolean GetMainColliderEnable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETMAINCOLLIDERENABLE_OFFSET))(this);
		}

		::System::Boolean GetMainColliderEnableExceptReason(::RPG::GameCore::ColliderEnableReason a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::ColliderEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETMAINCOLLIDERENABLEEXCEPTREASON_OFFSET))(this, a1);
		}

		::System::Void SetMainColliderEnable(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETMAINCOLLIDERENABLE_OFFSET))(this, a1, a2);
		}

		::System::Void _SetMainColliderEnable(::System::Boolean a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT__SETMAINCOLLIDERENABLE_OFFSET))(this, a1, a2);
		}

		::System::Void SetAllColliderEnable(::System::Boolean a1, ::RPG::GameCore::ColliderEnableReason a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::GameCore::ColliderEnableReason, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_SETALLCOLLIDERENABLE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void MuteAudio()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_MUTEAUDIO_OFFSET))(this);
		}

		::System::Void UnmuteAudio()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_UNMUTEAUDIO_OFFSET))(this);
		}

		::System::Boolean GetIsMute()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_GETISMUTE_OFFSET))(this);
		}

		::System::Void ResetToDefault()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_CHARACTERVISIBLECOMPONENT_RESETTODEFAULT_OFFSET))(this);
		}
	};
}
