#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/GameCore/AliveStateMask.h"
#include "unitysdk/RPG/GameCore/CharacterFormationType.h"
#include "unitysdk/RPG/GameCore/CharacterSomatoType.h"
#include "unitysdk/RPG/GameCore/CustomTeamFormationRefreshReason.h"
#include "unitysdk/RPG/GameCore/EntityTypeMask.h"
#include "unitysdk/RPG/GameCore/GameComponentBase.h"
#include "unitysdk/RPG/GameCore/NormalTeamFormationServantState.h"
#include "unitysdk/RPG/GameCore/TeamFormationComponent_DataViewRestoreData.h"
#include "unitysdk/RPG/GameCore/TeamFormationType.h"
#include "unitysdk/RPG/GameCore/TeamLocationType.h"
#include "unitysdk/RPG/GameCore/TeamMemberCountingOption.h"
#include "unitysdk/RPG/GameCore/TeamType.h"
#include "unitysdk/RPG/MQuaternion.h"
#include "unitysdk/RPG/MVector3.h"
#include "unitysdk/Struct_2_2B6684D3E43696AE.h"

class Class_0_16E4307DCC419505_425;
class Class_0_16E4307DCC419505_594;
class Class_1_00BFC1287967D239;
class Class_1_38B626F970688CCD;
class Class_2_BF927CBEA754F6BE;
class Class_3_E03EC9D105CCFA3C;
namespace RPG { template <typename T> class PoolList_1; }
namespace RPG::GameCore { class DarkTeamFightFormationConfig; }
namespace RPG::GameCore { class DarkTeamFightFormationParams; }
namespace RPG::GameCore { class GameEntity; }
namespace RPG::GameCore { class LightTeamFightFormationConfig; }
namespace RPG::GameCore { class LightTeamFightFormationParams; }
namespace RPG::GameCore { class LocationConfig; }
namespace RPG::GameCore { class LocationExtraConfig; }
namespace RPG::GameCore { class TeamFormationComponent_MultiRowLocationContext; }
namespace RPG::GameCore { class TeamFormationComponent_MultiRowTargetSelector; }
namespace RPG::GameCore { class TeamFormationComponent_RowFormationLocationData; }
namespace RPG::GameCore { class TransformComponent; }
namespace System { class Object; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class IList_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace System::Collections::Generic { template <typename T> class Stack_1; }
namespace UnityEngine { class Camera; }

#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ADDCUSTOMUPDATEFORMATION_OFFSET UNITYSDK_OFFSET(0xDBC05B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ADDTEAMMATEENTITY_OFFSET UNITYSDK_OFFSET(0xDBBF530)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CALCNEWENTITYTEAMFORMATIONPOS_OFFSET UNITYSDK_OFFSET(0xDBBD860)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CLEARFORMATIONSNAPSHOT_OFFSET UNITYSDK_OFFSET(0xDBCB0F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CLEARRECORDENTITYFORMATION_OFFSET UNITYSDK_OFFSET(0xDBCADD0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CLEARUSECUSTOMTEAMFORMATION_OFFSET UNITYSDK_OFFSET(0xDBC3770)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CONTAINSMONSTERRANKSCOREKEY_OFFSET UNITYSDK_OFFSET(0xDBCAB90)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CREATEFORMATIONSNAPSHOT_OFFSET UNITYSDK_OFFSET(0xDBCAE30)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_DISPOSE_OFFSET UNITYSDK_OFFSET(0xDBBA210)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETCURRENTDARKTEAMFIGHTFORMATIONCONFIG_OFFSET UNITYSDK_OFFSET(0xDBB9AA0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETCURRENTLIGHTTEAMFIGHTFORMATIONCONFIG_OFFSET UNITYSDK_OFFSET(0xDBC8820)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETDEFAULTDARKTEAMFIGHTFORMATIONCONFIG_OFFSET UNITYSDK_OFFSET(0xDBC88C0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETDEFAULTFACEDIR_OFFSET UNITYSDK_OFFSET(0xDBC3250)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETDEFAULTLIGHTTEAMFIGHTFORMATIONCONFIG_OFFSET UNITYSDK_OFFSET(0xDBC8860)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYBYFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBC1240)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYFORMATIONINCAMERASPACE_OFFSET UNITYSDK_OFFSET(0xDBC12E0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBB6000)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYFORMATIONPOS_OFFSET UNITYSDK_OFFSET(0xDBC10B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYWIDTHBYFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBC1160)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONCENTERWORLDPOSWITHENTITYFILTER_OFFSET UNITYSDK_OFFSET(0xDBC8100)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONDATAS_OFFSET UNITYSDK_OFFSET(0xDBBCBC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONENTITYINCAMERASPACE_OFFSET UNITYSDK_OFFSET(0xDBC1D70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBC9560)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETMAXSOMATOINFORMATION_OFFSET UNITYSDK_OFFSET(0xDBBC2B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETPUPPETENTITYCOUNT_OFFSET UNITYSDK_OFFSET(0xDBBD180)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETROWFORMATIONDATACOUNT_OFFSET UNITYSDK_OFFSET(0xDBBC530)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETROWFORMATIONDATAS_OFFSET UNITYSDK_OFFSET(0xDBBC5B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETROWFORMATIONINDEXRANGE_OFFSET UNITYSDK_OFFSET(0xDBBC790)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETTEAMADJOINENTITY_OFFSET UNITYSDK_OFFSET(0xDBC0F60)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETTEAMENTITYCOUNT_OFFSET UNITYSDK_OFFSET(0xDBB5F60)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETTEAMENTITYLIST_OFFSET UNITYSDK_OFFSET(0xDBBCD80)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETVALIDROWCOUNT_OFFSET UNITYSDK_OFFSET(0xDBBC440)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ALIVEENTITIESFORMATIONCENTERWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBCBB40)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ANYMEMBERUSECUSTOMPOSTION_OFFSET UNITYSDK_OFFSET(0xDBBBBF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_AUTOBALANCEDEFAULTFORMATION_OFFSET UNITYSDK_OFFSET(0xDBD2020)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_COMFORTZONEWIDTHOVERRIDE_OFFSET UNITYSDK_OFFSET(0xDBD2000)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_COMFORTZONEWIDTH_OFFSET UNITYSDK_OFFSET(0xDBD1CC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CURRENTCUSTOMFORMATIONNAME_OFFSET UNITYSDK_OFFSET(0xDBD1EF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CURRENTFORMATIONTYPE_OFFSET UNITYSDK_OFFSET(0xDBD1ED0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CUSTOMFORMATIONCENTERWORLDPOSFROMBOUNDBOX_OFFSET UNITYSDK_OFFSET(0xDBD1F70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CUSTOMFORMATIONCENTERWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBD1F00)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_DEFAULTFORMATIONCENTERENTITY_OFFSET UNITYSDK_OFFSET(0xDBD1E60)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ENEMYFORMATION_OFFSET UNITYSDK_OFFSET(0xDBD1DC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_FORMATIONCENTERWORLDPOSFROMBOUNDBOX_OFFSET UNITYSDK_OFFSET(0xDBCBB00)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_FORMATIONCENTERWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBCBAC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_FORMATIONWIDTH_OFFSET UNITYSDK_OFFSET(0xDBCB700)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_INVERSEFLAG_OFFSET UNITYSDK_OFFSET(0xDBD1FF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ISINCUSTOMFORMATION_OFFSET UNITYSDK_OFFSET(0xDBBBB90)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_LOCATIONROOTWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBCB730)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_LOCKFORMATIONREFRESH_OFFSET UNITYSDK_OFFSET(0xDBCB6D0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_REMOVEVERSIONCOUNTER_OFFSET UNITYSDK_OFFSET(0xDBD1EC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_SERVANTFORMATIONSTATE_OFFSET UNITYSDK_OFFSET(0xDBD1EE0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMFACEDIR_OFFSET UNITYSDK_OFFSET(0xDBCB780)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMFORWARD_OFFSET UNITYSDK_OFFSET(0xDBCB790)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMLEFT_OFFSET UNITYSDK_OFFSET(0xDBCB980)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMROTATION_OFFSET UNITYSDK_OFFSET(0xDBCB760)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMZOFFSET_OFFSET UNITYSDK_OFFSET(0xDBD1FE0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_WAVEOFMONSTERRUNTIMEID_OFFSET UNITYSDK_OFFSET(0xDBCBB80)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_HASSPARETEAMFORMATION_OFFSET UNITYSDK_OFFSET(0xDBBD600)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_IGNOREAROUNDCASTERCALCULATION_OFFSET UNITYSDK_OFFSET(0xDBBD510)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_INITCOMPONENT_OFFSET UNITYSDK_OFFSET(0xDBBA8B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_INVERSEFORMATIONENTITYLIST_OFFSET UNITYSDK_OFFSET(0xDBC0B70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISACTIVEMULTIROW_OFFSET UNITYSDK_OFFSET(0xDBB9CF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISFORMATIONEDGEENTITY_OFFSET UNITYSDK_OFFSET(0xDBB6780)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISFULLFORPUPPET_OFFSET UNITYSDK_OFFSET(0xDBBD4B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISFULL_OFFSET UNITYSDK_OFFSET(0xDBBD3D0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISMEMBERUSECUSTOMPOSTION_OFFSET UNITYSDK_OFFSET(0xDBC3D20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISREMOVINGTEAMMATE_OFFSET UNITYSDK_OFFSET(0xDBBD2C0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MARKLOCATIONDIRTY_OFFSET UNITYSDK_OFFSET(0xDBC80B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MARKMEMBERUSECUSTOMPOSTION_OFFSET UNITYSDK_OFFSET(0xDBC3C80)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MARKTEAMMATEDIRTY_OFFSET UNITYSDK_OFFSET(0xDBC0B20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MODIFYDEFAULTTEAMFORMATION_OFFSET UNITYSDK_OFFSET(0xDBCA3B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ONBATTLEDATAVIEW_OFFSET UNITYSDK_OFFSET(0xDBCB660)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_PREPAREMULTIROWSELECTOR_OFFSET UNITYSDK_OFFSET(0xDBB71B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_PREREMOVETEAMMATEENTITY_OFFSET UNITYSDK_OFFSET(0xDBC0330)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RECORDENTITYFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBCACF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFOLLOWTEAMFOLLOWFORMATIONS_OFFSET UNITYSDK_OFFSET(0xDBC3980)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONBYSNAPSHOT_OFFSET UNITYSDK_OFFSET(0xDBCB280)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONCENTER_OFFSET UNITYSDK_OFFSET(0xDBC0CE0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONFORVIEWMODE_OFFSET UNITYSDK_OFFSET(0xDBBB950)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONINCAMERASPACE_OFFSET UNITYSDK_OFFSET(0xDBC1360)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHLOCATIONLIST_OFFSET UNITYSDK_OFFSET(0xDBBBE50)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REGISTEREVENTS_OFFSET UNITYSDK_OFFSET(0xDBBAB00)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REMOVECUSTOMUPDATEFORMATION_OFFSET UNITYSDK_OFFSET(0xDBC0730)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REMOVETEAMMATEENTITY_OFFSET UNITYSDK_OFFSET(0xDBC03A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETCURRENTTEMPLATECONFIGNAME_OFFSET UNITYSDK_OFFSET(0xDBBAA70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETDEFAULTTEAMFORMATION_OFFSET UNITYSDK_OFFSET(0xDBCA490)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETFACEDIR_OFFSET UNITYSDK_OFFSET(0xDBC2D70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETLEVELAREAROOTASBATTLECENTER_OFFSET UNITYSDK_OFFSET(0xDBC8550)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETLOCATION_OFFSET UNITYSDK_OFFSET(0xDBC2570)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETROOTWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBC1E20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETCURRENTTEMPLATECONFIGNAME_OFFSET UNITYSDK_OFFSET(0xDBBBC50)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETENTITYFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBC0110)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETROOTWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBC2380)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETSERVANTFORCEFOLLOWPOS_OFFSET UNITYSDK_OFFSET(0xDBC7B10)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTEAMMATEENTITYWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBC0C10)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTEAMMATEPOS_1_OFFSET UNITYSDK_OFFSET(0xDBBE6B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTEAMMATEPOS_OFFSET UNITYSDK_OFFSET(0xDBBD6D0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTLETEMPORARYLOCATION_OFFSET UNITYSDK_OFFSET(0xDBC8920)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_ALIVEENTITIESFORMATIONCENTERWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBCBB60)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_COMFORTZONEWIDTHOVERRIDE_OFFSET UNITYSDK_OFFSET(0xDBD2010)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_FORMATIONCENTERWORLDPOSFROMBOUNDBOX_OFFSET UNITYSDK_OFFSET(0xDBCBB20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_FORMATIONCENTERWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBCBAE0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_FORMATIONWIDTH_OFFSET UNITYSDK_OFFSET(0xDBCB6F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_LOCATIONROOTWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBCB710)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_LOCKFORMATIONREFRESH_OFFSET UNITYSDK_OFFSET(0xDBCB6E0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_TEAMFACEDIR_OFFSET UNITYSDK_OFFSET(0xDBCB770)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_TEAMROTATION_OFFSET UNITYSDK_OFFSET(0xDBCB750)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_WAVEOFMONSTERRUNTIMEID_OFFSET UNITYSDK_OFFSET(0xDBCBB90)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SORTENTITYBYFORMATIONINDEXINCLUDEREMOVED_OFFSET UNITYSDK_OFFSET(0xDBC07A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_UNREGISTEREVENTS_OFFSET UNITYSDK_OFFSET(0xDBBA5C0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT_USECUSTOMFORMATION_OFFSET UNITYSDK_OFFSET(0xDBC3500)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__AFTERFORMATIONREFRESH_OFFSET UNITYSDK_OFFSET(0xDBBB9A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__APPLYBACKROWOFFSET_OFFSET UNITYSDK_OFFSET(0xDBB9510)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__APPLYLOCATIONPOSLISTCENTRALOFFSET_OFFSET UNITYSDK_OFFSET(0xDBB8EF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__BALANCEDEFAULTFORMATION_OFFSET UNITYSDK_OFFSET(0xDBCF350)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__BALANCEEDGEFORMATION_OFFSET UNITYSDK_OFFSET(0xDBCE460)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__BALANCEFORMATION_OFFSET UNITYSDK_OFFSET(0xDBBEC00)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CACHELASTDIETEAMMATE_OFFSET UNITYSDK_OFFSET(0xDBBAED0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCEDGEFORMATIONENTITYCOUNT_OFFSET UNITYSDK_OFFSET(0xDBCA510)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCPUPPETAROUNDCASTERINSERTINDEX_OFFSET UNITYSDK_OFFSET(0xDBD07B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCULATEENEMYBACKROWOFFSET_OFFSET UNITYSDK_OFFSET(0xDBC26A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCULATETEAMDISTANCE_OFFSET UNITYSDK_OFFSET(0xDBD13F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__COLLECTFORMATIONBOUNDS_OFFSET UNITYSDK_OFFSET(0xDBCC340)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__COLLECTFORMATIONSWITHCUSTOMTEAMFORMATIONTYPE_OFFSET UNITYSDK_OFFSET(0xDBCBE20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__COLLECTNEXTROWDATAS_OFFSET UNITYSDK_OFFSET(0xDBCE220)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CONVERTFORMATIONINDEX_OFFSET UNITYSDK_OFFSET(0xDBCAA10)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CTOR_OFFSET UNITYSDK_OFFSET(0xDBB9D90)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__DARKTEAMREFRESHLOCATIONLIST_OFFSET UNITYSDK_OFFSET(0xDBC6A70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__DARKTEAMREFRESHLOCATIONLIST_ONEROW_OFFSET UNITYSDK_OFFSET(0xDBB7CB0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FILTERDARKFORMATIONIGNORE_OFFSET UNITYSDK_OFFSET(0xDBB7C00)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FINDBIGBOSSINDEXINDARKTEAM_OFFSET UNITYSDK_OFFSET(0xDBB8D50)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FORCEREFRESHINVERSEDACTIVEROWINDEX_OFFSET UNITYSDK_OFFSET(0xDBCBBA0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FORMATIONINDEXTOPOS_OFFSET UNITYSDK_OFFSET(0xDBBB030)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FORMATIONPOSTOINDEX_OFFSET UNITYSDK_OFFSET(0xDBD0A20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETCOMFORTZONEOFFSET_OFFSET UNITYSDK_OFFSET(0xDBCDFC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETCURRENTCUSTOMFORMATIONCENTER_OFFSET UNITYSDK_OFFSET(0xDBC9700)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETDARKTEAMFIGHTFORMATIONPARAMS_OFFSET UNITYSDK_OFFSET(0xDBB7B20)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETDEFAULTWORLDROOTPOS_OFFSET UNITYSDK_OFFSET(0xDBC20A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETDEFAULTWORLDROOTROT_OFFSET UNITYSDK_OFFSET(0xDBC9390)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETFORMATIONCENTERWORLDPOSWITHENTITYFILTERINTERNAL_OFFSET UNITYSDK_OFFSET(0xDBC98D0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETINSERTENTITYINDEX_OFFSET UNITYSDK_OFFSET(0xDBBFA70)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETLIGHTTEAMFIGHTFORMATIONPARAMS_OFFSET UNITYSDK_OFFSET(0xDBC94E0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETMULTIROWCOMFORTZONEWIDTH_OFFSET UNITYSDK_OFFSET(0xDBB9B30)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETTEAMROTATION_OFFSET UNITYSDK_OFFSET(0xDBCD760)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ISMATCHTEAMMEMBERCOUNTINGOPTION_OFFSET UNITYSDK_OFFSET(0xDBBC8B0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__LIGHTTEAMCUSTOMZOFFSETCALCULATOR_OFFSET UNITYSDK_OFFSET(0xDBC72F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__LIGHTTEAMNORMALCALCULATOR_OFFSET UNITYSDK_OFFSET(0xDBC3D90)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__LIGHTTEAMSELECTTARGETCALCULATOR_OFFSET UNITYSDK_OFFSET(0xDBC5100)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__MOVEPUPPETTOROWINDEX_OFFSET UNITYSDK_OFFSET(0xDBD08F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEACTIVEENTITYCHANGE_OFFSET UNITYSDK_OFFSET(0xDBBB7D0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLECAMERAMODECHANGE_OFFSET UNITYSDK_OFFSET(0xDBBB8F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEEVENTDIE_OFFSET UNITYSDK_OFFSET(0xDBBAF50)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEGAMEPAGEONFRAMECAPTUREDONE_OFFSET UNITYSDK_OFFSET(0xDBBB890)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEONSETCURRENTSKILLINDEX_OFFSET UNITYSDK_OFFSET(0xDBBB830)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBEFORELEVELTURNSTATECHANGEEVENT_OFFSET UNITYSDK_OFFSET(0xDBBB6E0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONCHARACTERDIE_OFFSET UNITYSDK_OFFSET(0xDBBADF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONENTITYUSESKILL_OFFSET UNITYSDK_OFFSET(0xDBBB770)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONVCAMERASTATECHANGE_OFFSET UNITYSDK_OFFSET(0xDBBB210)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__PRECOMPUTEROWWIDTHSHRINKRATIO_OFFSET UNITYSDK_OFFSET(0xDBB78A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__RANDOMLOCALZOFFSET_OFFSET UNITYSDK_OFFSET(0xDBB8B80)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REARRANGEPUPPETCHARACTERS_OFFSET UNITYSDK_OFFSET(0xDBCFD30)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__RECORDENTITYINITIALPROPERTY_OFFSET UNITYSDK_OFFSET(0xDBC0070)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHBACKROWFORMATIONOFFSET_OFFSET UNITYSDK_OFFSET(0xDBB9AF0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHCUSTOMTEAMFORMATIONINFOS_OFFSET UNITYSDK_OFFSET(0xDBBEEC0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHLEVELENTITYTRANSFORM_OFFSET UNITYSDK_OFFSET(0xDBC81A0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHMODELFLIP_OFFSET UNITYSDK_OFFSET(0xDBD0B80)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHTEAMCENTERFOLLOW_OFFSET UNITYSDK_OFFSET(0xDBCC8F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHTEAMMATEINDEX_OFFSET UNITYSDK_OFFSET(0xDBBE900)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHTEAMZOFFSET_OFFSET UNITYSDK_OFFSET(0xDBCD9E0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__SETTEAMMATEENTITYWORLDPOS_OFFSET UNITYSDK_OFFSET(0xDBB90F0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__SORTTEAMCENTERFOLLOWFORMATION_OFFSET UNITYSDK_OFFSET(0xDBCD3C0)
#define RPG_GAMECORE_TEAMFORMATIONCOMPONENT__TRIGGERFORMATIONREFRESHWITHREASON_OFFSET UNITYSDK_OFFSET(0xDBBB270)

namespace RPG::GameCore
{
	inline static constexpr unsigned int TeamFormationComponent_TypeDefinitionIndex = 55133;

	class TeamFormationComponent : public ::RPG::GameCore::GameComponentBase
	{
	public:
		// static const ::RPG::GameCore::TeamMemberCountingOption FormationLimitCheckMask; // 0x0
		// static const ::System::String* _DEFAULT_TEMPLATE_CONFIG_NAME; // 0x0
		::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* _AllTeammate; // 0x18
		::RPG::GameCore::LightTeamFightFormationConfig* _CurrentLightTeamFightFormationConfig; // 0x20
		::Class_1_38B626F970688CCD* _Random; // 0x28
		::System::Collections::Generic::Dictionary_2<::System::String*, ::Class_1_00BFC1287967D239*>* _FormationSnapshots; // 0x30
		::System::Collections::Generic::HashSet_1<::Class_2_BF927CBEA754F6BE*>* _UseCustomFormationMembers; // 0x38
		::System::Collections::Generic::Stack_1<::Struct_2_2B6684D3E43696AE>* _RecordFormationIndices; // 0x40
		::Il2CppArray<::RPG::GameCore::LocationExtraConfig*>* _DefaultLocationExtCfgs2; // 0x48
		::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* _FormationDatasNormal; // 0x50
		::System::String* _CurrentCustomFormationName; // 0x58
		::RPG::GameCore::TeamFormationComponent_MultiRowTargetSelector* _multiRowTargetSelector; // 0x60
		::RPG::GameCore::TeamFormationComponent_MultiRowLocationContext* _TeamRefreshLocationContext; // 0x68
		::System::String* _CurrentUseTemplateConfigName; // 0x70
		::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* _TeamFormationDatas; // 0x78
		::Il2CppArray<::RPG::GameCore::LocationExtraConfig*>* _DefaultLocationExtCfgs; // 0x80
		::RPG::GameCore::DarkTeamFightFormationConfig* _CurrentDarkTeamFightFormationConfig; // 0x88
		::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* _FormationInCameraSpace; // 0x90
		::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* _AllTeammateCopy; // 0x98
		::System::Collections::Generic::List_1<::System::UInt32>* _WaveOfMonsterRuntimeID_k__BackingField; // 0xA0
		::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* _CustomUpdateFormationDatas; // 0xA8
		::Class_2_BF927CBEA754F6BE* _DefaultFormationCenter; // 0xB0
		::System::String* _LastRefreshLocationTemplateConfigName; // 0xB8
		::RPG::MVector3 _FormationCenterWorldPosFromBoundBox_k__BackingField; // 0xC0
		::RPG::MVector3 _FormationCenterWorldPos_k__BackingField; // 0xCC
		::RPG::MVector3 _CustomFormationCenter; // 0xD8
		::System::Int32 _MaxLocationCount; // 0xE4
		::System::UInt32 _RemoveVersionCounter; // 0xE8
		::RPG::MVector3 _CustomFormationCenterFromBoundBox; // 0xEC
		::RPG::MVector3 _AliveEntitiesFormationCenterWorldPos_k__BackingField; // 0xF8
		::System::Boolean _IsTeammateDirty; // 0x104
		::System::Boolean _HasCustomTeamFormation; // 0x105
		::System::Boolean _InverseFlag; // 0x106
		::System::Boolean _AutoBalanceDefaultFormation; // 0x107
		::System::Single _FormationForceWidthMax; // 0x108
		::System::Single _ComfortZoneWidthOverride_k__BackingField; // 0x10C
		::RPG::GameCore::NormalTeamFormationServantState _ServantFormationState; // 0x110
		::Struct_2_2B6684D3E43696AE _LastDieTeammatePos; // 0x114
		::RPG::GameCore::TeamFormationType _CurrentFormationType; // 0x11C
		::RPG::GameCore::TeamType _Team; // 0x120
		::RPG::GameCore::TeamFormationComponent_DataViewRestoreData _dataViewRestoreData; // 0x124
		::System::Single _TeamDistanceCache; // 0x130
		::RPG::MVector3 _LocationRootWorldPos_k__BackingField; // 0x134
		::System::UInt32 _AllowPuppetMaxCount; // 0x140
		::System::Single _TeamFaceDir_k__BackingField; // 0x144
		::System::Single _FormationWidth_k__BackingField; // 0x148
		::System::Single _FormationForceWidthMin; // 0x14C
		::System::Single _TeamZOffset; // 0x150
		::RPG::MVector3 RecordLastMoveTeamOffset; // 0x154
		::RPG::GameCore::AliveStateMask _TeamActiveRowAliveStateFilter; // 0x160
		::RPG::MQuaternion _TeamRotation_k__BackingField; // 0x164
		::System::Boolean _LockFormationRefresh_k__BackingField; // 0x174
		::System::Boolean _CustomFormationCenterDirty; // 0x175
		::System::Boolean _IsLocationDirty; // 0x176
		::System::Boolean _IsInited; // 0x177

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CTOR_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_594* PrepareMultiRowSelector(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::System::Boolean a3, ::System::Boolean a4)
		{
			return ((::Class_0_16E4307DCC419505_594*(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamMemberCountingOption, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_PREPAREMULTIROWSELECTOR_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Single _PrecomputeRowWidthShrinkRatio(::System::Single& a1)
		{
			return ((::System::Single(*)(::PVOID, ::System::Single&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__PRECOMPUTEROWWIDTHSHRINKRATIO_OFFSET))(this, a1);
		}

		::System::Boolean _FilterDarkFormationIgnore(::RPG::GameCore::TeamFormationComponent_RowFormationLocationData* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::TeamFormationComponent_RowFormationLocationData*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FILTERDARKFORMATIONIGNORE_OFFSET))(this, a1);
		}

		::System::Void _DarkTeamRefreshLocationList_OneRow(::System::Single& a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__DARKTEAMREFRESHLOCATIONLIST_ONEROW_OFFSET))(this, a1);
		}

		::System::Void _ApplyBackRowOffset(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__APPLYBACKROWOFFSET_OFFSET))(this, a1);
		}

		::System::Void _RefreshBackRowFormationOffset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHBACKROWFORMATIONOFFSET_OFFSET))(this);
		}

		::System::Single _GetMultiRowComfortZoneWidth()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETMULTIROWCOMFORTZONEWIDTH_OFFSET))(this);
		}

		::System::Boolean IsActiveMultiRow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISACTIVEMULTIROW_OFFSET))(this);
		}

		::System::Int32 _FindBigBossIndexInDarkTeam()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FINDBIGBOSSINDEXINDARKTEAM_OFFSET))(this);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_DISPOSE_OFFSET))(this);
		}

		::System::Void InitComponent(::RPG::GameCore::TeamType a1, ::System::Int32 a2, ::RPG::GameCore::AliveStateMask a3, ::System::UInt32 a4)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TeamType, ::System::Int32, ::RPG::GameCore::AliveStateMask, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_INITCOMPONENT_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void RegisterEvents()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REGISTEREVENTS_OFFSET))(this);
		}

		::System::Void UnRegisterEvents()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_UNREGISTEREVENTS_OFFSET))(this);
		}

		::System::Void _OnCharacterDie(::Class_0_16E4307DCC419505_425* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_425*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONCHARACTERDIE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEventDie(::Class_0_16E4307DCC419505_425* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_425*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEEVENTDIE_OFFSET))(this, a1);
		}

		::System::Void _CacheLastDieTeammate(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CACHELASTDIETEAMMATE_OFFSET))(this, a1);
		}

		::System::Void _OnVCameraStateChange(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONVCAMERASTATECHANGE_OFFSET))(this, a1);
		}

		::System::Void _OnBeforeLevelTurnStateChangeEvent(::Class_0_16E4307DCC419505_425* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_425*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBEFORELEVELTURNSTATECHANGEEVENT_OFFSET))(this, a1);
		}

		::System::Void _OnEntityUseSkill(::Class_0_16E4307DCC419505_425* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_425*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONENTITYUSESKILL_OFFSET))(this, a1);
		}

		::System::Void _OnBattleActiveEntityChange(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEACTIVEENTITYCHANGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleOnSetCurrentSkillIndex(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEONSETCURRENTSKILLINDEX_OFFSET))(this, a1);
		}

		::System::Void _OnBattleGamePageOnFrameCaptureDone(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLEGAMEPAGEONFRAMECAPTUREDONE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleCameraModeChange(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ONBATTLECAMERAMODECHANGE_OFFSET))(this, a1);
		}

		::System::Void RefreshFormationForViewMode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONFORVIEWMODE_OFFSET))(this);
		}

		::System::Void _TriggerFormationRefreshWithReason(::RPG::GameCore::CustomTeamFormationRefreshReason a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::CustomTeamFormationRefreshReason, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__TRIGGERFORMATIONREFRESHWITHREASON_OFFSET))(this, a1, a2);
		}

		::RPG::GameCore::CharacterSomatoType GetMaxSomatoInFormation(::RPG::GameCore::EntityTypeMask a1)
		{
			return ((::RPG::GameCore::CharacterSomatoType(*)(::PVOID, ::RPG::GameCore::EntityTypeMask))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETMAXSOMATOINFORMATION_OFFSET))(this, a1);
		}

		::System::Int32 GetValidRowCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETVALIDROWCOUNT_OFFSET))(this);
		}

		::System::Int32 GetRowFormationDataCount(::System::Int32 a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::GameEntity* a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETROWFORMATIONDATACOUNT_OFFSET))(this, a1, a2, a3);
		}

		::System::Void GetRowFormationIndexRange(::System::Int32 a1, ::System::Int32& a2, ::System::Int32& a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETROWFORMATIONINDEXRANGE_OFFSET))(this, a1, a2, a3);
		}

		::RPG::PoolList_1<::Class_2_BF927CBEA754F6BE*>* GetRowFormationDatas(::System::Int32 a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::GameEntity* a3)
		{
			return ((::RPG::PoolList_1<::Class_2_BF927CBEA754F6BE*>*(*)(::PVOID, ::System::Int32, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETROWFORMATIONDATAS_OFFSET))(this, a1, a2, a3);
		}

		::RPG::PoolList_1<::Class_2_BF927CBEA754F6BE*>* GetFormationDatas(::RPG::GameCore::TeamMemberCountingOption a1, ::RPG::GameCore::GameEntity* a2)
		{
			return ((::RPG::PoolList_1<::Class_2_BF927CBEA754F6BE*>*(*)(::PVOID, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONDATAS_OFFSET))(this, a1, a2);
		}

		::System::Int32 GetTeamEntityCount(::RPG::GameCore::TeamMemberCountingOption a1)
		{
			return ((::System::Int32(*)(::PVOID, ::RPG::GameCore::TeamMemberCountingOption))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETTEAMENTITYCOUNT_OFFSET))(this, a1);
		}

		::System::UInt32 GetPuppetEntityCount(::RPG::GameCore::TeamMemberCountingOption a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::RPG::GameCore::TeamMemberCountingOption))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETPUPPETENTITYCOUNT_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* GetTeamEntityList(::RPG::GameCore::TeamMemberCountingOption a1, ::RPG::GameCore::GameEntity* a2)
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*(*)(::PVOID, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETTEAMENTITYLIST_OFFSET))(this, a1, a2);
		}

		::System::Boolean _IsMatchTeamMemberCountingOption(::Class_2_BF927CBEA754F6BE* a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::GameEntity* a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__ISMATCHTEAMMEMBERCOUNTINGOPTION_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean IsFull(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISFULL_OFFSET))(this, a1);
		}

		::System::Boolean IsFullForPuppet()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISFULLFORPUPPET_OFFSET))(this);
		}

		::System::Boolean IsRemovingTeammate(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISREMOVINGTEAMMATE_OFFSET))(this, a1);
		}

		::System::Boolean IgnoreAroundCasterCalculation(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_IGNOREAROUNDCASTERCALCULATION_OFFSET))(this, a1);
		}

		::System::Boolean HasSpareTeamFormation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_HASSPARETEAMFORMATION_OFFSET))(this);
		}

		::System::Void SetTeammatePos(::Class_2_BF927CBEA754F6BE* a1, ::RPG::GameCore::GameEntity* a2, ::RPG::GameCore::TeamLocationType a3, ::System::Int32 a4)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamLocationType, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTEAMMATEPOS_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetTeammatePos_1(::Class_2_BF927CBEA754F6BE* a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTEAMMATEPOS_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean AddTeammateEntity(::Class_2_BF927CBEA754F6BE* a1, ::System::Int32 a2, ::System::Int32 a3, ::System::Boolean a4)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::System::Int32, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ADDTEAMMATEENTITY_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetEntityFormationIndex(::RPG::GameCore::GameEntity* a1, ::System::Int32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETENTITYFORMATIONINDEX_OFFSET))(this, a1, a2);
		}

		::System::Void PreRemoveTeammateEntity(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_PREREMOVETEAMMATEENTITY_OFFSET))(this, a1);
		}

		::System::Void RemoveTeammateEntity(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REMOVETEAMMATEENTITY_OFFSET))(this, a1);
		}

		::System::Void AddCustomUpdateFormation(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ADDCUSTOMUPDATEFORMATION_OFFSET))(this, a1);
		}

		::System::Void RemoveCustomUpdateFormation(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REMOVECUSTOMUPDATEFORMATION_OFFSET))(this, a1);
		}

		static ::System::Void SortEntityByFormationIndexIncludeRemoved(::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* a1)
		{
			return ((::System::Void(*)(::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SORTENTITYBYFORMATIONINDEXINCLUDEREMOVED_OFFSET))(a1);
		}

		::System::Void MarkTeammateDirty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MARKTEAMMATEDIRTY_OFFSET))(this);
		}

		::System::Void InverseFormationEntityList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_INVERSEFORMATIONENTITYLIST_OFFSET))(this);
		}

		::System::Void SetTeammateEntityWorldPos(::RPG::GameCore::GameEntity* a1, ::RPG::MVector3 a2, ::System::Boolean a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::MVector3, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTEAMMATEENTITYWORLDPOS_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Boolean IsFormationEdgeEntity(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISFORMATIONEDGEENTITY_OFFSET))(this, a1);
		}

		::RPG::GameCore::GameEntity* GetTeamAdjoinEntity(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::TeamMemberCountingOption a2)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamMemberCountingOption))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETTEAMADJOINENTITY_OFFSET))(this, a1, a2);
		}

		::Struct_2_2B6684D3E43696AE GetEntityFormationPos(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::GameEntity* a3)
		{
			return ((::Struct_2_2B6684D3E43696AE(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYFORMATIONPOS_OFFSET))(this, a1, a2, a3);
		}

		::System::Int32 GetEntityFormationIndex(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::System::Boolean a3)
		{
			return ((::System::Int32(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamMemberCountingOption, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYFORMATIONINDEX_OFFSET))(this, a1, a2, a3);
		}

		::System::Single GetEntityWidthByFormationIndex(::System::Int32 a1, ::RPG::GameCore::TeamMemberCountingOption a2)
		{
			return ((::System::Single(*)(::PVOID, ::System::Int32, ::RPG::GameCore::TeamMemberCountingOption))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYWIDTHBYFORMATIONINDEX_OFFSET))(this, a1, a2);
		}

		::RPG::GameCore::GameEntity* GetEntityByFormationIndex(::System::Int32 a1, ::RPG::GameCore::TeamMemberCountingOption a2)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID, ::System::Int32, ::RPG::GameCore::TeamMemberCountingOption))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYBYFORMATIONINDEX_OFFSET))(this, a1, a2);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>* GetEntityFormationInCameraSpace(::UnityEngine::Camera* a1, ::System::String* a2)
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::GameEntity*>*(*)(::PVOID, ::UnityEngine::Camera*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETENTITYFORMATIONINCAMERASPACE_OFFSET))(this, a1, a2);
		}

		::RPG::GameCore::GameEntity* GetFormationEntityInCameraSpace(::UnityEngine::Camera* a1, ::System::Int32 a2, ::System::String* a3)
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID, ::UnityEngine::Camera*, ::System::Int32, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONENTITYINCAMERASPACE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ResetRootWorldPos()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETROOTWORLDPOS_OFFSET))(this);
		}

		::System::Void SetRootWorldPos(::RPG::MVector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::MVector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETROOTWORLDPOS_OFFSET))(this, a1);
		}

		::System::Void ResetLocation(::System::Collections::Generic::List_1<::RPG::MVector3>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::RPG::MVector3>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETLOCATION_OFFSET))(this, a1);
		}

		::System::Void _CalculateEnemyBackRowOffset(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCULATEENEMYBACKROWOFFSET_OFFSET))(this, a1);
		}

		::System::Void ResetFaceDir()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETFACEDIR_OFFSET))(this);
		}

		::System::Single GetDefaultFaceDir(::RPG::GameCore::TransformComponent* a1, ::RPG::GameCore::TeamFormationComponent* a2)
		{
			return ((::System::Single(*)(::PVOID, ::RPG::GameCore::TransformComponent*, ::RPG::GameCore::TeamFormationComponent*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETDEFAULTFACEDIR_OFFSET))(this, a1, a2);
		}

		::System::Void UseCustomFormation(::System::String* a1, ::System::Boolean a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_USECUSTOMFORMATION_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ClearUseCustomTeamFormation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CLEARUSECUSTOMTEAMFORMATION_OFFSET))(this);
		}

		::System::Void MarkMemberUseCustomPostion(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MARKMEMBERUSECUSTOMPOSTION_OFFSET))(this, a1);
		}

		::System::Boolean IsMemberUseCustomPostion(::Class_2_BF927CBEA754F6BE* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ISMEMBERUSECUSTOMPOSTION_OFFSET))(this, a1);
		}

		::System::Void RefreshLocationList(::RPG::GameCore::TeamFormationType a1, ::System::Boolean a2, ::RPG::GameCore::GameEntity* a3, ::System::Boolean a4, ::System::Boolean a5, ::RPG::GameCore::NormalTeamFormationServantState a6)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TeamFormationType, ::System::Boolean, ::RPG::GameCore::GameEntity*, ::System::Boolean, ::System::Boolean, ::RPG::GameCore::NormalTeamFormationServantState))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHLOCATIONLIST_OFFSET))(this, a1, a2, a3, a4, a5, a6);
		}

		::System::Void MarkLocationDirty()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MARKLOCATIONDIRTY_OFFSET))(this);
		}

		::System::Void _RefreshCustomTeamFormationInfos()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHCUSTOMTEAMFORMATIONINFOS_OFFSET))(this);
		}

		::System::Void RefreshFormationCenter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONCENTER_OFFSET))(this);
		}

		::System::Void ResetLevelAreaRootAsBattleCenter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETLEVELAREAROOTASBATTLECENTER_OFFSET))(this);
		}

		::System::Void ResetCurrentTemplateConfigName()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETCURRENTTEMPLATECONFIGNAME_OFFSET))(this);
		}

		::System::Void SetCurrentTemplateConfigName(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETCURRENTTEMPLATECONFIGNAME_OFFSET))(this, a1);
		}

		::RPG::GameCore::LightTeamFightFormationConfig* GetCurrentLightTeamFightFormationConfig()
		{
			return ((::RPG::GameCore::LightTeamFightFormationConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETCURRENTLIGHTTEAMFIGHTFORMATIONCONFIG_OFFSET))(this);
		}

		::RPG::GameCore::DarkTeamFightFormationConfig* GetCurrentDarkTeamFightFormationConfig()
		{
			return ((::RPG::GameCore::DarkTeamFightFormationConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETCURRENTDARKTEAMFIGHTFORMATIONCONFIG_OFFSET))(this);
		}

		::RPG::GameCore::LightTeamFightFormationConfig* GetDefaultLightTeamFightFormationConfig()
		{
			return ((::RPG::GameCore::LightTeamFightFormationConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETDEFAULTLIGHTTEAMFIGHTFORMATIONCONFIG_OFFSET))(this);
		}

		::RPG::GameCore::DarkTeamFightFormationConfig* GetDefaultDarkTeamFightFormationConfig()
		{
			return ((::RPG::GameCore::DarkTeamFightFormationConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETDEFAULTDARKTEAMFIGHTFORMATIONCONFIG_OFFSET))(this);
		}

		::System::Void SettleTemporaryLocation(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETTLETEMPORARYLOCATION_OFFSET))(this, a1);
		}

		::System::Int32 GetFormationIndex(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::GameEntity* a3)
		{
			return ((::System::Int32(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONINDEX_OFFSET))(this, a1, a2, a3);
		}

		::RPG::MVector3 _GetCurrentCustomFormationCenter(::System::Boolean a1)
		{
			return ((::RPG::MVector3(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETCURRENTCUSTOMFORMATIONCENTER_OFFSET))(this, a1);
		}

		::RPG::MVector3 GetFormationCenterWorldPosWithEntityFilter(::RPG::GameCore::AliveStateMask a1, ::System::Boolean a2, ::System::Boolean a3)
		{
			return ((::RPG::MVector3(*)(::PVOID, ::RPG::GameCore::AliveStateMask, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GETFORMATIONCENTERWORLDPOSWITHENTITYFILTER_OFFSET))(this, a1, a2, a3);
		}

		::RPG::MVector3 _GetFormationCenterWorldPosWithEntityFilterInternal(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::RPG::GameCore::AliveStateMask a2, ::System::Boolean a3, ::System::Boolean a4)
		{
			return ((::RPG::MVector3(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::RPG::GameCore::AliveStateMask, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETFORMATIONCENTERWORLDPOSWITHENTITYFILTERINTERNAL_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void ModifyDefaultTeamFormation(::System::Single a1, ::System::Single a2, ::RPG::GameCore::GameEntity* a3, ::System::Boolean a4, ::Il2CppArray<::RPG::GameCore::LocationExtraConfig*>* a5, ::Il2CppArray<::RPG::GameCore::LocationExtraConfig*>* a6)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single, ::System::Single, ::RPG::GameCore::GameEntity*, ::System::Boolean, ::Il2CppArray<::RPG::GameCore::LocationExtraConfig*>*, ::Il2CppArray<::RPG::GameCore::LocationExtraConfig*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_MODIFYDEFAULTTEAMFORMATION_OFFSET))(this, a1, a2, a3, a4, a5, a6);
		}

		::System::Void ResetDefaultTeamFormation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RESETDEFAULTTEAMFORMATION_OFFSET))(this);
		}

		::System::Void _CalcEdgeFormationEntityCount(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::System::Int32& a2, ::System::Int32& a3, ::System::Int32& a4, ::System::Int32& a5)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::System::Int32&, ::System::Int32&, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCEDGEFORMATIONENTITYCOUNT_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::Struct_2_2B6684D3E43696AE CalcNewEntityTeamFormationPos(::RPG::GameCore::GameEntity* a1, ::RPG::GameCore::TeamLocationType a2, ::System::Int32 a3, ::System::Collections::Generic::IList_1<::RPG::GameCore::GameEntity*>* a4, ::Class_2_BF927CBEA754F6BE* a5)
		{
			return ((::Struct_2_2B6684D3E43696AE(*)(::PVOID, ::RPG::GameCore::GameEntity*, ::RPG::GameCore::TeamLocationType, ::System::Int32, ::System::Collections::Generic::IList_1<::RPG::GameCore::GameEntity*>*, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CALCNEWENTITYTEAMFORMATIONPOS_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Boolean ContainsMonsterRankScoreKey(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CONTAINSMONSTERRANKSCOREKEY_OFFSET))(this, a1);
		}

		::System::Void RecordEntityFormationIndex(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_RECORDENTITYFORMATIONINDEX_OFFSET))(this, a1);
		}

		::System::Void ClearRecordEntityFormation()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CLEARRECORDENTITYFORMATION_OFFSET))(this);
		}

		::System::Void CreateFormationSnapshot(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CREATEFORMATIONSNAPSHOT_OFFSET))(this, a1);
		}

		::System::Void ClearFormationSnapshot(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_CLEARFORMATIONSNAPSHOT_OFFSET))(this, a1);
		}

		::System::Void RefreshFormationBySnapshot(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONBYSNAPSHOT_OFFSET))(this, a1);
		}

		::System::Void OnBattleDataView(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_ONBATTLEDATAVIEW_OFFSET))(this, a1);
		}

		::System::Boolean get_LockFormationRefresh()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_LOCKFORMATIONREFRESH_OFFSET))(this);
		}

		::System::Void set_LockFormationRefresh(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_LOCKFORMATIONREFRESH_OFFSET))(this, a1);
		}

		::System::Void set_FormationWidth(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_FORMATIONWIDTH_OFFSET))(this, a1);
		}

		::System::Single get_FormationWidth()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_FORMATIONWIDTH_OFFSET))(this);
		}

		::System::Void set_LocationRootWorldPos(::RPG::MVector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::MVector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_LOCATIONROOTWORLDPOS_OFFSET))(this, a1);
		}

		::RPG::MVector3 get_LocationRootWorldPos()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_LOCATIONROOTWORLDPOS_OFFSET))(this);
		}

		::System::Void set_TeamRotation(::RPG::MQuaternion a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::MQuaternion))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_TEAMROTATION_OFFSET))(this, a1);
		}

		::RPG::MQuaternion get_TeamRotation()
		{
			return ((::RPG::MQuaternion(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMROTATION_OFFSET))(this);
		}

		::System::Void set_TeamFaceDir(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_TEAMFACEDIR_OFFSET))(this, a1);
		}

		::System::Single get_TeamFaceDir()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMFACEDIR_OFFSET))(this);
		}

		::RPG::MVector3 get_TeamForward()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMFORWARD_OFFSET))(this);
		}

		::RPG::MVector3 get_TeamLeft()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMLEFT_OFFSET))(this);
		}

		::RPG::MVector3 get_FormationCenterWorldPos()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_FORMATIONCENTERWORLDPOS_OFFSET))(this);
		}

		::System::Void set_FormationCenterWorldPos(::RPG::MVector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::MVector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_FORMATIONCENTERWORLDPOS_OFFSET))(this, a1);
		}

		::RPG::MVector3 get_FormationCenterWorldPosFromBoundBox()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_FORMATIONCENTERWORLDPOSFROMBOUNDBOX_OFFSET))(this);
		}

		::System::Void set_FormationCenterWorldPosFromBoundBox(::RPG::MVector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::MVector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_FORMATIONCENTERWORLDPOSFROMBOUNDBOX_OFFSET))(this, a1);
		}

		::RPG::MVector3 get_AliveEntitiesFormationCenterWorldPos()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ALIVEENTITIESFORMATIONCENTERWORLDPOS_OFFSET))(this);
		}

		::System::Void set_AliveEntitiesFormationCenterWorldPos(::RPG::MVector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::MVector3))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_ALIVEENTITIESFORMATIONCENTERWORLDPOS_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_WaveOfMonsterRuntimeID()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_WAVEOFMONSTERRUNTIMEID_OFFSET))(this);
		}

		::System::Void set_WaveOfMonsterRuntimeID(::System::Collections::Generic::List_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_WAVEOFMONSTERRUNTIMEID_OFFSET))(this, a1);
		}

		::System::Void _RefreshTeammateIndex()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHTEAMMATEINDEX_OFFSET))(this);
		}

		::System::Void _ForceRefreshInversedActiveRowIndex()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FORCEREFRESHINVERSEDACTIVEROWINDEX_OFFSET))(this);
		}

		::System::Void _RecordEntityInitialProperty(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__RECORDENTITYINITIALPROPERTY_OFFSET))(this, a1);
		}

		::System::Int32 _GetInsertEntityIndex(::System::Int32 a1, ::RPG::GameCore::GameEntity* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETINSERTENTITYINDEX_OFFSET))(this, a1, a2);
		}

		::System::Void RefreshFollowTeamFollowFormations()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFOLLOWTEAMFOLLOWFORMATIONS_OFFSET))(this);
		}

		::System::Int32 _CollectFormationsWithCustomTeamFormationType(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::RPG::GameCore::CharacterFormationType a2, ::System::Boolean a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::RPG::GameCore::CharacterFormationType, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__COLLECTFORMATIONSWITHCUSTOMTEAMFORMATIONTYPE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _RefreshTeamCenterFollow(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::RPG::MVector3 a2, ::System::Single a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::RPG::MVector3, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHTEAMCENTERFOLLOW_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _CollectFormationBounds(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::RPG::MVector3& a2, ::RPG::MVector3& a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::RPG::MVector3&, ::RPG::MVector3&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__COLLECTFORMATIONBOUNDS_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _AfterFormationRefresh(::Class_2_BF927CBEA754F6BE* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__AFTERFORMATIONREFRESH_OFFSET))(this, a1, a2);
		}

		::System::Int32 _SortTeamCenterFollowFormation(::Class_2_BF927CBEA754F6BE* a1, ::Class_2_BF927CBEA754F6BE* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::Class_2_BF927CBEA754F6BE*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__SORTTEAMCENTERFOLLOWFORMATION_OFFSET))(this, a1, a2);
		}

		::System::Void _LightTeamNormalCalculator()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__LIGHTTEAMNORMALCALCULATOR_OFFSET))(this);
		}

		::System::Single _RandomLocalZOffset(::RPG::GameCore::LocationConfig* a1)
		{
			return ((::System::Single(*)(::PVOID, ::RPG::GameCore::LocationConfig*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__RANDOMLOCALZOFFSET_OFFSET))(this, a1);
		}

		::System::Void SetServantForceFollowPos(::RPG::GameCore::NormalTeamFormationServantState a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::NormalTeamFormationServantState, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SETSERVANTFORCEFOLLOWPOS_OFFSET))(this, a1, a2);
		}

		::System::Void _LightTeamSelectTargetCalculator(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__LIGHTTEAMSELECTTARGETCALCULATOR_OFFSET))(this, a1);
		}

		::System::Void _LightTeamCustomZOffsetCalculator(::RPG::GameCore::GameEntity* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__LIGHTTEAMCUSTOMZOFFSETCALCULATOR_OFFSET))(this, a1);
		}

		::System::Boolean _BalanceFormation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__BALANCEFORMATION_OFFSET))(this);
		}

		::System::Boolean _BalanceEdgeFormation(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__BALANCEEDGEFORMATION_OFFSET))(this, a1);
		}

		::System::Boolean _BalanceDefaultFormation(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__BALANCEDEFAULTFORMATION_OFFSET))(this, a1);
		}

		::System::Int32 _CalcPuppetAroundCasterInsertIndex(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::Class_2_BF927CBEA754F6BE* a2, ::System::Int32 a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::Class_2_BF927CBEA754F6BE*, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCPUPPETAROUNDCASTERINSERTINDEX_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _MovePuppetToRowIndex(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::Class_2_BF927CBEA754F6BE* a2, ::System::Int32 a3, ::System::Boolean& a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::Class_2_BF927CBEA754F6BE*, ::System::Int32, ::System::Boolean&))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__MOVEPUPPETTOROWINDEX_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Boolean _RearrangePuppetCharacters(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REARRANGEPUPPETCHARACTERS_OFFSET))(this, a1);
		}

		::Struct_2_2B6684D3E43696AE _FormationIndexToPos(::System::Int32 a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::TeamMemberCountingOption a3, ::RPG::GameCore::GameEntity* a4)
		{
			return ((::Struct_2_2B6684D3E43696AE(*)(::PVOID, ::System::Int32, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FORMATIONINDEXTOPOS_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Int32 _FormationPosToIndex(::Struct_2_2B6684D3E43696AE a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::TeamMemberCountingOption a3, ::RPG::GameCore::GameEntity* a4)
		{
			return ((::System::Int32(*)(::PVOID, ::Struct_2_2B6684D3E43696AE, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__FORMATIONPOSTOINDEX_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Int32 _ConvertFormationIndex(::System::Int32 a1, ::RPG::GameCore::TeamMemberCountingOption a2, ::RPG::GameCore::TeamMemberCountingOption a3, ::RPG::GameCore::GameEntity* a4, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a5)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::TeamMemberCountingOption, ::RPG::GameCore::GameEntity*, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CONVERTFORMATIONINDEX_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		static ::System::Boolean _CollectNextRowDatas(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a1, ::System::Int32 a2, ::System::Int32& a3, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>* a4)
		{
			return ((::System::Boolean(*)(::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*, ::System::Int32, ::System::Int32&, ::System::Collections::Generic::List_1<::Class_2_BF927CBEA754F6BE*>*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__COLLECTNEXTROWDATAS_OFFSET))(a1, a2, a3, a4);
		}

		::System::Void _DarkTeamRefreshLocationList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__DARKTEAMREFRESHLOCATIONLIST_OFFSET))(this);
		}

		::System::Void _RefreshModelFlip()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHMODELFLIP_OFFSET))(this);
		}

		::RPG::GameCore::LightTeamFightFormationParams* _GetLightTeamFightFormationParams()
		{
			return ((::RPG::GameCore::LightTeamFightFormationParams*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETLIGHTTEAMFIGHTFORMATIONPARAMS_OFFSET))(this);
		}

		::RPG::GameCore::DarkTeamFightFormationParams* _GetDarkTeamFightFormationParams()
		{
			return ((::RPG::GameCore::DarkTeamFightFormationParams*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETDARKTEAMFIGHTFORMATIONPARAMS_OFFSET))(this);
		}

		::System::Void _RefreshTeamZOffset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHTEAMZOFFSET_OFFSET))(this);
		}

		::System::Void _SetTeammateEntityWorldPos(::Class_2_BF927CBEA754F6BE* a1, ::RPG::MVector3 a2, ::System::Boolean a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_BF927CBEA754F6BE*, ::RPG::MVector3, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__SETTEAMMATEENTITYWORLDPOS_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void _RefreshLevelEntityTransform()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__REFRESHLEVELENTITYTRANSFORM_OFFSET))(this);
		}

		::System::Void _ApplyLocationPosListCentralOffset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__APPLYLOCATIONPOSLISTCENTRALOFFSET_OFFSET))(this);
		}

		::RPG::MVector3 _GetComfortZoneOffset(::System::Int32 a1)
		{
			return ((::RPG::MVector3(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETCOMFORTZONEOFFSET_OFFSET))(this, a1);
		}

		::RPG::MVector3 _GetDefaultWorldRootPos()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETDEFAULTWORLDROOTPOS_OFFSET))(this);
		}

		::RPG::MQuaternion _GetDefaultWorldRootRot()
		{
			return ((::RPG::MQuaternion(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETDEFAULTWORLDROOTROT_OFFSET))(this);
		}

		::RPG::MQuaternion _GetTeamRotation(::RPG::GameCore::TeamType a1)
		{
			return ((::RPG::MQuaternion(*)(::PVOID, ::RPG::GameCore::TeamType))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__GETTEAMROTATION_OFFSET))(this, a1);
		}

		::System::Void RefreshFormationInCameraSpace(::UnityEngine::Camera* a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Camera*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_REFRESHFORMATIONINCAMERASPACE_OFFSET))(this, a1, a2);
		}

		static ::System::Single _CalculateTeamDistance(::Class_3_E03EC9D105CCFA3C* a1, ::RPG::GameCore::TeamFormationComponent* a2, ::RPG::GameCore::TeamFormationComponent* a3, ::RPG::GameCore::DarkTeamFightFormationParams* a4)
		{
			return ((::System::Single(*)(::Class_3_E03EC9D105CCFA3C*, ::RPG::GameCore::TeamFormationComponent*, ::RPG::GameCore::TeamFormationComponent*, ::RPG::GameCore::DarkTeamFightFormationParams*))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT__CALCULATETEAMDISTANCE_OFFSET))(a1, a2, a3, a4);
		}

		::RPG::GameCore::TeamFormationComponent* get_EnemyFormation()
		{
			return ((::RPG::GameCore::TeamFormationComponent*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ENEMYFORMATION_OFFSET))(this);
		}

		::RPG::GameCore::GameEntity* get_DefaultFormationCenterEntity()
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_DEFAULTFORMATIONCENTERENTITY_OFFSET))(this);
		}

		::System::UInt32 get_RemoveVersionCounter()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_REMOVEVERSIONCOUNTER_OFFSET))(this);
		}

		::RPG::GameCore::TeamFormationType get_CurrentFormationType()
		{
			return ((::RPG::GameCore::TeamFormationType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CURRENTFORMATIONTYPE_OFFSET))(this);
		}

		::RPG::GameCore::NormalTeamFormationServantState get_ServantFormationState()
		{
			return ((::RPG::GameCore::NormalTeamFormationServantState(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_SERVANTFORMATIONSTATE_OFFSET))(this);
		}

		::System::Boolean get_IsInCustomFormation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ISINCUSTOMFORMATION_OFFSET))(this);
		}

		::System::String* get_CurrentCustomFormationName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CURRENTCUSTOMFORMATIONNAME_OFFSET))(this);
		}

		::System::Boolean get_AnyMemberUseCustomPostion()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_ANYMEMBERUSECUSTOMPOSTION_OFFSET))(this);
		}

		::RPG::MVector3 get_CustomFormationCenterWorldPos()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CUSTOMFORMATIONCENTERWORLDPOS_OFFSET))(this);
		}

		::RPG::MVector3 get_CustomFormationCenterWorldPosFromBoundBox()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_CUSTOMFORMATIONCENTERWORLDPOSFROMBOUNDBOX_OFFSET))(this);
		}

		::System::Single get_TeamZOffset()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_TEAMZOFFSET_OFFSET))(this);
		}

		::System::Boolean get_InverseFlag()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_INVERSEFLAG_OFFSET))(this);
		}

		::System::Single get_ComfortZoneWidth()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_COMFORTZONEWIDTH_OFFSET))(this);
		}

		::System::Single get_ComfortZoneWidthOverride()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_COMFORTZONEWIDTHOVERRIDE_OFFSET))(this);
		}

		::System::Void set_ComfortZoneWidthOverride(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_SET_COMFORTZONEWIDTHOVERRIDE_OFFSET))(this, a1);
		}

		::System::Boolean get_AutoBalanceDefaultFormation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_GAMECORE_TEAMFORMATIONCOMPONENT_GET_AUTOBALANCEDEFAULTFORMATION_OFFSET))(this);
		}
	};
}
