#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/InControl/InputControlType.h"
#include "unitysdk/InControl/InputDeviceProfile.h"

namespace InControl { class InputControlMapping; }
namespace System { class String; }

#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACCELEROMETERXMAPPING_OFFSET UNITYSDK_OFFSET(0x199B19F0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACCELEROMETERYMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1A90)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACCELEROMETERZMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1B30)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION1MAPPING_OFFSET UNITYSDK_OFFSET(0x199B0930)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION2MAPPING_OFFSET UNITYSDK_OFFSET(0x199B09A0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION3MAPPING_OFFSET UNITYSDK_OFFSET(0x199B0A20)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION4MAPPING_OFFSET UNITYSDK_OFFSET(0x199B0AA0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DEFINE_OFFSET UNITYSDK_OFFSET(0x199B08B0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADDOWNMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0F50)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADLEFTMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0FE0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADRIGHTMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1070)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADUPMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0EC0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_GYROSCOPEXMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1BD0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_GYROSCOPEYMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1C70)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_GYROSCOPEZMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1D10)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTBUMPERMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0DC0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTCOMMANDMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0B20)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKBUTTONMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0CA0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKDOWNMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1600)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKLEFTMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1450)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKRIGHTMAPPING_OFFSET UNITYSDK_OFFSET(0x199B14E0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKUPMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1570)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTTRIGGERMAPPING_OFFSET UNITYSDK_OFFSET(0x199B18D0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_MISC1MAPPING_OFFSET UNITYSDK_OFFSET(0x199B1100)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE1MAPPING_OFFSET UNITYSDK_OFFSET(0x199B1180)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE2MAPPING_OFFSET UNITYSDK_OFFSET(0x199B1210)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE3MAPPING_OFFSET UNITYSDK_OFFSET(0x199B12A0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE4MAPPING_OFFSET UNITYSDK_OFFSET(0x199B1330)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTBUMPERMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0E40)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTCOMMANDMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0C20)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKBUTTONMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0D30)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKDOWNMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1840)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKLEFTMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1690)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKRIGHTMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1720)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKUPMAPPING_OFFSET UNITYSDK_OFFSET(0x199B17B0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTTRIGGERMAPPING_OFFSET UNITYSDK_OFFSET(0x199B1960)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_SYSTEMMAPPING_OFFSET UNITYSDK_OFFSET(0x199B0BA0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_TOUCHPADBUTTONMAPPING_OFFSET UNITYSDK_OFFSET(0x199B13C0)
#define INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE__CTOR_OFFSET UNITYSDK_OFFSET(0x199B1DB0)

namespace InControl::NativeDeviceProfiles
{
	inline static constexpr unsigned int SDLControllerNativeProfile_TypeDefinitionIndex = 39122;

	class SDLControllerNativeProfile : public ::InControl::InputDeviceProfile
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE__CTOR_OFFSET))(this);
		}

		::System::Void Define()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DEFINE_OFFSET))(this);
		}

		static ::InControl::InputControlMapping* Action1Mapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION1MAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* Action2Mapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION2MAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* Action3Mapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION3MAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* Action4Mapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACTION4MAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* LeftCommandMapping(::System::String* a1, ::InControl::InputControlType a2)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*, ::InControl::InputControlType))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTCOMMANDMAPPING_OFFSET))(a1, a2);
		}

		static ::InControl::InputControlMapping* SystemMapping(::System::String* a1, ::InControl::InputControlType a2)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*, ::InControl::InputControlType))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_SYSTEMMAPPING_OFFSET))(a1, a2);
		}

		static ::InControl::InputControlMapping* RightCommandMapping(::System::String* a1, ::InControl::InputControlType a2)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*, ::InControl::InputControlType))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTCOMMANDMAPPING_OFFSET))(a1, a2);
		}

		static ::InControl::InputControlMapping* LeftStickButtonMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKBUTTONMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* RightStickButtonMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKBUTTONMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* LeftBumperMapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTBUMPERMAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* RightBumperMapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTBUMPERMAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* DPadUpMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADUPMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* DPadDownMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADDOWNMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* DPadLeftMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADLEFTMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* DPadRightMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_DPADRIGHTMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* Misc1Mapping(::System::String* a1, ::InControl::InputControlType a2)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*, ::InControl::InputControlType))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_MISC1MAPPING_OFFSET))(a1, a2);
		}

		static ::InControl::InputControlMapping* Paddle1Mapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE1MAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* Paddle2Mapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE2MAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* Paddle3Mapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE3MAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* Paddle4Mapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_PADDLE4MAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* TouchPadButtonMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_TOUCHPADBUTTONMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* LeftStickLeftMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKLEFTMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* LeftStickRightMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKRIGHTMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* LeftStickUpMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKUPMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* LeftStickDownMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTSTICKDOWNMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* RightStickLeftMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKLEFTMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* RightStickRightMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKRIGHTMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* RightStickUpMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKUPMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* RightStickDownMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTSTICKDOWNMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* LeftTriggerMapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_LEFTTRIGGERMAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* RightTriggerMapping(::System::String* a1)
		{
			return ((::InControl::InputControlMapping*(*)(::System::String*))((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_RIGHTTRIGGERMAPPING_OFFSET))(a1);
		}

		static ::InControl::InputControlMapping* AccelerometerXMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACCELEROMETERXMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* AccelerometerYMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACCELEROMETERYMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* AccelerometerZMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_ACCELEROMETERZMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* GyroscopeXMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_GYROSCOPEXMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* GyroscopeYMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_GYROSCOPEYMAPPING_OFFSET))();
		}

		static ::InControl::InputControlMapping* GyroscopeZMapping()
		{
			return ((::InControl::InputControlMapping*(*)())((::PBYTE)hIl2Cpp + INCONTROL_NATIVEDEVICEPROFILES_SDLCONTROLLERNATIVEPROFILE_GYROSCOPEZMAPPING_OFFSET))();
		}
	};
}
