#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

class Class_1_B6808D299FB635FC;
namespace RPG::Client { class BattleSilverWolf999BatteryUIData; }
namespace RPG::Client { class BattleSilverWolf999UltraSkillUIData; }

#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_ADDHANDLERS_OFFSET UNITYSDK_OFFSET(0xBE98960)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_DISPOSE_OFFSET UNITYSDK_OFFSET(0xBE98770)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_GET_BATTERYDATA_OFFSET UNITYSDK_OFFSET(0xBE99040)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_GET_PROPPROGRESSDATA_OFFSET UNITYSDK_OFFSET(0xBE99060)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_GET_ULTRASKILLDATA_OFFSET UNITYSDK_OFFSET(0xBE99020)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_LATETICK_OFFSET UNITYSDK_OFFSET(0xBE98AF0)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_SET_BATTERYDATA_OFFSET UNITYSDK_OFFSET(0xBE99050)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_SET_PROPPROGRESSDATA_OFFSET UNITYSDK_OFFSET(0xBE99070)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_SET_ULTRASKILLDATA_OFFSET UNITYSDK_OFFSET(0xBE99030)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xBE99080)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ENSUREPROPPROGRESSDATA_OFFSET UNITYSDK_OFFSET(0xBE98DB0)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESETSILVERWOLF999BATTERYUI_OFFSET UNITYSDK_OFFSET(0xBE98BE0)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESETSILVERWOLF999ULTRASINGLEPROPPROGRESS_OFFSET UNITYSDK_OFFSET(0xBE98F20)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESHOWSILVERWOLF999ULTRAPROPPROGRESS_OFFSET UNITYSDK_OFFSET(0xBE98C60)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESILVERWOLF999ULTRASKILLUIDATA_OFFSET UNITYSDK_OFFSET(0xBE98B60)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESWITCHSILVERWOLF999ULTRAPROPSTATE_OFFSET UNITYSDK_OFFSET(0xBE98E20)
#define RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__REMOVEHANDLERS_OFFSET UNITYSDK_OFFSET(0xBE987C0)

namespace RPG::Client
{
	inline static constexpr unsigned int BattleSilverWolf999CustomUIData_TypeDefinitionIndex = 68242;

	class BattleSilverWolf999CustomUIData : public ::System::Object
	{
	public:
		::RPG::Client::BattleSilverWolf999BatteryUIData* _BatteryData_k__BackingField; // 0x10
		::Class_1_B6808D299FB635FC* _PropProgressData_k__BackingField; // 0x18
		::RPG::Client::BattleSilverWolf999UltraSkillUIData* _UltraSkillData_k__BackingField; // 0x20
		::System::Boolean _AddedHandlers; // 0x28

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__CTOR_OFFSET))(this);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_DISPOSE_OFFSET))(this);
		}

		::System::Void AddHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_ADDHANDLERS_OFFSET))(this);
		}

		::System::Void LateTick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_LATETICK_OFFSET))(this, a1);
		}

		::System::Void _RemoveHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__REMOVEHANDLERS_OFFSET))(this);
		}

		::System::Void _OnBattleSilverWolf999UltraSkillUIData(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESILVERWOLF999ULTRASKILLUIDATA_OFFSET))(this, a1);
		}

		::System::Void _OnBattleSetSilverWolf999BatteryUI(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESETSILVERWOLF999BATTERYUI_OFFSET))(this, a1);
		}

		::System::Void _OnBattleShowSilverWolf999UltraPropProgress(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESHOWSILVERWOLF999ULTRAPROPPROGRESS_OFFSET))(this, a1);
		}

		::System::Void _OnBattleSwitchSilverWolf999UltraPropState(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESWITCHSILVERWOLF999ULTRAPROPSTATE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleSetSilverWolf999UltraSinglePropProgress(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ONBATTLESETSILVERWOLF999ULTRASINGLEPROPPROGRESS_OFFSET))(this, a1);
		}

		::System::Void _EnsurePropProgressData(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA__ENSUREPROPPROGRESSDATA_OFFSET))(this, a1);
		}

		::RPG::Client::BattleSilverWolf999UltraSkillUIData* get_UltraSkillData()
		{
			return ((::RPG::Client::BattleSilverWolf999UltraSkillUIData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_GET_ULTRASKILLDATA_OFFSET))(this);
		}

		::System::Void set_UltraSkillData(::RPG::Client::BattleSilverWolf999UltraSkillUIData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::BattleSilverWolf999UltraSkillUIData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_SET_ULTRASKILLDATA_OFFSET))(this, a1);
		}

		::RPG::Client::BattleSilverWolf999BatteryUIData* get_BatteryData()
		{
			return ((::RPG::Client::BattleSilverWolf999BatteryUIData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_GET_BATTERYDATA_OFFSET))(this);
		}

		::System::Void set_BatteryData(::RPG::Client::BattleSilverWolf999BatteryUIData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::BattleSilverWolf999BatteryUIData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_SET_BATTERYDATA_OFFSET))(this, a1);
		}

		::Class_1_B6808D299FB635FC* get_PropProgressData()
		{
			return ((::Class_1_B6808D299FB635FC*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_GET_PROPPROGRESSDATA_OFFSET))(this);
		}

		::System::Void set_PropProgressData(::Class_1_B6808D299FB635FC* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_B6808D299FB635FC*))((::PBYTE)hIl2Cpp + RPG_CLIENT_BATTLESILVERWOLF999CUSTOMUIDATA_SET_PROPPROGRESSDATA_OFFSET))(this, a1);
		}
	};
}
