#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

namespace RPG::GameCore { class CakeConfigRow; }
namespace System { class String; }

#define RPG_CLIENT_CAKECATCHCATDATA_CREATE_OFFSET UNITYSDK_OFFSET(0xBEEAA40)
#define RPG_CLIENT_CAKECATCHCATDATA_DISPOSE_OFFSET UNITYSDK_OFFSET(0xBEECC90)
#define RPG_CLIENT_CAKECATCHCATDATA_GETCAKECATCHCOUNTHISTORY_OFFSET UNITYSDK_OFFSET(0xBEEB1A0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CATDESC_OFFSET UNITYSDK_OFFSET(0xBEED600)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CATID_OFFSET UNITYSDK_OFFSET(0xBEED4A0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CATIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xBEED6E0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CATMINIIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xBEECAB0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CATNAME_OFFSET UNITYSDK_OFFSET(0xBEED4C0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CATTAILIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xBEECA00)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_CAUGHTTALKSENTENCEIDS_OFFSET UNITYSDK_OFFSET(0xBEED790)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_DARKMATERIALPATH_OFFSET UNITYSDK_OFFSET(0xBEEDA40)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_FINISHEDTALKSENTENCEIDS_OFFSET UNITYSDK_OFFSET(0xBEED840)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_ISUNLOCKED_OFFSET UNITYSDK_OFFSET(0xBEEDAF0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_MATERIALPATH_OFFSET UNITYSDK_OFFSET(0xBEED990)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_NPCID_OFFSET UNITYSDK_OFFSET(0xBEEAAF0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET_TAILCOLOUR_OFFSET UNITYSDK_OFFSET(0xBEED8F0)
#define RPG_CLIENT_CAKECATCHCATDATA_GET__ROW_OFFSET UNITYSDK_OFFSET(0xBEED5A0)
#define RPG_CLIENT_CAKECATCHCATDATA_INITCONFIG_OFFSET UNITYSDK_OFFSET(0xBEECC40)
#define RPG_CLIENT_CAKECATCHCATDATA_ISARRANGEUNLOCKSTATUSSEEN_OFFSET UNITYSDK_OFFSET(0xBEED280)
#define RPG_CLIENT_CAKECATCHCATDATA_ISATLASCAKESTORYSEEN_OFFSET UNITYSDK_OFFSET(0xBEECDD0)
#define RPG_CLIENT_CAKECATCHCATDATA_ISATLASUNLOCKSTATUSSEEN_OFFSET UNITYSDK_OFFSET(0xBEECCD0)
#define RPG_CLIENT_CAKECATCHCATDATA_SETARRANGEUNLOCKSTATUSSEEN_OFFSET UNITYSDK_OFFSET(0xBEED380)
#define RPG_CLIENT_CAKECATCHCATDATA_SETATLASCAKESTORYSEEN_OFFSET UNITYSDK_OFFSET(0xBEED0A0)
#define RPG_CLIENT_CAKECATCHCATDATA_SETATLASUNLOCKSTATUSSEEN_OFFSET UNITYSDK_OFFSET(0xBEECF00)
#define RPG_CLIENT_CAKECATCHCATDATA_SET_CATID_OFFSET UNITYSDK_OFFSET(0xBEED4B0)
#define RPG_CLIENT_CAKECATCHCATDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xBEECC30)

namespace RPG::Client
{
	inline static constexpr unsigned int CakeCatchCatData_TypeDefinitionIndex = 60203;

	class CakeCatchCatData : public ::System::Object
	{
	public:
		::System::UInt32 _CatID_k__BackingField; // 0x10

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::CakeCatchCatData* Create(::System::UInt32 a1)
		{
			return ((::RPG::Client::CakeCatchCatData*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_CREATE_OFFSET))(a1);
		}

		::System::Void InitConfig(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_INITCONFIG_OFFSET))(this, a1);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_DISPOSE_OFFSET))(this);
		}

		::System::UInt32 GetCakeCatchCountHistory()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GETCAKECATCHCOUNTHISTORY_OFFSET))(this);
		}

		::System::Boolean IsAtlasUnlockStatusSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_ISATLASUNLOCKSTATUSSEEN_OFFSET))(this);
		}

		::System::Boolean IsAtlasCakeStorySeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_ISATLASCAKESTORYSEEN_OFFSET))(this);
		}

		::System::Void SetAtlasUnlockStatusSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_SETATLASUNLOCKSTATUSSEEN_OFFSET))(this);
		}

		::System::Void SetAtlasCakeStorySeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_SETATLASCAKESTORYSEEN_OFFSET))(this);
		}

		::System::Boolean IsArrangeUnlockStatusSeen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_ISARRANGEUNLOCKSTATUSSEEN_OFFSET))(this);
		}

		::System::Void SetArrangeUnlockStatusSeen()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_SETARRANGEUNLOCKSTATUSSEEN_OFFSET))(this);
		}

		::System::UInt32 get_CatID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CATID_OFFSET))(this);
		}

		::System::Void set_CatID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_SET_CATID_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_CatName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CATNAME_OFFSET))(this);
		}

		::RPG::Client::TextID get_CatDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CATDESC_OFFSET))(this);
		}

		::System::String* get_CatImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CATIMAGEPATH_OFFSET))(this);
		}

		::System::String* get_CatMiniImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CATMINIIMAGEPATH_OFFSET))(this);
		}

		::System::String* get_CatTailImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CATTAILIMAGEPATH_OFFSET))(this);
		}

		::System::UInt32 get_NPCID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_NPCID_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_CaughtTalkSentenceIDs()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_CAUGHTTALKSENTENCEIDS_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_FinishedTalkSentenceIDs()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_FINISHEDTALKSENTENCEIDS_OFFSET))(this);
		}

		::System::UInt32 get_TailColour()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_TAILCOLOUR_OFFSET))(this);
		}

		::System::String* get_MaterialPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_MATERIALPATH_OFFSET))(this);
		}

		::System::String* get_DarkMaterialPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_DARKMATERIALPATH_OFFSET))(this);
		}

		::System::Boolean get_IsUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET_ISUNLOCKED_OFFSET))(this);
		}

		::RPG::GameCore::CakeConfigRow* get__Row()
		{
			return ((::RPG::GameCore::CakeConfigRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CAKECATCHCATDATA_GET__ROW_OFFSET))(this);
		}
	};
}
