#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TABehaviorBase.h"

namespace RPG::Client { class CharacterCustomBlushMonoPlugin; }

#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_ENDOFLATETICK_OFFSET UNITYSDK_OFFSET(0xBFCD0F0)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET UNITYSDK_OFFSET(0xBFCD0B0)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_2A820A17D62802B8_OFFSET UNITYSDK_OFFSET(0xBFCCB10)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0xBFCD410)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET UNITYSDK_OFFSET(0xBFCD2F0)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET UNITYSDK_OFFSET(0xBFCD350)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET UNITYSDK_OFFSET(0xBFCD3B0)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET UNITYSDK_OFFSET(0xBFCD450)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_5_OFFSET UNITYSDK_OFFSET(0xBFCD4B0)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET UNITYSDK_OFFSET(0xBFCD290)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_9681042564541CD6_OFFSET UNITYSDK_OFFSET(0xBFCD150)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_AB1A8DFD378DB0BE_OFFSET UNITYSDK_OFFSET(0xBFCD1E0)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR__CCTOR_OFFSET UNITYSDK_OFFSET(0xBFCD520)
#define RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR__CTOR_OFFSET UNITYSDK_OFFSET(0xBFCD510)

namespace RPG::Client
{
	inline static constexpr unsigned int CharacterCustomBlushBehavior_TypeDefinitionIndex = 67116;

	class CharacterCustomBlushBehavior : public ::RPG::Client::TABehaviorBase
	{
	public:
		static ::System::Int32* StaticGet__CustomBlushWorldToLocalMatrix1ShaderProperty()
		{
			return (::System::Int32*)Il2CppClass::FromTypeDefinitionIndex(CharacterCustomBlushBehavior_TypeDefinitionIndex)->GetStaticField(0x11500);
		}
		static ::System::Int32* StaticGet__CustomBlushWorldToLocalMatrix2ShaderProperty()
		{
			return (::System::Int32*)Il2CppClass::FromTypeDefinitionIndex(CharacterCustomBlushBehavior_TypeDefinitionIndex)->GetStaticField(0x11504);
		}
		static ::System::Int32* StaticGet__CustomBlushClipMultiplierShaderProperty()
		{
			return (::System::Int32*)Il2CppClass::FromTypeDefinitionIndex(CharacterCustomBlushBehavior_TypeDefinitionIndex)->GetStaticField(0x11508);
		}

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR__CCTOR_OFFSET))();
		}

		::System::Void Method_3_2A820A17D62802B8()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_2A820A17D62802B8_OFFSET))(this);
		}

		::System::Void EndOfLateTick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_ENDOFLATETICK_OFFSET))(this, a1);
		}

		::System::Void Method_3_9681042564541CD6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_9681042564541CD6_OFFSET))(this);
		}

		::System::Void Method_3_AB1A8DFD378DB0BE()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_AB1A8DFD378DB0BE_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET))(this);
		}

		::System::Boolean Method_3_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_391A84BCD9F51317_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_5()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_METHOD_3_4343F372F34C05BF_5_OFFSET))(this);
		}

		::RPG::Client::CharacterCustomBlushMonoPlugin* get__OwnerMonoPlugin()
		{
			return ((::RPG::Client::CharacterCustomBlushMonoPlugin*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHARACTERCUSTOMBLUSHBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET))(this);
		}
	};
}
