#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_96F6662CA3713095_7.h"
#include "unitysdk/Enum_3_DB663931210BBC27_20.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

class Class_1_17FEFE8D0589AF18;
class Class_1_43BD383C98B4C0C5_162;
class Class_1_C9DFE5EE7107C629_4;
namespace RPG::Client { class ChessRogueBoardCellBossSelectData; }
namespace RPG::Client { class ChessRogueBoardCellDecayData; }
namespace RPG::GameCore { class RogueDLCBlockTypeRow; }
namespace RPG::GameCore { class RogueDLCMarkTypeRow; }
namespace System { class String; }

#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_CLONE_OFFSET UNITYSDK_OFFSET(0xC0E40E0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_DISPOSE_OFFSET UNITYSDK_OFFSET(0xC0E4B00)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GETEXTRABOSSSELECTDATA_OFFSET UNITYSDK_OFFSET(0xC0E51A0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GETEXTRADECAYDATA_OFFSET UNITYSDK_OFFSET(0xC0E53C0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GETMARKTYPEROW_OFFSET UNITYSDK_OFFSET(0xC0E5500)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKINTROID_OFFSET UNITYSDK_OFFSET(0xC0E5C90)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPECHESSBOARDCOLOR_OFFSET UNITYSDK_OFFSET(0xC0E5B40)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPECHESSBOARDICON_OFFSET UNITYSDK_OFFSET(0xC0E59F0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPEICON_OFFSET UNITYSDK_OFFSET(0xC0E58A0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPENAME_OFFSET UNITYSDK_OFFSET(0xC0E56A0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPE_OFFSET UNITYSDK_OFFSET(0xC0E5680)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_CELLID_OFFSET UNITYSDK_OFFSET(0xC0E5580)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_CELLSPECIALTYPE_OFFSET UNITYSDK_OFFSET(0xC0E5640)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_CELLSTATUS_OFFSET UNITYSDK_OFFSET(0xC0E5600)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_ISCOLLAPSE_OFFSET UNITYSDK_OFFSET(0xC0E5660)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_MARKTYPE_OFFSET UNITYSDK_OFFSET(0xC0E55E0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_POSX_OFFSET UNITYSDK_OFFSET(0xC0E55A0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_POSY_OFFSET UNITYSDK_OFFSET(0xC0E55C0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_ROOMID_OFFSET UNITYSDK_OFFSET(0xC0E5620)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET__ROW_OFFSET UNITYSDK_OFFSET(0xC0E5820)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISBOSSSELECTCELL_OFFSET UNITYSDK_OFFSET(0xC0E4FB0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISBOSSSELECTDECAYCELL_OFFSET UNITYSDK_OFFSET(0xC0E50F0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISBOSSTYPE_OFFSET UNITYSDK_OFFSET(0xC0E54A0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISDECAYCELL_OFFSET UNITYSDK_OFFSET(0xC0E5280)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_BLOCKTYPE_OFFSET UNITYSDK_OFFSET(0xC0E5690)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_CELLID_OFFSET UNITYSDK_OFFSET(0xC0E5590)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_CELLSPECIALTYPE_OFFSET UNITYSDK_OFFSET(0xC0E5650)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_CELLSTATUS_OFFSET UNITYSDK_OFFSET(0xC0E5610)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_ISCOLLAPSE_OFFSET UNITYSDK_OFFSET(0xC0E5670)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_MARKTYPE_OFFSET UNITYSDK_OFFSET(0xC0E55F0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_POSX_OFFSET UNITYSDK_OFFSET(0xC0E55B0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_POSY_OFFSET UNITYSDK_OFFSET(0xC0E55D0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_ROOMID_OFFSET UNITYSDK_OFFSET(0xC0E5630)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCALL_OFFSET UNITYSDK_OFFSET(0xC0E4880)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCBLOCKTYPE_OFFSET UNITYSDK_OFFSET(0xC0E4BB0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCCELLSTATUS_OFFSET UNITYSDK_OFFSET(0xC0E4D40)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCEXTRAINFO_OFFSET UNITYSDK_OFFSET(0xC0E4D90)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCISCOLLAPSE_OFFSET UNITYSDK_OFFSET(0xC0E4CF0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCMARKTYPE_OFFSET UNITYSDK_OFFSET(0xC0E4C00)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCPOS_OFFSET UNITYSDK_OFFSET(0xC0E4B50)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCROOMID_OFFSET UNITYSDK_OFFSET(0xC0E4C50)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCSPECIALTYPE_OFFSET UNITYSDK_OFFSET(0xC0E4CA0)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM__CTOR_1_OFFSET UNITYSDK_OFFSET(0xC0E4860)
#define RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM__CTOR_OFFSET UNITYSDK_OFFSET(0xC0E40D0)

namespace RPG::Client
{
	inline static constexpr unsigned int ChessRogueBoardCellDataItem_TypeDefinitionIndex = 63925;

	class ChessRogueBoardCellDataItem : public ::System::Object
	{
	public:
		::RPG::GameCore::RogueDLCBlockTypeRow* _CacheRow; // 0x10
		::RPG::GameCore::RogueDLCMarkTypeRow* _MarkTypeRow; // 0x18
		::Class_1_43BD383C98B4C0C5_162* _ExtraData; // 0x20
		::Enum_3_DB663931210BBC27_20 _CellStatus_k__BackingField; // 0x28
		::System::UInt32 _PosX_k__BackingField; // 0x2C
		::System::UInt32 _CellID_k__BackingField; // 0x30
		::System::Boolean _IsCollapse_k__BackingField; // 0x34
		::System::UInt32 _RoomID_k__BackingField; // 0x38
		::System::UInt32 _BlockType_k__BackingField; // 0x3C
		::System::UInt32 _PosY_k__BackingField; // 0x40
		::System::UInt32 _MarkType_k__BackingField; // 0x44
		::Enum_3_96F6662CA3713095_7 _CellSpecialType_k__BackingField; // 0x48

		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM__CTOR_OFFSET))(this, a1);
		}

		::System::Void _ctor_1(::Class_1_C9DFE5EE7107C629_4* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_C9DFE5EE7107C629_4*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM__CTOR_1_OFFSET))(this, a1);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_DISPOSE_OFFSET))(this);
		}

		::System::Void Clone(::RPG::Client::ChessRogueBoardCellDataItem* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChessRogueBoardCellDataItem*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_CLONE_OFFSET))(this, a1);
		}

		::System::Void SyncAll(::Class_1_C9DFE5EE7107C629_4* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_C9DFE5EE7107C629_4*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCALL_OFFSET))(this, a1);
		}

		::System::Void SyncPos(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCPOS_OFFSET))(this, a1, a2);
		}

		::System::Void SyncCellStatus(::Enum_3_DB663931210BBC27_20 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_DB663931210BBC27_20))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCCELLSTATUS_OFFSET))(this, a1);
		}

		::System::Void SyncBlockType(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCBLOCKTYPE_OFFSET))(this, a1);
		}

		::System::Void SyncMarkType(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCMARKTYPE_OFFSET))(this, a1);
		}

		::System::Void SyncRoomID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCROOMID_OFFSET))(this, a1);
		}

		::System::Void SyncSpecialType(::Enum_3_96F6662CA3713095_7 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_96F6662CA3713095_7))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCSPECIALTYPE_OFFSET))(this, a1);
		}

		::System::Void SyncIsCollapse(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCISCOLLAPSE_OFFSET))(this, a1);
		}

		::System::Void SyncExtraInfo(::Class_1_17FEFE8D0589AF18* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_17FEFE8D0589AF18*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SYNCEXTRAINFO_OFFSET))(this, a1);
		}

		::System::Boolean IsBossSelectCell()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISBOSSSELECTCELL_OFFSET))(this);
		}

		::RPG::Client::ChessRogueBoardCellBossSelectData* GetExtraBossSelectData()
		{
			return ((::RPG::Client::ChessRogueBoardCellBossSelectData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GETEXTRABOSSSELECTDATA_OFFSET))(this);
		}

		::System::Boolean IsDecayCell()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISDECAYCELL_OFFSET))(this);
		}

		::RPG::Client::ChessRogueBoardCellDecayData* GetExtraDecayData()
		{
			return ((::RPG::Client::ChessRogueBoardCellDecayData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GETEXTRADECAYDATA_OFFSET))(this);
		}

		::System::Boolean IsBossSelectDecayCell()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISBOSSSELECTDECAYCELL_OFFSET))(this);
		}

		::System::Boolean IsBossType()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_ISBOSSTYPE_OFFSET))(this);
		}

		::RPG::GameCore::RogueDLCMarkTypeRow* GetMarkTypeRow()
		{
			return ((::RPG::GameCore::RogueDLCMarkTypeRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GETMARKTYPEROW_OFFSET))(this);
		}

		::System::UInt32 get_CellID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_CELLID_OFFSET))(this);
		}

		::System::Void set_CellID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_CELLID_OFFSET))(this, a1);
		}

		::System::UInt32 get_PosX()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_POSX_OFFSET))(this);
		}

		::System::Void set_PosX(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_POSX_OFFSET))(this, a1);
		}

		::System::UInt32 get_PosY()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_POSY_OFFSET))(this);
		}

		::System::Void set_PosY(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_POSY_OFFSET))(this, a1);
		}

		::System::UInt32 get_MarkType()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_MARKTYPE_OFFSET))(this);
		}

		::System::Void set_MarkType(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_MARKTYPE_OFFSET))(this, a1);
		}

		::Enum_3_DB663931210BBC27_20 get_CellStatus()
		{
			return ((::Enum_3_DB663931210BBC27_20(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_CELLSTATUS_OFFSET))(this);
		}

		::System::Void set_CellStatus(::Enum_3_DB663931210BBC27_20 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_DB663931210BBC27_20))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_CELLSTATUS_OFFSET))(this, a1);
		}

		::System::UInt32 get_RoomID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_ROOMID_OFFSET))(this);
		}

		::System::Void set_RoomID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_ROOMID_OFFSET))(this, a1);
		}

		::Enum_3_96F6662CA3713095_7 get_CellSpecialType()
		{
			return ((::Enum_3_96F6662CA3713095_7(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_CELLSPECIALTYPE_OFFSET))(this);
		}

		::System::Void set_CellSpecialType(::Enum_3_96F6662CA3713095_7 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_96F6662CA3713095_7))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_CELLSPECIALTYPE_OFFSET))(this, a1);
		}

		::System::Boolean get_IsCollapse()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_ISCOLLAPSE_OFFSET))(this);
		}

		::System::Void set_IsCollapse(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_ISCOLLAPSE_OFFSET))(this, a1);
		}

		::System::UInt32 get_BlockType()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPE_OFFSET))(this);
		}

		::System::Void set_BlockType(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_SET_BLOCKTYPE_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_BlockTypeName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPENAME_OFFSET))(this);
		}

		::System::String* get_BlockTypeIcon()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPEICON_OFFSET))(this);
		}

		::System::String* get_BlockTypeChessBoardIcon()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPECHESSBOARDICON_OFFSET))(this);
		}

		::System::String* get_BlockTypeChessBoardColor()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKTYPECHESSBOARDCOLOR_OFFSET))(this);
		}

		::System::UInt32 get_BlockIntroID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET_BLOCKINTROID_OFFSET))(this);
		}

		::RPG::GameCore::RogueDLCBlockTypeRow* get__Row()
		{
			return ((::RPG::GameCore::RogueDLCBlockTypeRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHESSROGUEBOARDCELLDATAITEM_GET__ROW_OFFSET))(this);
		}
	};
}
