#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

class Class_0_16E4307DCC419505_678;
namespace RPG::Client { class ActivityLightConeQuestCondition; }

#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_FULLPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199E20)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_GOTOCONFIG_OFFSET UNITYSDK_OFFSET(0xC199CE0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISCLOSE_OFFSET UNITYSDK_OFFSET(0xC198B80)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISFINISHORCLOSE_OFFSET UNITYSDK_OFFSET(0xC199D80)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISFINISH_OFFSET UNITYSDK_OFFSET(0xC1988C0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISUNLOCK_OFFSET UNITYSDK_OFFSET(0xC199CF0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_LIGHTCONEQUEST_OFFSET UNITYSDK_OFFSET(0xC199FA0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_NOWPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199E60)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_PASTPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199E40)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_PROGRESSTEXT_OFFSET UNITYSDK_OFFSET(0xC199CD0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_QUESTID_OFFSET UNITYSDK_OFFSET(0xC1990C0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_REWARDID_OFFSET UNITYSDK_OFFSET(0xC199DD0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_REWARDITEMID_OFFSET UNITYSDK_OFFSET(0xC199E80)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SETFULLPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199BB0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SETNOWPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC198D80)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SETPASTPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199AE0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_FULLPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199E30)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_LIGHTCONEQUEST_OFFSET UNITYSDK_OFFSET(0xC199FB0)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_NOWPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199E70)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_PASTPROGRESSNUM_OFFSET UNITYSDK_OFFSET(0xC199E50)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_TAKEREWARD_OFFSET UNITYSDK_OFFSET(0xC199C80)
#define RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP__CTOR_OFFSET UNITYSDK_OFFSET(0xC199B30)

namespace RPG::Client
{
	inline static constexpr unsigned int CommonActivityLightConeRewardGroup_TypeDefinitionIndex = 58936;

	class CommonActivityLightConeRewardGroup : public ::System::Object
	{
	public:
		::RPG::Client::ActivityLightConeQuestCondition* _LightConeQuest_k__BackingField; // 0x10
		::Class_0_16E4307DCC419505_678* _GotoConfig_k__BackingField; // 0x18
		::System::UInt32 _NowProgressNum_k__BackingField; // 0x20
		::RPG::Client::TextID _ProgressText_k__BackingField; // 0x28
		::System::UInt32 _PastProgressNum_k__BackingField; // 0x38
		::System::UInt32 _FullProgressNum_k__BackingField; // 0x3C

		::System::Void _ctor(::System::UInt32 a1, ::System::UInt32 a2, ::RPG::Client::TextID a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP__CTOR_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetFullProgressNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SETFULLPROGRESSNUM_OFFSET))(this, a1);
		}

		::System::Void SetPastProgressNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SETPASTPROGRESSNUM_OFFSET))(this, a1);
		}

		::System::Void SetNowProgressNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SETNOWPROGRESSNUM_OFFSET))(this, a1);
		}

		::System::Void TakeReward()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_TAKEREWARD_OFFSET))(this);
		}

		::RPG::Client::TextID get_ProgressText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_PROGRESSTEXT_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_678* get_GotoConfig()
		{
			return ((::Class_0_16E4307DCC419505_678*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_GOTOCONFIG_OFFSET))(this);
		}

		::System::Boolean get_IsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISUNLOCK_OFFSET))(this);
		}

		::System::Boolean get_IsFinish()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISFINISH_OFFSET))(this);
		}

		::System::Boolean get_IsClose()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISCLOSE_OFFSET))(this);
		}

		::System::Boolean get_IsFinishOrClose()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_ISFINISHORCLOSE_OFFSET))(this);
		}

		::System::UInt32 get_RewardID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_REWARDID_OFFSET))(this);
		}

		::System::UInt32 get_FullProgressNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_FULLPROGRESSNUM_OFFSET))(this);
		}

		::System::Void set_FullProgressNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_FULLPROGRESSNUM_OFFSET))(this, a1);
		}

		::System::UInt32 get_PastProgressNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_PASTPROGRESSNUM_OFFSET))(this);
		}

		::System::Void set_PastProgressNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_PASTPROGRESSNUM_OFFSET))(this, a1);
		}

		::System::UInt32 get_NowProgressNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_NOWPROGRESSNUM_OFFSET))(this);
		}

		::System::Void set_NowProgressNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_NOWPROGRESSNUM_OFFSET))(this, a1);
		}

		::System::UInt32 get_RewardItemID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_REWARDITEMID_OFFSET))(this);
		}

		::System::UInt32 get_QuestID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_QUESTID_OFFSET))(this);
		}

		::RPG::Client::ActivityLightConeQuestCondition* get_LightConeQuest()
		{
			return ((::RPG::Client::ActivityLightConeQuestCondition*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_GET_LIGHTCONEQUEST_OFFSET))(this);
		}

		::System::Void set_LightConeQuest(::RPG::Client::ActivityLightConeQuestCondition* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityLightConeQuestCondition*))((::PBYTE)hIl2Cpp + RPG_CLIENT_COMMONACTIVITYLIGHTCONEREWARDGROUP_SET_LIGHTCONEQUEST_OFFSET))(this, a1);
		}
	};
}
