#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/ActivityPanelData.h"

namespace RPG::Client { class DiceCombatModule; }

#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_GOTOACTIVITYMAINPAGE_OFFSET UNITYSDK_OFFSET(0xC2A5E60)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_GOTOACTIVITYMULTIPLAYERPAGE_OFFSET UNITYSDK_OFFSET(0xC2A5FF0)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISALLRESIDENTREWARDGOT_OFFSET UNITYSDK_OFFSET(0xC2A5BF0)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISFINISHCONDITIONSCOMPLETED_OFFSET UNITYSDK_OFFSET(0xC2A5C50)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISMULTIPLAYERACTIVITYACTIVE_OFFSET UNITYSDK_OFFSET(0xC2A5E00)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWGOTOBTNREDDOT_OFFSET UNITYSDK_OFFSET(0xC2A5B60)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWMAPPINGINFONEWCONTENTREDDOT_OFFSET UNITYSDK_OFFSET(0xC2A5D30)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET UNITYSDK_OFFSET(0xC2A5B00)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0xC2A59F0)
#define RPG_CLIENT_DICECOMBATV2ACTIVITYDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xC2A5980)

namespace RPG::Client
{
	inline static constexpr unsigned int DiceCombatV2ActivityData_TypeDefinitionIndex = 58873;

	class DiceCombatV2ActivityData : public ::RPG::Client::ActivityPanelData
	{
	public:
		::RPG::Client::DiceCombatModule* _Module; // 0xA0

		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA__CTOR_OFFSET))(this, a1);
		}

		::System::Boolean IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowGotoBtnRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWGOTOBTNREDDOT_OFFSET))(this);
		}

		::System::Boolean IsAllResidentRewardGot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISALLRESIDENTREWARDGOT_OFFSET))(this);
		}

		::System::Boolean IsShowMappingInfoRewardRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET))(this);
		}

		::System::Boolean IsFinishConditionsCompleted()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISFINISHCONDITIONSCOMPLETED_OFFSET))(this);
		}

		::System::Boolean IsShowMappingInfoNewContentRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISSHOWMAPPINGINFONEWCONTENTREDDOT_OFFSET))(this);
		}

		::System::Boolean IsMultiPlayerActivityActive()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_ISMULTIPLAYERACTIVITYACTIVE_OFFSET))(this);
		}

		::System::Void GotoActivityMainPage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_GOTOACTIVITYMAINPAGE_OFFSET))(this);
		}

		::System::Void GotoActivityMultiPlayerPage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBATV2ACTIVITYDATA_GOTOACTIVITYMULTIPLAYERPAGE_OFFSET))(this);
		}
	};
}
