#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace RPG::GameCore { class DynamicValue; }
namespace System::Collections { class IEnumerator; }
namespace System::Collections::Generic { template <typename T> class IEnumerator_1; }

#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_MOVENEXT_OFFSET UNITYSDK_OFFSET(0xC3B47D0)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_SYSTEM_UINT32__GETENUMERATOR_OFFSET UNITYSDK_OFFSET(0xC3B49D0)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_UINT32__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0xC3B4940)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_IENUMERABLE_GETENUMERATOR_OFFSET UNITYSDK_OFFSET(0xC3B4A40)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0xC3B49A0)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0xC3B4950)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0xC3B47C0)
#define RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3__CTOR_OFFSET UNITYSDK_OFFSET(0xC3B3160)

namespace RPG::Client
{
	inline static constexpr unsigned int ElfRestaurantProfileInfo__IterateCumulativeRewardQuestIDs_d__3_TypeDefinitionIndex = 60924;

	class ElfRestaurantProfileInfo__IterateCumulativeRewardQuestIDs_d__3 : public ::System::Object
	{
	public:
		::Il2CppArray<::RPG::GameCore::DynamicValue*>* __7__wrap1; // 0x10
		::System::Int32 __7__wrap2; // 0x18
		::System::UInt32 __2__current; // 0x1C
		::System::Int32 __1__state; // 0x20
		::System::Int32 __l__initialThreadId; // 0x24

		::System::Void _ctor(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3__CTOR_OFFSET))(this, a1);
		}

		::System::Void System_IDisposable_Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
		}

		::System::Boolean MoveNext()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_MOVENEXT_OFFSET))(this);
		}

		::System::UInt32 System_Collections_Generic_IEnumerator_System_UInt32__get_Current()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_UINT32__GET_CURRENT_OFFSET))(this);
		}

		::System::Void System_Collections_IEnumerator_Reset()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
		}

		::System::Object* System_Collections_IEnumerator_get_Current()
		{
			return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
		}

		::System::Collections::Generic::IEnumerator_1<::System::UInt32>* System_Collections_Generic_IEnumerable_System_UInt32__GetEnumerator()
		{
			return ((::System::Collections::Generic::IEnumerator_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_GENERIC_IENUMERABLE_SYSTEM_UINT32__GETENUMERATOR_OFFSET))(this);
		}

		::System::Collections::IEnumerator* System_Collections_IEnumerable_GetEnumerator()
		{
			return ((::System::Collections::IEnumerator*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ELFRESTAURANTPROFILEINFO__ITERATECUMULATIVEREWARDQUESTIDS_D__3_SYSTEM_COLLECTIONS_IENUMERABLE_GETENUMERATOR_OFFSET))(this);
		}
	};
}
