#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/ValueType.h"

#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_DROPGEAR_OFFSET UNITYSDK_OFFSET(0x148ED0)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_EXPCHANGE_OFFSET UNITYSDK_OFFSET(0x148C50)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_FORGETID_OFFSET UNITYSDK_OFFSET(0x148D90)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_FORGEUNLOCK_OFFSET UNITYSDK_OFFSET(0x148DE0)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_LEVELUP_OFFSET UNITYSDK_OFFSET(0x148CA0)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_REROLLGEAR_OFFSET UNITYSDK_OFFSET(0x148F20)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_REWARDBOX_OFFSET UNITYSDK_OFFSET(0x148E80)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_STAGE1FORGEUNLOCK_OFFSET UNITYSDK_OFFSET(0x148E30)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_WEAPONID_OFFSET UNITYSDK_OFFSET(0x148CF0)
#define RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_WEAPONLEVELSEVEN_OFFSET UNITYSDK_OFFSET(0x148D40)

namespace RPG::Client
{
	inline static constexpr unsigned int EvolveBuildTutorialUnlockScConfig_TypeDefinitionIndex = 61038;

	struct alignas(1) EvolveBuildTutorialUnlockScConfig
	{
		::System::UInt32 get_ExpChange()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_EXPCHANGE_OFFSET))(this);
		}

		::System::UInt32 get_LevelUp()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_LEVELUP_OFFSET))(this);
		}

		::System::UInt32 get_WeaponID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_WEAPONID_OFFSET))(this);
		}

		::System::UInt32 get_WeaponLevelSeven()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_WEAPONLEVELSEVEN_OFFSET))(this);
		}

		::System::UInt32 get_ForgetID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_FORGETID_OFFSET))(this);
		}

		::System::UInt32 get_ForgeUnlock()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_FORGEUNLOCK_OFFSET))(this);
		}

		::System::UInt32 get_Stage1ForgeUnlock()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_STAGE1FORGEUNLOCK_OFFSET))(this);
		}

		::System::UInt32 get_RewardBox()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_REWARDBOX_OFFSET))(this);
		}

		::System::UInt32 get_DropGear()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_DROPGEAR_OFFSET))(this);
		}

		::System::UInt32 get_ReRollGear()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_EVOLVEBUILDTUTORIALUNLOCKSCCONFIG_GET_REROLLGEAR_OFFSET))(this);
		}
	};
}
