#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_4608E37A1B3D374A_15.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/ActivityRank.h"
#include "unitysdk/RPG/GameCore/AttackDamageType.h"
#include "unitysdk/System/Object.h"

class Class_1_1CBA230307F9C289_30;
namespace RPG::Client { class FightFestPlayerInfo; }
namespace RPG::Client { class FightFestRaceData; }
namespace RPG::GameCore { class FightFestChallengeRow; }
namespace RPG::GameCore { class FightFestStageInfoRow; }
namespace System { class String; }

#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_BATTLETARGETLIST_OFFSET UNITYSDK_OFFSET(0xC5CBC30)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGEID_OFFSET UNITYSDK_OFFSET(0xC5CB1B0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGENAME_OFFSET UNITYSDK_OFFSET(0xC5CBAD0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFDES_OFFSET UNITYSDK_OFFSET(0xC5CBA10)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFID_OFFSET UNITYSDK_OFFSET(0xC5CB900)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFNAME_OFFSET UNITYSDK_OFFSET(0xC5CB9A0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_EVENTID_OFFSET UNITYSDK_OFFSET(0xC5CB8B0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_FIGUREPATH_OFFSET UNITYSDK_OFFSET(0xC5CBE70)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASRECORD_OFFSET UNITYSDK_OFFSET(0xC5CB350)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASREWARDCANTAKE_OFFSET UNITYSDK_OFFSET(0xC5CB480)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISFINISHALLQUEST_OFFSET UNITYSDK_OFFSET(0xC5CB680)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISSEENUNLOCK_OFFSET UNITYSDK_OFFSET(0xC5CB370)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISUNLOCK_OFFSET UNITYSDK_OFFSET(0xC5CB210)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALFIGUREPATH_OFFSET UNITYSDK_OFFSET(0xC5CBE20)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALSTAGENAME_OFFSET UNITYSDK_OFFSET(0xC5CBDB0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_PREVIEWMONSTERLIST_OFFSET UNITYSDK_OFFSET(0xC5CBB40)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTGROUPID_OFFSET UNITYSDK_OFFSET(0xC5CBBE0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTIDLIST_OFFSET UNITYSDK_OFFSET(0xC5CB630)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RACEDATA_OFFSET UNITYSDK_OFFSET(0xC5CB870)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RANK_OFFSET UNITYSDK_OFFSET(0xC5CB1D0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RECOMMADNATURE_OFFSET UNITYSDK_OFFSET(0xC5CBB90)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RIVALINFO_OFFSET UNITYSDK_OFFSET(0xC5CB890)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ROW_OFFSET UNITYSDK_OFFSET(0xC5CB830)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_SPECIALAVATARLIST_OFFSET UNITYSDK_OFFSET(0xC5CBA80)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STAGEINFOROW_OFFSET UNITYSDK_OFFSET(0xC5CB850)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STORYDESC_OFFSET UNITYSDK_OFFSET(0xC5CBD40)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TURNLEFTCOUNT_OFFSET UNITYSDK_OFFSET(0xC5CB1F0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TUTORIALID_OFFSET UNITYSDK_OFFSET(0xC5CBC80)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UIENTERBATTLEAREAID_OFFSET UNITYSDK_OFFSET(0xC5CB950)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKSUBMISSIONID_OFFSET UNITYSDK_OFFSET(0xC5CB300)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKTIPS_OFFSET UNITYSDK_OFFSET(0xC5CBCD0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_CHALLENGEID_OFFSET UNITYSDK_OFFSET(0xC5CB1C0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_HASRECORD_OFFSET UNITYSDK_OFFSET(0xC5CB360)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RACEDATA_OFFSET UNITYSDK_OFFSET(0xC5CB880)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RANK_OFFSET UNITYSDK_OFFSET(0xC5CB1E0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RIVALINFO_OFFSET UNITYSDK_OFFSET(0xC5CB8A0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_ROW_OFFSET UNITYSDK_OFFSET(0xC5CB840)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_STAGEINFOROW_OFFSET UNITYSDK_OFFSET(0xC5CB860)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_TURNLEFTCOUNT_OFFSET UNITYSDK_OFFSET(0xC5CB200)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXRANK_OFFSET UNITYSDK_OFFSET(0xC5CB0F0)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXTURNLEFTCOUNT_OFFSET UNITYSDK_OFFSET(0xC5CB160)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNC_OFFSET UNITYSDK_OFFSET(0xC5CB000)
#define RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xC5CAF00)

namespace RPG::Client
{
	inline static constexpr unsigned int FightFestChallengeLevelData_TypeDefinitionIndex = 61254;

	class FightFestChallengeLevelData : public ::System::Object
	{
	public:
		::RPG::GameCore::FightFestStageInfoRow* _StageInfoRow_k__BackingField; // 0x10
		::RPG::GameCore::FightFestChallengeRow* _Row_k__BackingField; // 0x18
		::RPG::Client::FightFestPlayerInfo* _RivalInfo_k__BackingField; // 0x20
		::RPG::Client::FightFestRaceData* _RaceData_k__BackingField; // 0x28
		::System::UInt32 _ChallengeID_k__BackingField; // 0x30
		::System::Boolean _HasRecord_k__BackingField; // 0x34
		::System::UInt32 _TurnLeftCount_k__BackingField; // 0x38
		::RPG::GameCore::ActivityRank _Rank_k__BackingField; // 0x3C

		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA__CTOR_OFFSET))(this, a1);
		}

		::System::Void Sync(::Class_1_1CBA230307F9C289_30* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_1CBA230307F9C289_30*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNC_OFFSET))(this, a1);
		}

		::System::Void SyncHistoryMaxRank(::Enum_3_4608E37A1B3D374A_15 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_4608E37A1B3D374A_15))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXRANK_OFFSET))(this, a1);
		}

		::System::Void SyncHistoryMaxTurnLeftCount(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SYNCHISTORYMAXTURNLEFTCOUNT_OFFSET))(this, a1);
		}

		::System::UInt32 get_ChallengeID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGEID_OFFSET))(this);
		}

		::System::Void set_ChallengeID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_CHALLENGEID_OFFSET))(this, a1);
		}

		::RPG::GameCore::ActivityRank get_Rank()
		{
			return ((::RPG::GameCore::ActivityRank(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RANK_OFFSET))(this);
		}

		::System::Void set_Rank(::RPG::GameCore::ActivityRank a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ActivityRank))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RANK_OFFSET))(this, a1);
		}

		::System::UInt32 get_TurnLeftCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TURNLEFTCOUNT_OFFSET))(this);
		}

		::System::Void set_TurnLeftCount(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_TURNLEFTCOUNT_OFFSET))(this, a1);
		}

		::System::Boolean get_IsUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISUNLOCK_OFFSET))(this);
		}

		::System::UInt32 get_UnlockSubMissionID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKSUBMISSIONID_OFFSET))(this);
		}

		::System::Boolean get_HasRecord()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASRECORD_OFFSET))(this);
		}

		::System::Void set_HasRecord(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_HASRECORD_OFFSET))(this, a1);
		}

		::System::Boolean get_IsSeenUnlock()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISSEENUNLOCK_OFFSET))(this);
		}

		::System::Boolean get_HasRewardCanTake()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_HASREWARDCANTAKE_OFFSET))(this);
		}

		::System::Boolean get_IsFinishAllQuest()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ISFINISHALLQUEST_OFFSET))(this);
		}

		::RPG::GameCore::FightFestChallengeRow* get_Row()
		{
			return ((::RPG::GameCore::FightFestChallengeRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ROW_OFFSET))(this);
		}

		::System::Void set_Row(::RPG::GameCore::FightFestChallengeRow* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FightFestChallengeRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_ROW_OFFSET))(this, a1);
		}

		::RPG::GameCore::FightFestStageInfoRow* get_StageInfoRow()
		{
			return ((::RPG::GameCore::FightFestStageInfoRow*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STAGEINFOROW_OFFSET))(this);
		}

		::System::Void set_StageInfoRow(::RPG::GameCore::FightFestStageInfoRow* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FightFestStageInfoRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_STAGEINFOROW_OFFSET))(this, a1);
		}

		::RPG::Client::FightFestRaceData* get_RaceData()
		{
			return ((::RPG::Client::FightFestRaceData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RACEDATA_OFFSET))(this);
		}

		::System::Void set_RaceData(::RPG::Client::FightFestRaceData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FightFestRaceData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RACEDATA_OFFSET))(this, a1);
		}

		::RPG::Client::FightFestPlayerInfo* get_RivalInfo()
		{
			return ((::RPG::Client::FightFestPlayerInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RIVALINFO_OFFSET))(this);
		}

		::System::Void set_RivalInfo(::RPG::Client::FightFestPlayerInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FightFestPlayerInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_SET_RIVALINFO_OFFSET))(this, a1);
		}

		::System::UInt32 get_EventID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_EVENTID_OFFSET))(this);
		}

		::System::UInt32 get_EnvironmentBuffID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFID_OFFSET))(this);
		}

		::System::UInt32 get_UIEnterBattleAreaID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UIENTERBATTLEAREAID_OFFSET))(this);
		}

		::RPG::Client::TextID get_EnvironmentBuffName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFNAME_OFFSET))(this);
		}

		::RPG::Client::TextID get_EnvironmentBuffDes()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ENVIRONMENTBUFFDES_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_SpecialAvatarList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_SPECIALAVATARLIST_OFFSET))(this);
		}

		::RPG::Client::TextID get_ChallengeName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_CHALLENGENAME_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_PreviewMonsterList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_PREVIEWMONSTERLIST_OFFSET))(this);
		}

		::Il2CppArray<::RPG::GameCore::AttackDamageType>* get_RecommadNature()
		{
			return ((::Il2CppArray<::RPG::GameCore::AttackDamageType>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_RECOMMADNATURE_OFFSET))(this);
		}

		::System::UInt32 get_QuestGroupID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTGROUPID_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_QuestIDList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_QUESTIDLIST_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_BattleTargetList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_BATTLETARGETLIST_OFFSET))(this);
		}

		::System::UInt32 get_TutorialID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_TUTORIALID_OFFSET))(this);
		}

		::RPG::Client::TextID get_UnlockTips()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_UNLOCKTIPS_OFFSET))(this);
		}

		::RPG::Client::TextID get_StoryDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_STORYDESC_OFFSET))(this);
		}

		::RPG::Client::TextID get_OriginalStageName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALSTAGENAME_OFFSET))(this);
		}

		::System::String* get_OriginalFigurePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_ORIGINALFIGUREPATH_OFFSET))(this);
		}

		::System::String* get_FigurePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIGHTFESTCHALLENGELEVELDATA_GET_FIGUREPATH_OFFSET))(this);
		}
	};
}
