#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_E0103A0EA6CD0F4C.h"
#include "unitysdk/RPG/Client/FiveDimGameInstance_CreateLevelPhase.h"
#include "unitysdk/RPG/Client/FiveDimGameInstance_VisibleReason.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/ComponentInvisibleReason.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/FiveDimMiniGameEnterType.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/MiniGameEventReason.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/PlayerDisableInteractReason.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/TimeScaleReason.h"
#include "unitysdk/RPG/Client/LittleGame/FiveDim/ViewLoadModePriorityLevel.h"
#include "unitysdk/RPG/Client/ReasonBool_1.h"
#include "unitysdk/RPG/GameCore/FiveDimCameraFollowClampMask.h"
#include "unitysdk/RPG/GameCore/FiveDimGameplayMode.h"
#include "unitysdk/RPG/GameCore/FiveDimLoadMode.h"
#include "unitysdk/RPG/GameCore/FiveDimPlayerResetMode.h"
#include "unitysdk/RPG/GameCore/FiveDimPlayerResetSweepDirection.h"
#include "unitysdk/RPG/GameCore/FixPoint.h"
#include "unitysdk/Struct_2_52A902145F5BE513_1.h"
#include "unitysdk/Struct_2_5887222B9AE38D34_1.h"
#include "unitysdk/Struct_2_9195B4006FDD1545.h"
#include "unitysdk/Struct_2_B7F6733609A5D9EA.h"
#include "unitysdk/Struct_2_B82597A91E4CD455.h"
#include "unitysdk/Struct_2_EAC1BB0F093534A5.h"
#include "unitysdk/Struct_2_EC98B14B1B23001B.h"
#include "unitysdk/Struct_2_F01DF3CDCF3FD7AC.h"
#include "unitysdk/Struct_2_F8D9CEC872B937AF.h"
#include "unitysdk/Struct_2_FC595D1A561D8C6F.h"
#include "unitysdk/System/ValueTuple_2.h"
#include "unitysdk/UnityEngine/Vector2.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_256;
class Class_0_16E4307DCC419505_425;
class Class_1_47EE63CB5C4DC8FC_5;
class Class_1_4CD8A1ACD565F336;
class Class_1_58F7C510A0EB2163;
class Class_1_B4357A1C72BABC6B;
class Class_2_B9E8C2EEAA5C96EC;
class Class_3_1E4F9B0ED3BF21DE;
class Class_3_206F177A6C7E89E8;
namespace Entitas { class IComponent; }
namespace Entitas { class IContext; }
namespace Entitas { class IEntity; }
namespace Entitas { template <typename T> class IGroup_1; }
namespace RPG::Client { class FiveDimGameInstance_MusicBeatEffect; }
namespace RPG::Client { class FiveDimPlayerEnterLeaveInfo; }
namespace RPG::Client { class FiveDimTrainModeDisplayInfos; }
namespace RPG::Client::LittleGame { template <typename T> class SimpleEventService_1; }
namespace RPG::GameCore { class CharacterModelComponent; }
namespace RPG::GameCore { class DynamicFloat; }
namespace RPG::GameCore { class FiveDimBakedLevelConfig; }
namespace RPG::GameCore { class FiveDimGameConfig; }
namespace RPG::GameCore { class FiveDimLevelSettings; }
namespace RPG::GameCore { class FiveDimPortalTarget; }
namespace RPG::GameCore { class GameEntity; }
namespace RPG::GameCore { class LevelLittleGameInfo; }
namespace RPG::GameCore { class LittleGameFireEffectParams; }
namespace RPG::GameCore { class LittleGameKillEffectParams; }
namespace RPG::GameCore { class LittleGameLevelConfig; }
namespace RPG::GameCore { class LittleGameLevelVarBindingMap; }
namespace RPG::GameCore { class MeshBound; }
namespace RPG::GameCore { class TaskConfig; }
namespace RPG::GameCore { class TaskContext; }
namespace System { class Action; }
namespace System { class Object; }
namespace System { class String; }
namespace System { template <typename T> class Action_1; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class Collider; }
namespace UnityEngine { class GameObject; }
namespace UnityEngine { class Material; }
namespace UnityEngine { class Transform; }

#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDBUTTONLISTENER_OFFSET UNITYSDK_OFFSET(0xC5F14E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDGLOBALTIMESCALE_OFFSET UNITYSDK_OFFSET(0xC5F7700)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDLEVELVARIABLELISTENER_OFFSET UNITYSDK_OFFSET(0xC5F4460)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDLITTLEGAMECUSTOMEVENTLISTENER_1_OFFSET UNITYSDK_OFFSET(0xC5F3C60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDLITTLEGAMECUSTOMEVENTLISTENER_OFFSET UNITYSDK_OFFSET(0xC5F3B90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDPLAYERINLISTENER_OFFSET UNITYSDK_OFFSET(0xC5EEE30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDPLAYEROUTLISTENER_OFFSET UNITYSDK_OFFSET(0xC5EEEC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDTASKMUSICBEATCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EC6E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_APPLYPLAYERIN_OFFSET UNITYSDK_OFFSET(0xC5F1F40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_APPLYPLAYEROUT_1_OFFSET UNITYSDK_OFFSET(0xC5F2170)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_APPLYPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5F1E60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_AVATARFIREEFFECT_OFFSET UNITYSDK_OFFSET(0xC5E7AF0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_AVATARKILLEFFECT_OFFSET UNITYSDK_OFFSET(0xC5E7B70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANCELWINDOWSTAGEDRAGGING_OFFSET UNITYSDK_OFFSET(0xC5E7F90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANPLAYERUSESKILL_OFFSET UNITYSDK_OFFSET(0xC5F2990)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANSTART_OFFSET UNITYSDK_OFFSET(0xC5F3920)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANUSECAMERAOBSERVE_OFFSET UNITYSDK_OFFSET(0xC5F36D0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CHANGEWORLDSEAMATERIAL_OFFSET UNITYSDK_OFFSET(0xC5EE960)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CHECKHASVISIBLEITEMS_OFFSET UNITYSDK_OFFSET(0xC5EE500)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CHECKPLAYERGRAVITYOPPOSITETOCURRENTSURFACE_OFFSET UNITYSDK_OFFSET(0xC5EA6D0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CLEARTRIGGER_OFFSET UNITYSDK_OFFSET(0xC5F1410)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_CREATEPHANTOMPLAYER_OFFSET UNITYSDK_OFFSET(0xC5EA3F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_DESTROYPHANTOMPLAYER_OFFSET UNITYSDK_OFFSET(0xC5EA490)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_DISPOSETHREADCOLLECTDATA_OFFSET UNITYSDK_OFFSET(0xC5EB3B0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENABLEFORCEIGNORETICKLOD_OFFSET UNITYSDK_OFFSET(0xC5FACC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENABLEPLAYERMOVEMENTSYNC_OFFSET UNITYSDK_OFFSET(0xC5FAC10)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENDWINDOWSTAGEDRAGGING_OFFSET UNITYSDK_OFFSET(0xC5E7EB0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENTITYFIREEFFECT_OFFSET UNITYSDK_OFFSET(0xC5E7970)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_EVALUATELEVELVARNUMBER_OFFSET UNITYSDK_OFFSET(0xC5F4310)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_EVALUATELEVELVARSHORT_OFFSET UNITYSDK_OFFSET(0xC5F40E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_EXITMINIGAME_OFFSET UNITYSDK_OFFSET(0xC5E91A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_FETCHTRAINMODEINFOS_OFFSET UNITYSDK_OFFSET(0xC5EDB30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_FIREEFFECT_OFFSET UNITYSDK_OFFSET(0xC5F4760)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_FLUSHENTITYLODCALCRESULT_OFFSET UNITYSDK_OFFSET(0xC5EBD10)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_FORCELOADALLMODELBYTASK_OFFSET UNITYSDK_OFFSET(0xC5EA9A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_FORCERESETPLAYER_OFFSET UNITYSDK_OFFSET(0xC5F2BD0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETATTACHPOINTTRANSFORMONSURFACE_1_OFFSET UNITYSDK_OFFSET(0xC5ECE70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETATTACHPOINTTRANSFORMONSURFACE_OFFSET UNITYSDK_OFFSET(0xC5ECD10)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETCURRENTSURFACECOLLIDERS_OFFSET UNITYSDK_OFFSET(0xC5F34D0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETDASHINFOS_OFFSET UNITYSDK_OFFSET(0xC5F2730)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETENTITYNAME_OFFSET UNITYSDK_OFFSET(0xC5F70E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETENTITYWORLDPOSITION_OFFSET UNITYSDK_OFFSET(0xC5F0A60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETLEVELCONFIG_OFFSET UNITYSDK_OFFSET(0xC5EB370)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERCAPSULECENTERPOSITION_OFFSET UNITYSDK_OFFSET(0xC5ECBD0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERGAMEOBJECT_OFFSET UNITYSDK_OFFSET(0xC5ED450)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERSKILLPANELCONFIGID_OFFSET UNITYSDK_OFFSET(0xC5F3810)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERWORLDPOSITION_OFFSET UNITYSDK_OFFSET(0xC5ECB20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETSERVICES_OFFSET UNITYSDK_OFFSET(0xC5F4A40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETSURFACEPLAYERIN_OFFSET UNITYSDK_OFFSET(0xC5ECC30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETTICKLODEXTRASAMPLEPOSITIONS_OFFSET UNITYSDK_OFFSET(0xC5F4A90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETWAYPOINTATTACHPOINTTRANSFORM_OFFSET UNITYSDK_OFFSET(0xC5F0D60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_CONTAINERID_OFFSET UNITYSDK_OFFSET(0xC5FECC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_CONTAINERINFO_OFFSET UNITYSDK_OFFSET(0xC5FEC40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_DISABLECAMERABLENDONCE_OFFSET UNITYSDK_OFFSET(0xC5FEC20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_FIVEDIMLOADMODE_OFFSET UNITYSDK_OFFSET(0xC5EBE40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_GAMEPLAYMODE_OFFSET UNITYSDK_OFFSET(0xC5EA350)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_GROUPID_OFFSET UNITYSDK_OFFSET(0xC5FEC60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_GROUPSTOKEEPONENTER_OFFSET UNITYSDK_OFFSET(0xC5FED20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_ISLEVELCREATED_OFFSET UNITYSDK_OFFSET(0xC5E7950)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_ISLEVELDESTROYED_OFFSET UNITYSDK_OFFSET(0xC5E7960)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_LASTENTERLEAVEINFO_OFFSET UNITYSDK_OFFSET(0xC5FED70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_LEVELBOUND_OFFSET UNITYSDK_OFFSET(0xC5FED50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_LISTENERFOLLOWTARGET_OFFSET UNITYSDK_OFFSET(0xC5FED90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_SHOULDSAVEGAMESTATEONSERVER_OFFSET UNITYSDK_OFFSET(0xC5F9D40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASASYNCLOADINGVIEW_OFFSET UNITYSDK_OFFSET(0xC5F29F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASDRAGGINGWINDOW_OFFSET UNITYSDK_OFFSET(0xC5E80A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASGAMEPLAYMODE_OFFSET UNITYSDK_OFFSET(0xC5F2B70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASHOVERINGWINDOW_OFFSET UNITYSDK_OFFSET(0xC5E8000)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_HIDEALLMODELBYLEVEL_OFFSET UNITYSDK_OFFSET(0xC5EAAA0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_INITSETONCELEVELVAR_OFFSET UNITYSDK_OFFSET(0xC5FD870)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_INITTHREADCOLLECTDATA_OFFSET UNITYSDK_OFFSET(0xC5EAD70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISENTITYLOADED_OFFSET UNITYSDK_OFFSET(0xC5F3870)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISFADINGOUTFINISH_OFFSET UNITYSDK_OFFSET(0xC5F7280)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISPLAYERONGROUNDSTATIC_OFFSET UNITYSDK_OFFSET(0xC5F37B0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISPLAYERSKILLUPGRADED_OFFSET UNITYSDK_OFFSET(0xC5F3370)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISWINDOWINSLOT_OFFSET UNITYSDK_OFFSET(0xC5E8140)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISWINDOWPERMCODESMATCH_OFFSET UNITYSDK_OFFSET(0xC5E8530)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_KILLEFFECT_OFFSET UNITYSDK_OFFSET(0xC5F47F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_MUTEPLAYERINPUT_OFFSET UNITYSDK_OFFSET(0xC5F1B00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_MUTEPLAYERSKILL_OFFSET UNITYSDK_OFFSET(0xC5F1B70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_ONWINDOWSTAGEDRAGGING_OFFSET UNITYSDK_OFFSET(0xC5E7E40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_PAUSEGAME_OFFSET UNITYSDK_OFFSET(0xC5F71F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERBASESCROLLGAMECALLBACK_OFFSET UNITYSDK_OFFSET(0xC5E99C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERCOLLECTCOINCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5E9400)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERMUSICBEATCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EC440)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERTASKSEQUENCES_OFFSET UNITYSDK_OFFSET(0xC5F3980)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEATTACHTARGET_OFFSET UNITYSDK_OFFSET(0xC5F0FB0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEBUTTONLISTENER_OFFSET UNITYSDK_OFFSET(0xC5F15A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEGLOBALTIMESCALE_OFFSET UNITYSDK_OFFSET(0xC5F7A30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVELEVELVARIABLELISTENER_OFFSET UNITYSDK_OFFSET(0xC5F4600)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVELITTLEGAMECUSTOMEVENTLISTENER_1_OFFSET UNITYSDK_OFFSET(0xC5F3DE0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVELITTLEGAMECUSTOMEVENTLISTENER_OFFSET UNITYSDK_OFFSET(0xC5F3D10)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEPLAYERINLISTENER_OFFSET UNITYSDK_OFFSET(0xC5F0900)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEPLAYEROUTLISTENER_OFFSET UNITYSDK_OFFSET(0xC5F0980)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVETASKMUSICBEATCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EC7B0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTLASTMINIGAMERESULT_OFFSET UNITYSDK_OFFSET(0xC5E9F20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5F1D40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTQUITCHENLINGGAMEBOY_OFFSET UNITYSDK_OFFSET(0xC5E7BF0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTTELEPORT_OFFSET UNITYSDK_OFFSET(0xC5F2600)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_RESETCHENLINGGAMEBOY_OFFSET UNITYSDK_OFFSET(0xC5E7C60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_RESETSIMPLEUIGAME_OFFSET UNITYSDK_OFFSET(0xC5E90C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_RESTARTMINIGAME_OFFSET UNITYSDK_OFFSET(0xC5E9130)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETATTACHTARGET_OFFSET UNITYSDK_OFFSET(0xC5F0F20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETAUDIOLISTENERMODE_OFFSET UNITYSDK_OFFSET(0xC5FE680)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETBUTTONENABLED_OFFSET UNITYSDK_OFFSET(0xC5F1660)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETCAMERAACTIVEBYTASK_OFFSET UNITYSDK_OFFSET(0xC5F1C50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETCAMERAORTHOGRAPHICSIZEBYTASK_OFFSET UNITYSDK_OFFSET(0xC5F1CC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETENTITYCOLLIDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xC5F19E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETENTITYRENDERVISIBLEWITHDITHER_OFFSET UNITYSDK_OFFSET(0xC5F1780)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETENTITYRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xC5F16E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETFOLLOWCAMERACLAMPMASK_OFFSET UNITYSDK_OFFSET(0xC5F1A70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETIGNORECOLLISIONTARGET_OFFSET UNITYSDK_OFFSET(0xC5F1060)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETLEVELVARSHORT_OFFSET UNITYSDK_OFFSET(0xC5F3E90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETMINIGAMELISTENERCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5E9210)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERINTERACTENABLED_OFFSET UNITYSDK_OFFSET(0xC5F1BE0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERRENDERVISIBLEWITHDITHER_OFFSET UNITYSDK_OFFSET(0xC5F1900)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xC5F1830)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERRESETMODE_OFFSET UNITYSDK_OFFSET(0xC5F2C30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERSKILLUPGRADED_OFFSET UNITYSDK_OFFSET(0xC5F2F60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETRENDERVISIBLE_OFFSET UNITYSDK_OFFSET(0xC5F4880)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETTRIGGERENABLE_OFFSET UNITYSDK_OFFSET(0xC5F1470)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETUPBUTTONLISTTRIGGER_OFFSET UNITYSDK_OFFSET(0xC5F13A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETUPSIMPLETRIGGER_OFFSET UNITYSDK_OFFSET(0xC5F1170)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETVISIBLE_OFFSET UNITYSDK_OFFSET(0xC5EE410)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETWINDOWPERMUTATION_OFFSET UNITYSDK_OFFSET(0xC5E8B00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_CONTAINERINFO_OFFSET UNITYSDK_OFFSET(0xC5FEC50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_DISABLECAMERABLENDONCE_OFFSET UNITYSDK_OFFSET(0xC5FEC30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_FIVEDIMLOADMODE_OFFSET UNITYSDK_OFFSET(0xC5EBE50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_LASTENTERLEAVEINFO_OFFSET UNITYSDK_OFFSET(0xC5FED80)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_LISTENERFOLLOWTARGET_OFFSET UNITYSDK_OFFSET(0xC5FEDA0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_SHOULDREVERSEINPUTDEADZONE_OFFSET UNITYSDK_OFFSET(0xC5F2ED0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTLOADINGINVISIBLEENTITIESVIEW_OFFSET UNITYSDK_OFFSET(0xC5F2A50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTUNLOADINVISIBLEENTITIESVIEW_OFFSET UNITYSDK_OFFSET(0xC5F2AE0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTWINDOWSTAGEDRAGGING_OFFSET UNITYSDK_OFFSET(0xC5E7DD0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTWINDOWSTAGE_OFFSET UNITYSDK_OFFSET(0xC5E7CD0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_GAMEBEGIN_OFFSET UNITYSDK_OFFSET(0xC5ED910)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_GAMEEND_OFFSET UNITYSDK_OFFSET(0xC5ED980)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_INITENTERBASICINFO_OFFSET UNITYSDK_OFFSET(0xC5ED6C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_INITEXITBASICINFO_OFFSET UNITYSDK_OFFSET(0xC5ED810)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_MINIGAMESTART_OFFSET UNITYSDK_OFFSET(0xC5EE020)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_RECORDENTERHIDDENAREA_OFFSET UNITYSDK_OFFSET(0xC5EE0F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_REPORTPLAYFLUTEINFO_OFFSET UNITYSDK_OFFSET(0xC5EE160)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_RESETENTERBASICINFO_OFFSET UNITYSDK_OFFSET(0xC5ED750)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTIC_INITEXITBASICINFO_OFFSET UNITYSDK_OFFSET(0xC5ED890)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_STOPWINDOWSTAGE_OFFSET UNITYSDK_OFFSET(0xC5E7D60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TELEPORTPLAYERTO_OFFSET UNITYSDK_OFFSET(0xC5F2480)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TICKRENDERINGPANEL_OFFSET UNITYSDK_OFFSET(0xC5ED630)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRAINPREPARESTOP_OFFSET UNITYSDK_OFFSET(0xC5EE2B0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRIGGERLITTLEGAMECUSTOMEVENT_1_OFFSET UNITYSDK_OFFSET(0xC5F3B10)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRIGGERLITTLEGAMECUSTOMEVENT_OFFSET UNITYSDK_OFFSET(0xC5F3A80)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRIGGERPRELOADALLMODEL_OFFSET UNITYSDK_OFFSET(0xC5EAB00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYGETOVERRIDERESETPOINTENTITYID_OFFSET UNITYSDK_OFFSET(0xC5F33F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYGETPLAYERJUMPENERGY_OFFSET UNITYSDK_OFFSET(0xC5F28E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYGETPLAYERSKILLCOOLDOWN_OFFSET UNITYSDK_OFFSET(0xC5F26C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYLOADINGALLENTITIESIMMEDIATELY_OFFSET UNITYSDK_OFFSET(0xC5E6F50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_UNREGISTERBASESCROLLGAMECALLBACK_OFFSET UNITYSDK_OFFSET(0xC5E9C70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_UNREGISTERCOLLECTCOINCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5E96E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_UNREGISTERMUSICBEATCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EC640)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_UPDATEFIVEDIMLOADMODEBYSTREAMING_OFFSET UNITYSDK_OFFSET(0xC5EA890)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE_UPDATEWINDOWSTAGEHOVERING_OFFSET UNITYSDK_OFFSET(0xC5E7F20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ADDENTERINTERACTCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5F54B0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYPLAYERIN_OFFSET UNITYSDK_OFFSET(0xC5F1FF0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYPLAYEROUT_1_OFFSET UNITYSDK_OFFSET(0xC5F1EE0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5F21F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYSTREAMINGFIVEDIMLOADMODETOGAME_OFFSET UNITYSDK_OFFSET(0xC5EA930)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYVISIBLE_OFFSET UNITYSDK_OFFSET(0xC5EE480)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ASYNCSETLISTENERMODE_OFFSET UNITYSDK_OFFSET(0xC5FD3E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CALCCAMERATOLOOKATDISTANCE_OFFSET UNITYSDK_OFFSET(0xC5EFE80)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CANLATEUPDATE_OFFSET UNITYSDK_OFFSET(0xC5F5890)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CHANGEWATERREFLECTIONMATERIALBASICCONFIG_OFFSET UNITYSDK_OFFSET(0xC5EEAC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEANWATERREFLECTIONMATERIALREPLACE_OFFSET UNITYSDK_OFFSET(0xC5EF580)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEANWATERREFLECTION_OFFSET UNITYSDK_OFFSET(0xC5F0640)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEARMUSICBEATCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EC990)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEARTRAINPREPARESTOP_OFFSET UNITYSDK_OFFSET(0xC5EE330)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEARTRIGGERPRELOAD_OFFSET UNITYSDK_OFFSET(0xC5EAC40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CREATELEVELASYNCFINISH_OFFSET UNITYSDK_OFFSET(0xC5E7720)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CREATESTREAMINGANCHOR_OFFSET UNITYSDK_OFFSET(0xC5FCF30)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__CTOR_OFFSET UNITYSDK_OFFSET(0xC5FEDB0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__DEALPLAYERINPUT_OFFSET UNITYSDK_OFFSET(0xC5F56A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__DEPLOYENTERTRIGGERS_OFFSET UNITYSDK_OFFSET(0xC5F9EE0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__DEPLOYENTERTRIGGER_OFFSET UNITYSDK_OFFSET(0xC5FA330)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__DISABLEPLAYER_OFFSET UNITYSDK_OFFSET(0xC5FD210)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__DOONPLAYERIN_OFFSET UNITYSDK_OFFSET(0xC5FBC40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__DOONPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5F6360)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ENABLEFIVEDIMLOADMODE_OFFSET UNITYSDK_OFFSET(0xC5EAA00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__FILLENTEREXITINFO_OFFSET UNITYSDK_OFFSET(0xC5EE1F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__FINISHINIT_OFFSET UNITYSDK_OFFSET(0xC5F4FB0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__GETWATERREFLECTIONMATERIAL_OFFSET UNITYSDK_OFFSET(0xC5EF380)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__GETWATERREFLECTIONMATPATH_OFFSET UNITYSDK_OFFSET(0xC5F0A00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__HASCAMERALIVE_OFFSET UNITYSDK_OFFSET(0xC5F72D0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITBASICSSTEP1_OFFSET UNITYSDK_OFFSET(0xC5F4DF0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITBASICSSTEP2_OFFSET UNITYSDK_OFFSET(0xC5F5360)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITLEVEL_OFFSET UNITYSDK_OFFSET(0xC5E7050)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITPLAYERANIMINFO_OFFSET UNITYSDK_OFFSET(0xC5F9E20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITPOSTPROCESS_OFFSET UNITYSDK_OFFSET(0xC5FD5F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITROOTENTITY_OFFSET UNITYSDK_OFFSET(0xC5F8630)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITSERVICES_OFFSET UNITYSDK_OFFSET(0xC5F7A90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITSYSTEMS_OFFSET UNITYSDK_OFFSET(0xC5E7130)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__LATEUPDATEWATERREFLECTION_OFFSET UNITYSDK_OFFSET(0xC5EFB00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__NEEDWAITSTREAMING_OFFSET UNITYSDK_OFFSET(0xC5F71B0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONARTNODELOAD_OFFSET UNITYSDK_OFFSET(0xC5EFA70)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONCLEAR_OFFSET UNITYSDK_OFFSET(0xC5F5D60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONENTERINTERACT_OFFSET UNITYSDK_OFFSET(0xC5FA860)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONENTITYWILLBEDESTROYED_OFFSET UNITYSDK_OFFSET(0xC5EBC80)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONFIVEDIMINSTANCECHANGED_OFFSET UNITYSDK_OFFSET(0xC5FEAF0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONINIT_OFFSET UNITYSDK_OFFSET(0xC5F4B00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONLATEUPDATE_OFFSET UNITYSDK_OFFSET(0xC5F58E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONMAPROTATED_OFFSET UNITYSDK_OFFSET(0xC5EBFA0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONPLAYFLUTE_OFFSET UNITYSDK_OFFSET(0xC5EA640)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONQUALITYSETTINGCHANGE_OFFSET UNITYSDK_OFFSET(0xC5EF920)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONSTART_OFFSET UNITYSDK_OFFSET(0xC5F5460)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTICKINTERVALCHANGED_OFFSET UNITYSDK_OFFSET(0xC5FE9F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTICK_OFFSET UNITYSDK_OFFSET(0xC5F5580)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTRANSFORMENTITYADDED_OFFSET UNITYSDK_OFFSET(0xC5EBA50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTRANSFORMENTITYDIRTY_OFFSET UNITYSDK_OFFSET(0xC5EBB60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONVIEWBOUNDENTITYADDED_OFFSET UNITYSDK_OFFSET(0xC5EB940)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__POSTINITLEVEL_OFFSET UNITYSDK_OFFSET(0xC5E7780)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__PREINITLEVEL_OFFSET UNITYSDK_OFFSET(0xC5E7530)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__RECOVERPLAYER_OFFSET UNITYSDK_OFFSET(0xC5FDD40)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REFRESHTICKLODEXTRASAMPLEPOSITIONS_OFFSET UNITYSDK_OFFSET(0xC5F5990)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERFIVEDIMINSTANCECHANGED_OFFSET UNITYSDK_OFFSET(0xC5F9220)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERFLUTECALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EA500)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERMAPROTATIONNOTIFY_OFFSET UNITYSDK_OFFSET(0xC5EBE60)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERSETAUDIOLISTENERMODENOTIFY_OFFSET UNITYSDK_OFFSET(0xC5F92C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERTICKINTERVALCHANGED_OFFSET UNITYSDK_OFFSET(0xC5F9130)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__RELEASEBASICS_OFFSET UNITYSDK_OFFSET(0xC5F6E00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__RELEASEPLAYERANIMINFO_OFFSET UNITYSDK_OFFSET(0xC5F9920)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVEENTERINTERACTCALLBACK_OFFSET UNITYSDK_OFFSET(0xC5F6B50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVEENTERTRIGGERS_OFFSET UNITYSDK_OFFSET(0xC5F6C20)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVEENTERTRIGGER_OFFSET UNITYSDK_OFFSET(0xC5FA7C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVESTREAMINGANCHOR_OFFSET UNITYSDK_OFFSET(0xC5FDB50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REQUESTPLAYERIN_OFFSET UNITYSDK_OFFSET(0xC5FA9C0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REQUESTPLAYEROUT_1_OFFSET UNITYSDK_OFFSET(0xC5F1D90)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__REQUESTPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5FADA0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETAUDIOONPLAYEREXIT_OFFSET UNITYSDK_OFFSET(0xC5F9360)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETFORCESYNCLOADNEXTFRAME_OFFSET UNITYSDK_OFFSET(0xC5EABC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETPOSTPROCESSONCLEAR_OFFSET UNITYSDK_OFFSET(0xC5F7170)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETPOSTPROCESSONINIT_OFFSET UNITYSDK_OFFSET(0xC5F7130)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__SHOWGAMEMAINPAGE_OFFSET UNITYSDK_OFFSET(0xC5FD2D0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__STARTCOLLECTHLODCOLLIDERS_OFFSET UNITYSDK_OFFSET(0xC5FD120)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__STARTCREATELEVELASYNC_OFFSET UNITYSDK_OFFSET(0xC5E7330)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__STARTLEVELGRAPH_OFFSET UNITYSDK_OFFSET(0xC5F5420)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__STOPCOLLECTHLODCOLLIDERS_OFFSET UNITYSDK_OFFSET(0xC5FDC50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__SYNCTRANSFORMROOT_OFFSET UNITYSDK_OFFSET(0xC5EBFF0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__TELEPORTPLAYERTO_OFFSET UNITYSDK_OFFSET(0xC5FC440)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__TICKTRAINMODEPREPARESTOP_OFFSET UNITYSDK_OFFSET(0xC5EE3A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__TRYINITMUSICBEATEFFECT_OFFSET UNITYSDK_OFFSET(0xC5EC4E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__TRYINITWATERREFLECTION_OFFSET UNITYSDK_OFFSET(0xC5EEB80)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__TRYPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5F5CC0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNINITPOSTPROCESS_OFFSET UNITYSDK_OFFSET(0xC5FE0F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERFIVEDIMINSTANCECHANGED_OFFSET UNITYSDK_OFFSET(0xC5F97E0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERFLUTECALLBACK_OFFSET UNITYSDK_OFFSET(0xC5EA5A0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERMAPROTATIONNOTIFY_OFFSET UNITYSDK_OFFSET(0xC5EBF00)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERSETAUDIOLISTENERMODENOTIFY_OFFSET UNITYSDK_OFFSET(0xC5F9880)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERTICKINTERVALCHANGED_OFFSET UNITYSDK_OFFSET(0xC5F96F0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__UPDATEFIVEDIMLOADMODEFROMSERVICES_OFFSET UNITYSDK_OFFSET(0xC5EACE0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTIONREPLACEMATERIAL_OFFSET UNITYSDK_OFFSET(0xC5EEFA0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTION_INITMATERIALPROPERTY_OFFSET UNITYSDK_OFFSET(0xC5EF660)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTION_ONPLAYERIN_OFFSET UNITYSDK_OFFSET(0xC5EEF50)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTION_ONPLAYEROUT_OFFSET UNITYSDK_OFFSET(0xC5EF330)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE___ASYNCSETLISTENERMODE_B__263_0_OFFSET UNITYSDK_OFFSET(0xC5FEFA0)
#define RPG_CLIENT_FIVEDIMGAMEINSTANCE___ASYNCSETLISTENERMODE_B__263_1_OFFSET UNITYSDK_OFFSET(0xC5FEFB0)

namespace RPG::Client
{
	inline static constexpr unsigned int FiveDimGameInstance_TypeDefinitionIndex = 57684;

	class FiveDimGameInstance : public ::Class_1_E0103A0EA6CD0F4C
	{
	public:
		// static const ::System::Single _WaterReflection_CameraToLookAtDistanceSmoothTime; // 0x0
		::System::Collections::Generic::Dictionary_2<::System::String*, ::UnityEngine::Material*>* _WaterReflectionOverrideWaterMaterialDic; // 0x78
		::RPG::GameCore::GameEntity* _ContainerEntity; // 0x80
		::System::String* _InstanceName; // 0x88
		::RPG::GameCore::GameEntity* _WaterEntity; // 0x90
		::UnityEngine::Transform* _GenericViewRoot; // 0x98
		::RPG::Client::FiveDimGameInstance_MusicBeatEffect* _MusicBeatEffect; // 0xA0
		::Class_3_1E4F9B0ED3BF21DE* _Services; // 0xA8
		::Class_3_206F177A6C7E89E8* _Systems; // 0xB0
		::System::String* _StreamingAnchorName; // 0xB8
		::RPG::GameCore::LevelLittleGameInfo* _ContainerInfo_k__BackingField; // 0xC0
		::UnityEngine::Transform* _CurveRoot; // 0xC8
		::RPG::GameCore::FiveDimGameConfig* _GameConfig; // 0xD0
		::UnityEngine::Transform* _TriggerRoot; // 0xD8
		::Class_1_B4357A1C72BABC6B* _Contexts; // 0xE0
		::System::Action* _OnPlayerInAction; // 0xE8
		::System::String* _WaterReflection_LowQualityMatPath; // 0xF0
		::System::String* _WaterReflection_WaterUniqueName; // 0xF8
		::RPG::GameCore::LittleGameLevelVarBindingMap* _LevelVarBindingMap; // 0x100
		::RPG::GameCore::FiveDimBakedLevelConfig* _BakedLevelConfig; // 0x108
		::System::String* _WaterReflection_DefaultMatPath; // 0x110
		::UnityEngine::Transform* _ListenerFollowTarget_k__BackingField; // 0x118
		::RPG::Client::LittleGame::SimpleEventService_1<::Class_2_B9E8C2EEAA5C96EC*>* _EventService; // 0x120
		::UnityEngine::Transform* _CameraRoot; // 0x128
		::RPG::Client::FiveDimPlayerEnterLeaveInfo* _LastEnterLeaveInfo_k__BackingField; // 0x130
		::System::Collections::Generic::List_1<::UnityEngine::Vector3>* _TickLodExtraSamplePositions; // 0x138
		::System::Action* _OnPlayerOutAction; // 0x140
		::System::Boolean _SettingEnableRefraction; // 0x148
		::System::Boolean _TrainMode_IsPreparingStop; // 0x149
		::System::Int32 _WaterRefelction_Property_EnableNearCameraFade; // 0x14C
		::System::Int32 _WaterReflection_Property_FoamMaskTilingSpeed; // 0x150
		::RPG::GameCore::FiveDimLoadMode _FiveDimLoadMode_k__BackingField; // 0x154
		::RPG::Client::FiveDimGameInstance_CreateLevelPhase _CreatingLevelState; // 0x158
		::System::Int32 _WaterRefelection_Property_NearCameraFade; // 0x15C
		::System::Single _TrainMode_TargetSpeedFactorBlendTimeElapsed; // 0x160
		::System::Int32 _WaterReflection_Property_DepthFoamAtten; // 0x164
		::System::Single _WaterReflection_CameraToLookAtDistanceVelocity; // 0x168
		::System::Int32 _WaterReflection_Property_DepthFoamExtent; // 0x16C
		::System::Single _TrainMode_TargetSpeedFactorBlendTime; // 0x170
		::System::Single _WaterReflection_CameraToLookAtDistance; // 0x174
		::RPG::Client::ReasonBool_1<::RPG::Client::FiveDimGameInstance_VisibleReason> _VisibleReasonBool; // 0x178
		::RPG::GameCore::FiveDimLoadMode _StreamingFiveDimLoadMode; // 0x180
		::System::Single _WaterReflection_CameraToLookAtDistanceTarget; // 0x184
		::System::Single _TrainMode_TargetSpeedFactor; // 0x188
		::System::Boolean _EnableCalcAnimatorURO; // 0x18C
		::System::Boolean _IsReplaceWaterMaterial; // 0x18D
		::System::Boolean _WaterReflection_CameraToLookAtDistanceForceUpdate; // 0x18E
		::System::Boolean _DisableCameraBlendOnce_k__BackingField; // 0x18F

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CTOR_OFFSET))(this);
		}

		::System::Void TryLoadingAllEntitiesImmediately()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYLOADINGALLENTITIESIMMEDIATELY_OFFSET))(this);
		}

		::System::Void _StartCreateLevelAsync()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__STARTCREATELEVELASYNC_OFFSET))(this);
		}

		::System::Void _CreateLevelAsyncFinish()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CREATELEVELASYNCFINISH_OFFSET))(this);
		}

		::System::Boolean get_IsLevelCreated()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_ISLEVELCREATED_OFFSET))(this);
		}

		::System::Boolean get_IsLevelDestroyed()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_ISLEVELDESTROYED_OFFSET))(this);
		}

		::System::Void EntityFireEffect(::System::UInt32 a1, ::RPG::GameCore::LittleGameFireEffectParams* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::RPG::GameCore::LittleGameFireEffectParams*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENTITYFIREEFFECT_OFFSET))(this, a1, a2);
		}

		::System::Void AvatarFireEffect(::RPG::GameCore::LittleGameFireEffectParams* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::LittleGameFireEffectParams*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_AVATARFIREEFFECT_OFFSET))(this, a1);
		}

		::System::Void AvatarKillEffect(::RPG::GameCore::LittleGameKillEffectParams* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::LittleGameKillEffectParams*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_AVATARKILLEFFECT_OFFSET))(this, a1);
		}

		::System::Void RequestQuitChenLingGameBoy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTQUITCHENLINGGAMEBOY_OFFSET))(this);
		}

		::System::Void ResetChenLingGameBoy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_RESETCHENLINGGAMEBOY_OFFSET))(this);
		}

		::System::Void StartWindowStage(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTWINDOWSTAGE_OFFSET))(this, a1);
		}

		::System::Void StopWindowStage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STOPWINDOWSTAGE_OFFSET))(this);
		}

		::System::Void StartWindowStageDragging(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTWINDOWSTAGEDRAGGING_OFFSET))(this, a1);
		}

		::System::Void OnWindowStageDragging(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ONWINDOWSTAGEDRAGGING_OFFSET))(this, a1);
		}

		::System::Void EndWindowStageDragging(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENDWINDOWSTAGEDRAGGING_OFFSET))(this, a1);
		}

		::System::Void UpdateWindowStageHovering(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_UPDATEWINDOWSTAGEHOVERING_OFFSET))(this, a1);
		}

		::System::Void CancelWindowStageDragging()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANCELWINDOWSTAGEDRAGGING_OFFSET))(this);
		}

		::System::Boolean HasHoveringWindow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASHOVERINGWINDOW_OFFSET))(this);
		}

		::System::Boolean HasDraggingWindow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASDRAGGINGWINDOW_OFFSET))(this);
		}

		::System::Boolean IsWindowInSlot(::System::UInt32 a1, ::System::UInt32 a2, ::System::UInt32 a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISWINDOWINSLOT_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean IsWindowPermCodesMatch(::System::UInt32 a1, ::Il2CppArray<::System::Int32>* a2, ::Il2CppArray<::System::Boolean>* a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::Il2CppArray<::System::Int32>*, ::Il2CppArray<::System::Boolean>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISWINDOWPERMCODESMATCH_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean SetWindowPermutation(::System::UInt32 a1, ::Il2CppArray<::System::UInt32>* a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::Il2CppArray<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETWINDOWPERMUTATION_OFFSET))(this, a1, a2);
		}

		::System::Void ResetSimpleUIGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_RESETSIMPLEUIGAME_OFFSET))(this);
		}

		::System::Void RestartMiniGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_RESTARTMINIGAME_OFFSET))(this);
		}

		::System::Void ExitMiniGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_EXITMINIGAME_OFFSET))(this);
		}

		::System::Void SetMiniGameListenerCallback(::System::Boolean a1, ::System::Action_1<::RPG::Client::LittleGame::FiveDim::MiniGameEventReason>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Action_1<::RPG::Client::LittleGame::FiveDim::MiniGameEventReason>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETMINIGAMELISTENERCALLBACK_OFFSET))(this, a1, a2);
		}

		::System::Void RegisterCollectCoinCallback(::System::Action* a1, ::System::Action* a2, ::System::Action* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*, ::System::Action*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERCOLLECTCOINCALLBACK_OFFSET))(this, a1, a2, a3);
		}

		::System::Void UnregisterCollectCoinCallback(::System::Action* a1, ::System::Action* a2, ::System::Action* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*, ::System::Action*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_UNREGISTERCOLLECTCOINCALLBACK_OFFSET))(this, a1, a2, a3);
		}

		::System::Void RegisterBaseScrollGameCallback(::System::Action* a1, ::System::Action* a2, ::System::Action* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*, ::System::Action*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERBASESCROLLGAMECALLBACK_OFFSET))(this, a1, a2, a3);
		}

		::System::Void UnregisterBaseScrollGameCallback(::System::Action* a1, ::System::Action* a2, ::System::Action* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*, ::System::Action*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_UNREGISTERBASESCROLLGAMECALLBACK_OFFSET))(this, a1, a2, a3);
		}

		::System::Void RequestLastMiniGameResult()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTLASTMINIGAMERESULT_OFFSET))(this);
		}

		::System::Void CreatePhantomPlayer(::Struct_2_5887222B9AE38D34_1 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_5887222B9AE38D34_1))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CREATEPHANTOMPLAYER_OFFSET))(this, a1);
		}

		::System::Void DestroyPhantomPlayer(::System::String* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_DESTROYPHANTOMPLAYER_OFFSET))(this, a1, a2);
		}

		::System::Void _RegisterFluteCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERFLUTECALLBACK_OFFSET))(this);
		}

		::System::Void _UnregisterFluteCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERFLUTECALLBACK_OFFSET))(this);
		}

		::System::Void _OnPlayFlute(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONPLAYFLUTE_OFFSET))(this, a1);
		}

		::System::Boolean CheckPlayerGravityOppositeToCurrentSurface()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CHECKPLAYERGRAVITYOPPOSITETOCURRENTSURFACE_OFFSET))(this);
		}

		::RPG::GameCore::FiveDimGameplayMode get_GameplayMode()
		{
			return ((::RPG::GameCore::FiveDimGameplayMode(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_GAMEPLAYMODE_OFFSET))(this);
		}

		::System::Void UpdateFiveDimLoadModeByStreaming(::RPG::GameCore::FiveDimLoadMode a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FiveDimLoadMode))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_UPDATEFIVEDIMLOADMODEBYSTREAMING_OFFSET))(this, a1);
		}

		::System::Void ForceLoadAllModelByTask(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_FORCELOADALLMODELBYTASK_OFFSET))(this, a1);
		}

		::System::Void HideAllModelByLevel(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_HIDEALLMODELBYLEVEL_OFFSET))(this, a1);
		}

		::System::Void TriggerPreloadAllModel(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRIGGERPRELOADALLMODEL_OFFSET))(this, a1);
		}

		::System::Void _ClearTriggerPreload()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEARTRIGGERPRELOAD_OFFSET))(this);
		}

		::System::Void _ApplyStreamingFiveDimLoadModeToGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYSTREAMINGFIVEDIMLOADMODETOGAME_OFFSET))(this);
		}

		::System::Void _EnableFiveDimLoadMode(::RPG::GameCore::FiveDimLoadMode a1, ::RPG::Client::LittleGame::FiveDim::ViewLoadModePriorityLevel a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FiveDimLoadMode, ::RPG::Client::LittleGame::FiveDim::ViewLoadModePriorityLevel, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ENABLEFIVEDIMLOADMODE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _UpdateFiveDimLoadModeFromServices()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UPDATEFIVEDIMLOADMODEFROMSERVICES_OFFSET))(this);
		}

		::System::Void _SetForceSyncLoadNextFrame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETFORCESYNCLOADNEXTFRAME_OFFSET))(this);
		}

		::System::Void InitThreadCollectData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_INITTHREADCOLLECTDATA_OFFSET))(this);
		}

		::System::Void DisposeThreadCollectData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_DISPOSETHREADCOLLECTDATA_OFFSET))(this);
		}

		::System::Void _OnViewBoundEntityAdded(::Entitas::IGroup_1<::Class_2_B9E8C2EEAA5C96EC*>* a1, ::Class_2_B9E8C2EEAA5C96EC* a2, ::System::Int32 a3, ::Entitas::IComponent* a4)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IGroup_1<::Class_2_B9E8C2EEAA5C96EC*>*, ::Class_2_B9E8C2EEAA5C96EC*, ::System::Int32, ::Entitas::IComponent*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONVIEWBOUNDENTITYADDED_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void _OnTransformEntityAdded(::Entitas::IGroup_1<::Class_2_B9E8C2EEAA5C96EC*>* a1, ::Class_2_B9E8C2EEAA5C96EC* a2, ::System::Int32 a3, ::Entitas::IComponent* a4)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IGroup_1<::Class_2_B9E8C2EEAA5C96EC*>*, ::Class_2_B9E8C2EEAA5C96EC*, ::System::Int32, ::Entitas::IComponent*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTRANSFORMENTITYADDED_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void _OnTransformEntityDirty(::Entitas::IGroup_1<::Class_2_B9E8C2EEAA5C96EC*>* a1, ::Class_2_B9E8C2EEAA5C96EC* a2, ::System::Int32 a3, ::Entitas::IComponent* a4)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IGroup_1<::Class_2_B9E8C2EEAA5C96EC*>*, ::Class_2_B9E8C2EEAA5C96EC*, ::System::Int32, ::Entitas::IComponent*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTRANSFORMENTITYDIRTY_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void _OnEntityWillBeDestroyed(::Entitas::IContext* a1, ::Entitas::IEntity* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IContext*, ::Entitas::IEntity*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONENTITYWILLBEDESTROYED_OFFSET))(this, a1, a2);
		}

		::System::Void FlushEntityLodCalcResult(::Struct_2_EC98B14B1B23001B a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_EC98B14B1B23001B))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_FLUSHENTITYLODCALCRESULT_OFFSET))(this, a1);
		}

		::RPG::GameCore::FiveDimLoadMode get_FiveDimLoadMode()
		{
			return ((::RPG::GameCore::FiveDimLoadMode(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_FIVEDIMLOADMODE_OFFSET))(this);
		}

		::System::Void set_FiveDimLoadMode(::RPG::GameCore::FiveDimLoadMode a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FiveDimLoadMode))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_FIVEDIMLOADMODE_OFFSET))(this, a1);
		}

		::System::Void _RegisterMapRotationNotify()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERMAPROTATIONNOTIFY_OFFSET))(this);
		}

		::System::Void _UnregisterMapRotationNotify()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERMAPROTATIONNOTIFY_OFFSET))(this);
		}

		::System::Void _OnMapRotated(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONMAPROTATED_OFFSET))(this, a1);
		}

		::System::Void RegisterMusicBeatCallback(::Class_0_16E4307DCC419505_256* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_256*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERMUSICBEATCALLBACK_OFFSET))(this, a1);
		}

		::System::Void UnRegisterMusicBeatCallback(::Class_0_16E4307DCC419505_256* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_256*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_UNREGISTERMUSICBEATCALLBACK_OFFSET))(this, a1);
		}

		::System::Void AddTaskMusicBeatCallback(::System::Action_1<::System::Single>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Single>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDTASKMUSICBEATCALLBACK_OFFSET))(this, a1);
		}

		::System::Void RemoveTaskMusicBeatCallback(::System::Action_1<::System::Single>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Single>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVETASKMUSICBEATCALLBACK_OFFSET))(this, a1);
		}

		::System::Void _TryInitMusicBeatEffect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__TRYINITMUSICBEATEFFECT_OFFSET))(this);
		}

		::System::Void _ClearMusicBeatCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEARMUSICBEATCALLBACK_OFFSET))(this);
		}

		::UnityEngine::Vector3 GetPlayerWorldPosition()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERWORLDPOSITION_OFFSET))(this);
		}

		::System::Boolean GetPlayerCapsuleCenterPosition(::UnityEngine::Vector3& a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERCAPSULECENTERPOSITION_OFFSET))(this, a1);
		}

		::Class_2_B9E8C2EEAA5C96EC* GetSurfacePlayerIn()
		{
			return ((::Class_2_B9E8C2EEAA5C96EC*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETSURFACEPLAYERIN_OFFSET))(this);
		}

		::System::Boolean GetAttachPointTransformOnSurface(::System::UInt32 a1, ::System::String* a2, ::Struct_2_EAC1BB0F093534A5& a3, ::System::Boolean a4)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::String*, ::Struct_2_EAC1BB0F093534A5&, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETATTACHPOINTTRANSFORMONSURFACE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Boolean GetAttachPointTransformOnSurface_1(::Class_2_B9E8C2EEAA5C96EC* a1, ::System::String* a2, ::Struct_2_EAC1BB0F093534A5& a3, ::System::Boolean a4)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_2_B9E8C2EEAA5C96EC*, ::System::String*, ::Struct_2_EAC1BB0F093534A5&, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETATTACHPOINTTRANSFORMONSURFACE_1_OFFSET))(this, a1, a2, a3, a4);
		}

		::UnityEngine::GameObject* GetPlayerGameObject()
		{
			return ((::UnityEngine::GameObject*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERGAMEOBJECT_OFFSET))(this);
		}

		::System::Void TickRenderingPanel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TICKRENDERINGPANEL_OFFSET))(this);
		}

		::System::Void Statistics_InitEnterBasicInfo(::System::String* a1, ::Struct_2_B82597A91E4CD455& a2, ::Struct_2_F01DF3CDCF3FD7AC& a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::Struct_2_B82597A91E4CD455&, ::Struct_2_F01DF3CDCF3FD7AC&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_INITENTERBASICINFO_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Statistics_ResetEnterBasicInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_RESETENTERBASICINFO_OFFSET))(this);
		}

		::System::Void Statistics_InitExitBasicInfo(::Struct_2_B82597A91E4CD455& a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_B82597A91E4CD455&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_INITEXITBASICINFO_OFFSET))(this, a1);
		}

		::System::Void Statistic_InitExitBasicInfo(::Struct_2_B7F6733609A5D9EA& a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_B7F6733609A5D9EA&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTIC_INITEXITBASICINFO_OFFSET))(this, a1);
		}

		::System::Void Statistics_GameBegin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_GAMEBEGIN_OFFSET))(this);
		}

		::System::Void Statistics_GameEnd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_GAMEEND_OFFSET))(this);
		}

		::System::Void Statistics_MiniGameStart(::RPG::Client::LittleGame::FiveDim::FiveDimMiniGameEnterType a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::LittleGame::FiveDim::FiveDimMiniGameEnterType))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_MINIGAMESTART_OFFSET))(this, a1);
		}

		::System::Void Statistics_RecordEnterHiddenArea(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_RECORDENTERHIDDENAREA_OFFSET))(this, a1);
		}

		::System::Void Statistics_ReportPlayFluteInfo(::System::Int32 a1, ::System::UInt32 a2, ::System::UInt32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STATISTICS_REPORTPLAYFLUTEINFO_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _FillEnterExitInfo(::RPG::Client::FiveDimPlayerEnterLeaveInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimPlayerEnterLeaveInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__FILLENTEREXITINFO_OFFSET))(this, a1);
		}

		::System::Void FetchTrainModeInfos(::RPG::Client::FiveDimTrainModeDisplayInfos* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimTrainModeDisplayInfos*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_FETCHTRAINMODEINFOS_OFFSET))(this, a1);
		}

		::System::Void TrainPrepareStop(::System::Single a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRAINPREPARESTOP_OFFSET))(this, a1, a2);
		}

		::System::Void _ClearTrainPrepareStop()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEARTRAINPREPARESTOP_OFFSET))(this);
		}

		::System::Void _TickTrainModePrepareStop(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__TICKTRAINMODEPREPARESTOP_OFFSET))(this, a1);
		}

		::System::Void SetVisible(::System::Boolean a1, ::RPG::Client::FiveDimGameInstance_VisibleReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::Client::FiveDimGameInstance_VisibleReason))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETVISIBLE_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckHasVisibleItems()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CHECKHASVISIBLEITEMS_OFFSET))(this);
		}

		::System::Void _ApplyVisible()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYVISIBLE_OFFSET))(this);
		}

		::System::Void ChangeWorldSeaMaterial(::System::String* a1, ::System::String* a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CHANGEWORLDSEAMATERIAL_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _TryInitWaterReflection()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__TRYINITWATERREFLECTION_OFFSET))(this);
		}

		::System::Void _WaterReflection_OnPlayerIn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTION_ONPLAYERIN_OFFSET))(this);
		}

		::System::Void _WaterReflection_OnPlayerOut()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTION_ONPLAYEROUT_OFFSET))(this);
		}

		::System::Void _WaterReflectionReplaceMaterial(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTIONREPLACEMATERIAL_OFFSET))(this, a1);
		}

		::System::Void _OnQualitySettingChange(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONQUALITYSETTINGCHANGE_OFFSET))(this, a1);
		}

		::System::Void _OnArtNodeLoad(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONARTNODELOAD_OFFSET))(this, a1);
		}

		::System::Void _LateUpdateWaterReflection()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__LATEUPDATEWATERREFLECTION_OFFSET))(this);
		}

		::System::Void _WaterReflection_InitMaterialProperty(::RPG::GameCore::CharacterModelComponent* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::CharacterModelComponent*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__WATERREFLECTION_INITMATERIALPROPERTY_OFFSET))(this, a1);
		}

		::System::Boolean _CalcCameraToLookAtDistance(::RPG::GameCore::FiveDimLevelSettings* a1, ::System::Single& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::FiveDimLevelSettings*, ::System::Single&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CALCCAMERATOLOOKATDISTANCE_OFFSET))(this, a1, a2);
		}

		::System::Void _CleanWaterReflection()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEANWATERREFLECTION_OFFSET))(this);
		}

		::System::Void _CleanWaterReflectionMaterialReplace()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CLEANWATERREFLECTIONMATERIALREPLACE_OFFSET))(this);
		}

		::System::String* _GetWaterReflectionMatPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__GETWATERREFLECTIONMATPATH_OFFSET))(this);
		}

		::UnityEngine::Material* _GetWaterReflectionMaterial()
		{
			return ((::UnityEngine::Material*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__GETWATERREFLECTIONMATERIAL_OFFSET))(this);
		}

		::System::Void _ChangeWaterReflectionMaterialBasicConfig(::System::String* a1, ::System::String* a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CHANGEWATERREFLECTIONMATERIALBASICCONFIG_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean GetEntityWorldPosition(::UnityEngine::Vector3& a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::UnityEngine::Vector3&, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETENTITYWORLDPOSITION_OFFSET))(this, a1, a2);
		}

		::System::Boolean GetWayPointAttachPointTransform(::Struct_2_EAC1BB0F093534A5& a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::Struct_2_EAC1BB0F093534A5&, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETWAYPOINTATTACHPOINTTRANSFORM_OFFSET))(this, a1, a2);
		}

		::System::Void SetAttachTarget(::System::UInt32 a1, ::System::ValueTuple_2<::System::UInt32, ::System::UInt32> a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::ValueTuple_2<::System::UInt32, ::System::UInt32>, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETATTACHTARGET_OFFSET))(this, a1, a2, a3);
		}

		::System::Void RemoveAttachTarget(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEATTACHTARGET_OFFSET))(this, a1);
		}

		::System::Void SetIgnoreCollisionTarget(::System::ValueTuple_2<::System::UInt32, ::System::UInt32> a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::ValueTuple_2<::System::UInt32, ::System::UInt32>, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETIGNORECOLLISIONTARGET_OFFSET))(this, a1, a2);
		}

		::System::Void SetupSimpleTrigger(::System::UInt32 a1, ::Struct_2_F8D9CEC872B937AF a2, ::Struct_2_F8D9CEC872B937AF a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::Struct_2_F8D9CEC872B937AF, ::Struct_2_F8D9CEC872B937AF, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETUPSIMPLETRIGGER_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetupButtonListTrigger(::System::UInt32 a1, ::Class_1_58F7C510A0EB2163* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::Class_1_58F7C510A0EB2163*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETUPBUTTONLISTTRIGGER_OFFSET))(this, a1, a2);
		}

		::System::Void ClearTrigger(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CLEARTRIGGER_OFFSET))(this, a1);
		}

		::System::Void SetTriggerEnable(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETTRIGGERENABLE_OFFSET))(this, a1, a2);
		}

		::System::Void AddButtonListener(::System::UInt32 a1, ::System::String* a2, ::Struct_2_F8D9CEC872B937AF a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::String*, ::Struct_2_F8D9CEC872B937AF))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDBUTTONLISTENER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void RemoveButtonListener(::System::UInt32 a1, ::System::String* a2, ::Struct_2_F8D9CEC872B937AF a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::String*, ::Struct_2_F8D9CEC872B937AF))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEBUTTONLISTENER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetButtonEnabled(::System::UInt32 a1, ::System::Collections::Generic::List_1<::System::String*>* a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Collections::Generic::List_1<::System::String*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETBUTTONENABLED_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetEntityRenderVisible(::System::UInt32 a1, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason a2, ::System::Boolean a3, ::System::Collections::Generic::List_1<::System::String*>* a4, ::System::Boolean a5)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason, ::System::Boolean, ::System::Collections::Generic::List_1<::System::String*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETENTITYRENDERVISIBLE_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Void SetEntityRenderVisibleWithDither(::System::UInt32 a1, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason a2, ::System::Boolean a3, ::System::Single a4, ::System::Boolean a5)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason, ::System::Boolean, ::System::Single, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETENTITYRENDERVISIBLEWITHDITHER_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Void SetPlayerRenderVisible(::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason a1, ::System::Boolean a2, ::System::Collections::Generic::List_1<::System::String*>* a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason, ::System::Boolean, ::System::Collections::Generic::List_1<::System::String*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERRENDERVISIBLE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetPlayerRenderVisibleWithDither(::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason a1, ::System::Boolean a2, ::System::Single a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason, ::System::Boolean, ::System::Single, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERRENDERVISIBLEWITHDITHER_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetEntityColliderVisible(::System::UInt32 a1, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason a2, ::System::Boolean a3, ::System::Collections::Generic::List_1<::System::String*>* a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::RPG::Client::LittleGame::FiveDim::ComponentInvisibleReason, ::System::Boolean, ::System::Collections::Generic::List_1<::System::String*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETENTITYCOLLIDERVISIBLE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void SetFollowCameraClampMask(::System::UInt32 a1, ::RPG::GameCore::FiveDimCameraFollowClampMask a2, ::System::Boolean a3, ::System::Single a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::RPG::GameCore::FiveDimCameraFollowClampMask, ::System::Boolean, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETFOLLOWCAMERACLAMPMASK_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void MutePlayerInput(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_MUTEPLAYERINPUT_OFFSET))(this, a1);
		}

		::System::Void MutePlayerSkill(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_MUTEPLAYERSKILL_OFFSET))(this, a1);
		}

		::System::Void SetPlayerInteractEnabled(::System::Boolean a1, ::RPG::Client::LittleGame::FiveDim::PlayerDisableInteractReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::Client::LittleGame::FiveDim::PlayerDisableInteractReason))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERINTERACTENABLED_OFFSET))(this, a1, a2);
		}

		::System::Void SetCameraActiveByTask(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETCAMERAACTIVEBYTASK_OFFSET))(this, a1, a2);
		}

		::System::Void SetCameraOrthographicSizeByTask(::System::UInt32 a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETCAMERAORTHOGRAPHICSIZEBYTASK_OFFSET))(this, a1, a2);
		}

		::System::Void RequestPlayerOut()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTPLAYEROUT_OFFSET))(this);
		}

		::System::Void ApplyPlayerOut()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_APPLYPLAYEROUT_OFFSET))(this);
		}

		::System::Void ApplyPlayerIn(::Struct_2_9195B4006FDD1545 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_9195B4006FDD1545, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_APPLYPLAYERIN_OFFSET))(this, a1, a2);
		}

		::System::Void ApplyPlayerOut_1(::Struct_2_FC595D1A561D8C6F a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_FC595D1A561D8C6F))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_APPLYPLAYEROUT_1_OFFSET))(this, a1);
		}

		::System::Void TeleportPlayerTo(::Struct_2_9195B4006FDD1545 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_9195B4006FDD1545, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TELEPORTPLAYERTO_OFFSET))(this, a1, a2);
		}

		::System::Void RequestTeleport(::RPG::GameCore::FiveDimPortalTarget* a1, ::System::Boolean a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FiveDimPortalTarget*, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REQUESTTELEPORT_OFFSET))(this, a1, a2, a3);
		}

		::System::Void AddPlayerInListener(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDPLAYERINLISTENER_OFFSET))(this, a1);
		}

		::System::Void RemovePlayerInListener(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEPLAYERINLISTENER_OFFSET))(this, a1);
		}

		::System::Void AddPlayerOutListener(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDPLAYEROUTLISTENER_OFFSET))(this, a1);
		}

		::System::Void RemovePlayerOutListener(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEPLAYEROUTLISTENER_OFFSET))(this, a1);
		}

		::System::Boolean TryGetPlayerSkillCoolDown(::System::Single& a1, ::System::Single& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Single&, ::System::Single&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYGETPLAYERSKILLCOOLDOWN_OFFSET))(this, a1, a2);
		}

		::System::Void GetDashInfos(::System::Boolean& a1, ::System::Boolean& a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean&, ::System::Boolean&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETDASHINFOS_OFFSET))(this, a1, a2);
		}

		::System::Boolean TryGetPlayerJumpEnergy(::System::UInt32& a1, ::System::UInt32& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32&, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYGETPLAYERJUMPENERGY_OFFSET))(this, a1, a2);
		}

		::System::Boolean CanPlayerUseSkill()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANPLAYERUSESKILL_OFFSET))(this);
		}

		::System::Boolean HasAsyncLoadingView()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASASYNCLOADINGVIEW_OFFSET))(this);
		}

		::System::Void StartLoadingInvisibleEntitiesView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTLOADINGINVISIBLEENTITIESVIEW_OFFSET))(this);
		}

		::System::Void StartUnloadInvisibleEntitiesView()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_STARTUNLOADINVISIBLEENTITIESVIEW_OFFSET))(this);
		}

		::System::Boolean HasGameplayMode(::RPG::GameCore::FiveDimGameplayMode a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::FiveDimGameplayMode))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_HASGAMEPLAYMODE_OFFSET))(this, a1);
		}

		::System::Void ForceResetPlayer()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_FORCERESETPLAYER_OFFSET))(this);
		}

		::System::Void SetPlayerResetMode(::RPG::GameCore::FiveDimPlayerResetMode a1, ::RPG::GameCore::FiveDimPlayerResetSweepDirection a2, ::System::Single a3, ::System::Single a4)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::FiveDimPlayerResetMode, ::RPG::GameCore::FiveDimPlayerResetSweepDirection, ::System::Single, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERRESETMODE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Boolean ShouldReverseInputDeadZone()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SHOULDREVERSEINPUTDEADZONE_OFFSET))(this);
		}

		::System::Void SetPlayerSkillUpgraded(::System::Boolean a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETPLAYERSKILLUPGRADED_OFFSET))(this, a1, a2);
		}

		::System::Boolean IsPlayerSkillUpgraded()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISPLAYERSKILLUPGRADED_OFFSET))(this);
		}

		::System::Boolean TryGetOverrideResetPointEntityID(::System::UInt32& a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRYGETOVERRIDERESETPOINTENTITYID_OFFSET))(this, a1);
		}

		::System::Void GetCurrentSurfaceColliders(::System::Collections::Generic::List_1<::UnityEngine::Collider*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::UnityEngine::Collider*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETCURRENTSURFACECOLLIDERS_OFFSET))(this, a1);
		}

		::System::Boolean CanUseCameraObserve()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANUSECAMERAOBSERVE_OFFSET))(this);
		}

		::System::Boolean IsPlayerOnGroundStatic()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISPLAYERONGROUNDSTATIC_OFFSET))(this);
		}

		::System::UInt32 GetPlayerSkillPanelConfigID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETPLAYERSKILLPANELCONFIGID_OFFSET))(this);
		}

		::System::Boolean IsEntityLoaded(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISENTITYLOADED_OFFSET))(this, a1);
		}

		::System::Boolean CanStart()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_CANSTART_OFFSET))(this);
		}

		::System::Void RegisterTaskSequences(::Il2CppArray<::RPG::GameCore::TaskConfig*>* a1, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a2, ::Il2CppArray<::RPG::GameCore::TaskConfig*>* a3, ::RPG::GameCore::TaskContext* a4)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*, ::Il2CppArray<::RPG::GameCore::TaskConfig*>*, ::RPG::GameCore::TaskContext*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REGISTERTASKSEQUENCES_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void TriggerLittleGameCustomEvent(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRIGGERLITTLEGAMECUSTOMEVENT_OFFSET))(this, a1);
		}

		::System::Void TriggerLittleGameCustomEvent_1(::System::String* a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_TRIGGERLITTLEGAMECUSTOMEVENT_1_OFFSET))(this, a1, a2);
		}

		::System::Void AddLittleGameCustomEventListener(::System::String* a1, ::System::Action* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDLITTLEGAMECUSTOMEVENTLISTENER_OFFSET))(this, a1, a2);
		}

		::System::Void AddLittleGameCustomEventListener_1(::System::String* a1, ::System::UInt32 a2, ::System::Action* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::UInt32, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDLITTLEGAMECUSTOMEVENTLISTENER_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Void RemoveLittleGameCustomEventListener(::System::String* a1, ::System::Action* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVELITTLEGAMECUSTOMEVENTLISTENER_OFFSET))(this, a1, a2);
		}

		::System::Void RemoveLittleGameCustomEventListener_1(::System::String* a1, ::System::UInt32 a2, ::System::Action* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::UInt32, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVELITTLEGAMECUSTOMEVENTLISTENER_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetLevelVarShort(::System::String* a1, ::RPG::GameCore::DynamicFloat* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::RPG::GameCore::DynamicFloat*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETLEVELVARSHORT_OFFSET))(this, a1, a2);
		}

		::System::Int16 EvaluateLevelVarShort(::RPG::GameCore::DynamicFloat* a1)
		{
			return ((::System::Int16(*)(::PVOID, ::RPG::GameCore::DynamicFloat*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_EVALUATELEVELVARSHORT_OFFSET))(this, a1);
		}

		::RPG::GameCore::FixPoint EvaluateLevelVarNumber(::RPG::GameCore::DynamicFloat* a1)
		{
			return ((::RPG::GameCore::FixPoint(*)(::PVOID, ::RPG::GameCore::DynamicFloat*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_EVALUATELEVELVARNUMBER_OFFSET))(this, a1);
		}

		::System::Void AddLevelVariableListener(::System::String* a1, ::System::Action* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDLEVELVARIABLELISTENER_OFFSET))(this, a1, a2);
		}

		::System::Void RemoveLevelVariableListener(::System::String* a1, ::System::Action* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVELEVELVARIABLELISTENER_OFFSET))(this, a1, a2);
		}

		::System::Void FireEffect(::Entitas::IEntity* a1, ::RPG::GameCore::LittleGameFireEffectParams* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IEntity*, ::RPG::GameCore::LittleGameFireEffectParams*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_FIREEFFECT_OFFSET))(this, a1, a2);
		}

		::System::Void KillEffect(::Entitas::IEntity* a1, ::RPG::GameCore::LittleGameKillEffectParams* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IEntity*, ::RPG::GameCore::LittleGameKillEffectParams*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_KILLEFFECT_OFFSET))(this, a1, a2);
		}

		::System::Void SetRenderVisible(::Entitas::IEntity* a1, ::System::Boolean a2, ::Il2CppArray<::System::String*>* a3)
		{
			return ((::System::Void(*)(::PVOID, ::Entitas::IEntity*, ::System::Boolean, ::Il2CppArray<::System::String*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETRENDERVISIBLE_OFFSET))(this, a1, a2, a3);
		}

		::Class_1_47EE63CB5C4DC8FC_5* GetServices()
		{
			return ((::Class_1_47EE63CB5C4DC8FC_5*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETSERVICES_OFFSET))(this);
		}

		::System::Void GetTickLodExtraSamplePositions(::System::Collections::Generic::List_1<::UnityEngine::Vector3>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::List_1<::UnityEngine::Vector3>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETTICKLODEXTRASAMPLEPOSITIONS_OFFSET))(this, a1);
		}

		::System::Void _OnInit(::Class_1_4CD8A1ACD565F336* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_4CD8A1ACD565F336*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONINIT_OFFSET))(this, a1);
		}

		::System::Void _FinishInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__FINISHINIT_OFFSET))(this);
		}

		::System::Void _StartLevelGraph()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__STARTLEVELGRAPH_OFFSET))(this);
		}

		::System::Void _OnStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONSTART_OFFSET))(this);
		}

		::System::Void _OnTick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTICK_OFFSET))(this, a1);
		}

		::System::Boolean _CanLateUpdate()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CANLATEUPDATE_OFFSET))(this);
		}

		::System::Void _OnLateUpdate(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONLATEUPDATE_OFFSET))(this, a1);
		}

		::System::Void _OnClear()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONCLEAR_OFFSET))(this);
		}

		::RPG::GameCore::LittleGameLevelConfig* GetLevelConfig()
		{
			return ((::RPG::GameCore::LittleGameLevelConfig*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETLEVELCONFIG_OFFSET))(this);
		}

		::System::String* GetEntityName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GETENTITYNAME_OFFSET))(this);
		}

		::System::Void _SetPostProcessOnInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETPOSTPROCESSONINIT_OFFSET))(this);
		}

		::System::Void _SetPostProcessOnClear()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETPOSTPROCESSONCLEAR_OFFSET))(this);
		}

		::System::Boolean _NeedWaitStreaming()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__NEEDWAITSTREAMING_OFFSET))(this);
		}

		::System::Void PauseGame(::System::Boolean a1, ::RPG::Client::LittleGame::FiveDim::TimeScaleReason a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::Client::LittleGame::FiveDim::TimeScaleReason))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_PAUSEGAME_OFFSET))(this, a1, a2);
		}

		::System::Boolean IsFadingOutFinish()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ISFADINGOUTFINISH_OFFSET))(this);
		}

		::System::Boolean _HasCameraLive()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__HASCAMERALIVE_OFFSET))(this);
		}

		::System::Void AddGlobalTimeScale(::System::String* a1, ::System::Single a2, ::System::Collections::Generic::List_1<::System::UInt32>* a3, ::System::Boolean a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Single, ::System::Collections::Generic::List_1<::System::UInt32>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ADDGLOBALTIMESCALE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void RemoveGlobalTimeScale(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_REMOVEGLOBALTIMESCALE_OFFSET))(this, a1);
		}

		::System::Void _InitBasicsStep1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITBASICSSTEP1_OFFSET))(this);
		}

		::System::Void _InitBasicsStep2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITBASICSSTEP2_OFFSET))(this);
		}

		::System::Void _InitSystems()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITSYSTEMS_OFFSET))(this);
		}

		::System::Void _InitServices()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITSERVICES_OFFSET))(this);
		}

		::System::Void _ReleaseBasics()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__RELEASEBASICS_OFFSET))(this);
		}

		::System::Void _InitRootEntity()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITROOTENTITY_OFFSET))(this);
		}

		::System::Void _SyncTransformRoot()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__SYNCTRANSFORMROOT_OFFSET))(this);
		}

		::System::Void _InitLevel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITLEVEL_OFFSET))(this);
		}

		::System::Void _PreInitLevel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__PREINITLEVEL_OFFSET))(this);
		}

		::System::Void _PostInitLevel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__POSTINITLEVEL_OFFSET))(this);
		}

		::System::Void _DealPlayerInput()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__DEALPLAYERINPUT_OFFSET))(this);
		}

		::System::Void _InitPlayerAnimInfo(::Struct_2_52A902145F5BE513_1& a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_52A902145F5BE513_1&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITPLAYERANIMINFO_OFFSET))(this, a1);
		}

		::System::Void _ReleasePlayerAnimInfo(::Struct_2_52A902145F5BE513_1& a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_52A902145F5BE513_1&))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__RELEASEPLAYERANIMINFO_OFFSET))(this, a1);
		}

		::System::Void _DeployEnterTriggers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__DEPLOYENTERTRIGGERS_OFFSET))(this);
		}

		::System::Void _RemoveEnterTriggers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVEENTERTRIGGERS_OFFSET))(this);
		}

		::System::Void _DeployEnterTrigger(::Class_2_B9E8C2EEAA5C96EC* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_B9E8C2EEAA5C96EC*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__DEPLOYENTERTRIGGER_OFFSET))(this, a1);
		}

		::System::Void _RemoveEnterTrigger(::Class_2_B9E8C2EEAA5C96EC* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_B9E8C2EEAA5C96EC*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVEENTERTRIGGER_OFFSET))(this, a1);
		}

		::System::Void _OnEnterInteract(::Class_0_16E4307DCC419505_425* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_425*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONENTERINTERACT_OFFSET))(this, a1);
		}

		::System::Void _AddEnterInteractCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ADDENTERINTERACTCALLBACK_OFFSET))(this);
		}

		::System::Void _RemoveEnterInteractCallback()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVEENTERINTERACTCALLBACK_OFFSET))(this);
		}

		::System::Void EnablePlayerMovementSync(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENABLEPLAYERMOVEMENTSYNC_OFFSET))(this, a1);
		}

		::System::Void EnableForceIgnoreTickLod()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_ENABLEFORCEIGNORETICKLOD_OFFSET))(this);
		}

		::System::Void _TryPlayerOut()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__TRYPLAYEROUT_OFFSET))(this);
		}

		::System::Void _RequestPlayerIn(::Class_2_B9E8C2EEAA5C96EC* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_B9E8C2EEAA5C96EC*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REQUESTPLAYERIN_OFFSET))(this, a1);
		}

		::System::Void _RequestPlayerOut(::Class_2_B9E8C2EEAA5C96EC* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_2_B9E8C2EEAA5C96EC*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REQUESTPLAYEROUT_OFFSET))(this, a1);
		}

		::System::Void _RequestPlayerOut_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REQUESTPLAYEROUT_1_OFFSET))(this);
		}

		::System::Void _ApplyPlayerIn(::Struct_2_9195B4006FDD1545 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_9195B4006FDD1545))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYPLAYERIN_OFFSET))(this, a1);
		}

		::System::Void _ApplyPlayerOut(::Struct_2_FC595D1A561D8C6F a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_FC595D1A561D8C6F))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYPLAYEROUT_OFFSET))(this, a1);
		}

		::System::Void _ApplyPlayerOut_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__APPLYPLAYEROUT_1_OFFSET))(this);
		}

		::System::Void _DoOnPlayerIn()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__DOONPLAYERIN_OFFSET))(this);
		}

		::System::Void _DoOnPlayerOut()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__DOONPLAYEROUT_OFFSET))(this);
		}

		::System::Void _CreateStreamingAnchor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__CREATESTREAMINGANCHOR_OFFSET))(this);
		}

		::System::Void _RemoveStreamingAnchor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REMOVESTREAMINGANCHOR_OFFSET))(this);
		}

		::System::Void _TeleportPlayerTo(::Struct_2_EAC1BB0F093534A5 a1)
		{
			return ((::System::Void(*)(::PVOID, ::Struct_2_EAC1BB0F093534A5))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__TELEPORTPLAYERTO_OFFSET))(this, a1);
		}

		::System::Void _DisablePlayer()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__DISABLEPLAYER_OFFSET))(this);
		}

		::System::Void _RecoverPlayer()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__RECOVERPLAYER_OFFSET))(this);
		}

		::System::Void _ShowGameMainPage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__SHOWGAMEMAINPAGE_OFFSET))(this);
		}

		::System::Void _AsyncSetListenerMode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ASYNCSETLISTENERMODE_OFFSET))(this);
		}

		::System::Void SetAudioListenerMode(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SETAUDIOLISTENERMODE_OFFSET))(this, a1);
		}

		::System::Void _RegisterSetAudioListenerModeNotify()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERSETAUDIOLISTENERMODENOTIFY_OFFSET))(this);
		}

		::System::Void _UnregisterSetAudioListenerModeNotify()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERSETAUDIOLISTENERMODENOTIFY_OFFSET))(this);
		}

		::System::Void _SetAudioOnPlayerExit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__SETAUDIOONPLAYEREXIT_OFFSET))(this);
		}

		::System::Void _InitPostProcess()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__INITPOSTPROCESS_OFFSET))(this);
		}

		::System::Void _UninitPostProcess()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNINITPOSTPROCESS_OFFSET))(this);
		}

		::System::Void InitSetOnceLevelVar()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_INITSETONCELEVELVAR_OFFSET))(this);
		}

		::System::Void _StartCollectHLODColliders()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__STARTCOLLECTHLODCOLLIDERS_OFFSET))(this);
		}

		::System::Void _StopCollectHLODColliders()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__STOPCOLLECTHLODCOLLIDERS_OFFSET))(this);
		}

		::System::Void _RefreshTickLodExtraSamplePositions()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REFRESHTICKLODEXTRASAMPLEPOSITIONS_OFFSET))(this);
		}

		::System::Void _OnTickIntervalChanged(::Class_0_16E4307DCC419505_425* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_0_16E4307DCC419505_425*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONTICKINTERVALCHANGED_OFFSET))(this, a1);
		}

		::System::Void _RegisterTickIntervalChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERTICKINTERVALCHANGED_OFFSET))(this);
		}

		::System::Void _UnregisterTickIntervalChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERTICKINTERVALCHANGED_OFFSET))(this);
		}

		::System::Void _OnFiveDimInstanceChanged(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__ONFIVEDIMINSTANCECHANGED_OFFSET))(this, a1);
		}

		::System::Void _RegisterFiveDimInstanceChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__REGISTERFIVEDIMINSTANCECHANGED_OFFSET))(this);
		}

		::System::Void _UnregisterFiveDimInstanceChanged()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE__UNREGISTERFIVEDIMINSTANCECHANGED_OFFSET))(this);
		}

		::System::Boolean get_DisableCameraBlendOnce()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_DISABLECAMERABLENDONCE_OFFSET))(this);
		}

		::System::Void set_DisableCameraBlendOnce(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_DISABLECAMERABLENDONCE_OFFSET))(this, a1);
		}

		::System::Boolean get_ShouldSaveGameStateOnServer()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_SHOULDSAVEGAMESTATEONSERVER_OFFSET))(this);
		}

		::RPG::GameCore::LevelLittleGameInfo* get_ContainerInfo()
		{
			return ((::RPG::GameCore::LevelLittleGameInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_CONTAINERINFO_OFFSET))(this);
		}

		::System::Void set_ContainerInfo(::RPG::GameCore::LevelLittleGameInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::LevelLittleGameInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_CONTAINERINFO_OFFSET))(this, a1);
		}

		::System::UInt32 get_GroupID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_GROUPID_OFFSET))(this);
		}

		::System::UInt32 get_ContainerID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_CONTAINERID_OFFSET))(this);
		}

		::Il2CppArray<::System::UInt32>* get_GroupsToKeepOnEnter()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_GROUPSTOKEEPONENTER_OFFSET))(this);
		}

		::RPG::GameCore::MeshBound* get_LevelBound()
		{
			return ((::RPG::GameCore::MeshBound*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_LEVELBOUND_OFFSET))(this);
		}

		::RPG::Client::FiveDimPlayerEnterLeaveInfo* get_LastEnterLeaveInfo()
		{
			return ((::RPG::Client::FiveDimPlayerEnterLeaveInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_LASTENTERLEAVEINFO_OFFSET))(this);
		}

		::System::Void set_LastEnterLeaveInfo(::RPG::Client::FiveDimPlayerEnterLeaveInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FiveDimPlayerEnterLeaveInfo*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_LASTENTERLEAVEINFO_OFFSET))(this, a1);
		}

		::UnityEngine::Transform* get_ListenerFollowTarget()
		{
			return ((::UnityEngine::Transform*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_GET_LISTENERFOLLOWTARGET_OFFSET))(this);
		}

		::System::Void set_ListenerFollowTarget(::UnityEngine::Transform* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Transform*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE_SET_LISTENERFOLLOWTARGET_OFFSET))(this, a1);
		}

		::System::Void __AsyncSetListenerMode_b__263_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE___ASYNCSETLISTENERMODE_B__263_0_OFFSET))(this);
		}

		::System::Boolean __AsyncSetListenerMode_b__263_1()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FIVEDIMGAMEINSTANCE___ASYNCSETLISTENERMODE_B__263_1_OFFSET))(this);
		}
	};
}
