#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Class_1_41E07A9DDAB7FC78.h"
#include "unitysdk/Enum_3_75A1C8C41006A504.h"

class Class_1_D17272E82AE804C2_457;
namespace RPG::Client { class GridFightBattleResultBonus; }
namespace System::Collections::Generic { template <typename T> class IList_1; }

#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_ISCONCERNEDWITH_OFFSET UNITYSDK_OFFSET(0xC6C49A0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATEBEFORE_OFFSET UNITYSDK_OFFSET(0xC6C4A30)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATECOIN_OFFSET UNITYSDK_OFFSET(0xC6C4CF0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATELEVELANDEXP_OFFSET UNITYSDK_OFFSET(0xC6C4EE0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATEMAXROLENUM_OFFSET UNITYSDK_OFFSET(0xC6C5290)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATEORB_OFFSET UNITYSDK_OFFSET(0xC6C5480)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATESTART_OFFSET UNITYSDK_OFFSET(0xC6C49F0)
#define RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER__CTOR_OFFSET UNITYSDK_OFFSET(0xC6C5710)

namespace RPG::Client
{
	inline static constexpr unsigned int GridFightBonusServerData_BattleResultBonusSummarizer_TypeDefinitionIndex = 61508;

	class GridFightBonusServerData_BattleResultBonusSummarizer : public ::Class_1_41E07A9DDAB7FC78
	{
	public:
		::RPG::Client::GridFightBattleResultBonus* _BattleBonus; // 0x10

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER__CTOR_OFFSET))(this);
		}

		::System::Boolean IsConcernedWith(::Enum_3_75A1C8C41006A504 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Enum_3_75A1C8C41006A504))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_ISCONCERNEDWITH_OFFSET))(this, a1);
		}

		::System::Void UpdateStart()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATESTART_OFFSET))(this);
		}

		::System::Void UpdateBefore(::Enum_3_75A1C8C41006A504 a1, ::System::Collections::Generic::IList_1<::System::UInt32>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_75A1C8C41006A504, ::System::Collections::Generic::IList_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATEBEFORE_OFFSET))(this, a1, a2);
		}

		::System::Void UpdateCoin(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATECOIN_OFFSET))(this, a1);
		}

		::System::Void UpdateLevelAndExp(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATELEVELANDEXP_OFFSET))(this, a1, a2);
		}

		::System::Void UpdateMaxRoleNum(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATEMAXROLENUM_OFFSET))(this, a1);
		}

		::System::Void UpdateOrb(::Class_1_D17272E82AE804C2_457* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D17272E82AE804C2_457*))((::PBYTE)hIl2Cpp + RPG_CLIENT_GRIDFIGHTBONUSSERVERDATA_BATTLERESULTBONUSSUMMARIZER_UPDATEORB_OFFSET))(this, a1);
		}
	};
}
