#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Enum_3_01618AD0437C8486.h"
#include "unitysdk/Enum_3_0A3761FE34514D6C_48.h"
#include "unitysdk/Enum_3_5AA38DC400740F29.h"
#include "unitysdk/RPG/Client/BaseModule.h"
#include "unitysdk/RPG/Client/ItemData_ProductPlatformType.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/InventorySortType.h"
#include "unitysdk/RPG/GameCore/ItemMainType.h"
#include "unitysdk/RPG/GameCore/ItemRarity.h"
#include "unitysdk/RPG/GameCore/ItemSubType.h"

class Class_1_097D93F83453E9A1_1;
class Class_1_21DCD4640D389503_2;
class Class_1_3699B5F0EA586362;
class Class_1_38FAAB38F863E2D1;
class Class_1_45BB92167AED63A0_103;
class Class_1_45BB92167AED63A0_52;
class Class_1_66F48F07052E8E37;
class Class_1_7E1E05C17C895270;
class Class_1_C086E47345F86771_11;
class Class_1_C086E47345F86771_12;
class Class_1_C9E417278351157F_7;
class Class_1_D17272E82AE804C2_1114;
class Class_1_D17272E82AE804C2_575;
class Class_1_D17272E82AE804C2_854;
class Class_1_EBB10EC01CCC4716_11;
class Class_1_FC8BF52F067E8047;
namespace Google::Protobuf::Collections { template <typename T> class RepeatedField_1; }
namespace Proto { class ItemList; }
namespace Proto { class PileItem; }
namespace RPG::Client { class AetherSkillCoreItemData; }
namespace RPG::Client { class ConvertibleItemData; }
namespace RPG::Client { class EquipmentItemData; }
namespace RPG::Client { class ItemAutoConversionRecord; }
namespace RPG::Client { class ItemData; }
namespace RPG::Client { class ItemDisplayData; }
namespace RPG::Client { class RelicItemData; }
namespace RPG::GameCore { class InventoryTabRow; }
namespace RPG::GameCore { class ItemComefromRow; }
namespace RPG::GameCore { class ItemRarityConfigRow; }
namespace RPG::GameCore { class ItemRow; }
namespace RPG::GameCore { class ItemUseDataRow; }
namespace System { class Object; }
namespace System { template <typename T> class Predicate_1; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class IList_1; }
namespace System::Collections::Generic { template <typename T> class IReadOnlyList_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define RPG_CLIENT_INVENTORYMODULE_CHECKISHEROAVATAREIDOLONITEMTYPE_OFFSET UNITYSDK_OFFSET(0xC8ED380)
#define RPG_CLIENT_INVENTORYMODULE_CHECKUSEITEM_OFFSET UNITYSDK_OFFSET(0xC8E9710)
#define RPG_CLIENT_INVENTORYMODULE_DISPOSE_OFFSET UNITYSDK_OFFSET(0xC8E8BE0)
#define RPG_CLIENT_INVENTORYMODULE_ENABLESETFAVORITE_OFFSET UNITYSDK_OFFSET(0xC8E4E00)
#define RPG_CLIENT_INVENTORYMODULE_FINDALLEQUIPMENTS_OFFSET UNITYSDK_OFFSET(0xC8EA1B0)
#define RPG_CLIENT_INVENTORYMODULE_FINDEQUIPMENT_OFFSET UNITYSDK_OFFSET(0xC8EA040)
#define RPG_CLIENT_INVENTORYMODULE_FINDTABIDBYITEMID_OFFSET UNITYSDK_OFFSET(0xC8EB190)
#define RPG_CLIENT_INVENTORYMODULE_GETAETHERSKILLCOREITEMDATABYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8ED590)
#define RPG_CLIENT_INVENTORYMODULE_GETCONVERTIBLEITEMDATABYITEMID_OFFSET UNITYSDK_OFFSET(0xC8EE2D0)
#define RPG_CLIENT_INVENTORYMODULE_GETCONVERTIBLEITEMDATABYITEMSUBTYPE_OFFSET UNITYSDK_OFFSET(0xC8EE1D0)
#define RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTDATABYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E9EC0)
#define RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTDATABYUID_OFFSET UNITYSDK_OFFSET(0xC8EA3F0)
#define RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTMAXRANKANDCOUNTBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E9C60)
#define RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTMAXRANKBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E99F0)
#define RPG_CLIENT_INVENTORYMODULE_GETFOODCOUNTBYCONSUMETYPEID_OFFSET UNITYSDK_OFFSET(0xC8E3E90)
#define RPG_CLIENT_INVENTORYMODULE_GETFOODITEMSBYCONSUMETYPE_OFFSET UNITYSDK_OFFSET(0xC8E4480)
#define RPG_CLIENT_INVENTORYMODULE_GETFOODITEMSBYMAZEBUFFPOOL_OFFSET UNITYSDK_OFFSET(0xC8EBC30)
#define RPG_CLIENT_INVENTORYMODULE_GETHCOINCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8EE6E0)
#define RPG_CLIENT_INVENTORYMODULE_GETINVENTORYTABITEMS_OFFSET UNITYSDK_OFFSET(0xC8EB540)
#define RPG_CLIENT_INVENTORYMODULE_GETISPILEBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8EE150)
#define RPG_CLIENT_INVENTORYMODULE_GETISPILEBYITEMMAINTYPE_OFFSET UNITYSDK_OFFSET(0xC8EE960)
#define RPG_CLIENT_INVENTORYMODULE_GETISPILEBYITEMSUBTYPE_OFFSET UNITYSDK_OFFSET(0xC8EC080)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMAUTOCONVERSIONRECORDS_OFFSET UNITYSDK_OFFSET(0xC8ECB50)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMCOMEFROM_OFFSET UNITYSDK_OFFSET(0xC8EEE20)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMCOUNTAFTERDELETEBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E92A0)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMCOUNTBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E9240)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMDATABYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E4C30)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMDATABYUID_OFFSET UNITYSDK_OFFSET(0xC8E9960)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMRARITYCONFIG_OFFSET UNITYSDK_OFFSET(0xC8EE4F0)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMROW_OFFSET UNITYSDK_OFFSET(0xC8EE3D0)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMSBYMAINTYPES_OFFSET UNITYSDK_OFFSET(0xC8E2A80)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMSBYSUBTYPES_OFFSET UNITYSDK_OFFSET(0xC8E3710)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMSBYSUBTYPE_OFFSET UNITYSDK_OFFSET(0xC8EA5F0)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMSINTYPES_OFFSET UNITYSDK_OFFSET(0xC8EA670)
#define RPG_CLIENT_INVENTORYMODULE_GETITEMUSEDATAROWBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8EE9B0)
#define RPG_CLIENT_INVENTORYMODULE_GETLIGHTCONECOUNT_OFFSET UNITYSDK_OFFSET(0xC8EAC00)
#define RPG_CLIENT_INVENTORYMODULE_GETLIGHTCONEITEMSMAXNUM_OFFSET UNITYSDK_OFFSET(0xC8EE760)
#define RPG_CLIENT_INVENTORYMODULE_GETMPITEMS_OFFSET UNITYSDK_OFFSET(0xC8E39D0)
#define RPG_CLIENT_INVENTORYMODULE_GETONETIMESYNCITEMAUTOCONVERSIONRECORD_OFFSET UNITYSDK_OFFSET(0xC8ECB90)
#define RPG_CLIENT_INVENTORYMODULE_GETPILEITEMS_OFFSET UNITYSDK_OFFSET(0xC8EBBB0)
#define RPG_CLIENT_INVENTORYMODULE_GETQUICKCONSUMABLEITEMBYCONSUMETYPE_OFFSET UNITYSDK_OFFSET(0xC8E4B20)
#define RPG_CLIENT_INVENTORYMODULE_GETQUICKCONSUMABLEITEMIDBYCONSUMETYPE_OFFSET UNITYSDK_OFFSET(0xC8E49D0)
#define RPG_CLIENT_INVENTORYMODULE_GETQUICKCONSUMABLEITEMS_OFFSET UNITYSDK_OFFSET(0xC8E40A0)
#define RPG_CLIENT_INVENTORYMODULE_GETRELICDATABYUID_OFFSET UNITYSDK_OFFSET(0xC8EA4F0)
#define RPG_CLIENT_INVENTORYMODULE_GETRELICITEMSMAXNUM_OFFSET UNITYSDK_OFFSET(0xC8EE860)
#define RPG_CLIENT_INVENTORYMODULE_GETRESBARCOUNTBYCONFIGID_OFFSET UNITYSDK_OFFSET(0xC8E9460)
#define RPG_CLIENT_INVENTORYMODULE_GETREVIVEITEMS_OFFSET UNITYSDK_OFFSET(0xC8E3490)
#define RPG_CLIENT_INVENTORYMODULE_GETREWARDITEMDISPLAYDATA_OFFSET UNITYSDK_OFFSET(0xC8EEA10)
#define RPG_CLIENT_INVENTORYMODULE_GETSORTEDMPITEMS_OFFSET UNITYSDK_OFFSET(0xC8E3CC0)
#define RPG_CLIENT_INVENTORYMODULE_GETSORTTYPENAME_OFFSET UNITYSDK_OFFSET(0xC8EE5A0)
#define RPG_CLIENT_INVENTORYMODULE_GETSUPERRARELIGHTCONECOUNT_OFFSET UNITYSDK_OFFSET(0xC8EAC90)
#define RPG_CLIENT_INVENTORYMODULE_GETUNIQUEITEMSCOUNTBYMAINTYPE_OFFSET UNITYSDK_OFFSET(0xC8EBA70)
#define RPG_CLIENT_INVENTORYMODULE_GETUNIQUEITEMSCOUNT_OFFSET UNITYSDK_OFFSET(0xC8EBA00)
#define RPG_CLIENT_INVENTORYMODULE_GETUNIQUEITEMS_OFFSET UNITYSDK_OFFSET(0xC8EBBF0)
#define RPG_CLIENT_INVENTORYMODULE_GET_GOTOLOCATEITEMDATA_OFFSET UNITYSDK_OFFSET(0xC8F8DC0)
#define RPG_CLIENT_INVENTORYMODULE_GET_INSTANCE_OFFSET UNITYSDK_OFFSET(0xC8F8D20)
#define RPG_CLIENT_INVENTORYMODULE_GET_ITEMVISIBALEPREDICATE_OFFSET UNITYSDK_OFFSET(0xC8F8DA0)
#define RPG_CLIENT_INVENTORYMODULE_GET_QUICKCONSUMABLEITEMS_OFFSET UNITYSDK_OFFSET(0xC8E6380)
#define RPG_CLIENT_INVENTORYMODULE_GET__QUICKCONSUMABLEFEATURECLOSED_OFFSET UNITYSDK_OFFSET(0xC8E63E0)
#define RPG_CLIENT_INVENTORYMODULE_HASITEMINSUBTYPE_OFFSET UNITYSDK_OFFSET(0xC8EBF00)
#define RPG_CLIENT_INVENTORYMODULE_HASMPITEM_OFFSET UNITYSDK_OFFSET(0xC8E3770)
#define RPG_CLIENT_INVENTORYMODULE_INIT_OFFSET UNITYSDK_OFFSET(0xC8E6C50)
#define RPG_CLIENT_INVENTORYMODULE_ISCOMEFROMVALID_OFFSET UNITYSDK_OFFSET(0xC8EF480)
#define RPG_CLIENT_INVENTORYMODULE_ISFAVORITEFOODREACHMAX_OFFSET UNITYSDK_OFFSET(0xC8E3430)
#define RPG_CLIENT_INVENTORYMODULE_ISFAVORITENEW_OFFSET UNITYSDK_OFFSET(0xC8E4EB0)
#define RPG_CLIENT_INVENTORYMODULE_ISITEMCONVERSIONED_OFFSET UNITYSDK_OFFSET(0xC8ECCC0)
#define RPG_CLIENT_INVENTORYMODULE_ISITEMEXPIRED_OFFSET UNITYSDK_OFFSET(0xC8EC870)
#define RPG_CLIENT_INVENTORYMODULE_ISITEMIMPORTHINTBYID_OFFSET UNITYSDK_OFFSET(0xC8EEDD0)
#define RPG_CLIENT_INVENTORYMODULE_ISITEMIMPORTHINT_OFFSET UNITYSDK_OFFSET(0xC8EEC90)
#define RPG_CLIENT_INVENTORYMODULE_ISQUICKCONSUMABLETURNSWITCHOPEN_1_OFFSET UNITYSDK_OFFSET(0xC8E47B0)
#define RPG_CLIENT_INVENTORYMODULE_ISQUICKCONSUMABLETURNSWITCHOPEN_OFFSET UNITYSDK_OFFSET(0xC8E4710)
#define RPG_CLIENT_INVENTORYMODULE_ISREWARDITEMREACHPILELIMIT_OFFSET UNITYSDK_OFFSET(0xC8ED6B0)
#define RPG_CLIENT_INVENTORYMODULE_LOCKALLEQUIPMENTS_OFFSET UNITYSDK_OFFSET(0xC8E3130)
#define RPG_CLIENT_INVENTORYMODULE_ONEXPIREDITEMSSHOWN_OFFSET UNITYSDK_OFFSET(0xC8EC0D0)
#define RPG_CLIENT_INVENTORYMODULE_RECORDEXPIREDITEMS_1_OFFSET UNITYSDK_OFFSET(0xC8F5C40)
#define RPG_CLIENT_INVENTORYMODULE_RECORDEXPIREDITEMS_OFFSET UNITYSDK_OFFSET(0xC8F57C0)
#define RPG_CLIENT_INVENTORYMODULE_SENDCANCELAUTOCONVERSIONCACHECSREQ_OFFSET UNITYSDK_OFFSET(0xC8ECBD0)
#define RPG_CLIENT_INVENTORYMODULE_SENDPACKETSAFTERLOGINFINISHED_OFFSET UNITYSDK_OFFSET(0xC8E9060)
#define RPG_CLIENT_INVENTORYMODULE_SETITEMVISIBLEPREDICATE_OFFSET UNITYSDK_OFFSET(0xC8ED650)
#define RPG_CLIENT_INVENTORYMODULE_SETTURNFOODSWITCH_1_OFFSET UNITYSDK_OFFSET(0xC8E48A0)
#define RPG_CLIENT_INVENTORYMODULE_SETTURNFOODSWITCH_OFFSET UNITYSDK_OFFSET(0xC8E4840)
#define RPG_CLIENT_INVENTORYMODULE_SET_GOTOLOCATEITEMDATA_OFFSET UNITYSDK_OFFSET(0xC8F8DD0)
#define RPG_CLIENT_INVENTORYMODULE_SET_ITEMVISIBALEPREDICATE_OFFSET UNITYSDK_OFFSET(0xC8F8DB0)
#define RPG_CLIENT_INVENTORYMODULE_SYNCVIRTUALITEMNUM_OFFSET UNITYSDK_OFFSET(0xC8ED450)
#define RPG_CLIENT_INVENTORYMODULE_TRYGETEXPIREDDISPLAYITEMS_OFFSET UNITYSDK_OFFSET(0xC8EC2E0)
#define RPG_CLIENT_INVENTORYMODULE_TRYGETEXPIREDITEMS_OFFSET UNITYSDK_OFFSET(0xC8EC410)
#define RPG_CLIENT_INVENTORYMODULE_TRYGETEXPIREDTIMEBYITEMID_OFFSET UNITYSDK_OFFSET(0xC8ECA80)
#define RPG_CLIENT_INVENTORYMODULE_TRYHANDLEREBATEITEMS_OFFSET UNITYSDK_OFFSET(0xC8F50E0)
#define RPG_CLIENT_INVENTORYMODULE_TRYSETEXPIREDTIME_OFFSET UNITYSDK_OFFSET(0xC8F2B60)
#define RPG_CLIENT_INVENTORYMODULE_TRYSHOWEXPIREDITEMS_OFFSET UNITYSDK_OFFSET(0xC8EC690)
#define RPG_CLIENT_INVENTORYMODULE_TRYSHOWUSEBPITEMHINT_OFFSET UNITYSDK_OFFSET(0xC8F52C0)
#define RPG_CLIENT_INVENTORYMODULE_TRYSHOWUSEMONTHCARDITEMHINT_OFFSET UNITYSDK_OFFSET(0xC8F5140)
#define RPG_CLIENT_INVENTORYMODULE_UNLOCKALLEQUIPMENTS_OFFSET UNITYSDK_OFFSET(0xC8E2780)
#define RPG_CLIENT_INVENTORYMODULE_UNLOCKALLRANKMAXEQUIPMENTS_OFFSET UNITYSDK_OFFSET(0xC8E2B30)
#define RPG_CLIENT_INVENTORYMODULE_UPDATEAETHERSKILLCORE_OFFSET UNITYSDK_OFFSET(0xC8EFA30)
#define RPG_CLIENT_INVENTORYMODULE_UPDATEAETHERSPIRITFRAGMENT_OFFSET UNITYSDK_OFFSET(0xC8F0600)
#define RPG_CLIENT_INVENTORYMODULE_USEFOODITEM_OFFSET UNITYSDK_OFFSET(0xC8E9780)
#define RPG_CLIENT_INVENTORYMODULE_USEGIFTPACKITEM_OFFSET UNITYSDK_OFFSET(0xC8E9890)
#define RPG_CLIENT_INVENTORYMODULE_USEITEM_OFFSET UNITYSDK_OFFSET(0xC8E95A0)
#define RPG_CLIENT_INVENTORYMODULE__ADDITEM_OFFSET UNITYSDK_OFFSET(0xC8EFD00)
#define RPG_CLIENT_INVENTORYMODULE__ADDNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0xC8F6110)
#define RPG_CLIENT_INVENTORYMODULE__ADDPACKETHANDLERS_OFFSET UNITYSDK_OFFSET(0xC8F6150)
#define RPG_CLIENT_INVENTORYMODULE__ADDUNIQUEITEMS_OFFSET UNITYSDK_OFFSET(0xC8F2200)
#define RPG_CLIENT_INVENTORYMODULE__CHECKPLATFORMBOUNDGIFT_OFFSET UNITYSDK_OFFSET(0xC8F4D70)
#define RPG_CLIENT_INVENTORYMODULE__CHECKUSEITEMBP_OFFSET UNITYSDK_OFFSET(0xC8F49D0)
#define RPG_CLIENT_INVENTORYMODULE__CHECKUSEITEM_OFFSET UNITYSDK_OFFSET(0xC8E96C0)
#define RPG_CLIENT_INVENTORYMODULE__CLEAREXCEPTVIRTUALITEMS_OFFSET UNITYSDK_OFFSET(0xC8F0810)
#define RPG_CLIENT_INVENTORYMODULE__CTOR_OFFSET UNITYSDK_OFFSET(0xC8E64C0)
#define RPG_CLIENT_INVENTORYMODULE__DEFAULTVISIBLEPREDICATE_OFFSET UNITYSDK_OFFSET(0xC8F60C0)
#define RPG_CLIENT_INVENTORYMODULE__DELETEEQUIPMENTS_OFFSET UNITYSDK_OFFSET(0xC8F3A60)
#define RPG_CLIENT_INVENTORYMODULE__DELETERELICS_OFFSET UNITYSDK_OFFSET(0xC8F42B0)
#define RPG_CLIENT_INVENTORYMODULE__GETCURRENTPLATFORMTYPE_OFFSET UNITYSDK_OFFSET(0xC8F4FF0)
#define RPG_CLIENT_INVENTORYMODULE__INITCONVERTIBLEITEM_OFFSET UNITYSDK_OFFSET(0xC8E8120)
#define RPG_CLIENT_INVENTORYMODULE__INITHEROAVATAREIDOLONITEMIDLIST_OFFSET UNITYSDK_OFFSET(0xC8E8370)
#define RPG_CLIENT_INVENTORYMODULE__INITMAINTYPEFILTER_OFFSET UNITYSDK_OFFSET(0xC8E7AB0)
#define RPG_CLIENT_INVENTORYMODULE__INITSUBTYPEFILTER_OFFSET UNITYSDK_OFFSET(0xC8E7440)
#define RPG_CLIENT_INVENTORYMODULE__INITVIRTUALITEM_OFFSET UNITYSDK_OFFSET(0xC8E6E60)
#define RPG_CLIENT_INVENTORYMODULE__ISITEMREACHLIMIT_OFFSET UNITYSDK_OFFSET(0xC8EE000)
#define RPG_CLIENT_INVENTORYMODULE__ONCANCELMARKITEMNOTIFY_OFFSET UNITYSDK_OFFSET(0xC8E51E0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDADDEQUIPMENTSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8B40)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDDESTROYITEMSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8A00)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDEQUIPMENTQUICKUPSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8180)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDEXPUPEQUIPMENTSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F7EC0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDEXPUPRELICSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8490)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDGETBAGSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F6F00)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDGETRECYLETIMESCRSP_OFFSET UNITYSDK_OFFSET(0xC8F7130)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDLOCKEQUIPMENTSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8440)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDLOCKRELICSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F87A0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDPLAYERLOGINSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F7090)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDPLAYERSYNCSCNOTIFY_OFFSET UNITYSDK_OFFSET(0xC8F75E0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDPROMOTEEQUIPMENTSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8120)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDRANKUPEQUIPMENTSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F83E0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDSELLITEMSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F87F0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDSETTURNFOODSWITCHSCRSP_OFFSET UNITYSDK_OFFSET(0xC8E58E0)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDSYNCTURNFOODNOTIFY_OFFSET UNITYSDK_OFFSET(0xC8E5930)
#define RPG_CLIENT_INVENTORYMODULE__ONCMDUSEITEMSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F7920)
#define RPG_CLIENT_INVENTORYMODULE__ONDISCARDRELICSCRSP_OFFSET UNITYSDK_OFFSET(0xC8F86F0)
#define RPG_CLIENT_INVENTORYMODULE__ONGENERALVIRTUALITEMDATANOTIFY_OFFSET UNITYSDK_OFFSET(0xC8F8C40)
#define RPG_CLIENT_INVENTORYMODULE__ONGETMARKITEMLISTSCRSP_OFFSET UNITYSDK_OFFSET(0xC8E5330)
#define RPG_CLIENT_INVENTORYMODULE__ONGETPLAYERBOARDDATASCRSP_OFFSET UNITYSDK_OFFSET(0xC8F8A90)
#define RPG_CLIENT_INVENTORYMODULE__ONMARKITEMSCRSP_OFFSET UNITYSDK_OFFSET(0xC8E4FB0)
#define RPG_CLIENT_INVENTORYMODULE__ONSTAMINAINFOSCNOTIFY_OFFSET UNITYSDK_OFFSET(0xC8F7570)
#define RPG_CLIENT_INVENTORYMODULE__PROCESSNEWMATERIALITEM_OFFSET UNITYSDK_OFFSET(0xC8F29B0)
#define RPG_CLIENT_INVENTORYMODULE__RECORDITEMAUTOCONVERSION_OFFSET UNITYSDK_OFFSET(0xC8ECD30)
#define RPG_CLIENT_INVENTORYMODULE__RECORDONETIMESYNCITEMAUTOCONVERSION_OFFSET UNITYSDK_OFFSET(0xC8ED270)
#define RPG_CLIENT_INVENTORYMODULE__REMOVEITEMBYSUBTYPE_OFFSET UNITYSDK_OFFSET(0xC8F1080)
#define RPG_CLIENT_INVENTORYMODULE__REMOVEITEM_OFFSET UNITYSDK_OFFSET(0xC8F01B0)
#define RPG_CLIENT_INVENTORYMODULE__RESETMAINTYPEFILTER_OFFSET UNITYSDK_OFFSET(0xC8EAE30)
#define RPG_CLIENT_INVENTORYMODULE__RESETSUBTYPEFILTER_OFFSET UNITYSDK_OFFSET(0xC8EAF80)
#define RPG_CLIENT_INVENTORYMODULE__SYNCGENERALVIRTUALITEMS_OFFSET UNITYSDK_OFFSET(0xC8F4750)
#define RPG_CLIENT_INVENTORYMODULE__SYNCQUICKCONSUMABLEITEM_OFFSET UNITYSDK_OFFSET(0xC8E5A00)
#define RPG_CLIENT_INVENTORYMODULE__SYNCQUICKCONSUMABLETURNSWITCH_OFFSET UNITYSDK_OFFSET(0xC8E5EB0)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEBASICMODULE_OFFSET UNITYSDK_OFFSET(0xC8F14D0)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEEQUIPMENTS_OFFSET UNITYSDK_OFFSET(0xC8F3720)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEHEADICONS_OFFSET UNITYSDK_OFFSET(0xC8F2070)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEMATERIALS_OFFSET UNITYSDK_OFFSET(0xC8F26B0)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEPERSONALCARDS_OFFSET UNITYSDK_OFFSET(0xC8F4550)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEPETSUMMONITEMS_OFFSET UNITYSDK_OFFSET(0xC8F2520)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEPILEITEMWITHCOUNT_OFFSET UNITYSDK_OFFSET(0xC8F06A0)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEPLATFORMBOUNDGIFTS_OFFSET UNITYSDK_OFFSET(0xC8F2C70)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEPLAYERBOARDMODULE_OFFSET UNITYSDK_OFFSET(0xC8F15C0)
#define RPG_CLIENT_INVENTORYMODULE__UPDATERELICS_OFFSET UNITYSDK_OFFSET(0xC8F3D00)
#define RPG_CLIENT_INVENTORYMODULE__UPDATESTAMINAINFO_OFFSET UNITYSDK_OFFSET(0xC8F1530)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEVIRTUALITEMCOUNT_OFFSET UNITYSDK_OFFSET(0xC8F1400)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEVIRTUALITEMS_OFFSET UNITYSDK_OFFSET(0xC8F1360)
#define RPG_CLIENT_INVENTORYMODULE__UPDATEWAITDELRESOUCE_OFFSET UNITYSDK_OFFSET(0xC8F4590)
#define RPG_CLIENT_INVENTORYMODULE___SYNCQUICKCONSUMABLEITEM_B__24_0_OFFSET UNITYSDK_OFFSET(0xC8F8DE0)
#define RPG_CLIENT_INVENTORYMODULE___SYNCQUICKCONSUMABLETURNSWITCH_B__25_0_OFFSET UNITYSDK_OFFSET(0xC8F8E80)

namespace RPG::Client
{
	inline static constexpr unsigned int InventoryModule_TypeDefinitionIndex = 62764;

	class InventoryModule : public ::RPG::Client::BaseModule
	{
	public:
		::RPG::Client::ItemAutoConversionRecord* _OneTimeSyncItemAutoConversionRecord; // 0x10
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemDisplayData*>* _ExpiredItems; // 0x18
		::System::Collections::Generic::List_1<::System::UInt32>* _EmptyList; // 0x20
		::System::Collections::Generic::List_1<::System::UInt32>* _FavoriteFoodItems; // 0x28
		::System::Collections::Generic::HashSet_1<::Enum_3_0A3761FE34514D6C_48>* _QuickConsumableSwitches; // 0x30
		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* _FoundItemDatasCache; // 0x38
		::System::Collections::Generic::HashSet_1<::RPG::GameCore::ItemSubType>* _UniqueItemSubTypes; // 0x40
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemData*>* _UniqueItems; // 0x48
		::RPG::GameCore::InventoryTabRow* _ConsumableRow; // 0x50
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemData*>* _PileItems; // 0x58
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::ItemSubType, ::System::Boolean>* _SubTypeFilter; // 0x60
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _UniqueItemCountDict; // 0x68
		::System::Collections::Generic::Dictionary_2<::RPG::GameCore::ItemMainType, ::System::Boolean>* _MainTypeFilter; // 0x70
		::System::Collections::Generic::List_1<::RPG::Client::ItemAutoConversionRecord*>* _ItemAutoConversionRecords; // 0x78
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt64>* _ExpiredTimes; // 0x80
		::System::Predicate_1<::System::UInt32>* _ItemVisibalePredicate_k__BackingField; // 0x88
		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::System::UInt32>* _WaitDelItemCount; // 0x90
		::System::Collections::Generic::List_1<::RPG::Client::ConvertibleItemData*>* _ConvertibleItems; // 0x98
		::System::Collections::Generic::List_1<::System::UInt32>* _HeroAvatarEidolonItemIdList; // 0xA0
		::System::Collections::Generic::HashSet_1<::RPG::GameCore::ItemSubType>* _PileItemSubTypes; // 0xA8
		::RPG::Client::ItemData* _GotoLocateItemData_k__BackingField; // 0xB0
		::System::Collections::Generic::List_1<::System::UInt32>* _QuickConsumbaleItems; // 0xB8
		::System::Int32 LastOpenTabIndex; // 0xC0
		::System::UInt32 _FavoriteFoodMaxCount; // 0xC4

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__CTOR_OFFSET))(this);
		}

		::System::Void UnlockAllEquipments(::RPG::GameCore::ItemRarity a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ItemRarity))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_UNLOCKALLEQUIPMENTS_OFFSET))(this, a1);
		}

		::System::Void UnlockAllRankMaxEquipments(::RPG::GameCore::ItemRarity a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ItemRarity))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_UNLOCKALLRANKMAXEQUIPMENTS_OFFSET))(this, a1);
		}

		::System::Void LockAllEquipments(::RPG::GameCore::ItemRarity a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ItemRarity))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_LOCKALLEQUIPMENTS_OFFSET))(this, a1);
		}

		::System::Boolean IsFavoriteFoodReachMax()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISFAVORITEFOODREACHMAX_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetReviveItems()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETREVIVEITEMS_OFFSET))(this);
		}

		::System::Boolean HasMPItem()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_HASMPITEM_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetMPItems()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETMPITEMS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetSortedMPItems()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETSORTEDMPITEMS_OFFSET))(this);
		}

		::System::UInt32 GetFoodCountByConsumeTypeID(::System::UInt32 a1, ::System::Boolean a2, ::System::UInt32 a3)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32, ::System::Boolean, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETFOODCOUNTBYCONSUMETYPEID_OFFSET))(this, a1, a2, a3);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetQuickConsumableItems()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETQUICKCONSUMABLEITEMS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetFoodItemsByConsumeType(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETFOODITEMSBYCONSUMETYPE_OFFSET))(this, a1);
		}

		::System::Boolean IsQuickConsumableTurnSwitchOpen(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISQUICKCONSUMABLETURNSWITCHOPEN_OFFSET))(this, a1);
		}

		::System::Boolean IsQuickConsumableTurnSwitchOpen_1(::Enum_3_0A3761FE34514D6C_48 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Enum_3_0A3761FE34514D6C_48))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISQUICKCONSUMABLETURNSWITCHOPEN_1_OFFSET))(this, a1);
		}

		::System::Void SetTurnFoodSwitch(::System::UInt32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SETTURNFOODSWITCH_OFFSET))(this, a1, a2);
		}

		::System::Void SetTurnFoodSwitch_1(::Enum_3_0A3761FE34514D6C_48 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_0A3761FE34514D6C_48, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SETTURNFOODSWITCH_1_OFFSET))(this, a1, a2);
		}

		::System::UInt32 GetQuickConsumableItemIDByConsumeType(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETQUICKCONSUMABLEITEMIDBYCONSUMETYPE_OFFSET))(this, a1);
		}

		::RPG::Client::ItemData* GetQuickConsumableItemByConsumeType(::System::UInt32 a1)
		{
			return ((::RPG::Client::ItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETQUICKCONSUMABLEITEMBYCONSUMETYPE_OFFSET))(this, a1);
		}

		::System::Boolean EnableSetFavorite(::RPG::GameCore::ItemSubType a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::GameCore::ItemSubType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ENABLESETFAVORITE_OFFSET))(this, a1);
		}

		::System::Boolean IsFavoriteNew(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISFAVORITENEW_OFFSET))(this, a1, a2);
		}

		::System::Void _OnMarkItemScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONMARKITEMSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCancelMarkItemNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCANCELMARKITEMNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnGetMarkItemListScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONGETMARKITEMLISTSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdSetTurnFoodSwitchScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDSETTURNFOODSWITCHSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdSyncTurnFoodNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDSYNCTURNFOODNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Boolean _SyncQuickConsumableItem(::Google::Protobuf::Collections::RepeatedField_1<::System::UInt32>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__SYNCQUICKCONSUMABLEITEM_OFFSET))(this, a1);
		}

		::System::Boolean _SyncQuickConsumableTurnSwitch(::Google::Protobuf::Collections::RepeatedField_1<::Enum_3_0A3761FE34514D6C_48>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Enum_3_0A3761FE34514D6C_48>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__SYNCQUICKCONSUMABLETURNSWITCH_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_QuickConsumableItems()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GET_QUICKCONSUMABLEITEMS_OFFSET))(this);
		}

		::System::Boolean get__QuickConsumableFeatureClosed()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GET__QUICKCONSUMABLEFEATURECLOSED_OFFSET))(this);
		}

		::System::Void Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_INIT_OFFSET))(this);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_DISPOSE_OFFSET))(this);
		}

		::System::Void SendPacketsAfterLoginFinished()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SENDPACKETSAFTERLOGINFINISHED_OFFSET))(this);
		}

		::System::UInt32 GetItemCountByConfigID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMCOUNTBYCONFIGID_OFFSET))(this, a1);
		}

		::System::Int64 GetItemCountAfterDeleteByConfigID(::System::UInt32 a1)
		{
			return ((::System::Int64(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMCOUNTAFTERDELETEBYCONFIGID_OFFSET))(this, a1);
		}

		::System::Int64 GetResBarCountByConfigID(::System::UInt32 a1)
		{
			return ((::System::Int64(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETRESBARCOUNTBYCONFIGID_OFFSET))(this, a1);
		}

		::System::Void UseItem(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_USEITEM_OFFSET))(this, a1, a2);
		}

		::System::Boolean CheckUseItem(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_CHECKUSEITEM_OFFSET))(this, a1);
		}

		::System::Void UseFoodItem(::System::UInt32 a1, ::System::UInt32 a2, ::System::UInt32 a3, ::Enum_3_01618AD0437C8486 a4, ::System::Boolean a5)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::UInt32, ::Enum_3_01618AD0437C8486, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_USEFOODITEM_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Void UseGiftPackItem(::System::UInt32 a1, ::System::UInt32 a2, ::System::UInt32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_USEGIFTPACKITEM_OFFSET))(this, a1, a2, a3);
		}

		::RPG::Client::ItemData* GetItemDataByConfigID(::System::UInt32 a1)
		{
			return ((::RPG::Client::ItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMDATABYCONFIGID_OFFSET))(this, a1);
		}

		::RPG::Client::ItemData* GetItemDataByUID(::System::UInt32 a1)
		{
			return ((::RPG::Client::ItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMDATABYUID_OFFSET))(this, a1);
		}

		::System::UInt32 GetEquipmentMaxRankByConfigID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTMAXRANKBYCONFIGID_OFFSET))(this, a1);
		}

		::System::Void GetEquipmentMaxRankAndCountByConfigID(::System::UInt32 a1, ::System::UInt32& a2, ::System::UInt32& a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32&, ::System::UInt32&))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTMAXRANKANDCOUNTBYCONFIGID_OFFSET))(this, a1, a2, a3);
		}

		::RPG::Client::EquipmentItemData* GetEquipmentDataByConfigID(::System::UInt32 a1)
		{
			return ((::RPG::Client::EquipmentItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTDATABYCONFIGID_OFFSET))(this, a1);
		}

		::RPG::Client::EquipmentItemData* FindEquipment(::System::Predicate_1<::RPG::Client::EquipmentItemData*>* a1)
		{
			return ((::RPG::Client::EquipmentItemData*(*)(::PVOID, ::System::Predicate_1<::RPG::Client::EquipmentItemData*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_FINDEQUIPMENT_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::EquipmentItemData*>* FindAllEquipments(::System::Predicate_1<::RPG::Client::EquipmentItemData*>* a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::EquipmentItemData*>*(*)(::PVOID, ::System::Predicate_1<::RPG::Client::EquipmentItemData*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_FINDALLEQUIPMENTS_OFFSET))(this, a1);
		}

		::RPG::Client::EquipmentItemData* GetEquipmentDataByUID(::System::UInt32 a1)
		{
			return ((::RPG::Client::EquipmentItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETEQUIPMENTDATABYUID_OFFSET))(this, a1);
		}

		::RPG::Client::RelicItemData* GetRelicDataByUID(::System::UInt32 a1)
		{
			return ((::RPG::Client::RelicItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETRELICDATABYUID_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetItemsBySubType(::RPG::GameCore::ItemSubType a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::RPG::GameCore::ItemSubType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMSBYSUBTYPE_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetItemsBySubTypes(::Il2CppArray<::RPG::GameCore::ItemSubType>* a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::ItemSubType>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMSBYSUBTYPES_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetItemsByMainTypes(::Il2CppArray<::RPG::GameCore::ItemMainType>* a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::ItemMainType>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMSBYMAINTYPES_OFFSET))(this, a1);
		}

		::System::Int32 GetLightConeCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETLIGHTCONECOUNT_OFFSET))(this);
		}

		::System::Int32 GetSuperRareLightConeCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETSUPERRARELIGHTCONECOUNT_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetItemsInTypes(::Il2CppArray<::RPG::GameCore::ItemMainType>* a1, ::Il2CppArray<::RPG::GameCore::ItemSubType>* a2)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::ItemMainType>*, ::Il2CppArray<::RPG::GameCore::ItemSubType>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMSINTYPES_OFFSET))(this, a1, a2);
		}

		::System::UInt32 FindTabIDByItemID(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_FINDTABIDBYITEMID_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetInventoryTabItems(::RPG::GameCore::InventoryTabRow* a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::RPG::GameCore::InventoryTabRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETINVENTORYTABITEMS_OFFSET))(this, a1);
		}

		::System::Int32 GetUniqueItemsCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETUNIQUEITEMSCOUNT_OFFSET))(this);
		}

		::System::Int32 GetUniqueItemsCountByMainType(::RPG::GameCore::ItemMainType a1)
		{
			return ((::System::Int32(*)(::PVOID, ::RPG::GameCore::ItemMainType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETUNIQUEITEMSCOUNTBYMAINTYPE_OFFSET))(this, a1);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemData*>* GetPileItems()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETPILEITEMS_OFFSET))(this);
		}

		::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemData*>* GetUniqueItems()
		{
			return ((::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETUNIQUEITEMS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* GetFoodItemsByMazeBuffPool(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETFOODITEMSBYMAZEBUFFPOOL_OFFSET))(this, a1);
		}

		::System::Boolean HasItemInSubType(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_HASITEMINSUBTYPE_OFFSET))(this, a1);
		}

		::System::Void OnExpiredItemsShown()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ONEXPIREDITEMSSHOWN_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>* TryGetExpiredDisplayItems()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYGETEXPIREDDISPLAYITEMS_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemData*>* TryGetExpiredItems()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemData*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYGETEXPIREDITEMS_OFFSET))(this);
		}

		::System::Void TryShowExpiredItems()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYSHOWEXPIREDITEMS_OFFSET))(this);
		}

		::System::Boolean IsItemExpired(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISITEMEXPIRED_OFFSET))(this, a1);
		}

		::System::UInt64 TryGetExpiredTimeByItemID(::System::UInt32 a1)
		{
			return ((::System::UInt64(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYGETEXPIREDTIMEBYITEMID_OFFSET))(this, a1);
		}

		::System::Collections::Generic::List_1<::RPG::Client::ItemAutoConversionRecord*>* GetItemAutoConversionRecords()
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemAutoConversionRecord*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMAUTOCONVERSIONRECORDS_OFFSET))(this);
		}

		::RPG::Client::ItemAutoConversionRecord* GetOneTimeSyncItemAutoConversionRecord()
		{
			return ((::RPG::Client::ItemAutoConversionRecord*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETONETIMESYNCITEMAUTOCONVERSIONRECORD_OFFSET))(this);
		}

		::System::Void SendCancelAutoConversionCacheCsReq()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SENDCANCELAUTOCONVERSIONCACHECSREQ_OFFSET))(this);
		}

		::System::Boolean IsItemConversioned(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISITEMCONVERSIONED_OFFSET))(this, a1);
		}

		::System::Void _RecordItemAutoConversion(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_66F48F07052E8E37*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_66F48F07052E8E37*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__RECORDITEMAUTOCONVERSION_OFFSET))(this, a1);
		}

		::System::Void _RecordOneTimeSyncItemAutoConversion(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_FC8BF52F067E8047*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_FC8BF52F067E8047*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__RECORDONETIMESYNCITEMAUTOCONVERSION_OFFSET))(this, a1);
		}

		::System::Boolean CheckIsHeroAvatarEidolonItemType(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_CHECKISHEROAVATAREIDOLONITEMTYPE_OFFSET))(this, a1);
		}

		::System::Void SyncVirtualItemNum(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SYNCVIRTUALITEMNUM_OFFSET))(this, a1, a2);
		}

		::RPG::Client::AetherSkillCoreItemData* GetAetherSkillCoreItemDataByConfigID(::System::UInt32 a1)
		{
			return ((::RPG::Client::AetherSkillCoreItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETAETHERSKILLCOREITEMDATABYCONFIGID_OFFSET))(this, a1);
		}

		::System::Void SetItemVisiblePredicate(::System::Predicate_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Predicate_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SETITEMVISIBLEPREDICATE_OFFSET))(this, a1);
		}

		::System::Boolean IsRewardItemReachPileLimit(::System::Collections::Generic::List_1<::System::UInt32>* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Collections::Generic::List_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISREWARDITEMREACHPILELIMIT_OFFSET))(this, a1);
		}

		::System::Boolean _IsItemReachLimit(::RPG::Client::ItemDisplayData* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::RPG::Client::ItemDisplayData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ISITEMREACHLIMIT_OFFSET))(this, a1);
		}

		::RPG::Client::ConvertibleItemData* GetConvertibleItemDataByitemSubType(::RPG::GameCore::ItemSubType a1)
		{
			return ((::RPG::Client::ConvertibleItemData*(*)(::PVOID, ::RPG::GameCore::ItemSubType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETCONVERTIBLEITEMDATABYITEMSUBTYPE_OFFSET))(this, a1);
		}

		::RPG::Client::ConvertibleItemData* GetConvertibleItemDataByItemID(::System::UInt32 a1)
		{
			return ((::RPG::Client::ConvertibleItemData*(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETCONVERTIBLEITEMDATABYITEMID_OFFSET))(this, a1);
		}

		static ::RPG::GameCore::ItemRow* GetItemRow(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::ItemRow*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMROW_OFFSET))(a1);
		}

		static ::RPG::GameCore::ItemRarityConfigRow* GetItemRarityConfig(::RPG::GameCore::ItemRarity a1)
		{
			return ((::RPG::GameCore::ItemRarityConfigRow*(*)(::RPG::GameCore::ItemRarity))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMRARITYCONFIG_OFFSET))(a1);
		}

		static ::RPG::Client::TextID GetSortTypeName(::RPG::GameCore::InventorySortType a1)
		{
			return ((::RPG::Client::TextID(*)(::RPG::GameCore::InventorySortType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETSORTTYPENAME_OFFSET))(a1);
		}

		static ::System::UInt32 GetHCoinConfigID()
		{
			return ((::System::UInt32(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETHCOINCONFIGID_OFFSET))();
		}

		static ::System::Int32 GetLightConeItemsMaxNum()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETLIGHTCONEITEMSMAXNUM_OFFSET))();
		}

		static ::System::Int32 GetRelicItemsMaxNum()
		{
			return ((::System::Int32(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETRELICITEMSMAXNUM_OFFSET))();
		}

		static ::System::Boolean GetIsPileByConfigID(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETISPILEBYCONFIGID_OFFSET))(a1);
		}

		static ::System::Boolean GetIsPileByItemMainType(::RPG::GameCore::ItemMainType a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::ItemMainType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETISPILEBYITEMMAINTYPE_OFFSET))(a1);
		}

		static ::System::Boolean GetIsPileByItemSubType(::RPG::GameCore::ItemSubType a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::ItemSubType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETISPILEBYITEMSUBTYPE_OFFSET))(a1);
		}

		static ::RPG::GameCore::ItemUseDataRow* GetItemUseDataRowByConfigID(::System::UInt32 a1)
		{
			return ((::RPG::GameCore::ItemUseDataRow*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMUSEDATAROWBYCONFIGID_OFFSET))(a1);
		}

		static ::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>* GetRewardItemDisplayData(::Proto::ItemList* a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::Client::ItemDisplayData*>*(*)(::Proto::ItemList*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETREWARDITEMDISPLAYDATA_OFFSET))(a1);
		}

		static ::System::Boolean IsItemImportHint(::RPG::GameCore::ItemRow* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::ItemRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISITEMIMPORTHINT_OFFSET))(a1);
		}

		static ::System::Boolean IsItemImportHintByID(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISITEMIMPORTHINTBYID_OFFSET))(a1);
		}

		static ::System::Collections::Generic::List_1<::RPG::GameCore::ItemComefromRow*>* GetItemComeFrom(::System::UInt32 a1)
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::ItemComefromRow*>*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GETITEMCOMEFROM_OFFSET))(a1);
		}

		static ::System::Boolean IsComeFromValid(::RPG::GameCore::ItemComefromRow* a1)
		{
			return ((::System::Boolean(*)(::RPG::GameCore::ItemComefromRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_ISCOMEFROMVALID_OFFSET))(a1);
		}

		::System::Void UpdateAetherSkillCore(::System::UInt32 a1, ::System::UInt32 a2, ::System::Boolean a3, ::System::UInt32 a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::Boolean, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_UPDATEAETHERSKILLCORE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void UpdateAetherSpiritFragment(::System::UInt32 a1, ::System::UInt32 a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_UPDATEAETHERSPIRITFRAGMENT_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _ClearExceptVirtualItems(::Class_1_3699B5F0EA586362* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_3699B5F0EA586362*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__CLEAREXCEPTVIRTUALITEMS_OFFSET))(this, a1);
		}

		::System::Void _InitVirtualItem()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__INITVIRTUALITEM_OFFSET))(this);
		}

		::System::Void _InitSubTypeFilter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__INITSUBTYPEFILTER_OFFSET))(this);
		}

		::System::Void _InitMainTypeFilter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__INITMAINTYPEFILTER_OFFSET))(this);
		}

		::System::Void _InitConvertibleItem()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__INITCONVERTIBLEITEM_OFFSET))(this);
		}

		::System::Void _InitHeroAvatarEidolonItemIdList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__INITHEROAVATAREIDOLONITEMIDLIST_OFFSET))(this);
		}

		::System::Void _ResetSubTypeFilter(::Il2CppArray<::RPG::GameCore::ItemSubType>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::ItemSubType>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__RESETSUBTYPEFILTER_OFFSET))(this, a1);
		}

		::System::Void _ResetMainTypeFilter(::Il2CppArray<::RPG::GameCore::ItemMainType>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::RPG::GameCore::ItemMainType>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__RESETMAINTYPEFILTER_OFFSET))(this, a1);
		}

		::System::Void _AddItem(::RPG::Client::ItemData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ADDITEM_OFFSET))(this, a1);
		}

		::System::Void _RemoveItem(::RPG::Client::ItemData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__REMOVEITEM_OFFSET))(this, a1);
		}

		::System::Void _RemoveItemBySubType(::RPG::GameCore::ItemSubType a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::ItemSubType))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__REMOVEITEMBYSUBTYPE_OFFSET))(this, a1);
		}

		::System::Void _UpdateVirtualItems(::Class_1_21DCD4640D389503_2* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_21DCD4640D389503_2*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEVIRTUALITEMS_OFFSET))(this, a1);
		}

		::System::Void _UpdateBasicModule(::Class_1_D17272E82AE804C2_1114* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_D17272E82AE804C2_1114*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEBASICMODULE_OFFSET))(this, a1);
		}

		::System::Void _UpdateStaminaInfo(::Class_1_C9E417278351157F_7* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_C9E417278351157F_7*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATESTAMINAINFO_OFFSET))(this, a1);
		}

		::System::Void _UpdatePlayerBoardModule(::Class_1_7E1E05C17C895270* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_7E1E05C17C895270*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEPLAYERBOARDMODULE_OFFSET))(this, a1);
		}

		::System::Void _UpdateVirtualItemCount(::Enum_3_5AA38DC400740F29 a1, ::System::UInt32 a2)
		{
			return ((::System::Void(*)(::PVOID, ::Enum_3_5AA38DC400740F29, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEVIRTUALITEMCOUNT_OFFSET))(this, a1, a2);
		}

		::System::Void _UpdatePetSummonItems(::Class_1_45BB92167AED63A0_103* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_45BB92167AED63A0_103*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEPETSUMMONITEMS_OFFSET))(this, a1, a2);
		}

		::System::Void _AddUniqueItems(::Google::Protobuf::Collections::RepeatedField_1<::System::UInt32>* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::System::UInt32>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ADDUNIQUEITEMS_OFFSET))(this, a1, a2);
		}

		::System::Void _UpdateMaterials(::Il2CppArray<::Class_1_C086E47345F86771_11*>* a1, ::System::Boolean& a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::Class_1_C086E47345F86771_11*>*, ::System::Boolean&, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEMATERIALS_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _ProcessNewMaterialItem(::RPG::Client::ItemData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__PROCESSNEWMATERIALITEM_OFFSET))(this, a1);
		}

		::System::Void _UpdatePlatformBoundGifts(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_45BB92167AED63A0_52*>* a1, ::System::Boolean& a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_45BB92167AED63A0_52*>*, ::System::Boolean&, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEPLATFORMBOUNDGIFTS_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _UpdateEquipments(::System::Collections::Generic::IList_1<::Class_1_EBB10EC01CCC4716_11*>* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::IList_1<::Class_1_EBB10EC01CCC4716_11*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEEQUIPMENTS_OFFSET))(this, a1, a2);
		}

		::System::Void _DeleteEquipments(::System::Collections::Generic::IList_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::IList_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__DELETEEQUIPMENTS_OFFSET))(this, a1);
		}

		::System::Void _UpdateRelics(::System::Collections::Generic::IList_1<::Class_1_097D93F83453E9A1_1*>* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::IList_1<::Class_1_097D93F83453E9A1_1*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATERELICS_OFFSET))(this, a1, a2);
		}

		::System::Void _DeleteRelics(::System::Collections::Generic::IList_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::IList_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__DELETERELICS_OFFSET))(this, a1);
		}

		::System::Void _UpdateHeadIcons(::Il2CppArray<::Class_1_D17272E82AE804C2_854*>* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::Class_1_D17272E82AE804C2_854*>*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEHEADICONS_OFFSET))(this, a1, a2);
		}

		::System::Void _UpdatePersonalCards()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEPERSONALCARDS_OFFSET))(this);
		}

		::System::Void _UpdateWaitDelResouce(::Il2CppArray<::Class_1_D17272E82AE804C2_575*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::Class_1_D17272E82AE804C2_575*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEWAITDELRESOUCE_OFFSET))(this, a1);
		}

		::System::Void _SyncGeneralVirtualItems(::System::Collections::Generic::IReadOnlyList_1<::Proto::PileItem*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::IReadOnlyList_1<::Proto::PileItem*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__SYNCGENERALVIRTUALITEMS_OFFSET))(this, a1);
		}

		::System::Boolean _CheckUseItem(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__CHECKUSEITEM_OFFSET))(this, a1);
		}

		::System::Boolean _CheckUseItemBP(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__CHECKUSEITEMBP_OFFSET))(this, a1);
		}

		::System::Boolean _CheckPlatformBoundGift(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__CHECKPLATFORMBOUNDGIFT_OFFSET))(this, a1);
		}

		::RPG::Client::ItemData_ProductPlatformType _GetCurrentPlatformType()
		{
			return ((::RPG::Client::ItemData_ProductPlatformType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__GETCURRENTPLATFORMTYPE_OFFSET))(this);
		}

		::System::Void TryhandleRebateItems(::Class_1_38FAAB38F863E2D1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_38FAAB38F863E2D1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYHANDLEREBATEITEMS_OFFSET))(this, a1);
		}

		::System::Void TryShowUseMonthCardItemHint(::Class_1_38FAAB38F863E2D1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_38FAAB38F863E2D1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYSHOWUSEMONTHCARDITEMHINT_OFFSET))(this, a1);
		}

		::System::Void TryShowUseBPItemHint(::Class_1_38FAAB38F863E2D1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_38FAAB38F863E2D1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYSHOWUSEBPITEMHINT_OFFSET))(this, a1);
		}

		::System::Void RecordExpiredItems(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_C086E47345F86771_12*>* a1, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemDisplayData*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_C086E47345F86771_12*>*, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemDisplayData*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_RECORDEXPIREDITEMS_OFFSET))(this, a1, a2);
		}

		::System::Void RecordExpiredItems_1(::Google::Protobuf::Collections::RepeatedField_1<::Class_1_C086E47345F86771_11*>* a1, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemDisplayData*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Google::Protobuf::Collections::RepeatedField_1<::Class_1_C086E47345F86771_11*>*, ::System::Collections::Generic::Dictionary_2<::System::UInt32, ::RPG::Client::ItemDisplayData*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_RECORDEXPIREDITEMS_1_OFFSET))(this, a1, a2);
		}

		::System::Void TrySetExpiredTime(::RPG::Client::ItemData* a1, ::Class_1_C086E47345F86771_11* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ItemData*, ::Class_1_C086E47345F86771_11*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_TRYSETEXPIREDTIME_OFFSET))(this, a1, a2);
		}

		::System::Void _UpdatePileItemWithCount(::System::UInt32 a1, ::System::UInt32 a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32, ::System::UInt32, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__UPDATEPILEITEMWITHCOUNT_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean _DefaultVisiblePredicate(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__DEFAULTVISIBLEPREDICATE_OFFSET))(this, a1);
		}

		::System::Void _AddNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ADDNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _AddPacketHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ADDPACKETHANDLERS_OFFSET))(this);
		}

		::System::Void _OnCmdGetBagScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDGETBAGSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdPlayerLoginScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDPLAYERLOGINSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdGetRecyleTimeScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDGETRECYLETIMESCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnStaminaInfoScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONSTAMINAINFOSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdPlayerSyncScNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDPLAYERSYNCSCNOTIFY_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdUseItemScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDUSEITEMSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdExpUpEquipmentScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDEXPUPEQUIPMENTSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdPromoteEquipmentScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDPROMOTEEQUIPMENTSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdEquipmentQuickUpScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDEQUIPMENTQUICKUPSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdRankUpEquipmentScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDRANKUPEQUIPMENTSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdLockEquipmentScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDLOCKEQUIPMENTSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdExpUpRelicScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDEXPUPRELICSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnDiscardRelicScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONDISCARDRELICSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdLockRelicScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDLOCKRELICSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdSellItemScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDSELLITEMSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdDestroyItemScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDDESTROYITEMSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnGetPlayerBoardDataScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONGETPLAYERBOARDDATASCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnCmdAddEquipmentScRsp(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONCMDADDEQUIPMENTSCRSP_OFFSET))(this, a1, a2);
		}

		::System::Void _OnGeneralVirtualItemDataNotify(::System::UInt16 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt16, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE__ONGENERALVIRTUALITEMDATANOTIFY_OFFSET))(this, a1, a2);
		}

		static ::RPG::Client::InventoryModule* get_Instance()
		{
			return ((::RPG::Client::InventoryModule*(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GET_INSTANCE_OFFSET))();
		}

		::System::Predicate_1<::System::UInt32>* get_ItemVisibalePredicate()
		{
			return ((::System::Predicate_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GET_ITEMVISIBALEPREDICATE_OFFSET))(this);
		}

		::System::Void set_ItemVisibalePredicate(::System::Predicate_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Predicate_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SET_ITEMVISIBALEPREDICATE_OFFSET))(this, a1);
		}

		::RPG::Client::ItemData* get_GotoLocateItemData()
		{
			return ((::RPG::Client::ItemData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_GET_GOTOLOCATEITEMDATA_OFFSET))(this);
		}

		::System::Void set_GotoLocateItemData(::RPG::Client::ItemData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ItemData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE_SET_GOTOLOCATEITEMDATA_OFFSET))(this, a1);
		}

		::System::Boolean __SyncQuickConsumableItem_b__24_0(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE___SYNCQUICKCONSUMABLEITEM_B__24_0_OFFSET))(this, a1);
		}

		::System::Boolean __SyncQuickConsumableTurnSwitch_b__25_0(::Enum_3_0A3761FE34514D6C_48 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Enum_3_0A3761FE34514D6C_48))((::PBYTE)hIl2Cpp + RPG_CLIENT_INVENTORYMODULE___SYNCQUICKCONSUMABLETURNSWITCH_B__25_0_OFFSET))(this, a1);
		}
	};
}
