#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TABehaviorBase.h"

class Class_1_929E979D9ED7139E;
class Class_1_B044F82CBFAD3D4B;
namespace RPG::Client { class LinearModuleRendererMonoPlugin; }
namespace RPG::Client::LiteInstancedItem { class ItemPrototype; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace UnityEngine { class Material; }

#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_GET_ISINIT_OFFSET UNITYSDK_OFFSET(0xC965E50)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET UNITYSDK_OFFSET(0xC966960)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_391A84BCD9F51317_OFFSET UNITYSDK_OFFSET(0xC966F00)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET UNITYSDK_OFFSET(0xC966D70)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET UNITYSDK_OFFSET(0xC966DD0)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET UNITYSDK_OFFSET(0xC966E30)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET UNITYSDK_OFFSET(0xC966F40)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET UNITYSDK_OFFSET(0xC966D00)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_823F8D2340762FAF_OFFSET UNITYSDK_OFFSET(0xC966A10)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_9681042564541CD6_OFFSET UNITYSDK_OFFSET(0xC966C00)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_A874457E729FCC2D_OFFSET UNITYSDK_OFFSET(0xC966C90)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_EA0BA3E4AF50C583_OFFSET UNITYSDK_OFFSET(0xC965E60)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_TICK_OFFSET UNITYSDK_OFFSET(0xC966E90)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR__CCTOR_OFFSET UNITYSDK_OFFSET(0xC966FB0)
#define RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR__CTOR_OFFSET UNITYSDK_OFFSET(0xC966FA0)

namespace RPG::Client
{
	inline static constexpr unsigned int LinearModuleRendererBehavior_TypeDefinitionIndex = 67712;

	class LinearModuleRendererBehavior : public ::RPG::Client::TABehaviorBase
	{
	public:
		static ::System::Int32* StaticGet__UseInstanceItemID()
		{
			return (::System::Int32*)Il2CppClass::FromTypeDefinitionIndex(LinearModuleRendererBehavior_TypeDefinitionIndex)->GetStaticField(0x9190);
		}
		::System::Collections::Generic::List_1<::Class_1_929E979D9ED7139E*>* _ItemInstances; // 0x38
		::System::Collections::Generic::List_1<::RPG::Client::LiteInstancedItem::ItemPrototype*>* _ItemPrototypes; // 0x40
		::System::Collections::Generic::List_1<::UnityEngine::Material*>* _InstMats; // 0x48
		::Class_1_B044F82CBFAD3D4B* _ItemRenderer; // 0x50
		::System::Boolean _IsInit; // 0x58

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR__CTOR_OFFSET))(this);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR__CCTOR_OFFSET))();
		}

		::System::Boolean get_IsInit()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_GET_ISINIT_OFFSET))(this);
		}

		::System::Void Method_3_EA0BA3E4AF50C583()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_EA0BA3E4AF50C583_OFFSET))(this);
		}

		::System::Void Method_3_823F8D2340762FAF()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_823F8D2340762FAF_OFFSET))(this);
		}

		::System::Void Method_3_9681042564541CD6()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_9681042564541CD6_OFFSET))(this);
		}

		::System::Void Method_3_A874457E729FCC2D()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_A874457E729FCC2D_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_1()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_1_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_2()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_2_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_3()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_3_OFFSET))(this);
		}

		::System::Void Tick(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_TICK_OFFSET))(this, a1);
		}

		::System::Boolean Method_3_391A84BCD9F51317()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_391A84BCD9F51317_OFFSET))(this);
		}

		::System::Void Method_3_4343F372F34C05BF_4()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_METHOD_3_4343F372F34C05BF_4_OFFSET))(this);
		}

		::RPG::Client::LinearModuleRendererMonoPlugin* get__OwnerMonoPlugin()
		{
			return ((::RPG::Client::LinearModuleRendererMonoPlugin*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_LINEARMODULERENDERERBEHAVIOR_GET__OWNERMONOPLUGIN_OFFSET))(this);
		}
	};
}
