#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/MonoEffectPluginBase.h"
#include "unitysdk/RPG/Client/SyncPropertyType.h"

class Class_2_0FB6F5068D635FD7_5;

#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_AWAKEPLUGIN_OFFSET UNITYSDK_OFFSET(0xCCC9400)
#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_DISABLEPLUGIN_OFFSET UNITYSDK_OFFSET(0xCCC9570)
#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_DISPOSEPLUGIN_OFFSET UNITYSDK_OFFSET(0xCCC95B0)
#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_ENABLEPLUGIN_OFFSET UNITYSDK_OFFSET(0xCCC9530)
#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_IGNOREINEDITOR_OFFSET UNITYSDK_OFFSET(0xCCC93C0)
#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_RESETPLUGIN_OFFSET UNITYSDK_OFFSET(0xCCC94E0)
#define RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY__CTOR_OFFSET UNITYSDK_OFFSET(0xCCC9650)

namespace RPG::Client
{
	inline static constexpr unsigned int MonoEffectPluginSyncTargetShaderProperty_TypeDefinitionIndex = 66979;

	class MonoEffectPluginSyncTargetShaderProperty : public ::RPG::Client::MonoEffectPluginBase
	{
	public:
		::RPG::Client::SyncPropertyType SyncType; // 0x28
		::Class_2_0FB6F5068D635FD7_5* Field_6_1; // 0x30

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY__CTOR_OFFSET))(this);
		}

		::System::Boolean IgnoreInEditor()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_IGNOREINEDITOR_OFFSET))(this);
		}

		::System::Void AwakePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_AWAKEPLUGIN_OFFSET))(this);
		}

		::System::Void ResetPlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_RESETPLUGIN_OFFSET))(this);
		}

		::System::Void EnablePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_ENABLEPLUGIN_OFFSET))(this);
		}

		::System::Void DisablePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_DISABLEPLUGIN_OFFSET))(this);
		}

		::System::Void DisposePlugin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_MONOEFFECTPLUGINSYNCTARGETSHADERPROPERTY_DISPOSEPLUGIN_OFFSET))(this);
		}
	};
}
