#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/ActivityPanelData.h"

#define RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA_ISSHOWMAPPINGINFONEWCONTENTREDDOT_OFFSET UNITYSDK_OFFSET(0xD330B50)
#define RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET UNITYSDK_OFFSET(0xD330DD0)
#define RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET UNITYSDK_OFFSET(0xD3309B0)
#define RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xD3309A0)
#define RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA__ISEIDOLONREWARDCANTAKE_OFFSET UNITYSDK_OFFSET(0xD330A90)
#define RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA__ISENDINGREWARDCANTAKE_OFFSET UNITYSDK_OFFSET(0xD330AF0)

namespace RPG::Client
{
	inline static constexpr unsigned int ResidentSwordTrainingActivityData_TypeDefinitionIndex = 59021;

	class ResidentSwordTrainingActivityData : public ::RPG::Client::ActivityPanelData
	{
	public:
		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA__CTOR_OFFSET))(this, a1);
		}

		::System::Boolean IsShowNormalRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA_ISSHOWNORMALREDDOT_OFFSET))(this);
		}

		::System::Boolean _IsEidolonRewardCanTake()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA__ISEIDOLONREWARDCANTAKE_OFFSET))(this);
		}

		::System::Boolean _IsEndingRewardCanTake()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA__ISENDINGREWARDCANTAKE_OFFSET))(this);
		}

		::System::Boolean IsShowMappingInfoNewContentRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA_ISSHOWMAPPINGINFONEWCONTENTREDDOT_OFFSET))(this);
		}

		::System::Boolean IsShowMappingInfoRewardRedDot()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_RESIDENTSWORDTRAININGACTIVITYDATA_ISSHOWMAPPINGINFOREWARDREDDOT_OFFSET))(this);
		}
	};
}
