#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

class Class_1_21C7581DFE99F091_110;
namespace RPG::GameCore { class RogueHandBookEventRow; }
namespace System { class String; }

#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_EVENTTYPELIST_OFFSET UNITYSDK_OFFSET(0xD3A5400)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_HANDBOOKEVENTID_OFFSET UNITYSDK_OFFSET(0xD3A53B0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_HASUNTAKENREWARD_OFFSET UNITYSDK_OFFSET(0xD3ACAC0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_IMAGEID_OFFSET UNITYSDK_OFFSET(0xD3AC910)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_IMAGEPATH_OFFSET UNITYSDK_OFFSET(0xD3AC9D0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_ISINSCHEDULE_OFFSET UNITYSDK_OFFSET(0xD3ACB00)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_ISUNLOCKED_OFFSET UNITYSDK_OFFSET(0xD3ACAE0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_ORDER_OFFSET UNITYSDK_OFFSET(0xD3AC830)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_REWARDID_OFFSET UNITYSDK_OFFSET(0xD3ACA70)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_TITLE_OFFSET UNITYSDK_OFFSET(0xD3AC8A0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_TYPE_OFFSET UNITYSDK_OFFSET(0xD3AC960)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_UNLOCKHINTDESC_OFFSET UNITYSDK_OFFSET(0xD3ACB20)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_SET_HASUNTAKENREWARD_OFFSET UNITYSDK_OFFSET(0xD3ACAD0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_SET_ISINSCHEDULE_OFFSET UNITYSDK_OFFSET(0xD3ACB10)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_SET_ISUNLOCKED_OFFSET UNITYSDK_OFFSET(0xD3ACAF0)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_UPDATEBYSERVER_OFFSET UNITYSDK_OFFSET(0xD3ABA70)
#define RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xD3ABE80)

namespace RPG::Client
{
	inline static constexpr unsigned int RogueHandbookRandomEventData_TypeDefinitionIndex = 64375;

	class RogueHandbookRandomEventData : public ::System::Object
	{
	public:
		::RPG::GameCore::RogueHandBookEventRow* _Row; // 0x10
		::System::UInt32 SortingOrder; // 0x18
		::System::Boolean _HasUntakenReward_k__BackingField; // 0x1C
		::System::Boolean _IsInSchedule_k__BackingField; // 0x1D
		::System::Boolean _IsUnlocked_k__BackingField; // 0x1E

		::System::Void _ctor(::RPG::GameCore::RogueHandBookEventRow* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::RogueHandBookEventRow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA__CTOR_OFFSET))(this, a1);
		}

		::System::Void UpdateByServer(::Class_1_21C7581DFE99F091_110* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_21C7581DFE99F091_110*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_UPDATEBYSERVER_OFFSET))(this, a1);
		}

		::System::UInt32 get_HandbookEventID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_HANDBOOKEVENTID_OFFSET))(this);
		}

		::RPG::Client::TextID get_Title()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_TITLE_OFFSET))(this);
		}

		::System::UInt32 get_ImageID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_IMAGEID_OFFSET))(this);
		}

		::RPG::Client::TextID get_Type()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_TYPE_OFFSET))(this);
		}

		::System::String* get_ImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_IMAGEPATH_OFFSET))(this);
		}

		::System::UInt32 get_RewardID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_REWARDID_OFFSET))(this);
		}

		::System::UInt32 get_Order()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_ORDER_OFFSET))(this);
		}

		::System::Boolean get_HasUntakenReward()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_HASUNTAKENREWARD_OFFSET))(this);
		}

		::System::Void set_HasUntakenReward(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_SET_HASUNTAKENREWARD_OFFSET))(this, a1);
		}

		::System::Boolean get_IsUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_ISUNLOCKED_OFFSET))(this);
		}

		::System::Void set_IsUnlocked(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_SET_ISUNLOCKED_OFFSET))(this, a1);
		}

		::System::Boolean get_IsInSchedule()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_ISINSCHEDULE_OFFSET))(this);
		}

		::System::Void set_IsInSchedule(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_SET_ISINSCHEDULE_OFFSET))(this, a1);
		}

		::Il2CppArray<::System::UInt32>* get_EventTypeList()
		{
			return ((::Il2CppArray<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_EVENTTYPELIST_OFFSET))(this);
		}

		::RPG::Client::TextID get_UnlockHintDesc()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ROGUEHANDBOOKRANDOMEVENTDATA_GET_UNLOCKHINTDESC_OFFSET))(this);
		}
	};
}
