#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TimeRewindCheckSetStateResult.h"
#include "unitysdk/RPG/Client/TimeRewindTargetType.h"
#include "unitysdk/RPG/GameCore/TimeRewindState.h"
#include "unitysdk/RPG/GameCore/TimeRewindView.h"
#include "unitysdk/System/Object.h"

class Class_1_43BD383C98B4C0C5_128;
namespace RPG::Client { class EntityTimelineControlNode; }

#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CANINTERACTWHENPAUSE_OFFSET UNITYSDK_OFFSET(0xD6AA940)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CANTRIGGERPAUSE_OFFSET UNITYSDK_OFFSET(0xD6AA4B0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CHECKCANINTERACT_OFFSET UNITYSDK_OFFSET(0xD6A9810)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CHECKCOLLIDERHITTARGETVALID_OFFSET UNITYSDK_OFFSET(0xD6AA400)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CHECKCOLLIDERNEEDHITDETECT_OFFSET UNITYSDK_OFFSET(0xD6AA3B0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_DISPOSE_OFFSET UNITYSDK_OFFSET(0xD6A7760)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_ENTERCONTROLMODE_OFFSET UNITYSDK_OFFSET(0xD6A8F80)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_EXITCONTROLMODE_OFFSET UNITYSDK_OFFSET(0xD6A80C0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTARGETDURATION_OFFSET UNITYSDK_OFFSET(0xD6AA260)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTARGETRATIO_OFFSET UNITYSDK_OFFSET(0xD6AA2B0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTIMEREWINDSTATE_OFFSET UNITYSDK_OFFSET(0xD6AA070)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTIMEREWINDVIEWOVERRIDE_OFFSET UNITYSDK_OFFSET(0xD6AA0C0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTRACKNODECOUNT_OFFSET UNITYSDK_OFFSET(0xD6AA300)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTRACKNODEPERCENTAGE_OFFSET UNITYSDK_OFFSET(0xD6AA350)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_AUTOTRIGGERFINISHEVENT_OFFSET UNITYSDK_OFFSET(0xD6AAAA0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_BINDTYPE_OFFSET UNITYSDK_OFFSET(0xD6AAAC0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISINCONTROL_OFFSET UNITYSDK_OFFSET(0xD6A9220)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISINMOTION_OFFSET UNITYSDK_OFFSET(0xD6A9390)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISPAUSE_OFFSET UNITYSDK_OFFSET(0xD6AAA30)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISTARGETVALID_OFFSET UNITYSDK_OFFSET(0xD6AAAE0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_LOCKRAYCASTCHECKIGNOREINNERTARGET_OFFSET UNITYSDK_OFFSET(0xD6AAAB0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_PAUSEBYCONDITION_OFFSET UNITYSDK_OFFSET(0xD6AAAD0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_INIT_OFFSET UNITYSDK_OFFSET(0xD6A74B0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_ISACTIVETARGET_OFFSET UNITYSDK_OFFSET(0xD6A9D70)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_ONFINISHREBUILD_OFFSET UNITYSDK_OFFSET(0xD6A9580)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_PAUSE_OFFSET UNITYSDK_OFFSET(0xD6AA500)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_PRELOADEFFECT_OFFSET UNITYSDK_OFFSET(0xD6A77B0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_RELEASEPRELOADEFFECT_OFFSET UNITYSDK_OFFSET(0xD6A7890)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_RESUMEPAUSE_OFFSET UNITYSDK_OFFSET(0xD6AA730)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_REVERTTRANSITIONIMMEDIATELY_OFFSET UNITYSDK_OFFSET(0xD6A96A0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_SETSPECULARMATFADETIME_OFFSET UNITYSDK_OFFSET(0xD6AA150)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_SETSTATEBYSTATEHASH_OFFSET UNITYSDK_OFFSET(0xD6A7BE0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_STARTREBUILD_OFFSET UNITYSDK_OFFSET(0xD6A9400)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TICK_OFFSET UNITYSDK_OFFSET(0xD6A9890)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TRIGGERMOTIONPAUSEACTION_OFFSET UNITYSDK_OFFSET(0xD6A7A20)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TRIGGERRESUMEMOTIONPAUSEACTION_OFFSET UNITYSDK_OFFSET(0xD6A7B00)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TRYREWINDONCE_OFFSET UNITYSDK_OFFSET(0xD6A8AD0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__CTOR_OFFSET UNITYSDK_OFFSET(0xD6A7450)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__DOSETSTATEBYSTATEHASHNOTRANSITION_OFFSET UNITYSDK_OFFSET(0xD6A84B0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__REFRESHTRACKINITSTATE_OFFSET UNITYSDK_OFFSET(0xD6A8750)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__RESETCHECKSTATECHANGETRIGGER_OFFSET UNITYSDK_OFFSET(0xD6A8A60)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__SETFOUNDATIONANDBALLTOSTABLESTATE_OFFSET UNITYSDK_OFFSET(0xD6A9290)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__SETTIMEREWINDOWNERSTATE_OFFSET UNITYSDK_OFFSET(0xD6A85E0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__SINGLELINESETTARGETRATIOBYREWINDSTATE_OFFSET UNITYSDK_OFFSET(0xD6AA980)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TICKSINGLELINEINRATIORANGE_OFFSET UNITYSDK_OFFSET(0xD6A9DC0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TICKSINGLELINENOTINRATIORANGE_OFFSET UNITYSDK_OFFSET(0xD6A9F70)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TRYEXITMOTION_OFFSET UNITYSDK_OFFSET(0xD6A8DA0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TRYSAVECURRENTSTATE_OFFSET UNITYSDK_OFFSET(0xD6A86C0)
#define RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TRYSTARTMOTION_OFFSET UNITYSDK_OFFSET(0xD6A8B60)

namespace RPG::Client
{
	inline static constexpr unsigned int TimeRewindDestructibleBridgeTarget_TypeDefinitionIndex = 58083;

	class TimeRewindDestructibleBridgeTarget : public ::System::Object
	{
	public:
		::RPG::Client::EntityTimelineControlNode* _BridgePrevStableState; // 0x10
		::Class_1_43BD383C98B4C0C5_128* _MaxDurationProxy; // 0x18
		::Il2CppArray<::Class_1_43BD383C98B4C0C5_128*>* _ChildProxy; // 0x20
		::Il2CppArray<::System::Boolean>* _ChildTriggered; // 0x28
		::Class_1_43BD383C98B4C0C5_128* _BridgeProxy; // 0x30
		::Il2CppArray<::RPG::Client::EntityTimelineControlNode*>* _ChildPrevStableState; // 0x38
		::RPG::GameCore::TimeRewindState _TimeRewindState; // 0x40
		::System::Int32 _ChildAnimHash; // 0x44
		::System::Boolean _BridgeTriggered; // 0x48
		::System::Single _CurrentDuration; // 0x4C
		::System::Single _CurrentRatio; // 0x50

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__CTOR_OFFSET))(this);
		}

		::System::Void Init(::Class_1_43BD383C98B4C0C5_128* a1, ::Il2CppArray<::Class_1_43BD383C98B4C0C5_128*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::Il2CppArray<::Class_1_43BD383C98B4C0C5_128*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_INIT_OFFSET))(this, a1, a2);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_DISPOSE_OFFSET))(this);
		}

		::System::Boolean PreloadEffect()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_PRELOADEFFECT_OFFSET))(this);
		}

		::System::Void ReleasePreloadEffect()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_RELEASEPRELOADEFFECT_OFFSET))(this);
		}

		::System::Void TriggerMotionPauseAction()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TRIGGERMOTIONPAUSEACTION_OFFSET))(this);
		}

		::System::Void TriggerResumeMotionPauseAction()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TRIGGERRESUMEMOTIONPAUSEACTION_OFFSET))(this);
		}

		::RPG::Client::TimeRewindCheckSetStateResult SetStateByStateHash(::System::Int32 a1, ::System::Boolean a2, ::System::Boolean a3, ::Class_1_43BD383C98B4C0C5_128* a4, ::System::Boolean a5)
		{
			return ((::RPG::Client::TimeRewindCheckSetStateResult(*)(::PVOID, ::System::Int32, ::System::Boolean, ::System::Boolean, ::Class_1_43BD383C98B4C0C5_128*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_SETSTATEBYSTATEHASH_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Void TryRewindOnce()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TRYREWINDONCE_OFFSET))(this);
		}

		::System::Void _DoSetStateByStateHashNoTransition(::System::Int32 a1, ::Class_1_43BD383C98B4C0C5_128* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__DOSETSTATEBYSTATEHASHNOTRANSITION_OFFSET))(this, a1, a2);
		}

		::System::Void EnterControlMode(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_ENTERCONTROLMODE_OFFSET))(this, a1);
		}

		::System::Void ExitControlMode(::Class_1_43BD383C98B4C0C5_128* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_EXITCONTROLMODE_OFFSET))(this, a1, a2);
		}

		::System::Void StartRebuild(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_STARTREBUILD_OFFSET))(this, a1);
		}

		::System::Void OnFinishRebuild(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_ONFINISHREBUILD_OFFSET))(this, a1);
		}

		::System::Void RevertTransitionImmediately(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_REVERTTRANSITIONIMMEDIATELY_OFFSET))(this, a1);
		}

		::System::Boolean CheckCanInteract(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CHECKCANINTERACT_OFFSET))(this, a1);
		}

		::System::Void Tick(::System::Single a1, ::Class_1_43BD383C98B4C0C5_128* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_TICK_OFFSET))(this, a1, a2);
		}

		::System::Boolean IsActiveTarget(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_ISACTIVETARGET_OFFSET))(this, a1);
		}

		::RPG::GameCore::TimeRewindState GetTimeRewindState(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::RPG::GameCore::TimeRewindState(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTIMEREWINDSTATE_OFFSET))(this, a1);
		}

		::System::Boolean GetTimeRewindViewOverride(::Class_1_43BD383C98B4C0C5_128* a1, ::RPG::GameCore::TimeRewindView& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::RPG::GameCore::TimeRewindView&))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTIMEREWINDVIEWOVERRIDE_OFFSET))(this, a1, a2);
		}

		::System::Void SetSpecularMatFadeTime(::System::Single a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_SETSPECULARMATFADETIME_OFFSET))(this, a1, a2);
		}

		::System::Single GetTargetDuration()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTARGETDURATION_OFFSET))(this);
		}

		::System::Single GetTargetRatio()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTARGETRATIO_OFFSET))(this);
		}

		::System::Int32 GetTrackNodeCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTRACKNODECOUNT_OFFSET))(this);
		}

		::System::Single GetTrackNodePercentage(::System::Int32 a1)
		{
			return ((::System::Single(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GETTRACKNODEPERCENTAGE_OFFSET))(this, a1);
		}

		::System::Boolean CheckColliderNeedHitDetect(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CHECKCOLLIDERNEEDHITDETECT_OFFSET))(this, a1);
		}

		::System::Boolean CheckColliderHitTargetValid(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CHECKCOLLIDERHITTARGETVALID_OFFSET))(this, a1);
		}

		::System::Boolean CanTriggerPause(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CANTRIGGERPAUSE_OFFSET))(this, a1);
		}

		::System::Void Pause()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_PAUSE_OFFSET))(this);
		}

		::System::Void ResumePause()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_RESUMEPAUSE_OFFSET))(this);
		}

		::System::Boolean CanInteractWhenPause()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_CANINTERACTWHENPAUSE_OFFSET))(this);
		}

		::System::Void _SetFoundationAndBallToStableState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__SETFOUNDATIONANDBALLTOSTABLESTATE_OFFSET))(this);
		}

		::System::Void _SingleLineSetTargetRatioByRewindState(::RPG::GameCore::TimeRewindState a1, ::Class_1_43BD383C98B4C0C5_128* a2)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TimeRewindState, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__SINGLELINESETTARGETRATIOBYREWINDSTATE_OFFSET))(this, a1, a2);
		}

		::System::Void _TickSingleLineInRatioRange(::Class_1_43BD383C98B4C0C5_128* a1, ::System::Boolean& a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::System::Boolean&))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TICKSINGLELINEINRATIORANGE_OFFSET))(this, a1, a2);
		}

		::System::Void _TickSingleLineNotInRatioRange(::Class_1_43BD383C98B4C0C5_128* a1, ::System::Boolean& a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::System::Boolean&))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TICKSINGLELINENOTINRATIORANGE_OFFSET))(this, a1, a2);
		}

		::System::Void _TryStartMotion(::Class_1_43BD383C98B4C0C5_128* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TRYSTARTMOTION_OFFSET))(this, a1);
		}

		::System::Void _TryExitMotion(::Class_1_43BD383C98B4C0C5_128* a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TRYEXITMOTION_OFFSET))(this, a1, a2);
		}

		::System::Void _TrySaveCurrentState(::Class_1_43BD383C98B4C0C5_128* a1, ::RPG::Client::EntityTimelineControlNode* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_128*, ::RPG::Client::EntityTimelineControlNode*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__TRYSAVECURRENTSTATE_OFFSET))(this, a1, a2);
		}

		::System::Void _SetTimeRewindOwnerState(::RPG::GameCore::TimeRewindState a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::GameCore::TimeRewindState))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__SETTIMEREWINDOWNERSTATE_OFFSET))(this, a1);
		}

		::System::Void _ResetCheckStateChangeTrigger()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__RESETCHECKSTATECHANGETRIGGER_OFFSET))(this);
		}

		::System::Void _RefreshTrackInitState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET__REFRESHTRACKINITSTATE_OFFSET))(this);
		}

		::System::Boolean get_IsPause()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISPAUSE_OFFSET))(this);
		}

		::System::Boolean get_IsInMotion()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISINMOTION_OFFSET))(this);
		}

		::System::Boolean get_IsInControl()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISINCONTROL_OFFSET))(this);
		}

		::System::Boolean get_AutoTriggerFinishEvent()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_AUTOTRIGGERFINISHEVENT_OFFSET))(this);
		}

		::System::Boolean get_LockRaycastCheckIgnoreInnerTarget()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_LOCKRAYCASTCHECKIGNOREINNERTARGET_OFFSET))(this);
		}

		::RPG::Client::TimeRewindTargetType get_BindType()
		{
			return ((::RPG::Client::TimeRewindTargetType(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_BINDTYPE_OFFSET))(this);
		}

		::System::Boolean get_PauseByCondition()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_PAUSEBYCONDITION_OFFSET))(this);
		}

		::System::Boolean get_IsTargetValid()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TIMEREWINDDESTRUCTIBLEBRIDGETARGET_GET_ISTARGETVALID_OFFSET))(this);
		}
	};
}
