#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/ValueType.h"
#include "unitysdk/UnityEngine/ParticleSystemMeshShapeType.h"
#include "unitysdk/UnityEngine/ParticleSystemShapeMultiModeValue.h"
#include "unitysdk/UnityEngine/ParticleSystemShapeTextureChannel.h"
#include "unitysdk/UnityEngine/ParticleSystemShapeType.h"

namespace UnityEngine { class Mesh; }
namespace UnityEngine { class MeshRenderer; }
namespace UnityEngine { class ParticleSystem; }
namespace UnityEngine { class SkinnedMeshRenderer; }
namespace UnityEngine { class Sprite; }
namespace UnityEngine { class SpriteRenderer; }
namespace UnityEngine { class Texture2D; }

#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ALIGNTODIRECTION_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7A90)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ALIGNTODIRECTION_OFFSET UNITYSDK_OFFSET(0x3A38AC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ANGLE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7C80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ANGLE_OFFSET UNITYSDK_OFFSET(0x3A38BF0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCMODE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8170)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCMODE_OFFSET UNITYSDK_OFFSET(0x3A38ED0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEEDMULTIPLIER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8260)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEEDMULTIPLIER_OFFSET UNITYSDK_OFFSET(0x3A38F80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8220)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEED_OFFSET UNITYSDK_OFFSET(0x3A38F10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPREAD_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A81B0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPREAD_OFFSET UNITYSDK_OFFSET(0x3A38EF0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARC_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8130)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARC_OFFSET UNITYSDK_OFFSET(0x3A38EB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_BOXTHICKNESS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7D40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_BOXTHICKNESS_OFFSET UNITYSDK_OFFSET(0x3A38C30)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_DONUTRADIUS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A82A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_DONUTRADIUS_OFFSET UNITYSDK_OFFSET(0x3A38FA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ENABLED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7950)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ENABLED_OFFSET UNITYSDK_OFFSET(0x3A38A20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_LENGTH_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7CC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_LENGTH_OFFSET UNITYSDK_OFFSET(0x3A38C10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHMATERIALINDEX_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7F40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHMATERIALINDEX_OFFSET UNITYSDK_OFFSET(0x3A38D80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHRENDERER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7E00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHRENDERER_OFFSET UNITYSDK_OFFSET(0x3A38CE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSHAPETYPE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7D80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSHAPETYPE_OFFSET UNITYSDK_OFFSET(0x3A38CA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNMODE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8000)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNMODE_OFFSET UNITYSDK_OFFSET(0x3A38DE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEEDMULTIPLIER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A80F0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEEDMULTIPLIER_OFFSET UNITYSDK_OFFSET(0x3A38E90)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A80B0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEED_OFFSET UNITYSDK_OFFSET(0x3A38E20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPREAD_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8040)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPREAD_OFFSET UNITYSDK_OFFSET(0x3A38E00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESH_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7DC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESH_OFFSET UNITYSDK_OFFSET(0x3A38CC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_NORMALOFFSET_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7FC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_NORMALOFFSET_OFFSET UNITYSDK_OFFSET(0x3A38DC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_POSITION_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8320)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_POSITION_OFFSET UNITYSDK_OFFSET(0x3A38FC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSMODE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7B10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSMODE_OFFSET UNITYSDK_OFFSET(0x3A38B00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEEDMULTIPLIER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7C00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEEDMULTIPLIER_OFFSET UNITYSDK_OFFSET(0x3A38BB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7BC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEED_OFFSET UNITYSDK_OFFSET(0x3A38B40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPREAD_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7B50)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPREAD_OFFSET UNITYSDK_OFFSET(0x3A38B20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSTHICKNESS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7C40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSTHICKNESS_OFFSET UNITYSDK_OFFSET(0x3A38BD0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7AD0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUS_OFFSET UNITYSDK_OFFSET(0x3A38AE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMDIRECTIONAMOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A79D0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMDIRECTIONAMOUNT_OFFSET UNITYSDK_OFFSET(0x3A38A60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMPOSITIONAMOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7A50)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMPOSITIONAMOUNT_OFFSET UNITYSDK_OFFSET(0x3A38AA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ROTATION_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A83A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ROTATION_OFFSET UNITYSDK_OFFSET(0x3A39030)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SCALE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8420)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SCALE_OFFSET UNITYSDK_OFFSET(0x3A390A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SHAPETYPE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7990)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SHAPETYPE_OFFSET UNITYSDK_OFFSET(0x3A38A40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SKINNEDMESHRENDERER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7E40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SKINNEDMESHRENDERER_OFFSET UNITYSDK_OFFSET(0x3A38D00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPHERICALDIRECTIONAMOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7A10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPHERICALDIRECTIONAMOUNT_OFFSET UNITYSDK_OFFSET(0x3A38A80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITERENDERER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7EC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITERENDERER_OFFSET UNITYSDK_OFFSET(0x3A38D40)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7E80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITE_OFFSET UNITYSDK_OFFSET(0x3A38D20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREALPHAAFFECTSPARTICLES_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8600)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREALPHAAFFECTSPARTICLES_OFFSET UNITYSDK_OFFSET(0x3A39250)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREBILINEARFILTERING_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8640)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREBILINEARFILTERING_OFFSET UNITYSDK_OFFSET(0x3A39270)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPCHANNEL_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A84A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPCHANNEL_OFFSET UNITYSDK_OFFSET(0x3A39130)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMAX_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8580)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMAX_OFFSET UNITYSDK_OFFSET(0x3A391C0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMIN_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8510)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMIN_OFFSET UNITYSDK_OFFSET(0x3A39150)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECOLORAFFECTSPARTICLES_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A85C0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECOLORAFFECTSPARTICLES_OFFSET UNITYSDK_OFFSET(0x3A39230)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREUVCHANNEL_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8680)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREUVCHANNEL_OFFSET UNITYSDK_OFFSET(0x3A39290)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8460)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURE_OFFSET UNITYSDK_OFFSET(0x3A39110)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHCOLORS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7F80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHCOLORS_OFFSET UNITYSDK_OFFSET(0x3A38DA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHMATERIALINDEX_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7F00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHMATERIALINDEX_OFFSET UNITYSDK_OFFSET(0x3A38D60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ALIGNTODIRECTION_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7AB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ALIGNTODIRECTION_OFFSET UNITYSDK_OFFSET(0x3A38AD0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ANGLE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7CA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ANGLE_OFFSET UNITYSDK_OFFSET(0x3A38C00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCMODE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8190)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCMODE_OFFSET UNITYSDK_OFFSET(0x3A38EE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEEDMULTIPLIER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8280)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEEDMULTIPLIER_OFFSET UNITYSDK_OFFSET(0x3A38F90)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8240)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEED_OFFSET UNITYSDK_OFFSET(0x3A38F50)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPREAD_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A81D0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPREAD_OFFSET UNITYSDK_OFFSET(0x3A38F00)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARC_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8150)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARC_OFFSET UNITYSDK_OFFSET(0x3A38EC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_BOXTHICKNESS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7D60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_BOXTHICKNESS_OFFSET UNITYSDK_OFFSET(0x3A38C70)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_DONUTRADIUS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A82C0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_DONUTRADIUS_OFFSET UNITYSDK_OFFSET(0x3A38FB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ENABLED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7970)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ENABLED_OFFSET UNITYSDK_OFFSET(0x3A38A30)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_LENGTH_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7CE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_LENGTH_OFFSET UNITYSDK_OFFSET(0x3A38C20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHMATERIALINDEX_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7F60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHMATERIALINDEX_OFFSET UNITYSDK_OFFSET(0x3A38D90)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHRENDERER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7E20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHRENDERER_OFFSET UNITYSDK_OFFSET(0x3A38CF0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSHAPETYPE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7DA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSHAPETYPE_OFFSET UNITYSDK_OFFSET(0x3A38CB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNMODE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8020)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNMODE_OFFSET UNITYSDK_OFFSET(0x3A38DF0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEEDMULTIPLIER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8110)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEEDMULTIPLIER_OFFSET UNITYSDK_OFFSET(0x3A38EA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A80D0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEED_OFFSET UNITYSDK_OFFSET(0x3A38E60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPREAD_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8060)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPREAD_OFFSET UNITYSDK_OFFSET(0x3A38E10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESH_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7DE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESH_OFFSET UNITYSDK_OFFSET(0x3A38CD0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_NORMALOFFSET_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7FE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_NORMALOFFSET_OFFSET UNITYSDK_OFFSET(0x3A38DD0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_POSITION_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8340)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_POSITION_OFFSET UNITYSDK_OFFSET(0x3A39000)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSMODE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7B30)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSMODE_OFFSET UNITYSDK_OFFSET(0x3A38B10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEEDMULTIPLIER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7C20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEEDMULTIPLIER_OFFSET UNITYSDK_OFFSET(0x3A38BC0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEED_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7BE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEED_OFFSET UNITYSDK_OFFSET(0x3A38B80)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPREAD_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7B70)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPREAD_OFFSET UNITYSDK_OFFSET(0x3A38B30)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSTHICKNESS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7C60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSTHICKNESS_OFFSET UNITYSDK_OFFSET(0x3A38BE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7AF0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUS_OFFSET UNITYSDK_OFFSET(0x3A38AF0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMDIRECTIONAMOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A79F0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMDIRECTIONAMOUNT_OFFSET UNITYSDK_OFFSET(0x3A38A70)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMPOSITIONAMOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7A70)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMPOSITIONAMOUNT_OFFSET UNITYSDK_OFFSET(0x3A38AB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ROTATION_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A83C0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ROTATION_OFFSET UNITYSDK_OFFSET(0x3A39070)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SCALE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8440)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SCALE_OFFSET UNITYSDK_OFFSET(0x3A390E0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SHAPETYPE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A79B0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SHAPETYPE_OFFSET UNITYSDK_OFFSET(0x3A38A50)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SKINNEDMESHRENDERER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7E60)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SKINNEDMESHRENDERER_OFFSET UNITYSDK_OFFSET(0x3A38D10)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPHERICALDIRECTIONAMOUNT_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7A30)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPHERICALDIRECTIONAMOUNT_OFFSET UNITYSDK_OFFSET(0x3A38A90)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITERENDERER_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7EE0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITERENDERER_OFFSET UNITYSDK_OFFSET(0x3A38D50)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7EA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITE_OFFSET UNITYSDK_OFFSET(0x3A38D30)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREALPHAAFFECTSPARTICLES_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8620)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREALPHAAFFECTSPARTICLES_OFFSET UNITYSDK_OFFSET(0x3A39260)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREBILINEARFILTERING_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8660)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREBILINEARFILTERING_OFFSET UNITYSDK_OFFSET(0x3A39280)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPCHANNEL_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A84C0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPCHANNEL_OFFSET UNITYSDK_OFFSET(0x3A39140)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMAX_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A85A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMAX_OFFSET UNITYSDK_OFFSET(0x3A39200)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMIN_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8530)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMIN_OFFSET UNITYSDK_OFFSET(0x3A39190)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECOLORAFFECTSPARTICLES_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A85E0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECOLORAFFECTSPARTICLES_OFFSET UNITYSDK_OFFSET(0x3A39240)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREUVCHANNEL_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A86A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREUVCHANNEL_OFFSET UNITYSDK_OFFSET(0x3A392A0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A8480)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURE_OFFSET UNITYSDK_OFFSET(0x3A39120)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHCOLORS_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7FA0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHCOLORS_OFFSET UNITYSDK_OFFSET(0x3A38DB0)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHMATERIALINDEX_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D0A7F20)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHMATERIALINDEX_OFFSET UNITYSDK_OFFSET(0x3A38D70)
#define UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE__CTOR_OFFSET UNITYSDK_OFFSET(0xC630)

namespace UnityEngine
{
	inline static constexpr unsigned int ParticleSystem_ShapeModule_TypeDefinitionIndex = 5719;

	struct alignas(8) ParticleSystem_ShapeModule
	{
		::UnityEngine::ParticleSystem* m_ParticleSystem; // 0x10

		::System::Void _ctor(::UnityEngine::ParticleSystem* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE__CTOR_OFFSET))(this, a1);
		}

		::System::Boolean get_enabled()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ENABLED_OFFSET))(this);
		}

		::System::Void set_enabled(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ENABLED_OFFSET))(this, a1);
		}

		::UnityEngine::ParticleSystemShapeType get_shapeType()
		{
			return ((::UnityEngine::ParticleSystemShapeType(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SHAPETYPE_OFFSET))(this);
		}

		::System::Void set_shapeType(::UnityEngine::ParticleSystemShapeType a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemShapeType))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SHAPETYPE_OFFSET))(this, a1);
		}

		::System::Single get_randomDirectionAmount()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMDIRECTIONAMOUNT_OFFSET))(this);
		}

		::System::Void set_randomDirectionAmount(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMDIRECTIONAMOUNT_OFFSET))(this, a1);
		}

		::System::Single get_sphericalDirectionAmount()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPHERICALDIRECTIONAMOUNT_OFFSET))(this);
		}

		::System::Void set_sphericalDirectionAmount(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPHERICALDIRECTIONAMOUNT_OFFSET))(this, a1);
		}

		::System::Single get_randomPositionAmount()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMPOSITIONAMOUNT_OFFSET))(this);
		}

		::System::Void set_randomPositionAmount(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMPOSITIONAMOUNT_OFFSET))(this, a1);
		}

		::System::Boolean get_alignToDirection()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ALIGNTODIRECTION_OFFSET))(this);
		}

		::System::Void set_alignToDirection(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ALIGNTODIRECTION_OFFSET))(this, a1);
		}

		::System::Single get_radius()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUS_OFFSET))(this);
		}

		::System::Void set_radius(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUS_OFFSET))(this, a1);
		}

		::UnityEngine::ParticleSystemShapeMultiModeValue get_radiusMode()
		{
			return ((::UnityEngine::ParticleSystemShapeMultiModeValue(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSMODE_OFFSET))(this);
		}

		::System::Void set_radiusMode(::UnityEngine::ParticleSystemShapeMultiModeValue a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemShapeMultiModeValue))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSMODE_OFFSET))(this, a1);
		}

		::System::Single get_radiusSpread()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPREAD_OFFSET))(this);
		}

		::System::Void set_radiusSpread(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPREAD_OFFSET))(this, a1);
		}

		/*
		::UnityEngine::ParticleSystem_MinMaxCurve get_radiusSpeed()
		{
			return ((::UnityEngine::ParticleSystem_MinMaxCurve(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEED_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_radiusSpeed(::UnityEngine::ParticleSystem_MinMaxCurve a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem_MinMaxCurve))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEED_OFFSET))(this, a1);
		}
		*/

		::System::Single get_radiusSpeedMultiplier()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEEDMULTIPLIER_OFFSET))(this);
		}

		::System::Void set_radiusSpeedMultiplier(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEEDMULTIPLIER_OFFSET))(this, a1);
		}

		::System::Single get_radiusThickness()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSTHICKNESS_OFFSET))(this);
		}

		::System::Void set_radiusThickness(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSTHICKNESS_OFFSET))(this, a1);
		}

		::System::Single get_angle()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ANGLE_OFFSET))(this);
		}

		::System::Void set_angle(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ANGLE_OFFSET))(this, a1);
		}

		::System::Single get_length()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_LENGTH_OFFSET))(this);
		}

		::System::Void set_length(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_LENGTH_OFFSET))(this, a1);
		}

		/*
		::UnityEngine::Vector3 get_boxThickness()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_BOXTHICKNESS_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_boxThickness(::UnityEngine::Vector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_BOXTHICKNESS_OFFSET))(this, a1);
		}
		*/

		::UnityEngine::ParticleSystemMeshShapeType get_meshShapeType()
		{
			return ((::UnityEngine::ParticleSystemMeshShapeType(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSHAPETYPE_OFFSET))(this);
		}

		::System::Void set_meshShapeType(::UnityEngine::ParticleSystemMeshShapeType a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemMeshShapeType))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSHAPETYPE_OFFSET))(this, a1);
		}

		::UnityEngine::Mesh* get_mesh()
		{
			return ((::UnityEngine::Mesh*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESH_OFFSET))(this);
		}

		::System::Void set_mesh(::UnityEngine::Mesh* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Mesh*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESH_OFFSET))(this, a1);
		}

		::UnityEngine::MeshRenderer* get_meshRenderer()
		{
			return ((::UnityEngine::MeshRenderer*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHRENDERER_OFFSET))(this);
		}

		::System::Void set_meshRenderer(::UnityEngine::MeshRenderer* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::MeshRenderer*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHRENDERER_OFFSET))(this, a1);
		}

		::UnityEngine::SkinnedMeshRenderer* get_skinnedMeshRenderer()
		{
			return ((::UnityEngine::SkinnedMeshRenderer*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SKINNEDMESHRENDERER_OFFSET))(this);
		}

		::System::Void set_skinnedMeshRenderer(::UnityEngine::SkinnedMeshRenderer* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::SkinnedMeshRenderer*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SKINNEDMESHRENDERER_OFFSET))(this, a1);
		}

		::UnityEngine::Sprite* get_sprite()
		{
			return ((::UnityEngine::Sprite*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITE_OFFSET))(this);
		}

		::System::Void set_sprite(::UnityEngine::Sprite* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Sprite*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITE_OFFSET))(this, a1);
		}

		::UnityEngine::SpriteRenderer* get_spriteRenderer()
		{
			return ((::UnityEngine::SpriteRenderer*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITERENDERER_OFFSET))(this);
		}

		::System::Void set_spriteRenderer(::UnityEngine::SpriteRenderer* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::SpriteRenderer*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITERENDERER_OFFSET))(this, a1);
		}

		::System::Boolean get_useMeshMaterialIndex()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHMATERIALINDEX_OFFSET))(this);
		}

		::System::Void set_useMeshMaterialIndex(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHMATERIALINDEX_OFFSET))(this, a1);
		}

		::System::Int32 get_meshMaterialIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHMATERIALINDEX_OFFSET))(this);
		}

		::System::Void set_meshMaterialIndex(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHMATERIALINDEX_OFFSET))(this, a1);
		}

		::System::Boolean get_useMeshColors()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHCOLORS_OFFSET))(this);
		}

		::System::Void set_useMeshColors(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHCOLORS_OFFSET))(this, a1);
		}

		::System::Single get_normalOffset()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_NORMALOFFSET_OFFSET))(this);
		}

		::System::Void set_normalOffset(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_NORMALOFFSET_OFFSET))(this, a1);
		}

		::UnityEngine::ParticleSystemShapeMultiModeValue get_meshSpawnMode()
		{
			return ((::UnityEngine::ParticleSystemShapeMultiModeValue(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNMODE_OFFSET))(this);
		}

		::System::Void set_meshSpawnMode(::UnityEngine::ParticleSystemShapeMultiModeValue a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemShapeMultiModeValue))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNMODE_OFFSET))(this, a1);
		}

		::System::Single get_meshSpawnSpread()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPREAD_OFFSET))(this);
		}

		::System::Void set_meshSpawnSpread(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPREAD_OFFSET))(this, a1);
		}

		/*
		::UnityEngine::ParticleSystem_MinMaxCurve get_meshSpawnSpeed()
		{
			return ((::UnityEngine::ParticleSystem_MinMaxCurve(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEED_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_meshSpawnSpeed(::UnityEngine::ParticleSystem_MinMaxCurve a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem_MinMaxCurve))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEED_OFFSET))(this, a1);
		}
		*/

		::System::Single get_meshSpawnSpeedMultiplier()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEEDMULTIPLIER_OFFSET))(this);
		}

		::System::Void set_meshSpawnSpeedMultiplier(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEEDMULTIPLIER_OFFSET))(this, a1);
		}

		::System::Single get_arc()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARC_OFFSET))(this);
		}

		::System::Void set_arc(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARC_OFFSET))(this, a1);
		}

		::UnityEngine::ParticleSystemShapeMultiModeValue get_arcMode()
		{
			return ((::UnityEngine::ParticleSystemShapeMultiModeValue(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCMODE_OFFSET))(this);
		}

		::System::Void set_arcMode(::UnityEngine::ParticleSystemShapeMultiModeValue a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemShapeMultiModeValue))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCMODE_OFFSET))(this, a1);
		}

		::System::Single get_arcSpread()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPREAD_OFFSET))(this);
		}

		::System::Void set_arcSpread(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPREAD_OFFSET))(this, a1);
		}

		/*
		::UnityEngine::ParticleSystem_MinMaxCurve get_arcSpeed()
		{
			return ((::UnityEngine::ParticleSystem_MinMaxCurve(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEED_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_arcSpeed(::UnityEngine::ParticleSystem_MinMaxCurve a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem_MinMaxCurve))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEED_OFFSET))(this, a1);
		}
		*/

		::System::Single get_arcSpeedMultiplier()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEEDMULTIPLIER_OFFSET))(this);
		}

		::System::Void set_arcSpeedMultiplier(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEEDMULTIPLIER_OFFSET))(this, a1);
		}

		::System::Single get_donutRadius()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_DONUTRADIUS_OFFSET))(this);
		}

		::System::Void set_donutRadius(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_DONUTRADIUS_OFFSET))(this, a1);
		}

		/*
		::UnityEngine::Vector3 get_position()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_POSITION_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_position(::UnityEngine::Vector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_POSITION_OFFSET))(this, a1);
		}
		*/

		/*
		::UnityEngine::Vector3 get_rotation()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ROTATION_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_rotation(::UnityEngine::Vector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ROTATION_OFFSET))(this, a1);
		}
		*/

		/*
		::UnityEngine::Vector3 get_scale()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SCALE_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_scale(::UnityEngine::Vector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SCALE_OFFSET))(this, a1);
		}
		*/

		::UnityEngine::Texture2D* get_texture()
		{
			return ((::UnityEngine::Texture2D*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURE_OFFSET))(this);
		}

		::System::Void set_texture(::UnityEngine::Texture2D* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Texture2D*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURE_OFFSET))(this, a1);
		}

		::UnityEngine::ParticleSystemShapeTextureChannel get_textureClipChannel()
		{
			return ((::UnityEngine::ParticleSystemShapeTextureChannel(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPCHANNEL_OFFSET))(this);
		}

		::System::Void set_textureClipChannel(::UnityEngine::ParticleSystemShapeTextureChannel a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystemShapeTextureChannel))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPCHANNEL_OFFSET))(this, a1);
		}

		/*
		::UnityEngine::ParticleSystem_MinMaxCurve get_textureClipThresholdMin()
		{
			return ((::UnityEngine::ParticleSystem_MinMaxCurve(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMIN_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_textureClipThresholdMin(::UnityEngine::ParticleSystem_MinMaxCurve a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem_MinMaxCurve))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMIN_OFFSET))(this, a1);
		}
		*/

		/*
		::UnityEngine::ParticleSystem_MinMaxCurve get_textureClipThresholdMax()
		{
			return ((::UnityEngine::ParticleSystem_MinMaxCurve(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMAX_OFFSET))(this);
		}
		*/

		/*
		::System::Void set_textureClipThresholdMax(::UnityEngine::ParticleSystem_MinMaxCurve a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::ParticleSystem_MinMaxCurve))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMAX_OFFSET))(this, a1);
		}
		*/

		::System::Boolean get_textureColorAffectsParticles()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECOLORAFFECTSPARTICLES_OFFSET))(this);
		}

		::System::Void set_textureColorAffectsParticles(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECOLORAFFECTSPARTICLES_OFFSET))(this, a1);
		}

		::System::Boolean get_textureAlphaAffectsParticles()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREALPHAAFFECTSPARTICLES_OFFSET))(this);
		}

		::System::Void set_textureAlphaAffectsParticles(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREALPHAAFFECTSPARTICLES_OFFSET))(this, a1);
		}

		::System::Boolean get_textureBilinearFiltering()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREBILINEARFILTERING_OFFSET))(this);
		}

		::System::Void set_textureBilinearFiltering(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREBILINEARFILTERING_OFFSET))(this, a1);
		}

		::System::Int32 get_textureUVChannel()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREUVCHANNEL_OFFSET))(this);
		}

		::System::Void set_textureUVChannel(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREUVCHANNEL_OFFSET))(this, a1);
		}

		static ::System::Boolean get_enabled_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ENABLED_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_enabled_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ENABLED_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::ParticleSystemShapeType get_shapeType_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::ParticleSystemShapeType(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SHAPETYPE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_shapeType_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystemShapeType a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystemShapeType))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SHAPETYPE_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_randomDirectionAmount_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMDIRECTIONAMOUNT_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_randomDirectionAmount_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMDIRECTIONAMOUNT_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_sphericalDirectionAmount_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPHERICALDIRECTIONAMOUNT_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_sphericalDirectionAmount_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPHERICALDIRECTIONAMOUNT_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_randomPositionAmount_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RANDOMPOSITIONAMOUNT_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_randomPositionAmount_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RANDOMPOSITIONAMOUNT_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Boolean get_alignToDirection_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ALIGNTODIRECTION_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_alignToDirection_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ALIGNTODIRECTION_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_radius_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUS_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_radius_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUS_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::ParticleSystemShapeMultiModeValue get_radiusMode_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::ParticleSystemShapeMultiModeValue(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSMODE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_radiusMode_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystemShapeMultiModeValue a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystemShapeMultiModeValue))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSMODE_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_radiusSpread_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPREAD_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_radiusSpread_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPREAD_INJECTED_OFFSET))(a1, a2);
		}

		/*
		static ::System::Void get_radiusSpeed_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEED_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_radiusSpeed_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEED_INJECTED_OFFSET))(a1, a2);
		}
		*/

		static ::System::Single get_radiusSpeedMultiplier_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSSPEEDMULTIPLIER_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_radiusSpeedMultiplier_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSSPEEDMULTIPLIER_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_radiusThickness_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_RADIUSTHICKNESS_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_radiusThickness_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_RADIUSTHICKNESS_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_angle_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ANGLE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_angle_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ANGLE_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_length_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_LENGTH_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_length_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_LENGTH_INJECTED_OFFSET))(a1, a2);
		}

		/*
		static ::System::Void get_boxThickness_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_BOXTHICKNESS_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_boxThickness_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_BOXTHICKNESS_INJECTED_OFFSET))(a1, a2);
		}
		*/

		static ::UnityEngine::ParticleSystemMeshShapeType get_meshShapeType_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::ParticleSystemMeshShapeType(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSHAPETYPE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_meshShapeType_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystemMeshShapeType a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystemMeshShapeType))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSHAPETYPE_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::Mesh* get_mesh_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::Mesh*(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESH_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_mesh_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Mesh* a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Mesh*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESH_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::MeshRenderer* get_meshRenderer_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::MeshRenderer*(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHRENDERER_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_meshRenderer_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::MeshRenderer* a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::MeshRenderer*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHRENDERER_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::SkinnedMeshRenderer* get_skinnedMeshRenderer_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::SkinnedMeshRenderer*(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SKINNEDMESHRENDERER_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_skinnedMeshRenderer_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::SkinnedMeshRenderer* a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::SkinnedMeshRenderer*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SKINNEDMESHRENDERER_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::Sprite* get_sprite_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::Sprite*(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_sprite_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Sprite* a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Sprite*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITE_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::SpriteRenderer* get_spriteRenderer_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::SpriteRenderer*(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SPRITERENDERER_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_spriteRenderer_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::SpriteRenderer* a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::SpriteRenderer*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SPRITERENDERER_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Boolean get_useMeshMaterialIndex_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHMATERIALINDEX_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_useMeshMaterialIndex_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHMATERIALINDEX_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Int32 get_meshMaterialIndex_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Int32(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHMATERIALINDEX_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_meshMaterialIndex_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Int32 a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHMATERIALINDEX_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Boolean get_useMeshColors_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_USEMESHCOLORS_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_useMeshColors_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_USEMESHCOLORS_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_normalOffset_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_NORMALOFFSET_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_normalOffset_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_NORMALOFFSET_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::ParticleSystemShapeMultiModeValue get_meshSpawnMode_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::ParticleSystemShapeMultiModeValue(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNMODE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_meshSpawnMode_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystemShapeMultiModeValue a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystemShapeMultiModeValue))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNMODE_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_meshSpawnSpread_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPREAD_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_meshSpawnSpread_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPREAD_INJECTED_OFFSET))(a1, a2);
		}

		/*
		static ::System::Void get_meshSpawnSpeed_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEED_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_meshSpawnSpeed_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEED_INJECTED_OFFSET))(a1, a2);
		}
		*/

		static ::System::Single get_meshSpawnSpeedMultiplier_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_MESHSPAWNSPEEDMULTIPLIER_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_meshSpawnSpeedMultiplier_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_MESHSPAWNSPEEDMULTIPLIER_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_arc_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARC_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_arc_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARC_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::ParticleSystemShapeMultiModeValue get_arcMode_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::ParticleSystemShapeMultiModeValue(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCMODE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_arcMode_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystemShapeMultiModeValue a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystemShapeMultiModeValue))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCMODE_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_arcSpread_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPREAD_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_arcSpread_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPREAD_INJECTED_OFFSET))(a1, a2);
		}

		/*
		static ::System::Void get_arcSpeed_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEED_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_arcSpeed_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEED_INJECTED_OFFSET))(a1, a2);
		}
		*/

		static ::System::Single get_arcSpeedMultiplier_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ARCSPEEDMULTIPLIER_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_arcSpeedMultiplier_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ARCSPEEDMULTIPLIER_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Single get_donutRadius_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Single(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_DONUTRADIUS_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_donutRadius_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_DONUTRADIUS_INJECTED_OFFSET))(a1, a2);
		}

		/*
		static ::System::Void get_position_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_POSITION_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_position_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_POSITION_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void get_rotation_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_ROTATION_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_rotation_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_ROTATION_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void get_scale_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_SCALE_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_scale_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Vector3& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_SCALE_INJECTED_OFFSET))(a1, a2);
		}
		*/

		static ::UnityEngine::Texture2D* get_texture_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::Texture2D*(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURE_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_texture_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::Texture2D* a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::Texture2D*))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURE_INJECTED_OFFSET))(a1, a2);
		}

		static ::UnityEngine::ParticleSystemShapeTextureChannel get_textureClipChannel_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::UnityEngine::ParticleSystemShapeTextureChannel(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPCHANNEL_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_textureClipChannel_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystemShapeTextureChannel a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystemShapeTextureChannel))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPCHANNEL_INJECTED_OFFSET))(a1, a2);
		}

		/*
		static ::System::Void get_textureClipThresholdMin_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMIN_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_textureClipThresholdMin_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMIN_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void get_textureClipThresholdMax_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECLIPTHRESHOLDMAX_INJECTED_OFFSET))(a1, a2);
		}
		*/

		/*
		static ::System::Void set_textureClipThresholdMax_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::UnityEngine::ParticleSystem_MinMaxCurve& a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::UnityEngine::ParticleSystem_MinMaxCurve&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECLIPTHRESHOLDMAX_INJECTED_OFFSET))(a1, a2);
		}
		*/

		static ::System::Boolean get_textureColorAffectsParticles_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTURECOLORAFFECTSPARTICLES_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_textureColorAffectsParticles_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTURECOLORAFFECTSPARTICLES_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Boolean get_textureAlphaAffectsParticles_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREALPHAAFFECTSPARTICLES_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_textureAlphaAffectsParticles_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREALPHAAFFECTSPARTICLES_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Boolean get_textureBilinearFiltering_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Boolean(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREBILINEARFILTERING_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_textureBilinearFiltering_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREBILINEARFILTERING_INJECTED_OFFSET))(a1, a2);
		}

		static ::System::Int32 get_textureUVChannel_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1)
		{
			return ((::System::Int32(*)(::UnityEngine::ParticleSystem_ShapeModule&))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_GET_TEXTUREUVCHANNEL_INJECTED_OFFSET))(a1);
		}

		static ::System::Void set_textureUVChannel_Injected(::UnityEngine::ParticleSystem_ShapeModule& a1, ::System::Int32 a2)
		{
			return ((::System::Void(*)(::UnityEngine::ParticleSystem_ShapeModule&, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_PARTICLESYSTEM_SHAPEMODULE_SET_TEXTUREUVCHANNEL_INJECTED_OFFSET))(a1, a2);
		}
	};
}
