#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/UnityEngine/Bounds.h"
#include "unitysdk/UnityEngine/GfxBufferTarget.h"
#include "unitysdk/UnityEngine/Renderer.h"
#include "unitysdk/UnityEngine/SkinQuality.h"
#include "unitysdk/UnityEngine/Vector3.h"

namespace UnityEngine { class Mesh; }
namespace UnityEngine { class Transform; }

#define UNITYENGINE_SKINNEDMESHRENDERER_BAKEMESH_OFFSET UNITYSDK_OFFSET(0x1D05B180)
#define UNITYENGINE_SKINNEDMESHRENDERER_CLEARANDRESERVEBONES_OFFSET UNITYSDK_OFFSET(0x1D05B190)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETBLENDSHAPEWEIGHT_OFFSET UNITYSDK_OFFSET(0x1D05B160)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETLOCALAABB_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D05B200)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETLOCALAABB_OFFSET UNITYSDK_OFFSET(0x1D05B1B0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETMATERIALENABLED_OFFSET UNITYSDK_OFFSET(0x1D05B420)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETPREVIOUSVERTEXBUFFERIDIMPL_OFFSET UNITYSDK_OFFSET(0x1D05B3A0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETPREVIOUSVERTEXBUFFERID_OFFSET UNITYSDK_OFFSET(0x1D05B330)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETVERTEXBUFFERIDIMPL_OFFSET UNITYSDK_OFFSET(0x1D05B320)
#define UNITYENGINE_SKINNEDMESHRENDERER_GETVERTEXBUFFERID_OFFSET UNITYSDK_OFFSET(0x1D05B2B0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_BONES_OFFSET UNITYSDK_OFFSET(0x1D05B100)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_BOUNDEXPANDINGSCALE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D05B560)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_BOUNDEXPANDINGSCALE_OFFSET UNITYSDK_OFFSET(0x1D05B510)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_DISABLEGPUSKIN_OFFSET UNITYSDK_OFFSET(0x1D05B590)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_ENABLEGPUSKINNINGMAXCOUNT_OFFSET UNITYSDK_OFFSET(0x1D05B4D0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_ENABLESKINNING_OFFSET UNITYSDK_OFFSET(0x1D05B450)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_FORCEMATRIXRECALCULATIONPERRENDER_OFFSET UNITYSDK_OFFSET(0x1D05B0C0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_GPUSKINNINGMAXCOUNT_OFFSET UNITYSDK_OFFSET(0x1D05B4F0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_LAZYUPDATE_OFFSET UNITYSDK_OFFSET(0x1D05B470)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_LOCALBOUNDS_OFFSET UNITYSDK_OFFSET(0x1D05B230)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_QUALITY_OFFSET UNITYSDK_OFFSET(0x1D05B080)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_ROOTBONELOCOPTIMIZETHRESHOLD_OFFSET UNITYSDK_OFFSET(0x1D05B490)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_ROOTBONE_OFFSET UNITYSDK_OFFSET(0x1D05B0E0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_SHAREDMESH_OFFSET UNITYSDK_OFFSET(0x1D05B120)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_SKINNEDMOTIONVECTORS_OFFSET UNITYSDK_OFFSET(0x1D05B140)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_UPDATEWHENOFFSCREEN_OFFSET UNITYSDK_OFFSET(0x1D05B0A0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_USEOPTIMIZEDANIMATIONSKINNINGROOT_OFFSET UNITYSDK_OFFSET(0x1D05B4B0)
#define UNITYENGINE_SKINNEDMESHRENDERER_GET_VERTEXBUFFERTARGET_OFFSET UNITYSDK_OFFSET(0x1D05B430)
#define UNITYENGINE_SKINNEDMESHRENDERER_MARKALLSKINNEDMESHVERTEXDIRTY_OFFSET UNITYSDK_OFFSET(0x1D05B3B0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETBLENDSHAPEWEIGHT_OFFSET UNITYSDK_OFFSET(0x1D05B170)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETBONESATINDEX_OFFSET UNITYSDK_OFFSET(0x1D05B1A0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETLOCALAABB_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D05B220)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETLOCALAABB_OFFSET UNITYSDK_OFFSET(0x1D05B210)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETMATERIALENABLED_OFFSET UNITYSDK_OFFSET(0x1D05B410)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETOVERRIDEBOUNDS_OFFSET UNITYSDK_OFFSET(0x1D05B3E0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETOVERRIDEWORLDAABB_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D05B3D0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SETOVERRIDEWORLDAABB_OFFSET UNITYSDK_OFFSET(0x1D05B3C0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_BONES_OFFSET UNITYSDK_OFFSET(0x1D05B110)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_BOUNDEXPANDINGSCALE_INJECTED_OFFSET UNITYSDK_OFFSET(0x1D05B580)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_BOUNDEXPANDINGSCALE_OFFSET UNITYSDK_OFFSET(0x1D05B570)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_DISABLEGPUSKIN_OFFSET UNITYSDK_OFFSET(0x1D05B5A0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_ENABLEGPUSKINNINGMAXCOUNT_OFFSET UNITYSDK_OFFSET(0x1D05B4E0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_ENABLESKINNING_OFFSET UNITYSDK_OFFSET(0x1D05B460)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_FORCEMATRIXRECALCULATIONPERRENDER_OFFSET UNITYSDK_OFFSET(0x1D05B0D0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_GPUSKINNINGMAXCOUNT_OFFSET UNITYSDK_OFFSET(0x1D05B500)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_LAZYUPDATE_OFFSET UNITYSDK_OFFSET(0x1D05B480)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_LOCALBOUNDS_OFFSET UNITYSDK_OFFSET(0x1D05B280)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_QUALITY_OFFSET UNITYSDK_OFFSET(0x1D05B090)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_ROOTBONELOCOPTIMIZETHRESHOLD_OFFSET UNITYSDK_OFFSET(0x1D05B4A0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_ROOTBONE_OFFSET UNITYSDK_OFFSET(0x1D05B0F0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_SHAREDMESH_OFFSET UNITYSDK_OFFSET(0x1D05B130)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_SKINNEDMOTIONVECTORS_OFFSET UNITYSDK_OFFSET(0x1D05B150)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_UPDATEWHENOFFSCREEN_OFFSET UNITYSDK_OFFSET(0x1D05B0B0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_USEOPTIMIZEDANIMATIONSKINNINGROOT_OFFSET UNITYSDK_OFFSET(0x1D05B4C0)
#define UNITYENGINE_SKINNEDMESHRENDERER_SET_VERTEXBUFFERTARGET_OFFSET UNITYSDK_OFFSET(0x1D05B440)
#define UNITYENGINE_SKINNEDMESHRENDERER__CTOR_OFFSET UNITYSDK_OFFSET(0x1D05B5B0)

namespace UnityEngine
{
	inline static constexpr unsigned int SkinnedMeshRenderer_TypeDefinitionIndex = 4173;

	class SkinnedMeshRenderer : public ::UnityEngine::Renderer
	{
	public:
		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER__CTOR_OFFSET))(this);
		}

		::UnityEngine::SkinQuality get_quality()
		{
			return ((::UnityEngine::SkinQuality(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_QUALITY_OFFSET))(this);
		}

		::System::Void set_quality(::UnityEngine::SkinQuality a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::SkinQuality))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_QUALITY_OFFSET))(this, a1);
		}

		::System::Boolean get_updateWhenOffscreen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_UPDATEWHENOFFSCREEN_OFFSET))(this);
		}

		::System::Void set_updateWhenOffscreen(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_UPDATEWHENOFFSCREEN_OFFSET))(this, a1);
		}

		::System::Boolean get_forceMatrixRecalculationPerRender()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_FORCEMATRIXRECALCULATIONPERRENDER_OFFSET))(this);
		}

		::System::Void set_forceMatrixRecalculationPerRender(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_FORCEMATRIXRECALCULATIONPERRENDER_OFFSET))(this, a1);
		}

		::UnityEngine::Transform* get_rootBone()
		{
			return ((::UnityEngine::Transform*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_ROOTBONE_OFFSET))(this);
		}

		::System::Void set_rootBone(::UnityEngine::Transform* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Transform*))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_ROOTBONE_OFFSET))(this, a1);
		}

		::Il2CppArray<::UnityEngine::Transform*>* get_bones()
		{
			return ((::Il2CppArray<::UnityEngine::Transform*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_BONES_OFFSET))(this);
		}

		::System::Void set_bones(::Il2CppArray<::UnityEngine::Transform*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::UnityEngine::Transform*>*))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_BONES_OFFSET))(this, a1);
		}

		::UnityEngine::Mesh* get_sharedMesh()
		{
			return ((::UnityEngine::Mesh*(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_SHAREDMESH_OFFSET))(this);
		}

		::System::Void set_sharedMesh(::UnityEngine::Mesh* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Mesh*))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_SHAREDMESH_OFFSET))(this, a1);
		}

		::System::Boolean get_skinnedMotionVectors()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_SKINNEDMOTIONVECTORS_OFFSET))(this);
		}

		::System::Void set_skinnedMotionVectors(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_SKINNEDMOTIONVECTORS_OFFSET))(this, a1);
		}

		::System::Single GetBlendShapeWeight(::System::Int32 a1)
		{
			return ((::System::Single(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETBLENDSHAPEWEIGHT_OFFSET))(this, a1);
		}

		::System::Void SetBlendShapeWeight(::System::Int32 a1, ::System::Single a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETBLENDSHAPEWEIGHT_OFFSET))(this, a1, a2);
		}

		::System::Void BakeMesh(::UnityEngine::Mesh* a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Mesh*))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_BAKEMESH_OFFSET))(this, a1);
		}

		::System::Void ClearAndReserveBones(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_CLEARANDRESERVEBONES_OFFSET))(this, a1);
		}

		::System::Void SetBonesAtIndex(::System::Int32 a1, ::UnityEngine::Transform* a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::UnityEngine::Transform*, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETBONESATINDEX_OFFSET))(this, a1, a2, a3);
		}

		::UnityEngine::Bounds GetLocalAABB()
		{
			return ((::UnityEngine::Bounds(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETLOCALAABB_OFFSET))(this);
		}

		::System::Void SetLocalAABB(::UnityEngine::Bounds a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Bounds))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETLOCALAABB_OFFSET))(this, a1);
		}

		::UnityEngine::Bounds get_localBounds()
		{
			return ((::UnityEngine::Bounds(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_LOCALBOUNDS_OFFSET))(this);
		}

		::System::Void set_localBounds(::UnityEngine::Bounds a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Bounds))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_LOCALBOUNDS_OFFSET))(this, a1);
		}

		::System::UInt64 GetVertexBufferID()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETVERTEXBUFFERID_OFFSET))(this);
		}

		::System::UInt64 GetPreviousVertexBufferID()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETPREVIOUSVERTEXBUFFERID_OFFSET))(this);
		}

		::System::UInt64 GetVertexBufferIDImpl()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETVERTEXBUFFERIDIMPL_OFFSET))(this);
		}

		::System::UInt64 GetPreviousVertexBufferIDImpl()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETPREVIOUSVERTEXBUFFERIDIMPL_OFFSET))(this);
		}

		static ::System::Void MarkAllSkinnedMeshVertexDirty()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_MARKALLSKINNEDMESHVERTEXDIRTY_OFFSET))();
		}

		::System::Void SetOverrideWorldAABB(::System::Boolean a1, ::UnityEngine::Bounds a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::UnityEngine::Bounds))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETOVERRIDEWORLDAABB_OFFSET))(this, a1, a2);
		}

		::System::Void SetOverrideBounds(::System::Boolean a1, ::UnityEngine::Bounds a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::UnityEngine::Bounds))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETOVERRIDEBOUNDS_OFFSET))(this, a1, a2);
		}

		::System::Void SetMaterialEnabled(::System::Int32 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETMATERIALENABLED_OFFSET))(this, a1, a2);
		}

		::System::Boolean GetMaterialEnabled(::System::Int32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETMATERIALENABLED_OFFSET))(this, a1);
		}

		::UnityEngine::GfxBufferTarget get_vertexBufferTarget()
		{
			return ((::UnityEngine::GfxBufferTarget(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_VERTEXBUFFERTARGET_OFFSET))(this);
		}

		::System::Void set_vertexBufferTarget(::UnityEngine::GfxBufferTarget a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::GfxBufferTarget))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_VERTEXBUFFERTARGET_OFFSET))(this, a1);
		}

		::System::Boolean get_enableSkinning()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_ENABLESKINNING_OFFSET))(this);
		}

		::System::Void set_enableSkinning(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_ENABLESKINNING_OFFSET))(this, a1);
		}

		::System::Boolean get_lazyUpdate()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_LAZYUPDATE_OFFSET))(this);
		}

		::System::Void set_lazyUpdate(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_LAZYUPDATE_OFFSET))(this, a1);
		}

		static ::System::Single get_rootBoneLocOptimizeThreshold()
		{
			return ((::System::Single(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_ROOTBONELOCOPTIMIZETHRESHOLD_OFFSET))();
		}

		static ::System::Void set_rootBoneLocOptimizeThreshold(::System::Single a1)
		{
			return ((::System::Void(*)(::System::Single))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_ROOTBONELOCOPTIMIZETHRESHOLD_OFFSET))(a1);
		}

		static ::System::Boolean get_useOptimizedAnimationSkinningRoot()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_USEOPTIMIZEDANIMATIONSKINNINGROOT_OFFSET))();
		}

		static ::System::Void set_useOptimizedAnimationSkinningRoot(::System::Boolean a1)
		{
			return ((::System::Void(*)(::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_USEOPTIMIZEDANIMATIONSKINNINGROOT_OFFSET))(a1);
		}

		static ::System::Boolean get_enableGpuSkinningMaxCount()
		{
			return ((::System::Boolean(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_ENABLEGPUSKINNINGMAXCOUNT_OFFSET))();
		}

		static ::System::Void set_enableGpuSkinningMaxCount(::System::Boolean a1)
		{
			return ((::System::Void(*)(::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_ENABLEGPUSKINNINGMAXCOUNT_OFFSET))(a1);
		}

		static ::System::UInt32 get_gpuSkinningMaxCount()
		{
			return ((::System::UInt32(*)())((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_GPUSKINNINGMAXCOUNT_OFFSET))();
		}

		static ::System::Void set_gpuSkinningMaxCount(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::System::UInt32))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_GPUSKINNINGMAXCOUNT_OFFSET))(a1);
		}

		::UnityEngine::Vector3 get_boundExpandingScale()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_BOUNDEXPANDINGSCALE_OFFSET))(this);
		}

		::System::Void set_boundExpandingScale(::UnityEngine::Vector3 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_BOUNDEXPANDINGSCALE_OFFSET))(this, a1);
		}

		::System::Boolean get_disableGPUSkin()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_DISABLEGPUSKIN_OFFSET))(this);
		}

		::System::Void set_disableGPUSkin(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_DISABLEGPUSKIN_OFFSET))(this, a1);
		}

		::System::Void GetLocalAABB_Injected(::UnityEngine::Bounds& a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Bounds&))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GETLOCALAABB_INJECTED_OFFSET))(this, a1);
		}

		::System::Void SetLocalAABB_Injected(::UnityEngine::Bounds& a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Bounds&))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETLOCALAABB_INJECTED_OFFSET))(this, a1);
		}

		::System::Void SetOverrideWorldAABB_Injected(::System::Boolean a1, ::UnityEngine::Bounds& a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::UnityEngine::Bounds&))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SETOVERRIDEWORLDAABB_INJECTED_OFFSET))(this, a1, a2);
		}

		::System::Void get_boundExpandingScale_Injected(::UnityEngine::Vector3& a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_GET_BOUNDEXPANDINGSCALE_INJECTED_OFFSET))(this, a1);
		}

		::System::Void set_boundExpandingScale_Injected(::UnityEngine::Vector3& a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector3&))((::PBYTE)hIl2Cpp + UNITYENGINE_SKINNEDMESHRENDERER_SET_BOUNDEXPANDINGSCALE_INJECTED_OFFSET))(this, a1);
		}
	};
}
