#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/LittleGame/ChenLingFes/GameDayState.h"
#include "unitysdk/Sofa/BaseViewModel.h"

class Class_1_43BD383C98B4C0C5_225;
class Class_1_43BD383C98B4C0C5_226;
class Class_1_43BD383C98B4C0C5_227;
class Class_1_50AC12A2F890597C;
class Class_1_5F4D64A4B97E38F9;
class Class_1_ED45DA203CB525FD_1;
namespace RPG::Client::ChenLingFes { class ChenLingFesGameplayGameWeekViewModel; }
namespace System { class String; }

#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_CREATE_OFFSET UNITYSDK_OFFSET(0xC09A810)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYCOUNTDOWNPROGRESS_OFFSET UNITYSDK_OFFSET(0xC09A640)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYCOUNTDOWN_OFFSET UNITYSDK_OFFSET(0xC09A5E0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYINDEX_OFFSET UNITYSDK_OFFSET(0xC09BAA0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYPROGRESS_OFFSET UNITYSDK_OFFSET(0xC09A490)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTGAMEDAYSTATE_OFFSET UNITYSDK_OFFSET(0xC09B450)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTWEEKINDEX_OFFSET UNITYSDK_OFFSET(0xC09BA60)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_GAMEWEEKVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xC09BA40)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISENDLESSMODE_OFFSET UNITYSDK_OFFSET(0xC099D10)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISSHOWNEXTGROUPCHENLINGCOUNT_OFFSET UNITYSDK_OFFSET(0xC09B970)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISSHOWOPENING_OFFSET UNITYSDK_OFFSET(0xC09A5A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISSHOWPREPARE_OFFSET UNITYSDK_OFFSET(0xC09B8A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_NEXTGROUPCHENLINGCOUNT_OFFSET UNITYSDK_OFFSET(0xC09A560)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_STAR_OFFSET UNITYSDK_OFFSET(0xC09A520)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_TEXTCURGAMEDAY_OFFSET UNITYSDK_OFFSET(0xC09A320)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_TEXTCURGAMEWEEK_OFFSET UNITYSDK_OFFSET(0xC09A130)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_CURRENTDAYINDEX_OFFSET UNITYSDK_OFFSET(0xC09B6F0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_CURRENTWEEKINDEX_OFFSET UNITYSDK_OFFSET(0xC09B5D0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_GAMEWEEKVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xC09BA50)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_ISSHOWNEXTGROUPCHENLINGCOUNT_OFFSET UNITYSDK_OFFSET(0xC09B8E0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_ISSHOWOPENING_OFFSET UNITYSDK_OFFSET(0xC09B4B0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_ISSHOWPREPARE_OFFSET UNITYSDK_OFFSET(0xC09B540)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_NEXTGROUPCHENLINGCOUNT_OFFSET UNITYSDK_OFFSET(0xC09B9B0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_STAR_OFFSET UNITYSDK_OFFSET(0xC09B810)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xC09A9B0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__INIT_OFFSET UNITYSDK_OFFSET(0xC09AA60)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSCOREUPDATEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC09B310)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYMESSAGE_OFFSET UNITYSDK_OFFSET(0xC09B270)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYSTATEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC09B220)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHWEEKMESSAGE_OFFSET UNITYSDK_OFFSET(0xC09B2C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__SUBSCRIBEMESSAGES_OFFSET UNITYSDK_OFFSET(0xC09B080)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__SYNCGAMELOOPDATA_OFFSET UNITYSDK_OFFSET(0xC09AAB0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__SYNCSCOREINFO_OFFSET UNITYSDK_OFFSET(0xC09B360)

namespace RPG::Client::ChenLingFes
{
	inline static constexpr unsigned int ChenLingFesGameplayProgressInfoViewModel_TypeDefinitionIndex = 76421;

	class ChenLingFesGameplayProgressInfoViewModel : public ::Sofa::BaseViewModel
	{
	public:
		::RPG::Client::ChenLingFes::ChenLingFesGameplayGameWeekViewModel* _GameWeekViewModel_k__BackingField; // 0x20
		::Class_1_50AC12A2F890597C* _GameplayBridge; // 0x28
		::Class_1_5F4D64A4B97E38F9* _Messenger; // 0x30
		::Il2CppArray<::System::Single>* _DayProgress; // 0x38
		::System::Single _CountDownRatio; // 0x40
		::System::Int32 _Star; // 0x44
		::System::Boolean _IsShowPrepare; // 0x48
		::System::Boolean _IsShowNextGroupChenLingCount; // 0x49
		::System::Boolean _IsShowOpening; // 0x4A
		::System::Int32 _CurrentDayIndex; // 0x4C
		::System::Int32 _NextGroupChenLingCount; // 0x50
		::System::Int32 _CurrentWeekIndex; // 0x54

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::ChenLingFes::ChenLingFesGameplayProgressInfoViewModel* Create(::Class_1_50AC12A2F890597C* a1, ::Class_1_5F4D64A4B97E38F9* a2)
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplayProgressInfoViewModel*(*)(::Class_1_50AC12A2F890597C*, ::Class_1_5F4D64A4B97E38F9*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_CREATE_OFFSET))(a1, a2);
		}

		::System::Void _Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__INIT_OFFSET))(this);
		}

		::System::Void _SubscribeMessages()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__SUBSCRIBEMESSAGES_OFFSET))(this);
		}

		::System::Void _OnChenLingFesGameplaySwitchDayStateMessage(::Class_1_43BD383C98B4C0C5_226* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_226*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYSTATEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplaySwitchDayMessage(::Class_1_43BD383C98B4C0C5_225* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_225*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplaySwitchWeekMessage(::Class_1_43BD383C98B4C0C5_227* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_227*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHWEEKMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplayScoreUpdateMessage(::Class_1_ED45DA203CB525FD_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_ED45DA203CB525FD_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSCOREUPDATEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _SyncGameLoopData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__SYNCGAMELOOPDATA_OFFSET))(this);
		}

		::System::Void _SyncScoreInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL__SYNCSCOREINFO_OFFSET))(this);
		}

		::RPG::Client::ChenLingFes::ChenLingFesGameplayGameWeekViewModel* get_GameWeekViewModel()
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplayGameWeekViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_GAMEWEEKVIEWMODEL_OFFSET))(this);
		}

		::System::Void set_GameWeekViewModel(::RPG::Client::ChenLingFes::ChenLingFesGameplayGameWeekViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayGameWeekViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_GAMEWEEKVIEWMODEL_OFFSET))(this, a1);
		}

		::RPG::Client::LittleGame::ChenLingFes::GameDayState get_CurrentGameDayState()
		{
			return ((::RPG::Client::LittleGame::ChenLingFes::GameDayState(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTGAMEDAYSTATE_OFFSET))(this);
		}

		::System::String* get_TextCurGameWeek()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_TEXTCURGAMEWEEK_OFFSET))(this);
		}

		::System::String* get_TextCurGameDay()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_TEXTCURGAMEDAY_OFFSET))(this);
		}

		::System::Boolean get_IsShowPrepare()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISSHOWPREPARE_OFFSET))(this);
		}

		::System::Void set_IsShowPrepare(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_ISSHOWPREPARE_OFFSET))(this, a1);
		}

		::System::Boolean get_IsShowOpening()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISSHOWOPENING_OFFSET))(this);
		}

		::System::Void set_IsShowOpening(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_ISSHOWOPENING_OFFSET))(this, a1);
		}

		::System::Boolean get_IsShowNextGroupChenLingCount()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISSHOWNEXTGROUPCHENLINGCOUNT_OFFSET))(this);
		}

		::System::Void set_IsShowNextGroupChenLingCount(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_ISSHOWNEXTGROUPCHENLINGCOUNT_OFFSET))(this, a1);
		}

		::System::Int32 get_NextGroupChenLingCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_NEXTGROUPCHENLINGCOUNT_OFFSET))(this);
		}

		::System::Void set_NextGroupChenLingCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_NEXTGROUPCHENLINGCOUNT_OFFSET))(this, a1);
		}

		::System::Int32 get_CurrentWeekIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTWEEKINDEX_OFFSET))(this);
		}

		::System::Void set_CurrentWeekIndex(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_CURRENTWEEKINDEX_OFFSET))(this, a1);
		}

		::System::Int32 get_CurrentDayIndex()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYINDEX_OFFSET))(this);
		}

		::System::Void set_CurrentDayIndex(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_CURRENTDAYINDEX_OFFSET))(this, a1);
		}

		::System::Single get_CurrentDayProgress()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYPROGRESS_OFFSET))(this);
		}

		::System::Int32 get_Star()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_STAR_OFFSET))(this);
		}

		::System::Void set_Star(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_SET_STAR_OFFSET))(this, a1);
		}

		::System::Int32 get_CurrentDayCountdown()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYCOUNTDOWN_OFFSET))(this);
		}

		::System::Single get_CurrentDayCountdownProgress()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_CURRENTDAYCOUNTDOWNPROGRESS_OFFSET))(this);
		}

		::System::Boolean get_IsEndlessMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYPROGRESSINFOVIEWMODEL_GET_ISENDLESSMODE_OFFSET))(this);
		}
	};
}
