#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Sofa/BaseViewModel.h"

class Class_1_43BD383C98B4C0C5_227;
class Class_1_50AC12A2F890597C;
class Class_1_5F4D64A4B97E38F9;
class Class_1_ED45DA203CB525FD_1;
namespace RPG::Client::ChenLingFes { class ChenLingFesGameplayScoreItemViewModel; }
namespace Sofa::Core { template <typename T> class ObservableList_1; }

#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_CREATE_OFFSET UNITYSDK_OFFSET(0xC0A02A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_CURSCORE_OFFSET UNITYSDK_OFFSET(0xC0A15F0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ENDLESSCURRENTSCORE_OFFSET UNITYSDK_OFFSET(0xC0A1750)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ENDLESSPROGRESS_OFFSET UNITYSDK_OFFSET(0xC0A1A40)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ENDLESSTARGETSCORE_OFFSET UNITYSDK_OFFSET(0xC0A1790)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ISENDLESSMODE_OFFSET UNITYSDK_OFFSET(0xC0A0040)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ISENDLESSTARGETSCOREFINISH_OFFSET UNITYSDK_OFFSET(0xC0A0080)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_SCOREITEMS_OFFSET UNITYSDK_OFFSET(0xC0A1A20)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_CURSCORE_OFFSET UNITYSDK_OFFSET(0xC0A1580)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ENDLESSCURRENTSCORE_OFFSET UNITYSDK_OFFSET(0xC0A1630)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ENDLESSPROGRESS_OFFSET UNITYSDK_OFFSET(0xC0A17D0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ENDLESSTARGETSCORE_OFFSET UNITYSDK_OFFSET(0xC0A16C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ISENDLESSMODE_OFFSET UNITYSDK_OFFSET(0xC0A1450)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ISENDLESSTARGETSCOREFINISH_OFFSET UNITYSDK_OFFSET(0xC0A1870)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_SCOREITEMS_OFFSET UNITYSDK_OFFSET(0xC0A1A30)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xC0A0470)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__INITSCOREITEMS_OFFSET UNITYSDK_OFFSET(0xC0A0590)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__INIT_OFFSET UNITYSDK_OFFSET(0xC0A0530)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSCOREUPDATEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A14E0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHWEEKMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A1530)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__SUBSCRIBEMESSAGES_OFFSET UNITYSDK_OFFSET(0xC0A1280)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__SYNCSCOREINFO_OFFSET UNITYSDK_OFFSET(0xC0A0880)

namespace RPG::Client::ChenLingFes
{
	inline static constexpr unsigned int ChenLingFesGameplayScoreInfoViewModel_TypeDefinitionIndex = 76425;

	class ChenLingFesGameplayScoreInfoViewModel : public ::Sofa::BaseViewModel
	{
	public:
		::Class_1_5F4D64A4B97E38F9* _Messenger; // 0x20
		::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreItemViewModel*>* _ScoreItems_k__BackingField; // 0x28
		::Class_1_50AC12A2F890597C* _GameplayBridge; // 0x30
		::System::Int32 _CurScore; // 0x38
		::System::Int32 _EndlessCurrentScore; // 0x3C
		::System::Single _EndlessProgress; // 0x40
		::System::Boolean _IsEndlessTargetScoreFinish; // 0x44
		::System::Boolean _IsEndlessMode; // 0x45
		::System::Int32 _EndlessTargetScore; // 0x48

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreInfoViewModel* Create(::Class_1_50AC12A2F890597C* a1, ::Class_1_5F4D64A4B97E38F9* a2)
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreInfoViewModel*(*)(::Class_1_50AC12A2F890597C*, ::Class_1_5F4D64A4B97E38F9*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_CREATE_OFFSET))(a1, a2);
		}

		::System::Void _Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__INIT_OFFSET))(this);
		}

		::System::Void _InitScoreItems()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__INITSCOREITEMS_OFFSET))(this);
		}

		::System::Void _SubscribeMessages()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__SUBSCRIBEMESSAGES_OFFSET))(this);
		}

		::System::Void _OnChenLingFesGameplayScoreUpdateMessage(::Class_1_ED45DA203CB525FD_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_ED45DA203CB525FD_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSCOREUPDATEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplaySwitchWeekMessage(::Class_1_43BD383C98B4C0C5_227* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_227*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHWEEKMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _SyncScoreInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL__SYNCSCOREINFO_OFFSET))(this);
		}

		::System::Int32 get_CurScore()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_CURSCORE_OFFSET))(this);
		}

		::System::Void set_CurScore(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_CURSCORE_OFFSET))(this, a1);
		}

		::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreItemViewModel*>* get_ScoreItems()
		{
			return ((::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreItemViewModel*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_SCOREITEMS_OFFSET))(this);
		}

		::System::Void set_ScoreItems(::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreItemViewModel*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayScoreItemViewModel*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_SCOREITEMS_OFFSET))(this, a1);
		}

		::System::Boolean get_IsEndlessMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ISENDLESSMODE_OFFSET))(this);
		}

		::System::Void set_IsEndlessMode(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ISENDLESSMODE_OFFSET))(this, a1);
		}

		::System::Int32 get_EndlessCurrentScore()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ENDLESSCURRENTSCORE_OFFSET))(this);
		}

		::System::Void set_EndlessCurrentScore(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ENDLESSCURRENTSCORE_OFFSET))(this, a1);
		}

		::System::Int32 get_EndlessTargetScore()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ENDLESSTARGETSCORE_OFFSET))(this);
		}

		::System::Void set_EndlessTargetScore(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ENDLESSTARGETSCORE_OFFSET))(this, a1);
		}

		::System::Boolean get_IsEndlessTargetScoreFinish()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ISENDLESSTARGETSCOREFINISH_OFFSET))(this);
		}

		::System::Void set_IsEndlessTargetScoreFinish(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ISENDLESSTARGETSCOREFINISH_OFFSET))(this, a1);
		}

		::System::Single get_EndlessProgress()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_GET_ENDLESSPROGRESS_OFFSET))(this);
		}

		::System::Void set_EndlessProgress(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSCOREINFOVIEWMODEL_SET_ENDLESSPROGRESS_OFFSET))(this, a1);
		}
	};
}
