#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Sofa/BaseViewModel.h"

namespace System { class String; }

#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_CURSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xC08BFB0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ENDLESSNUMUNIT_OFFSET UNITYSDK_OFFSET(0xC08C0B0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ENDLESSNUM_OFFSET UNITYSDK_OFFSET(0xC08C090)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_FINISHSTARREQUIREMENT_OFFSET UNITYSDK_OFFSET(0xC08C010)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ISENDLESSMODE_OFFSET UNITYSDK_OFFSET(0xC08C070)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ISTOTALRECORD_OFFSET UNITYSDK_OFFSET(0xC08C050)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_REQUIREDSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xC08BFF0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_SCORE_OFFSET UNITYSDK_OFFSET(0xC08C030)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_TITLE_OFFSET UNITYSDK_OFFSET(0xC08BF90)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_TOTALSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xC08BFD0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_CURSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xC08BFC0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ENDLESSNUMUNIT_OFFSET UNITYSDK_OFFSET(0xC08C0C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ENDLESSNUM_OFFSET UNITYSDK_OFFSET(0xC08C0A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_FINISHSTARREQUIREMENT_OFFSET UNITYSDK_OFFSET(0xC08C020)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ISENDLESSMODE_OFFSET UNITYSDK_OFFSET(0xC08C080)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ISTOTALRECORD_OFFSET UNITYSDK_OFFSET(0xC08C060)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_REQUIREDSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xC08C000)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_SCORE_OFFSET UNITYSDK_OFFSET(0xC08C040)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_TITLE_OFFSET UNITYSDK_OFFSET(0xC08BFA0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_TOTALSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xC08BFE0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xC0893F0)

namespace RPG::Client::ChenLingFes
{
	inline static constexpr unsigned int ChenLingFesGameSettleRecordItemViewModel_TypeDefinitionIndex = 76441;

	class ChenLingFesGameSettleRecordItemViewModel : public ::Sofa::BaseViewModel
	{
	public:
		::System::String* _EndlessNumUnit_k__BackingField; // 0x20
		::System::String* _Title_k__BackingField; // 0x28
		::System::Int32 _TotalStarCount_k__BackingField; // 0x30
		::System::Int32 _EndlessNum_k__BackingField; // 0x34
		::System::Int32 _Score_k__BackingField; // 0x38
		::System::Int32 _CurStarCount_k__BackingField; // 0x3C
		::System::Int32 _RequiredStarCount_k__BackingField; // 0x40
		::System::Boolean _IsEndlessMode_k__BackingField; // 0x44
		::System::Boolean _IsTotalRecord_k__BackingField; // 0x45
		::System::Boolean _FinishStarRequirement_k__BackingField; // 0x46

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL__CTOR_OFFSET))(this);
		}

		::System::String* get_Title()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_TITLE_OFFSET))(this);
		}

		::System::Void set_Title(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_TITLE_OFFSET))(this, a1);
		}

		::System::Int32 get_CurStarCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_CURSTARCOUNT_OFFSET))(this);
		}

		::System::Void set_CurStarCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_CURSTARCOUNT_OFFSET))(this, a1);
		}

		::System::Int32 get_TotalStarCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_TOTALSTARCOUNT_OFFSET))(this);
		}

		::System::Void set_TotalStarCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_TOTALSTARCOUNT_OFFSET))(this, a1);
		}

		::System::Int32 get_RequiredStarCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_REQUIREDSTARCOUNT_OFFSET))(this);
		}

		::System::Void set_RequiredStarCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_REQUIREDSTARCOUNT_OFFSET))(this, a1);
		}

		::System::Boolean get_FinishStarRequirement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_FINISHSTARREQUIREMENT_OFFSET))(this);
		}

		::System::Void set_FinishStarRequirement(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_FINISHSTARREQUIREMENT_OFFSET))(this, a1);
		}

		::System::Int32 get_Score()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_SCORE_OFFSET))(this);
		}

		::System::Void set_Score(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_SCORE_OFFSET))(this, a1);
		}

		::System::Boolean get_IsTotalRecord()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ISTOTALRECORD_OFFSET))(this);
		}

		::System::Void set_IsTotalRecord(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ISTOTALRECORD_OFFSET))(this, a1);
		}

		::System::Boolean get_IsEndlessMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ISENDLESSMODE_OFFSET))(this);
		}

		::System::Void set_IsEndlessMode(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ISENDLESSMODE_OFFSET))(this, a1);
		}

		::System::Int32 get_EndlessNum()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ENDLESSNUM_OFFSET))(this);
		}

		::System::Void set_EndlessNum(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ENDLESSNUM_OFFSET))(this, a1);
		}

		::System::String* get_EndlessNumUnit()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_GET_ENDLESSNUMUNIT_OFFSET))(this);
		}

		::System::Void set_EndlessNumUnit(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMESETTLERECORDITEMVIEWMODEL_SET_ENDLESSNUMUNIT_OFFSET))(this, a1);
		}
	};
}
