#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/Sofa/BaseViewModel.h"

class Class_1_3692E67E590B5BD6;
class Class_1_43BD383C98B4C0C5_200;
class Class_1_43BD383C98B4C0C5_201;
class Class_1_43BD383C98B4C0C5_223;
class Class_1_43BD383C98B4C0C5_225;
class Class_1_43BD383C98B4C0C5_226;
class Class_1_43BD383C98B4C0C5_227;
class Class_1_50AC12A2F890597C;
class Class_1_5F4D64A4B97E38F9;
class Class_1_7550321EC955956C;
class Class_1_83665B095F1535B5_28;
namespace RPG::Client::ChenLingFes { class ChenLingFesGameplayItemViewModel; }
namespace RPG::Client::ChenLingFes { class ChenLingFesGameplayOperateItemViewModel; }
namespace Sofa::Core { class SimpleCommand; }
namespace Sofa::Core { template <typename T> class ObservableList_1; }
template <typename T> class Class_1_BF01A723AB4005C0;

#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_CREATE_OFFSET UNITYSDK_OFFSET(0xC0A7690)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CANEXECUTESELECTOPERATION_OFFSET UNITYSDK_OFFSET(0xC0A9B10)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CANREROLLITEM_OFFSET UNITYSDK_OFFSET(0xC0A6EB0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CANSKIPITEM_OFFSET UNITYSDK_OFFSET(0xC0A53F0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKCOLLAPSECOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA560)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKEXPANDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA540)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKREROLLCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA580)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKSKIPCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA5A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_DRAGGINGITEMVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xC0A5FF0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_EXTRACOUNT_OFFSET UNITYSDK_OFFSET(0xC0A6E10)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_GAMEPLAYBRIDGE_OFFSET UNITYSDK_OFFSET(0xC0A3A50)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ISEXPANDED_OFFSET UNITYSDK_OFFSET(0xC0A6260)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ISFORBIDSHOWITEMLIST_OFFSET UNITYSDK_OFFSET(0xC0A95F0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ISVISIBLE_OFFSET UNITYSDK_OFFSET(0xC0A6210)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ITEMREFRESHANIMPLAYEDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA5C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ITEMVIEWMODELS_OFFSET UNITYSDK_OFFSET(0xC0AA5E0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_NEEDPLAYITEMREFRESHANIM_OFFSET UNITYSDK_OFFSET(0xC0A6870)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ONDRAGENDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AAC20)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ONDRAGEXCEEDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AAC40)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ONDRAGSTARTCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AAC00)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_OPERATEITEMVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xC0AA600)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_REROLLCOUNT_OFFSET UNITYSDK_OFFSET(0xC0A6E60)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_REFRESHITEMS_OFFSET UNITYSDK_OFFSET(0xC0A7E70)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CANEXECUTESELECTOPERATION_OFFSET UNITYSDK_OFFSET(0xC0A62C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKCOLLAPSECOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA570)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKEXPANDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA550)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKREROLLCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA590)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKSKIPCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA5B0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_DRAGGINGITEMVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xC0AA9A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_EXTRACOUNT_OFFSET UNITYSDK_OFFSET(0xC0A9DE0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ISEXPANDED_OFFSET UNITYSDK_OFFSET(0xC0A96B0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ISFORBIDSHOWITEMLIST_OFFSET UNITYSDK_OFFSET(0xC0A8C70)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ISVISIBLE_OFFSET UNITYSDK_OFFSET(0xC0A9640)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ITEMREFRESHANIMPLAYEDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AA5D0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ITEMVIEWMODELS_OFFSET UNITYSDK_OFFSET(0xC0AA5F0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_NEEDPLAYITEMREFRESHANIM_OFFSET UNITYSDK_OFFSET(0xC0A9D50)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ONDRAGENDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AAC30)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ONDRAGEXCEEDCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AAC50)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ONDRAGSTARTCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0AAC10)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_OPERATEITEMVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xC0AA610)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_REROLLCOUNT_OFFSET UNITYSDK_OFFSET(0xC0A9E70)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__APPLYDRAGGINGVISUALSTATETOLIST_OFFSET UNITYSDK_OFFSET(0xC0A9FA0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__CLEARSELECTEDITEM_OFFSET UNITYSDK_OFFSET(0xC0A8DB0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xC0A7820)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__EXPANDFORNEWITEMS_OFFSET UNITYSDK_OFFSET(0xC0A8EE0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__INITCOMMANDS_OFFSET UNITYSDK_OFFSET(0xC0A7C70)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__INITDRAGCOMMAND_OFFSET UNITYSDK_OFFSET(0xC0A8730)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__INIT_OFFSET UNITYSDK_OFFSET(0xC0A7900)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYFORCEHIDESELECTMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A8B50)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYITEMREDRAWMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A9060)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYITEMREFRESHMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A8D40)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A8AB0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYSTATEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A88A0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHWEEKSTATEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A8B00)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKCOLLAPSE_OFFSET UNITYSDK_OFFSET(0xC0A9950)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKEXPAND_OFFSET UNITYSDK_OFFSET(0xC0A9740)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKREROLL_OFFSET UNITYSDK_OFFSET(0xC0A9A70)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKSKIP_OFFSET UNITYSDK_OFFSET(0xC0A9BA0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONDRAGEND_OFFSET UNITYSDK_OFFSET(0xC0AA830)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONDRAGEXCEED_OFFSET UNITYSDK_OFFSET(0xC0AA890)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONDRAGSTART_OFFSET UNITYSDK_OFFSET(0xC0AA620)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONITEMOFFEROPCOUNTREFRESH_OFFSET UNITYSDK_OFFSET(0xC0A9120)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONITEMREFRESHANIMPLAYED_OFFSET UNITYSDK_OFFSET(0xC0A9C90)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONITEMSHOWDETAIL_OFFSET UNITYSDK_OFFSET(0xC0A9170)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONSELECTITEMMESSAGE_OFFSET UNITYSDK_OFFSET(0xC0A90D0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__REFRESHITEMOPCOUNT_OFFSET UNITYSDK_OFFSET(0xC0A8500)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__REFRESHVISIBLE_OFFSET UNITYSDK_OFFSET(0xC0A88F0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__SELECTDRAGGINGITEM_OFFSET UNITYSDK_OFFSET(0xC0AA6C0)
#define RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__SUBSCRIBEMESSAGES_OFFSET UNITYSDK_OFFSET(0xC0A7970)

namespace RPG::Client::ChenLingFes
{
	inline static constexpr unsigned int ChenLingFesGameplaySelectPanelViewModel_TypeDefinitionIndex = 76426;

	class ChenLingFesGameplaySelectPanelViewModel : public ::Sofa::BaseViewModel
	{
	public:
		::Sofa::Core::SimpleCommand* _ClickSkipCommand_k__BackingField; // 0x20
		::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* _OnDragEndCommand_k__BackingField; // 0x28
		::RPG::Client::ChenLingFes::ChenLingFesGameplayOperateItemViewModel* _OperateItemViewModel_k__BackingField; // 0x30
		::Sofa::Core::SimpleCommand* _ItemRefreshAnimPlayedCommand_k__BackingField; // 0x38
		::Sofa::Core::SimpleCommand* _ClickCollapseCommand_k__BackingField; // 0x40
		::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* _OnDragStartCommand_k__BackingField; // 0x48
		::Class_1_50AC12A2F890597C* _GameplayBridge; // 0x50
		::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* _ItemViewModels_k__BackingField; // 0x58
		::Sofa::Core::SimpleCommand* _ClickExpandCommand_k__BackingField; // 0x60
		::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* _OnDragExceedCommand_k__BackingField; // 0x68
		::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* _DraggingItemViewModel; // 0x70
		::Class_1_5F4D64A4B97E38F9* _Messenger; // 0x78
		::Sofa::Core::SimpleCommand* _ClickRerollCommand_k__BackingField; // 0x80
		::System::UInt32 _DraggingItemId; // 0x88
		::System::Boolean EnableSkipDoubleConfirm; // 0x8C
		::System::Boolean _CanExecuteSelectOperation; // 0x8D
		::System::Boolean _IsExpanded; // 0x8E
		::System::Boolean _IsForbidShowItemList; // 0x8F
		::System::Int32 _RerollCount; // 0x90
		::System::Boolean _NeedPlayItemRefreshAnim; // 0x94
		::System::Boolean _IsVisible; // 0x95
		::System::Int32 _ExtraCount; // 0x98

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__CTOR_OFFSET))(this);
		}

		static ::RPG::Client::ChenLingFes::ChenLingFesGameplaySelectPanelViewModel* Create(::Class_1_50AC12A2F890597C* a1, ::Class_1_5F4D64A4B97E38F9* a2)
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplaySelectPanelViewModel*(*)(::Class_1_50AC12A2F890597C*, ::Class_1_5F4D64A4B97E38F9*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_CREATE_OFFSET))(a1, a2);
		}

		::System::Void _Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__INIT_OFFSET))(this);
		}

		::System::Void _InitCommands()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__INITCOMMANDS_OFFSET))(this);
		}

		::System::Void _SubscribeMessages()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__SUBSCRIBEMESSAGES_OFFSET))(this);
		}

		::System::Void _OnChenLingFesGameplaySwitchDayStateMessage(::Class_1_43BD383C98B4C0C5_226* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_226*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYSTATEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplaySwitchDayMessage(::Class_1_43BD383C98B4C0C5_225* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_225*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHDAYMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplaySwitchWeekStateMessage(::Class_1_43BD383C98B4C0C5_227* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_227*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYSWITCHWEEKSTATEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplayForceHideSelectMessage(::Class_1_83665B095F1535B5_28* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_83665B095F1535B5_28*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYFORCEHIDESELECTMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplayItemRefreshMessage(::Class_1_43BD383C98B4C0C5_200* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_200*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYITEMREFRESHMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnChenLingFesGameplayItemRedrawMessage(::Class_1_43BD383C98B4C0C5_201* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_201*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCHENLINGFESGAMEPLAYITEMREDRAWMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnSelectItemMessage(::Class_1_3692E67E590B5BD6* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_3692E67E590B5BD6*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONSELECTITEMMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnItemOfferOpCountRefresh(::Class_1_43BD383C98B4C0C5_223* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_43BD383C98B4C0C5_223*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONITEMOFFEROPCOUNTREFRESH_OFFSET))(this, a1);
		}

		::System::Void _OnItemShowDetail(::Class_1_7550321EC955956C* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_7550321EC955956C*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONITEMSHOWDETAIL_OFFSET))(this, a1);
		}

		::System::Void _ClearSelectedItem()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__CLEARSELECTEDITEM_OFFSET))(this);
		}

		::System::Void _RefreshVisible()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__REFRESHVISIBLE_OFFSET))(this);
		}

		::System::Void _ExpandForNewItems()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__EXPANDFORNEWITEMS_OFFSET))(this);
		}

		::System::Void _OnClickExpand()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKEXPAND_OFFSET))(this);
		}

		::System::Void _OnClickCollapse()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKCOLLAPSE_OFFSET))(this);
		}

		::System::Void _OnClickReroll()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKREROLL_OFFSET))(this);
		}

		::System::Void _OnClickSkip()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONCLICKSKIP_OFFSET))(this);
		}

		::System::Void _OnItemRefreshAnimPlayed()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONITEMREFRESHANIMPLAYED_OFFSET))(this);
		}

		::System::Void RefreshItems(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_REFRESHITEMS_OFFSET))(this, a1);
		}

		::System::Void _RefreshItemOpCount()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__REFRESHITEMOPCOUNT_OFFSET))(this);
		}

		::Sofa::Core::SimpleCommand* get_ClickExpandCommand()
		{
			return ((::Sofa::Core::SimpleCommand*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKEXPANDCOMMAND_OFFSET))(this);
		}

		::System::Void set_ClickExpandCommand(::Sofa::Core::SimpleCommand* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::SimpleCommand*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKEXPANDCOMMAND_OFFSET))(this, a1);
		}

		::Sofa::Core::SimpleCommand* get_ClickCollapseCommand()
		{
			return ((::Sofa::Core::SimpleCommand*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKCOLLAPSECOMMAND_OFFSET))(this);
		}

		::System::Void set_ClickCollapseCommand(::Sofa::Core::SimpleCommand* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::SimpleCommand*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKCOLLAPSECOMMAND_OFFSET))(this, a1);
		}

		::Sofa::Core::SimpleCommand* get_ClickRerollCommand()
		{
			return ((::Sofa::Core::SimpleCommand*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKREROLLCOMMAND_OFFSET))(this);
		}

		::System::Void set_ClickRerollCommand(::Sofa::Core::SimpleCommand* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::SimpleCommand*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKREROLLCOMMAND_OFFSET))(this, a1);
		}

		::Sofa::Core::SimpleCommand* get_ClickSkipCommand()
		{
			return ((::Sofa::Core::SimpleCommand*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CLICKSKIPCOMMAND_OFFSET))(this);
		}

		::System::Void set_ClickSkipCommand(::Sofa::Core::SimpleCommand* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::SimpleCommand*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CLICKSKIPCOMMAND_OFFSET))(this, a1);
		}

		::Sofa::Core::SimpleCommand* get_ItemRefreshAnimPlayedCommand()
		{
			return ((::Sofa::Core::SimpleCommand*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ITEMREFRESHANIMPLAYEDCOMMAND_OFFSET))(this);
		}

		::System::Void set_ItemRefreshAnimPlayedCommand(::Sofa::Core::SimpleCommand* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::SimpleCommand*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ITEMREFRESHANIMPLAYEDCOMMAND_OFFSET))(this, a1);
		}

		::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* get_ItemViewModels()
		{
			return ((::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ITEMVIEWMODELS_OFFSET))(this);
		}

		::System::Void set_ItemViewModels(::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Sofa::Core::ObservableList_1<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ITEMVIEWMODELS_OFFSET))(this, a1);
		}

		::RPG::Client::ChenLingFes::ChenLingFesGameplayOperateItemViewModel* get_OperateItemViewModel()
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplayOperateItemViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_OPERATEITEMVIEWMODEL_OFFSET))(this);
		}

		::System::Void set_OperateItemViewModel(::RPG::Client::ChenLingFes::ChenLingFesGameplayOperateItemViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayOperateItemViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_OPERATEITEMVIEWMODEL_OFFSET))(this, a1);
		}

		::Class_1_50AC12A2F890597C* get_GameplayBridge()
		{
			return ((::Class_1_50AC12A2F890597C*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_GAMEPLAYBRIDGE_OFFSET))(this);
		}

		::System::Boolean get_NeedPlayItemRefreshAnim()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_NEEDPLAYITEMREFRESHANIM_OFFSET))(this);
		}

		::System::Void set_NeedPlayItemRefreshAnim(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_NEEDPLAYITEMREFRESHANIM_OFFSET))(this, a1);
		}

		::System::Boolean get_CanSkipItem()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CANSKIPITEM_OFFSET))(this);
		}

		::System::Boolean get_CanRerollItem()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CANREROLLITEM_OFFSET))(this);
		}

		::System::Boolean get_CanExecuteSelectOperation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_CANEXECUTESELECTOPERATION_OFFSET))(this);
		}

		::System::Void set_CanExecuteSelectOperation(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_CANEXECUTESELECTOPERATION_OFFSET))(this, a1);
		}

		::System::Boolean get_IsForbidShowItemList()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ISFORBIDSHOWITEMLIST_OFFSET))(this);
		}

		::System::Void set_IsForbidShowItemList(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ISFORBIDSHOWITEMLIST_OFFSET))(this, a1);
		}

		::System::Boolean get_IsVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ISVISIBLE_OFFSET))(this);
		}

		::System::Void set_IsVisible(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ISVISIBLE_OFFSET))(this, a1);
		}

		::System::Boolean get_IsExpanded()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ISEXPANDED_OFFSET))(this);
		}

		::System::Void set_IsExpanded(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ISEXPANDED_OFFSET))(this, a1);
		}

		::System::Int32 get_ExtraCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_EXTRACOUNT_OFFSET))(this);
		}

		::System::Void set_ExtraCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_EXTRACOUNT_OFFSET))(this, a1);
		}

		::System::Int32 get_RerollCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_REROLLCOUNT_OFFSET))(this);
		}

		::System::Void set_RerollCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_REROLLCOUNT_OFFSET))(this, a1);
		}

		::System::Void _InitDragCommand()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__INITDRAGCOMMAND_OFFSET))(this);
		}

		::System::Void _OnDragStart(::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONDRAGSTART_OFFSET))(this, a1);
		}

		::System::Void _OnDragEnd(::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONDRAGEND_OFFSET))(this, a1);
		}

		::System::Void _OnDragExceed(::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__ONDRAGEXCEED_OFFSET))(this, a1);
		}

		::System::Void _SelectDraggingItem(::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__SELECTDRAGGINGITEM_OFFSET))(this, a1);
		}

		::System::Void _ApplyDraggingVisualStateToList()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL__APPLYDRAGGINGVISUALSTATETOLIST_OFFSET))(this);
		}

		::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* get_OnDragStartCommand()
		{
			return ((::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ONDRAGSTARTCOMMAND_OFFSET))(this);
		}

		::System::Void set_OnDragStartCommand(::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ONDRAGSTARTCOMMAND_OFFSET))(this, a1);
		}

		::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* get_OnDragEndCommand()
		{
			return ((::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ONDRAGENDCOMMAND_OFFSET))(this);
		}

		::System::Void set_OnDragEndCommand(::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ONDRAGENDCOMMAND_OFFSET))(this, a1);
		}

		::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* get_OnDragExceedCommand()
		{
			return ((::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_ONDRAGEXCEEDCOMMAND_OFFSET))(this);
		}

		::System::Void set_OnDragExceedCommand(::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_BF01A723AB4005C0<::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_ONDRAGEXCEEDCOMMAND_OFFSET))(this, a1);
		}

		::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* get_DraggingItemViewModel()
		{
			return ((::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_GET_DRAGGINGITEMVIEWMODEL_OFFSET))(this);
		}

		::System::Void set_DraggingItemViewModel(::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ChenLingFes::ChenLingFesGameplayItemViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_CHENLINGFES_CHENLINGFESGAMEPLAYSELECTPANELVIEWMODEL_SET_DRAGGINGITEMVIEWMODEL_OFFSET))(this, a1);
		}
	};
}
