#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Base64FormattingOptions.h"
#include "unitysdk/System/DateTime.h"
#include "unitysdk/System/Decimal.h"
#include "unitysdk/System/Object.h"
#include "unitysdk/System/TypeCode.h"

namespace System { class IConvertible; }
namespace System { class IFormatProvider; }
namespace System { class RuntimeType; }
namespace System { class String; }
namespace System { class Type; }

#define SYSTEM_CONVERT_CHANGETYPE_1_OFFSET UNITYSDK_OFFSET(0x1A082EC0)
#define SYSTEM_CONVERT_CHANGETYPE_2_OFFSET UNITYSDK_OFFSET(0x1A084C80)
#define SYSTEM_CONVERT_CHANGETYPE_3_OFFSET UNITYSDK_OFFSET(0x1A084D10)
#define SYSTEM_CONVERT_CHANGETYPE_OFFSET UNITYSDK_OFFSET(0x1A082E30)
#define SYSTEM_CONVERT_CONVERTTOBASE64ARRAY_OFFSET UNITYSDK_OFFSET(0x1A090A60)
#define SYSTEM_CONVERT_DEFAULTTOTYPE_OFFSET UNITYSDK_OFFSET(0x1A083EB0)
#define SYSTEM_CONVERT_FROMBASE64CHARARRAY_OFFSET UNITYSDK_OFFSET(0x1A0911A0)
#define SYSTEM_CONVERT_FROMBASE64CHARPTR_OFFSET UNITYSDK_OFFSET(0x1A091060)
#define SYSTEM_CONVERT_FROMBASE64STRING_OFFSET UNITYSDK_OFFSET(0x1A091010)
#define SYSTEM_CONVERT_FROMBASE64_COMPUTERESULTLENGTH_OFFSET UNITYSDK_OFFSET(0x1A091300)
#define SYSTEM_CONVERT_FROMBASE64_DECODE_OFFSET UNITYSDK_OFFSET(0x1A091390)
#define SYSTEM_CONVERT_GETTYPECODE_OFFSET UNITYSDK_OFFSET(0x1A082BB0)
#define SYSTEM_CONVERT_ISDBNULL_OFFSET UNITYSDK_OFFSET(0x1A082CD0)
#define SYSTEM_CONVERT_TOBASE64CHARARRAY_1_OFFSET UNITYSDK_OFFSET(0x1A090C80)
#define SYSTEM_CONVERT_TOBASE64CHARARRAY_OFFSET UNITYSDK_OFFSET(0x1A090C60)
#define SYSTEM_CONVERT_TOBASE64STRING_1_OFFSET UNITYSDK_OFFSET(0x1A0908F0)
#define SYSTEM_CONVERT_TOBASE64STRING_2_OFFSET UNITYSDK_OFFSET(0x1A090970)
#define SYSTEM_CONVERT_TOBASE64STRING_3_OFFSET UNITYSDK_OFFSET(0x1A090600)
#define SYSTEM_CONVERT_TOBASE64STRING_OFFSET UNITYSDK_OFFSET(0x1A0905B0)
#define SYSTEM_CONVERT_TOBASE64_CALCULATEANDVALIDATEOUTPUTLENGTH_OFFSET UNITYSDK_OFFSET(0x1A090980)
#define SYSTEM_CONVERT_TOBOOLEAN_10_OFFSET UNITYSDK_OFFSET(0x1A085D90)
#define SYSTEM_CONVERT_TOBOOLEAN_11_OFFSET UNITYSDK_OFFSET(0x1A085DA0)
#define SYSTEM_CONVERT_TOBOOLEAN_12_OFFSET UNITYSDK_OFFSET(0x1A085DB0)
#define SYSTEM_CONVERT_TOBOOLEAN_13_OFFSET UNITYSDK_OFFSET(0x1A085DF0)
#define SYSTEM_CONVERT_TOBOOLEAN_14_OFFSET UNITYSDK_OFFSET(0x1A085E30)
#define SYSTEM_CONVERT_TOBOOLEAN_15_OFFSET UNITYSDK_OFFSET(0x1A085E40)
#define SYSTEM_CONVERT_TOBOOLEAN_16_OFFSET UNITYSDK_OFFSET(0x1A085E60)
#define SYSTEM_CONVERT_TOBOOLEAN_17_OFFSET UNITYSDK_OFFSET(0x1A085F20)
#define SYSTEM_CONVERT_TOBOOLEAN_1_OFFSET UNITYSDK_OFFSET(0x1A085B20)
#define SYSTEM_CONVERT_TOBOOLEAN_2_OFFSET UNITYSDK_OFFSET(0x1A085C90)
#define SYSTEM_CONVERT_TOBOOLEAN_3_OFFSET UNITYSDK_OFFSET(0x1A085CA0)
#define SYSTEM_CONVERT_TOBOOLEAN_4_OFFSET UNITYSDK_OFFSET(0x1A085CB0)
#define SYSTEM_CONVERT_TOBOOLEAN_5_OFFSET UNITYSDK_OFFSET(0x1A085D40)
#define SYSTEM_CONVERT_TOBOOLEAN_6_OFFSET UNITYSDK_OFFSET(0x1A085D50)
#define SYSTEM_CONVERT_TOBOOLEAN_7_OFFSET UNITYSDK_OFFSET(0x1A085D60)
#define SYSTEM_CONVERT_TOBOOLEAN_8_OFFSET UNITYSDK_OFFSET(0x1A085D70)
#define SYSTEM_CONVERT_TOBOOLEAN_9_OFFSET UNITYSDK_OFFSET(0x1A085D80)
#define SYSTEM_CONVERT_TOBOOLEAN_OFFSET UNITYSDK_OFFSET(0x1A0859B0)
#define SYSTEM_CONVERT_TOBYTE_10_OFFSET UNITYSDK_OFFSET(0x1A087EB0)
#define SYSTEM_CONVERT_TOBYTE_11_OFFSET UNITYSDK_OFFSET(0x1A087F20)
#define SYSTEM_CONVERT_TOBYTE_12_OFFSET UNITYSDK_OFFSET(0x1A087F90)
#define SYSTEM_CONVERT_TOBYTE_13_OFFSET UNITYSDK_OFFSET(0x1A0880C0)
#define SYSTEM_CONVERT_TOBYTE_14_OFFSET UNITYSDK_OFFSET(0x1A0881F0)
#define SYSTEM_CONVERT_TOBYTE_15_OFFSET UNITYSDK_OFFSET(0x1A0883B0)
#define SYSTEM_CONVERT_TOBYTE_16_OFFSET UNITYSDK_OFFSET(0x1A088450)
#define SYSTEM_CONVERT_TOBYTE_17_OFFSET UNITYSDK_OFFSET(0x1A088490)
#define SYSTEM_CONVERT_TOBYTE_18_OFFSET UNITYSDK_OFFSET(0x1A08FD90)
#define SYSTEM_CONVERT_TOBYTE_1_OFFSET UNITYSDK_OFFSET(0x1A087A80)
#define SYSTEM_CONVERT_TOBYTE_2_OFFSET UNITYSDK_OFFSET(0x1A087BF0)
#define SYSTEM_CONVERT_TOBYTE_3_OFFSET UNITYSDK_OFFSET(0x1A087C00)
#define SYSTEM_CONVERT_TOBYTE_4_OFFSET UNITYSDK_OFFSET(0x1A087C10)
#define SYSTEM_CONVERT_TOBYTE_5_OFFSET UNITYSDK_OFFSET(0x1A087C80)
#define SYSTEM_CONVERT_TOBYTE_6_OFFSET UNITYSDK_OFFSET(0x1A087CF0)
#define SYSTEM_CONVERT_TOBYTE_7_OFFSET UNITYSDK_OFFSET(0x1A087D60)
#define SYSTEM_CONVERT_TOBYTE_8_OFFSET UNITYSDK_OFFSET(0x1A087DD0)
#define SYSTEM_CONVERT_TOBYTE_9_OFFSET UNITYSDK_OFFSET(0x1A087E40)
#define SYSTEM_CONVERT_TOBYTE_OFFSET UNITYSDK_OFFSET(0x1A087910)
#define SYSTEM_CONVERT_TOCHAR_10_OFFSET UNITYSDK_OFFSET(0x1A0865C0)
#define SYSTEM_CONVERT_TOCHAR_11_OFFSET UNITYSDK_OFFSET(0x1A086630)
#define SYSTEM_CONVERT_TOCHAR_12_OFFSET UNITYSDK_OFFSET(0x1A0866A0)
#define SYSTEM_CONVERT_TOCHAR_13_OFFSET UNITYSDK_OFFSET(0x1A0866B0)
#define SYSTEM_CONVERT_TOCHAR_14_OFFSET UNITYSDK_OFFSET(0x1A086750)
#define SYSTEM_CONVERT_TOCHAR_15_OFFSET UNITYSDK_OFFSET(0x1A0867E0)
#define SYSTEM_CONVERT_TOCHAR_16_OFFSET UNITYSDK_OFFSET(0x1A086870)
#define SYSTEM_CONVERT_TOCHAR_17_OFFSET UNITYSDK_OFFSET(0x1A0869D0)
#define SYSTEM_CONVERT_TOCHAR_1_OFFSET UNITYSDK_OFFSET(0x1A0861F0)
#define SYSTEM_CONVERT_TOCHAR_2_OFFSET UNITYSDK_OFFSET(0x1A086360)
#define SYSTEM_CONVERT_TOCHAR_3_OFFSET UNITYSDK_OFFSET(0x1A0863F0)
#define SYSTEM_CONVERT_TOCHAR_4_OFFSET UNITYSDK_OFFSET(0x1A086400)
#define SYSTEM_CONVERT_TOCHAR_5_OFFSET UNITYSDK_OFFSET(0x1A086470)
#define SYSTEM_CONVERT_TOCHAR_6_OFFSET UNITYSDK_OFFSET(0x1A086480)
#define SYSTEM_CONVERT_TOCHAR_7_OFFSET UNITYSDK_OFFSET(0x1A0864F0)
#define SYSTEM_CONVERT_TOCHAR_8_OFFSET UNITYSDK_OFFSET(0x1A086500)
#define SYSTEM_CONVERT_TOCHAR_9_OFFSET UNITYSDK_OFFSET(0x1A086550)
#define SYSTEM_CONVERT_TOCHAR_OFFSET UNITYSDK_OFFSET(0x1A086080)
#define SYSTEM_CONVERT_TODATETIME_10_OFFSET UNITYSDK_OFFSET(0x1A08EA50)
#define SYSTEM_CONVERT_TODATETIME_11_OFFSET UNITYSDK_OFFSET(0x1A08EAE0)
#define SYSTEM_CONVERT_TODATETIME_12_OFFSET UNITYSDK_OFFSET(0x1A08EB70)
#define SYSTEM_CONVERT_TODATETIME_13_OFFSET UNITYSDK_OFFSET(0x1A08EC00)
#define SYSTEM_CONVERT_TODATETIME_14_OFFSET UNITYSDK_OFFSET(0x1A08EC90)
#define SYSTEM_CONVERT_TODATETIME_15_OFFSET UNITYSDK_OFFSET(0x1A08ED20)
#define SYSTEM_CONVERT_TODATETIME_16_OFFSET UNITYSDK_OFFSET(0x1A08EDB0)
#define SYSTEM_CONVERT_TODATETIME_17_OFFSET UNITYSDK_OFFSET(0x1A08EE40)
#define SYSTEM_CONVERT_TODATETIME_1_OFFSET UNITYSDK_OFFSET(0x1A08E220)
#define SYSTEM_CONVERT_TODATETIME_2_OFFSET UNITYSDK_OFFSET(0x1A08E390)
#define SYSTEM_CONVERT_TODATETIME_3_OFFSET UNITYSDK_OFFSET(0x1A08E500)
#define SYSTEM_CONVERT_TODATETIME_4_OFFSET UNITYSDK_OFFSET(0x1A08E6F0)
#define SYSTEM_CONVERT_TODATETIME_5_OFFSET UNITYSDK_OFFSET(0x1A08E780)
#define SYSTEM_CONVERT_TODATETIME_6_OFFSET UNITYSDK_OFFSET(0x1A08E810)
#define SYSTEM_CONVERT_TODATETIME_7_OFFSET UNITYSDK_OFFSET(0x1A08E8A0)
#define SYSTEM_CONVERT_TODATETIME_8_OFFSET UNITYSDK_OFFSET(0x1A08E930)
#define SYSTEM_CONVERT_TODATETIME_9_OFFSET UNITYSDK_OFFSET(0x1A08E9C0)
#define SYSTEM_CONVERT_TODATETIME_OFFSET UNITYSDK_OFFSET(0x1A08E210)
#define SYSTEM_CONVERT_TODECIMAL_10_OFFSET UNITYSDK_OFFSET(0x1A08DD00)
#define SYSTEM_CONVERT_TODECIMAL_11_OFFSET UNITYSDK_OFFSET(0x1A08DD60)
#define SYSTEM_CONVERT_TODECIMAL_12_OFFSET UNITYSDK_OFFSET(0x1A08DDE0)
#define SYSTEM_CONVERT_TODECIMAL_13_OFFSET UNITYSDK_OFFSET(0x1A08DE60)
#define SYSTEM_CONVERT_TODECIMAL_14_OFFSET UNITYSDK_OFFSET(0x1A08DF90)
#define SYSTEM_CONVERT_TODECIMAL_15_OFFSET UNITYSDK_OFFSET(0x1A08E060)
#define SYSTEM_CONVERT_TODECIMAL_16_OFFSET UNITYSDK_OFFSET(0x1A08E070)
#define SYSTEM_CONVERT_TODECIMAL_17_OFFSET UNITYSDK_OFFSET(0x1A08E0B0)
#define SYSTEM_CONVERT_TODECIMAL_1_OFFSET UNITYSDK_OFFSET(0x1A08D750)
#define SYSTEM_CONVERT_TODECIMAL_2_OFFSET UNITYSDK_OFFSET(0x1A08D8F0)
#define SYSTEM_CONVERT_TODECIMAL_3_OFFSET UNITYSDK_OFFSET(0x1A08D990)
#define SYSTEM_CONVERT_TODECIMAL_4_OFFSET UNITYSDK_OFFSET(0x1A08D9F0)
#define SYSTEM_CONVERT_TODECIMAL_5_OFFSET UNITYSDK_OFFSET(0x1A08DA80)
#define SYSTEM_CONVERT_TODECIMAL_6_OFFSET UNITYSDK_OFFSET(0x1A08DB20)
#define SYSTEM_CONVERT_TODECIMAL_7_OFFSET UNITYSDK_OFFSET(0x1A08DB80)
#define SYSTEM_CONVERT_TODECIMAL_8_OFFSET UNITYSDK_OFFSET(0x1A08DC10)
#define SYSTEM_CONVERT_TODECIMAL_9_OFFSET UNITYSDK_OFFSET(0x1A08DC70)
#define SYSTEM_CONVERT_TODECIMAL_OFFSET UNITYSDK_OFFSET(0x1A08D5B0)
#define SYSTEM_CONVERT_TODOUBLE_10_OFFSET UNITYSDK_OFFSET(0x1A08D190)
#define SYSTEM_CONVERT_TODOUBLE_11_OFFSET UNITYSDK_OFFSET(0x1A08D1C0)
#define SYSTEM_CONVERT_TODOUBLE_12_OFFSET UNITYSDK_OFFSET(0x1A08D1D0)
#define SYSTEM_CONVERT_TODOUBLE_13_OFFSET UNITYSDK_OFFSET(0x1A08D1E0)
#define SYSTEM_CONVERT_TODOUBLE_14_OFFSET UNITYSDK_OFFSET(0x1A08D340)
#define SYSTEM_CONVERT_TODOUBLE_15_OFFSET UNITYSDK_OFFSET(0x1A08D3F0)
#define SYSTEM_CONVERT_TODOUBLE_16_OFFSET UNITYSDK_OFFSET(0x1A08D430)
#define SYSTEM_CONVERT_TODOUBLE_17_OFFSET UNITYSDK_OFFSET(0x1A08D450)
#define SYSTEM_CONVERT_TODOUBLE_1_OFFSET UNITYSDK_OFFSET(0x1A08CF20)
#define SYSTEM_CONVERT_TODOUBLE_2_OFFSET UNITYSDK_OFFSET(0x1A08D090)
#define SYSTEM_CONVERT_TODOUBLE_3_OFFSET UNITYSDK_OFFSET(0x1A08D0A0)
#define SYSTEM_CONVERT_TODOUBLE_4_OFFSET UNITYSDK_OFFSET(0x1A08D0B0)
#define SYSTEM_CONVERT_TODOUBLE_5_OFFSET UNITYSDK_OFFSET(0x1A08D0C0)
#define SYSTEM_CONVERT_TODOUBLE_6_OFFSET UNITYSDK_OFFSET(0x1A08D150)
#define SYSTEM_CONVERT_TODOUBLE_7_OFFSET UNITYSDK_OFFSET(0x1A08D160)
#define SYSTEM_CONVERT_TODOUBLE_8_OFFSET UNITYSDK_OFFSET(0x1A08D170)
#define SYSTEM_CONVERT_TODOUBLE_9_OFFSET UNITYSDK_OFFSET(0x1A08D180)
#define SYSTEM_CONVERT_TODOUBLE_OFFSET UNITYSDK_OFFSET(0x1A08CDB0)
#define SYSTEM_CONVERT_TOINT16_10_OFFSET UNITYSDK_OFFSET(0x1A088AD0)
#define SYSTEM_CONVERT_TOINT16_11_OFFSET UNITYSDK_OFFSET(0x1A088B40)
#define SYSTEM_CONVERT_TOINT16_12_OFFSET UNITYSDK_OFFSET(0x1A088BB0)
#define SYSTEM_CONVERT_TOINT16_13_OFFSET UNITYSDK_OFFSET(0x1A088CE0)
#define SYSTEM_CONVERT_TOINT16_14_OFFSET UNITYSDK_OFFSET(0x1A088E10)
#define SYSTEM_CONVERT_TOINT16_15_OFFSET UNITYSDK_OFFSET(0x1A088FD0)
#define SYSTEM_CONVERT_TOINT16_16_OFFSET UNITYSDK_OFFSET(0x1A089070)
#define SYSTEM_CONVERT_TOINT16_17_OFFSET UNITYSDK_OFFSET(0x1A0890B0)
#define SYSTEM_CONVERT_TOINT16_18_OFFSET UNITYSDK_OFFSET(0x1A08FF40)
#define SYSTEM_CONVERT_TOINT16_1_OFFSET UNITYSDK_OFFSET(0x1A088760)
#define SYSTEM_CONVERT_TOINT16_2_OFFSET UNITYSDK_OFFSET(0x1A0888D0)
#define SYSTEM_CONVERT_TOINT16_3_OFFSET UNITYSDK_OFFSET(0x1A0888E0)
#define SYSTEM_CONVERT_TOINT16_4_OFFSET UNITYSDK_OFFSET(0x1A088950)
#define SYSTEM_CONVERT_TOINT16_5_OFFSET UNITYSDK_OFFSET(0x1A088960)
#define SYSTEM_CONVERT_TOINT16_6_OFFSET UNITYSDK_OFFSET(0x1A088970)
#define SYSTEM_CONVERT_TOINT16_7_OFFSET UNITYSDK_OFFSET(0x1A0889E0)
#define SYSTEM_CONVERT_TOINT16_8_OFFSET UNITYSDK_OFFSET(0x1A088A50)
#define SYSTEM_CONVERT_TOINT16_9_OFFSET UNITYSDK_OFFSET(0x1A088AC0)
#define SYSTEM_CONVERT_TOINT16_OFFSET UNITYSDK_OFFSET(0x1A0885F0)
#define SYSTEM_CONVERT_TOINT32_10_OFFSET UNITYSDK_OFFSET(0x1A08A1F0)
#define SYSTEM_CONVERT_TOINT32_11_OFFSET UNITYSDK_OFFSET(0x1A08A240)
#define SYSTEM_CONVERT_TOINT32_12_OFFSET UNITYSDK_OFFSET(0x1A08A2B0)
#define SYSTEM_CONVERT_TOINT32_13_OFFSET UNITYSDK_OFFSET(0x1A087410)
#define SYSTEM_CONVERT_TOINT32_14_OFFSET UNITYSDK_OFFSET(0x1A08A370)
#define SYSTEM_CONVERT_TOINT32_15_OFFSET UNITYSDK_OFFSET(0x1A08A3D0)
#define SYSTEM_CONVERT_TOINT32_16_OFFSET UNITYSDK_OFFSET(0x1A08A470)
#define SYSTEM_CONVERT_TOINT32_17_OFFSET UNITYSDK_OFFSET(0x1A08A4B0)
#define SYSTEM_CONVERT_TOINT32_18_OFFSET UNITYSDK_OFFSET(0x1A0900F0)
#define SYSTEM_CONVERT_TOINT32_1_OFFSET UNITYSDK_OFFSET(0x1A089FA0)
#define SYSTEM_CONVERT_TOINT32_2_OFFSET UNITYSDK_OFFSET(0x1A08A110)
#define SYSTEM_CONVERT_TOINT32_3_OFFSET UNITYSDK_OFFSET(0x1A08A120)
#define SYSTEM_CONVERT_TOINT32_4_OFFSET UNITYSDK_OFFSET(0x1A08A130)
#define SYSTEM_CONVERT_TOINT32_5_OFFSET UNITYSDK_OFFSET(0x1A08A140)
#define SYSTEM_CONVERT_TOINT32_6_OFFSET UNITYSDK_OFFSET(0x1A08A150)
#define SYSTEM_CONVERT_TOINT32_7_OFFSET UNITYSDK_OFFSET(0x1A08A160)
#define SYSTEM_CONVERT_TOINT32_8_OFFSET UNITYSDK_OFFSET(0x1A08A170)
#define SYSTEM_CONVERT_TOINT32_9_OFFSET UNITYSDK_OFFSET(0x1A08A1E0)
#define SYSTEM_CONVERT_TOINT32_OFFSET UNITYSDK_OFFSET(0x1A089E30)
#define SYSTEM_CONVERT_TOINT64_10_OFFSET UNITYSDK_OFFSET(0x1A08B450)
#define SYSTEM_CONVERT_TOINT64_11_OFFSET UNITYSDK_OFFSET(0x1A08B4C0)
#define SYSTEM_CONVERT_TOINT64_12_OFFSET UNITYSDK_OFFSET(0x1A08B4D0)
#define SYSTEM_CONVERT_TOINT64_13_OFFSET UNITYSDK_OFFSET(0x1A08B590)
#define SYSTEM_CONVERT_TOINT64_14_OFFSET UNITYSDK_OFFSET(0x1A08B640)
#define SYSTEM_CONVERT_TOINT64_15_OFFSET UNITYSDK_OFFSET(0x1A08B870)
#define SYSTEM_CONVERT_TOINT64_16_OFFSET UNITYSDK_OFFSET(0x1A08B910)
#define SYSTEM_CONVERT_TOINT64_17_OFFSET UNITYSDK_OFFSET(0x1A08B950)
#define SYSTEM_CONVERT_TOINT64_18_OFFSET UNITYSDK_OFFSET(0x1A090210)
#define SYSTEM_CONVERT_TOINT64_1_OFFSET UNITYSDK_OFFSET(0x1A08B260)
#define SYSTEM_CONVERT_TOINT64_2_OFFSET UNITYSDK_OFFSET(0x1A08B3D0)
#define SYSTEM_CONVERT_TOINT64_3_OFFSET UNITYSDK_OFFSET(0x1A08B3E0)
#define SYSTEM_CONVERT_TOINT64_4_OFFSET UNITYSDK_OFFSET(0x1A08B3F0)
#define SYSTEM_CONVERT_TOINT64_5_OFFSET UNITYSDK_OFFSET(0x1A08B400)
#define SYSTEM_CONVERT_TOINT64_6_OFFSET UNITYSDK_OFFSET(0x1A08B410)
#define SYSTEM_CONVERT_TOINT64_7_OFFSET UNITYSDK_OFFSET(0x1A08B420)
#define SYSTEM_CONVERT_TOINT64_8_OFFSET UNITYSDK_OFFSET(0x1A08B430)
#define SYSTEM_CONVERT_TOINT64_9_OFFSET UNITYSDK_OFFSET(0x1A08B440)
#define SYSTEM_CONVERT_TOINT64_OFFSET UNITYSDK_OFFSET(0x1A08B0F0)
#define SYSTEM_CONVERT_TOSBYTE_10_OFFSET UNITYSDK_OFFSET(0x1A0870D0)
#define SYSTEM_CONVERT_TOSBYTE_11_OFFSET UNITYSDK_OFFSET(0x1A087140)
#define SYSTEM_CONVERT_TOSBYTE_12_OFFSET UNITYSDK_OFFSET(0x1A0871B0)
#define SYSTEM_CONVERT_TOSBYTE_13_OFFSET UNITYSDK_OFFSET(0x1A0872E0)
#define SYSTEM_CONVERT_TOSBYTE_14_OFFSET UNITYSDK_OFFSET(0x1A0874D0)
#define SYSTEM_CONVERT_TOSBYTE_15_OFFSET UNITYSDK_OFFSET(0x1A0876E0)
#define SYSTEM_CONVERT_TOSBYTE_16_OFFSET UNITYSDK_OFFSET(0x1A087780)
#define SYSTEM_CONVERT_TOSBYTE_17_OFFSET UNITYSDK_OFFSET(0x1A0877B0)
#define SYSTEM_CONVERT_TOSBYTE_18_OFFSET UNITYSDK_OFFSET(0x1A08FE60)
#define SYSTEM_CONVERT_TOSBYTE_1_OFFSET UNITYSDK_OFFSET(0x1A086CA0)
#define SYSTEM_CONVERT_TOSBYTE_2_OFFSET UNITYSDK_OFFSET(0x1A086E10)
#define SYSTEM_CONVERT_TOSBYTE_3_OFFSET UNITYSDK_OFFSET(0x1A086E20)
#define SYSTEM_CONVERT_TOSBYTE_4_OFFSET UNITYSDK_OFFSET(0x1A086E30)
#define SYSTEM_CONVERT_TOSBYTE_5_OFFSET UNITYSDK_OFFSET(0x1A086EA0)
#define SYSTEM_CONVERT_TOSBYTE_6_OFFSET UNITYSDK_OFFSET(0x1A086F10)
#define SYSTEM_CONVERT_TOSBYTE_7_OFFSET UNITYSDK_OFFSET(0x1A086F80)
#define SYSTEM_CONVERT_TOSBYTE_8_OFFSET UNITYSDK_OFFSET(0x1A086FF0)
#define SYSTEM_CONVERT_TOSBYTE_9_OFFSET UNITYSDK_OFFSET(0x1A087060)
#define SYSTEM_CONVERT_TOSBYTE_OFFSET UNITYSDK_OFFSET(0x1A086B30)
#define SYSTEM_CONVERT_TOSINGLE_10_OFFSET UNITYSDK_OFFSET(0x1A08C980)
#define SYSTEM_CONVERT_TOSINGLE_11_OFFSET UNITYSDK_OFFSET(0x1A08C9B0)
#define SYSTEM_CONVERT_TOSINGLE_12_OFFSET UNITYSDK_OFFSET(0x1A08C9C0)
#define SYSTEM_CONVERT_TOSINGLE_13_OFFSET UNITYSDK_OFFSET(0x1A08C9D0)
#define SYSTEM_CONVERT_TOSINGLE_14_OFFSET UNITYSDK_OFFSET(0x1A08CB40)
#define SYSTEM_CONVERT_TOSINGLE_15_OFFSET UNITYSDK_OFFSET(0x1A08CBF0)
#define SYSTEM_CONVERT_TOSINGLE_16_OFFSET UNITYSDK_OFFSET(0x1A08CC30)
#define SYSTEM_CONVERT_TOSINGLE_17_OFFSET UNITYSDK_OFFSET(0x1A08CC50)
#define SYSTEM_CONVERT_TOSINGLE_1_OFFSET UNITYSDK_OFFSET(0x1A08C710)
#define SYSTEM_CONVERT_TOSINGLE_2_OFFSET UNITYSDK_OFFSET(0x1A08C880)
#define SYSTEM_CONVERT_TOSINGLE_3_OFFSET UNITYSDK_OFFSET(0x1A08C890)
#define SYSTEM_CONVERT_TOSINGLE_4_OFFSET UNITYSDK_OFFSET(0x1A08C8A0)
#define SYSTEM_CONVERT_TOSINGLE_5_OFFSET UNITYSDK_OFFSET(0x1A08C930)
#define SYSTEM_CONVERT_TOSINGLE_6_OFFSET UNITYSDK_OFFSET(0x1A08C940)
#define SYSTEM_CONVERT_TOSINGLE_7_OFFSET UNITYSDK_OFFSET(0x1A08C950)
#define SYSTEM_CONVERT_TOSINGLE_8_OFFSET UNITYSDK_OFFSET(0x1A08C960)
#define SYSTEM_CONVERT_TOSINGLE_9_OFFSET UNITYSDK_OFFSET(0x1A08C970)
#define SYSTEM_CONVERT_TOSINGLE_OFFSET UNITYSDK_OFFSET(0x1A08C5A0)
#define SYSTEM_CONVERT_TOSTRING_10_OFFSET UNITYSDK_OFFSET(0x1A08F520)
#define SYSTEM_CONVERT_TOSTRING_11_OFFSET UNITYSDK_OFFSET(0x1A08F5B0)
#define SYSTEM_CONVERT_TOSTRING_12_OFFSET UNITYSDK_OFFSET(0x1A08F5E0)
#define SYSTEM_CONVERT_TOSTRING_13_OFFSET UNITYSDK_OFFSET(0x1A08F670)
#define SYSTEM_CONVERT_TOSTRING_14_OFFSET UNITYSDK_OFFSET(0x1A08F6A0)
#define SYSTEM_CONVERT_TOSTRING_15_OFFSET UNITYSDK_OFFSET(0x1A08F730)
#define SYSTEM_CONVERT_TOSTRING_16_OFFSET UNITYSDK_OFFSET(0x1A08F750)
#define SYSTEM_CONVERT_TOSTRING_17_OFFSET UNITYSDK_OFFSET(0x1A08F7E0)
#define SYSTEM_CONVERT_TOSTRING_18_OFFSET UNITYSDK_OFFSET(0x1A08F800)
#define SYSTEM_CONVERT_TOSTRING_19_OFFSET UNITYSDK_OFFSET(0x1A08F890)
#define SYSTEM_CONVERT_TOSTRING_1_OFFSET UNITYSDK_OFFSET(0x1A08EFB0)
#define SYSTEM_CONVERT_TOSTRING_20_OFFSET UNITYSDK_OFFSET(0x1A08F8C0)
#define SYSTEM_CONVERT_TOSTRING_21_OFFSET UNITYSDK_OFFSET(0x1A08F950)
#define SYSTEM_CONVERT_TOSTRING_22_OFFSET UNITYSDK_OFFSET(0x1A08F980)
#define SYSTEM_CONVERT_TOSTRING_23_OFFSET UNITYSDK_OFFSET(0x1A08FA20)
#define SYSTEM_CONVERT_TOSTRING_24_OFFSET UNITYSDK_OFFSET(0x1A08FA50)
#define SYSTEM_CONVERT_TOSTRING_25_OFFSET UNITYSDK_OFFSET(0x1A08FAF0)
#define SYSTEM_CONVERT_TOSTRING_26_OFFSET UNITYSDK_OFFSET(0x1A08FB20)
#define SYSTEM_CONVERT_TOSTRING_27_OFFSET UNITYSDK_OFFSET(0x1A08FC10)
#define SYSTEM_CONVERT_TOSTRING_28_OFFSET UNITYSDK_OFFSET(0x1A08FC50)
#define SYSTEM_CONVERT_TOSTRING_29_OFFSET UNITYSDK_OFFSET(0x1A08FCD0)
#define SYSTEM_CONVERT_TOSTRING_2_OFFSET UNITYSDK_OFFSET(0x1A08F280)
#define SYSTEM_CONVERT_TOSTRING_30_OFFSET UNITYSDK_OFFSET(0x1A08FD70)
#define SYSTEM_CONVERT_TOSTRING_31_OFFSET UNITYSDK_OFFSET(0x1A08FD80)
#define SYSTEM_CONVERT_TOSTRING_32_OFFSET UNITYSDK_OFFSET(0x1A090330)
#define SYSTEM_CONVERT_TOSTRING_33_OFFSET UNITYSDK_OFFSET(0x1A0903D0)
#define SYSTEM_CONVERT_TOSTRING_34_OFFSET UNITYSDK_OFFSET(0x1A090470)
#define SYSTEM_CONVERT_TOSTRING_35_OFFSET UNITYSDK_OFFSET(0x1A090510)
#define SYSTEM_CONVERT_TOSTRING_3_OFFSET UNITYSDK_OFFSET(0x1A08F2A0)
#define SYSTEM_CONVERT_TOSTRING_4_OFFSET UNITYSDK_OFFSET(0x1A08F2C0)
#define SYSTEM_CONVERT_TOSTRING_5_OFFSET UNITYSDK_OFFSET(0x1A08F330)
#define SYSTEM_CONVERT_TOSTRING_6_OFFSET UNITYSDK_OFFSET(0x1A08F3A0)
#define SYSTEM_CONVERT_TOSTRING_7_OFFSET UNITYSDK_OFFSET(0x1A08F430)
#define SYSTEM_CONVERT_TOSTRING_8_OFFSET UNITYSDK_OFFSET(0x1A08F460)
#define SYSTEM_CONVERT_TOSTRING_9_OFFSET UNITYSDK_OFFSET(0x1A08F4F0)
#define SYSTEM_CONVERT_TOSTRING_OFFSET UNITYSDK_OFFSET(0x1A08EFA0)
#define SYSTEM_CONVERT_TOUINT16_10_OFFSET UNITYSDK_OFFSET(0x1A0896F0)
#define SYSTEM_CONVERT_TOUINT16_11_OFFSET UNITYSDK_OFFSET(0x1A089760)
#define SYSTEM_CONVERT_TOUINT16_12_OFFSET UNITYSDK_OFFSET(0x1A0897D0)
#define SYSTEM_CONVERT_TOUINT16_13_OFFSET UNITYSDK_OFFSET(0x1A089900)
#define SYSTEM_CONVERT_TOUINT16_14_OFFSET UNITYSDK_OFFSET(0x1A089A30)
#define SYSTEM_CONVERT_TOUINT16_15_OFFSET UNITYSDK_OFFSET(0x1A089BF0)
#define SYSTEM_CONVERT_TOUINT16_16_OFFSET UNITYSDK_OFFSET(0x1A089C90)
#define SYSTEM_CONVERT_TOUINT16_17_OFFSET UNITYSDK_OFFSET(0x1A089CD0)
#define SYSTEM_CONVERT_TOUINT16_18_OFFSET UNITYSDK_OFFSET(0x1A090020)
#define SYSTEM_CONVERT_TOUINT16_1_OFFSET UNITYSDK_OFFSET(0x1A089380)
#define SYSTEM_CONVERT_TOUINT16_2_OFFSET UNITYSDK_OFFSET(0x1A0894F0)
#define SYSTEM_CONVERT_TOUINT16_3_OFFSET UNITYSDK_OFFSET(0x1A089500)
#define SYSTEM_CONVERT_TOUINT16_4_OFFSET UNITYSDK_OFFSET(0x1A089510)
#define SYSTEM_CONVERT_TOUINT16_5_OFFSET UNITYSDK_OFFSET(0x1A089580)
#define SYSTEM_CONVERT_TOUINT16_6_OFFSET UNITYSDK_OFFSET(0x1A089590)
#define SYSTEM_CONVERT_TOUINT16_7_OFFSET UNITYSDK_OFFSET(0x1A089600)
#define SYSTEM_CONVERT_TOUINT16_8_OFFSET UNITYSDK_OFFSET(0x1A089670)
#define SYSTEM_CONVERT_TOUINT16_9_OFFSET UNITYSDK_OFFSET(0x1A089680)
#define SYSTEM_CONVERT_TOUINT16_OFFSET UNITYSDK_OFFSET(0x1A089210)
#define SYSTEM_CONVERT_TOUINT32_10_OFFSET UNITYSDK_OFFSET(0x1A08AA70)
#define SYSTEM_CONVERT_TOUINT32_11_OFFSET UNITYSDK_OFFSET(0x1A08AAC0)
#define SYSTEM_CONVERT_TOUINT32_12_OFFSET UNITYSDK_OFFSET(0x1A08AB30)
#define SYSTEM_CONVERT_TOUINT32_13_OFFSET UNITYSDK_OFFSET(0x1A08ABC0)
#define SYSTEM_CONVERT_TOUINT32_14_OFFSET UNITYSDK_OFFSET(0x1A08AC50)
#define SYSTEM_CONVERT_TOUINT32_15_OFFSET UNITYSDK_OFFSET(0x1A08AEB0)
#define SYSTEM_CONVERT_TOUINT32_16_OFFSET UNITYSDK_OFFSET(0x1A08AF50)
#define SYSTEM_CONVERT_TOUINT32_17_OFFSET UNITYSDK_OFFSET(0x1A08AF90)
#define SYSTEM_CONVERT_TOUINT32_18_OFFSET UNITYSDK_OFFSET(0x1A090180)
#define SYSTEM_CONVERT_TOUINT32_1_OFFSET UNITYSDK_OFFSET(0x1A08A780)
#define SYSTEM_CONVERT_TOUINT32_2_OFFSET UNITYSDK_OFFSET(0x1A08A8F0)
#define SYSTEM_CONVERT_TOUINT32_3_OFFSET UNITYSDK_OFFSET(0x1A08A900)
#define SYSTEM_CONVERT_TOUINT32_4_OFFSET UNITYSDK_OFFSET(0x1A08A910)
#define SYSTEM_CONVERT_TOUINT32_5_OFFSET UNITYSDK_OFFSET(0x1A08A980)
#define SYSTEM_CONVERT_TOUINT32_6_OFFSET UNITYSDK_OFFSET(0x1A08A990)
#define SYSTEM_CONVERT_TOUINT32_7_OFFSET UNITYSDK_OFFSET(0x1A08AA00)
#define SYSTEM_CONVERT_TOUINT32_8_OFFSET UNITYSDK_OFFSET(0x1A08AA10)
#define SYSTEM_CONVERT_TOUINT32_9_OFFSET UNITYSDK_OFFSET(0x1A08AA60)
#define SYSTEM_CONVERT_TOUINT32_OFFSET UNITYSDK_OFFSET(0x1A08A610)
#define SYSTEM_CONVERT_TOUINT64_10_OFFSET UNITYSDK_OFFSET(0x1A08BF30)
#define SYSTEM_CONVERT_TOUINT64_11_OFFSET UNITYSDK_OFFSET(0x1A08BF80)
#define SYSTEM_CONVERT_TOUINT64_12_OFFSET UNITYSDK_OFFSET(0x1A08BF90)
#define SYSTEM_CONVERT_TOUINT64_13_OFFSET UNITYSDK_OFFSET(0x1A08C050)
#define SYSTEM_CONVERT_TOUINT64_14_OFFSET UNITYSDK_OFFSET(0x1A08C100)
#define SYSTEM_CONVERT_TOUINT64_15_OFFSET UNITYSDK_OFFSET(0x1A08C360)
#define SYSTEM_CONVERT_TOUINT64_16_OFFSET UNITYSDK_OFFSET(0x1A08C400)
#define SYSTEM_CONVERT_TOUINT64_17_OFFSET UNITYSDK_OFFSET(0x1A08C440)
#define SYSTEM_CONVERT_TOUINT64_18_OFFSET UNITYSDK_OFFSET(0x1A0902A0)
#define SYSTEM_CONVERT_TOUINT64_1_OFFSET UNITYSDK_OFFSET(0x1A08BC20)
#define SYSTEM_CONVERT_TOUINT64_2_OFFSET UNITYSDK_OFFSET(0x1A08BD90)
#define SYSTEM_CONVERT_TOUINT64_3_OFFSET UNITYSDK_OFFSET(0x1A08BDA0)
#define SYSTEM_CONVERT_TOUINT64_4_OFFSET UNITYSDK_OFFSET(0x1A08BDB0)
#define SYSTEM_CONVERT_TOUINT64_5_OFFSET UNITYSDK_OFFSET(0x1A08BE20)
#define SYSTEM_CONVERT_TOUINT64_6_OFFSET UNITYSDK_OFFSET(0x1A08BE30)
#define SYSTEM_CONVERT_TOUINT64_7_OFFSET UNITYSDK_OFFSET(0x1A08BEA0)
#define SYSTEM_CONVERT_TOUINT64_8_OFFSET UNITYSDK_OFFSET(0x1A08BEB0)
#define SYSTEM_CONVERT_TOUINT64_9_OFFSET UNITYSDK_OFFSET(0x1A08BF20)
#define SYSTEM_CONVERT_TOUINT64_OFFSET UNITYSDK_OFFSET(0x1A08BAB0)
#define SYSTEM_CONVERT__CCTOR_OFFSET UNITYSDK_OFFSET(0x1A091600)

namespace System
{
	inline static constexpr unsigned int Convert_TypeDefinitionIndex = 222;

	class Convert : public ::System::Object
	{
	public:
		static ::System::Object** StaticGet_DBNull()
		{
			return (::System::Object**)Il2CppClass::FromTypeDefinitionIndex(Convert_TypeDefinitionIndex)->GetStaticField(0x45A0);
		}
		static ::Il2CppArray<::System::Char>** StaticGet_base64Table()
		{
			return (::Il2CppArray<::System::Char>**)Il2CppClass::FromTypeDefinitionIndex(Convert_TypeDefinitionIndex)->GetStaticField(0x45A8);
		}
		static ::System::RuntimeType** StaticGet_EnumType()
		{
			return (::System::RuntimeType**)Il2CppClass::FromTypeDefinitionIndex(Convert_TypeDefinitionIndex)->GetStaticField(0x45B0);
		}
		static ::Il2CppArray<::System::RuntimeType*>** StaticGet_ConvertTypes()
		{
			return (::Il2CppArray<::System::RuntimeType*>**)Il2CppClass::FromTypeDefinitionIndex(Convert_TypeDefinitionIndex)->GetStaticField(0x45B8);
		}
		// static const ::System::Int32 base64LineBreakPosition = 0x4C; // 0x0

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + SYSTEM_CONVERT__CCTOR_OFFSET))();
		}

		static ::System::TypeCode GetTypeCode(::System::Object* a1)
		{
			return ((::System::TypeCode(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_GETTYPECODE_OFFSET))(a1);
		}

		static ::System::Boolean IsDBNull(::System::Object* a1)
		{
			return ((::System::Boolean(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_ISDBNULL_OFFSET))(a1);
		}

		static ::System::Object* ChangeType(::System::Object* a1, ::System::TypeCode a2)
		{
			return ((::System::Object*(*)(::System::Object*, ::System::TypeCode))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_CHANGETYPE_OFFSET))(a1, a2);
		}

		static ::System::Object* ChangeType_1(::System::Object* a1, ::System::TypeCode a2, ::System::IFormatProvider* a3)
		{
			return ((::System::Object*(*)(::System::Object*, ::System::TypeCode, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_CHANGETYPE_1_OFFSET))(a1, a2, a3);
		}

		static ::System::Object* DefaultToType(::System::IConvertible* a1, ::System::Type* a2, ::System::IFormatProvider* a3)
		{
			return ((::System::Object*(*)(::System::IConvertible*, ::System::Type*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_DEFAULTTOTYPE_OFFSET))(a1, a2, a3);
		}

		static ::System::Object* ChangeType_2(::System::Object* a1, ::System::Type* a2)
		{
			return ((::System::Object*(*)(::System::Object*, ::System::Type*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_CHANGETYPE_2_OFFSET))(a1, a2);
		}

		static ::System::Object* ChangeType_3(::System::Object* a1, ::System::Type* a2, ::System::IFormatProvider* a3)
		{
			return ((::System::Object*(*)(::System::Object*, ::System::Type*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_CHANGETYPE_3_OFFSET))(a1, a2, a3);
		}

		static ::System::Boolean ToBoolean(::System::Object* a1)
		{
			return ((::System::Boolean(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Boolean(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_1_OFFSET))(a1, a2);
		}

		static ::System::Boolean ToBoolean_2(::System::Boolean a1)
		{
			return ((::System::Boolean(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_2_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_3(::System::SByte a1)
		{
			return ((::System::Boolean(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_3_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_4(::System::Char a1)
		{
			return ((::System::Boolean(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_4_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_5(::System::Byte a1)
		{
			return ((::System::Boolean(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_5_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_6(::System::Int16 a1)
		{
			return ((::System::Boolean(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_6_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_7(::System::UInt16 a1)
		{
			return ((::System::Boolean(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_7_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_8(::System::Int32 a1)
		{
			return ((::System::Boolean(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_8_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_9(::System::UInt32 a1)
		{
			return ((::System::Boolean(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_9_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_10(::System::Int64 a1)
		{
			return ((::System::Boolean(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_10_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_11(::System::UInt64 a1)
		{
			return ((::System::Boolean(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_11_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_12(::System::String* a1)
		{
			return ((::System::Boolean(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_12_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_13(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Boolean(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_13_OFFSET))(a1, a2);
		}

		static ::System::Boolean ToBoolean_14(::System::Single a1)
		{
			return ((::System::Boolean(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_14_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_15(::System::Double a1)
		{
			return ((::System::Boolean(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_15_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_16(::System::Decimal a1)
		{
			return ((::System::Boolean(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_16_OFFSET))(a1);
		}

		static ::System::Boolean ToBoolean_17(::System::DateTime a1)
		{
			return ((::System::Boolean(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBOOLEAN_17_OFFSET))(a1);
		}

		static ::System::Char ToChar(::System::Object* a1)
		{
			return ((::System::Char(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_OFFSET))(a1);
		}

		static ::System::Char ToChar_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Char(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_1_OFFSET))(a1, a2);
		}

		static ::System::Char ToChar_2(::System::Boolean a1)
		{
			return ((::System::Char(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_2_OFFSET))(a1);
		}

		static ::System::Char ToChar_3(::System::Char a1)
		{
			return ((::System::Char(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_3_OFFSET))(a1);
		}

		static ::System::Char ToChar_4(::System::SByte a1)
		{
			return ((::System::Char(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_4_OFFSET))(a1);
		}

		static ::System::Char ToChar_5(::System::Byte a1)
		{
			return ((::System::Char(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_5_OFFSET))(a1);
		}

		static ::System::Char ToChar_6(::System::Int16 a1)
		{
			return ((::System::Char(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_6_OFFSET))(a1);
		}

		static ::System::Char ToChar_7(::System::UInt16 a1)
		{
			return ((::System::Char(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_7_OFFSET))(a1);
		}

		static ::System::Char ToChar_8(::System::Int32 a1)
		{
			return ((::System::Char(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_8_OFFSET))(a1);
		}

		static ::System::Char ToChar_9(::System::UInt32 a1)
		{
			return ((::System::Char(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_9_OFFSET))(a1);
		}

		static ::System::Char ToChar_10(::System::Int64 a1)
		{
			return ((::System::Char(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_10_OFFSET))(a1);
		}

		static ::System::Char ToChar_11(::System::UInt64 a1)
		{
			return ((::System::Char(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_11_OFFSET))(a1);
		}

		static ::System::Char ToChar_12(::System::String* a1)
		{
			return ((::System::Char(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_12_OFFSET))(a1);
		}

		static ::System::Char ToChar_13(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Char(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_13_OFFSET))(a1, a2);
		}

		static ::System::Char ToChar_14(::System::Single a1)
		{
			return ((::System::Char(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_14_OFFSET))(a1);
		}

		static ::System::Char ToChar_15(::System::Double a1)
		{
			return ((::System::Char(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_15_OFFSET))(a1);
		}

		static ::System::Char ToChar_16(::System::Decimal a1)
		{
			return ((::System::Char(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_16_OFFSET))(a1);
		}

		static ::System::Char ToChar_17(::System::DateTime a1)
		{
			return ((::System::Char(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOCHAR_17_OFFSET))(a1);
		}

		static ::System::SByte ToSByte(::System::Object* a1)
		{
			return ((::System::SByte(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::SByte(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_1_OFFSET))(a1, a2);
		}

		static ::System::SByte ToSByte_2(::System::Boolean a1)
		{
			return ((::System::SByte(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_2_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_3(::System::SByte a1)
		{
			return ((::System::SByte(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_3_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_4(::System::Char a1)
		{
			return ((::System::SByte(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_4_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_5(::System::Byte a1)
		{
			return ((::System::SByte(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_5_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_6(::System::Int16 a1)
		{
			return ((::System::SByte(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_6_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_7(::System::UInt16 a1)
		{
			return ((::System::SByte(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_7_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_8(::System::Int32 a1)
		{
			return ((::System::SByte(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_8_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_9(::System::UInt32 a1)
		{
			return ((::System::SByte(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_9_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_10(::System::Int64 a1)
		{
			return ((::System::SByte(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_10_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_11(::System::UInt64 a1)
		{
			return ((::System::SByte(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_11_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_12(::System::Single a1)
		{
			return ((::System::SByte(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_12_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_13(::System::Double a1)
		{
			return ((::System::SByte(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_13_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_14(::System::Decimal a1)
		{
			return ((::System::SByte(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_14_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_15(::System::String* a1)
		{
			return ((::System::SByte(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_15_OFFSET))(a1);
		}

		static ::System::SByte ToSByte_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::SByte(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_16_OFFSET))(a1, a2);
		}

		static ::System::SByte ToSByte_17(::System::DateTime a1)
		{
			return ((::System::SByte(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_17_OFFSET))(a1);
		}

		static ::System::Byte ToByte(::System::Object* a1)
		{
			return ((::System::Byte(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_OFFSET))(a1);
		}

		static ::System::Byte ToByte_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Byte(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_1_OFFSET))(a1, a2);
		}

		static ::System::Byte ToByte_2(::System::Boolean a1)
		{
			return ((::System::Byte(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_2_OFFSET))(a1);
		}

		static ::System::Byte ToByte_3(::System::Byte a1)
		{
			return ((::System::Byte(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_3_OFFSET))(a1);
		}

		static ::System::Byte ToByte_4(::System::Char a1)
		{
			return ((::System::Byte(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_4_OFFSET))(a1);
		}

		static ::System::Byte ToByte_5(::System::SByte a1)
		{
			return ((::System::Byte(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_5_OFFSET))(a1);
		}

		static ::System::Byte ToByte_6(::System::Int16 a1)
		{
			return ((::System::Byte(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_6_OFFSET))(a1);
		}

		static ::System::Byte ToByte_7(::System::UInt16 a1)
		{
			return ((::System::Byte(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_7_OFFSET))(a1);
		}

		static ::System::Byte ToByte_8(::System::Int32 a1)
		{
			return ((::System::Byte(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_8_OFFSET))(a1);
		}

		static ::System::Byte ToByte_9(::System::UInt32 a1)
		{
			return ((::System::Byte(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_9_OFFSET))(a1);
		}

		static ::System::Byte ToByte_10(::System::Int64 a1)
		{
			return ((::System::Byte(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_10_OFFSET))(a1);
		}

		static ::System::Byte ToByte_11(::System::UInt64 a1)
		{
			return ((::System::Byte(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_11_OFFSET))(a1);
		}

		static ::System::Byte ToByte_12(::System::Single a1)
		{
			return ((::System::Byte(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_12_OFFSET))(a1);
		}

		static ::System::Byte ToByte_13(::System::Double a1)
		{
			return ((::System::Byte(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_13_OFFSET))(a1);
		}

		static ::System::Byte ToByte_14(::System::Decimal a1)
		{
			return ((::System::Byte(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_14_OFFSET))(a1);
		}

		static ::System::Byte ToByte_15(::System::String* a1)
		{
			return ((::System::Byte(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_15_OFFSET))(a1);
		}

		static ::System::Byte ToByte_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Byte(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_16_OFFSET))(a1, a2);
		}

		static ::System::Byte ToByte_17(::System::DateTime a1)
		{
			return ((::System::Byte(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_17_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16(::System::Object* a1)
		{
			return ((::System::Int16(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Int16(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_1_OFFSET))(a1, a2);
		}

		static ::System::Int16 ToInt16_2(::System::Boolean a1)
		{
			return ((::System::Int16(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_2_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_3(::System::Char a1)
		{
			return ((::System::Int16(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_3_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_4(::System::SByte a1)
		{
			return ((::System::Int16(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_4_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_5(::System::Byte a1)
		{
			return ((::System::Int16(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_5_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_6(::System::UInt16 a1)
		{
			return ((::System::Int16(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_6_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_7(::System::Int32 a1)
		{
			return ((::System::Int16(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_7_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_8(::System::UInt32 a1)
		{
			return ((::System::Int16(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_8_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_9(::System::Int16 a1)
		{
			return ((::System::Int16(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_9_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_10(::System::Int64 a1)
		{
			return ((::System::Int16(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_10_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_11(::System::UInt64 a1)
		{
			return ((::System::Int16(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_11_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_12(::System::Single a1)
		{
			return ((::System::Int16(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_12_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_13(::System::Double a1)
		{
			return ((::System::Int16(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_13_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_14(::System::Decimal a1)
		{
			return ((::System::Int16(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_14_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_15(::System::String* a1)
		{
			return ((::System::Int16(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_15_OFFSET))(a1);
		}

		static ::System::Int16 ToInt16_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Int16(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_16_OFFSET))(a1, a2);
		}

		static ::System::Int16 ToInt16_17(::System::DateTime a1)
		{
			return ((::System::Int16(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_17_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16(::System::Object* a1)
		{
			return ((::System::UInt16(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::UInt16(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_1_OFFSET))(a1, a2);
		}

		static ::System::UInt16 ToUInt16_2(::System::Boolean a1)
		{
			return ((::System::UInt16(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_2_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_3(::System::Char a1)
		{
			return ((::System::UInt16(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_3_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_4(::System::SByte a1)
		{
			return ((::System::UInt16(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_4_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_5(::System::Byte a1)
		{
			return ((::System::UInt16(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_5_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_6(::System::Int16 a1)
		{
			return ((::System::UInt16(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_6_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_7(::System::Int32 a1)
		{
			return ((::System::UInt16(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_7_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_8(::System::UInt16 a1)
		{
			return ((::System::UInt16(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_8_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_9(::System::UInt32 a1)
		{
			return ((::System::UInt16(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_9_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_10(::System::Int64 a1)
		{
			return ((::System::UInt16(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_10_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_11(::System::UInt64 a1)
		{
			return ((::System::UInt16(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_11_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_12(::System::Single a1)
		{
			return ((::System::UInt16(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_12_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_13(::System::Double a1)
		{
			return ((::System::UInt16(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_13_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_14(::System::Decimal a1)
		{
			return ((::System::UInt16(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_14_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_15(::System::String* a1)
		{
			return ((::System::UInt16(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_15_OFFSET))(a1);
		}

		static ::System::UInt16 ToUInt16_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::UInt16(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_16_OFFSET))(a1, a2);
		}

		static ::System::UInt16 ToUInt16_17(::System::DateTime a1)
		{
			return ((::System::UInt16(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_17_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32(::System::Object* a1)
		{
			return ((::System::Int32(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Int32(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_1_OFFSET))(a1, a2);
		}

		static ::System::Int32 ToInt32_2(::System::Boolean a1)
		{
			return ((::System::Int32(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_2_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_3(::System::Char a1)
		{
			return ((::System::Int32(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_3_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_4(::System::SByte a1)
		{
			return ((::System::Int32(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_4_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_5(::System::Byte a1)
		{
			return ((::System::Int32(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_5_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_6(::System::Int16 a1)
		{
			return ((::System::Int32(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_6_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_7(::System::UInt16 a1)
		{
			return ((::System::Int32(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_7_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_8(::System::UInt32 a1)
		{
			return ((::System::Int32(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_8_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_9(::System::Int32 a1)
		{
			return ((::System::Int32(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_9_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_10(::System::Int64 a1)
		{
			return ((::System::Int32(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_10_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_11(::System::UInt64 a1)
		{
			return ((::System::Int32(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_11_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_12(::System::Single a1)
		{
			return ((::System::Int32(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_12_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_13(::System::Double a1)
		{
			return ((::System::Int32(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_13_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_14(::System::Decimal a1)
		{
			return ((::System::Int32(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_14_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_15(::System::String* a1)
		{
			return ((::System::Int32(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_15_OFFSET))(a1);
		}

		static ::System::Int32 ToInt32_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Int32(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_16_OFFSET))(a1, a2);
		}

		static ::System::Int32 ToInt32_17(::System::DateTime a1)
		{
			return ((::System::Int32(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_17_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32(::System::Object* a1)
		{
			return ((::System::UInt32(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::UInt32(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_1_OFFSET))(a1, a2);
		}

		static ::System::UInt32 ToUInt32_2(::System::Boolean a1)
		{
			return ((::System::UInt32(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_2_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_3(::System::Char a1)
		{
			return ((::System::UInt32(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_3_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_4(::System::SByte a1)
		{
			return ((::System::UInt32(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_4_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_5(::System::Byte a1)
		{
			return ((::System::UInt32(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_5_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_6(::System::Int16 a1)
		{
			return ((::System::UInt32(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_6_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_7(::System::UInt16 a1)
		{
			return ((::System::UInt32(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_7_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_8(::System::Int32 a1)
		{
			return ((::System::UInt32(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_8_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_9(::System::UInt32 a1)
		{
			return ((::System::UInt32(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_9_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_10(::System::Int64 a1)
		{
			return ((::System::UInt32(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_10_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_11(::System::UInt64 a1)
		{
			return ((::System::UInt32(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_11_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_12(::System::Single a1)
		{
			return ((::System::UInt32(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_12_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_13(::System::Double a1)
		{
			return ((::System::UInt32(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_13_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_14(::System::Decimal a1)
		{
			return ((::System::UInt32(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_14_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_15(::System::String* a1)
		{
			return ((::System::UInt32(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_15_OFFSET))(a1);
		}

		static ::System::UInt32 ToUInt32_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::UInt32(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_16_OFFSET))(a1, a2);
		}

		static ::System::UInt32 ToUInt32_17(::System::DateTime a1)
		{
			return ((::System::UInt32(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_17_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64(::System::Object* a1)
		{
			return ((::System::Int64(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Int64(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_1_OFFSET))(a1, a2);
		}

		static ::System::Int64 ToInt64_2(::System::Boolean a1)
		{
			return ((::System::Int64(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_2_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_3(::System::Char a1)
		{
			return ((::System::Int64(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_3_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_4(::System::SByte a1)
		{
			return ((::System::Int64(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_4_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_5(::System::Byte a1)
		{
			return ((::System::Int64(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_5_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_6(::System::Int16 a1)
		{
			return ((::System::Int64(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_6_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_7(::System::UInt16 a1)
		{
			return ((::System::Int64(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_7_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_8(::System::Int32 a1)
		{
			return ((::System::Int64(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_8_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_9(::System::UInt32 a1)
		{
			return ((::System::Int64(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_9_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_10(::System::UInt64 a1)
		{
			return ((::System::Int64(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_10_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_11(::System::Int64 a1)
		{
			return ((::System::Int64(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_11_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_12(::System::Single a1)
		{
			return ((::System::Int64(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_12_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_13(::System::Double a1)
		{
			return ((::System::Int64(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_13_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_14(::System::Decimal a1)
		{
			return ((::System::Int64(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_14_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_15(::System::String* a1)
		{
			return ((::System::Int64(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_15_OFFSET))(a1);
		}

		static ::System::Int64 ToInt64_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Int64(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_16_OFFSET))(a1, a2);
		}

		static ::System::Int64 ToInt64_17(::System::DateTime a1)
		{
			return ((::System::Int64(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_17_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64(::System::Object* a1)
		{
			return ((::System::UInt64(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::UInt64(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_1_OFFSET))(a1, a2);
		}

		static ::System::UInt64 ToUInt64_2(::System::Boolean a1)
		{
			return ((::System::UInt64(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_2_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_3(::System::Char a1)
		{
			return ((::System::UInt64(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_3_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_4(::System::SByte a1)
		{
			return ((::System::UInt64(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_4_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_5(::System::Byte a1)
		{
			return ((::System::UInt64(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_5_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_6(::System::Int16 a1)
		{
			return ((::System::UInt64(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_6_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_7(::System::UInt16 a1)
		{
			return ((::System::UInt64(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_7_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_8(::System::Int32 a1)
		{
			return ((::System::UInt64(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_8_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_9(::System::UInt32 a1)
		{
			return ((::System::UInt64(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_9_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_10(::System::Int64 a1)
		{
			return ((::System::UInt64(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_10_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_11(::System::UInt64 a1)
		{
			return ((::System::UInt64(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_11_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_12(::System::Single a1)
		{
			return ((::System::UInt64(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_12_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_13(::System::Double a1)
		{
			return ((::System::UInt64(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_13_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_14(::System::Decimal a1)
		{
			return ((::System::UInt64(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_14_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_15(::System::String* a1)
		{
			return ((::System::UInt64(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_15_OFFSET))(a1);
		}

		static ::System::UInt64 ToUInt64_16(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::UInt64(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_16_OFFSET))(a1, a2);
		}

		static ::System::UInt64 ToUInt64_17(::System::DateTime a1)
		{
			return ((::System::UInt64(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_17_OFFSET))(a1);
		}

		static ::System::Single ToSingle(::System::Object* a1)
		{
			return ((::System::Single(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_OFFSET))(a1);
		}

		static ::System::Single ToSingle_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Single(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_1_OFFSET))(a1, a2);
		}

		static ::System::Single ToSingle_2(::System::SByte a1)
		{
			return ((::System::Single(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_2_OFFSET))(a1);
		}

		static ::System::Single ToSingle_3(::System::Byte a1)
		{
			return ((::System::Single(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_3_OFFSET))(a1);
		}

		static ::System::Single ToSingle_4(::System::Char a1)
		{
			return ((::System::Single(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_4_OFFSET))(a1);
		}

		static ::System::Single ToSingle_5(::System::Int16 a1)
		{
			return ((::System::Single(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_5_OFFSET))(a1);
		}

		static ::System::Single ToSingle_6(::System::UInt16 a1)
		{
			return ((::System::Single(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_6_OFFSET))(a1);
		}

		static ::System::Single ToSingle_7(::System::Int32 a1)
		{
			return ((::System::Single(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_7_OFFSET))(a1);
		}

		static ::System::Single ToSingle_8(::System::UInt32 a1)
		{
			return ((::System::Single(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_8_OFFSET))(a1);
		}

		static ::System::Single ToSingle_9(::System::Int64 a1)
		{
			return ((::System::Single(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_9_OFFSET))(a1);
		}

		static ::System::Single ToSingle_10(::System::UInt64 a1)
		{
			return ((::System::Single(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_10_OFFSET))(a1);
		}

		static ::System::Single ToSingle_11(::System::Single a1)
		{
			return ((::System::Single(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_11_OFFSET))(a1);
		}

		static ::System::Single ToSingle_12(::System::Double a1)
		{
			return ((::System::Single(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_12_OFFSET))(a1);
		}

		static ::System::Single ToSingle_13(::System::Decimal a1)
		{
			return ((::System::Single(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_13_OFFSET))(a1);
		}

		static ::System::Single ToSingle_14(::System::String* a1)
		{
			return ((::System::Single(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_14_OFFSET))(a1);
		}

		static ::System::Single ToSingle_15(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Single(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_15_OFFSET))(a1, a2);
		}

		static ::System::Single ToSingle_16(::System::Boolean a1)
		{
			return ((::System::Single(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_16_OFFSET))(a1);
		}

		static ::System::Single ToSingle_17(::System::DateTime a1)
		{
			return ((::System::Single(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSINGLE_17_OFFSET))(a1);
		}

		static ::System::Double ToDouble(::System::Object* a1)
		{
			return ((::System::Double(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_OFFSET))(a1);
		}

		static ::System::Double ToDouble_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Double(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_1_OFFSET))(a1, a2);
		}

		static ::System::Double ToDouble_2(::System::SByte a1)
		{
			return ((::System::Double(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_2_OFFSET))(a1);
		}

		static ::System::Double ToDouble_3(::System::Byte a1)
		{
			return ((::System::Double(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_3_OFFSET))(a1);
		}

		static ::System::Double ToDouble_4(::System::Int16 a1)
		{
			return ((::System::Double(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_4_OFFSET))(a1);
		}

		static ::System::Double ToDouble_5(::System::Char a1)
		{
			return ((::System::Double(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_5_OFFSET))(a1);
		}

		static ::System::Double ToDouble_6(::System::UInt16 a1)
		{
			return ((::System::Double(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_6_OFFSET))(a1);
		}

		static ::System::Double ToDouble_7(::System::Int32 a1)
		{
			return ((::System::Double(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_7_OFFSET))(a1);
		}

		static ::System::Double ToDouble_8(::System::UInt32 a1)
		{
			return ((::System::Double(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_8_OFFSET))(a1);
		}

		static ::System::Double ToDouble_9(::System::Int64 a1)
		{
			return ((::System::Double(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_9_OFFSET))(a1);
		}

		static ::System::Double ToDouble_10(::System::UInt64 a1)
		{
			return ((::System::Double(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_10_OFFSET))(a1);
		}

		static ::System::Double ToDouble_11(::System::Single a1)
		{
			return ((::System::Double(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_11_OFFSET))(a1);
		}

		static ::System::Double ToDouble_12(::System::Double a1)
		{
			return ((::System::Double(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_12_OFFSET))(a1);
		}

		static ::System::Double ToDouble_13(::System::Decimal a1)
		{
			return ((::System::Double(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_13_OFFSET))(a1);
		}

		static ::System::Double ToDouble_14(::System::String* a1)
		{
			return ((::System::Double(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_14_OFFSET))(a1);
		}

		static ::System::Double ToDouble_15(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Double(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_15_OFFSET))(a1, a2);
		}

		static ::System::Double ToDouble_16(::System::Boolean a1)
		{
			return ((::System::Double(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_16_OFFSET))(a1);
		}

		static ::System::Double ToDouble_17(::System::DateTime a1)
		{
			return ((::System::Double(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODOUBLE_17_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal(::System::Object* a1)
		{
			return ((::System::Decimal(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Decimal(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_1_OFFSET))(a1, a2);
		}

		static ::System::Decimal ToDecimal_2(::System::SByte a1)
		{
			return ((::System::Decimal(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_2_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_3(::System::Byte a1)
		{
			return ((::System::Decimal(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_3_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_4(::System::Char a1)
		{
			return ((::System::Decimal(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_4_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_5(::System::Int16 a1)
		{
			return ((::System::Decimal(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_5_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_6(::System::UInt16 a1)
		{
			return ((::System::Decimal(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_6_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_7(::System::Int32 a1)
		{
			return ((::System::Decimal(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_7_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_8(::System::UInt32 a1)
		{
			return ((::System::Decimal(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_8_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_9(::System::Int64 a1)
		{
			return ((::System::Decimal(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_9_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_10(::System::UInt64 a1)
		{
			return ((::System::Decimal(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_10_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_11(::System::Single a1)
		{
			return ((::System::Decimal(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_11_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_12(::System::Double a1)
		{
			return ((::System::Decimal(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_12_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_13(::System::String* a1)
		{
			return ((::System::Decimal(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_13_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_14(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::Decimal(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_14_OFFSET))(a1, a2);
		}

		static ::System::Decimal ToDecimal_15(::System::Decimal a1)
		{
			return ((::System::Decimal(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_15_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_16(::System::Boolean a1)
		{
			return ((::System::Decimal(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_16_OFFSET))(a1);
		}

		static ::System::Decimal ToDecimal_17(::System::DateTime a1)
		{
			return ((::System::Decimal(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODECIMAL_17_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime(::System::DateTime a1)
		{
			return ((::System::DateTime(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_1(::System::Object* a1)
		{
			return ((::System::DateTime(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_1_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_2(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::DateTime(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_2_OFFSET))(a1, a2);
		}

		static ::System::DateTime ToDateTime_3(::System::String* a1)
		{
			return ((::System::DateTime(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_3_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_4(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::DateTime(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_4_OFFSET))(a1, a2);
		}

		static ::System::DateTime ToDateTime_5(::System::SByte a1)
		{
			return ((::System::DateTime(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_5_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_6(::System::Byte a1)
		{
			return ((::System::DateTime(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_6_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_7(::System::Int16 a1)
		{
			return ((::System::DateTime(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_7_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_8(::System::UInt16 a1)
		{
			return ((::System::DateTime(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_8_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_9(::System::Int32 a1)
		{
			return ((::System::DateTime(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_9_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_10(::System::UInt32 a1)
		{
			return ((::System::DateTime(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_10_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_11(::System::Int64 a1)
		{
			return ((::System::DateTime(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_11_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_12(::System::UInt64 a1)
		{
			return ((::System::DateTime(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_12_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_13(::System::Boolean a1)
		{
			return ((::System::DateTime(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_13_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_14(::System::Char a1)
		{
			return ((::System::DateTime(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_14_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_15(::System::Single a1)
		{
			return ((::System::DateTime(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_15_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_16(::System::Double a1)
		{
			return ((::System::DateTime(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_16_OFFSET))(a1);
		}

		static ::System::DateTime ToDateTime_17(::System::Decimal a1)
		{
			return ((::System::DateTime(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TODATETIME_17_OFFSET))(a1);
		}

		static ::System::String* ToString(::System::Object* a1)
		{
			return ((::System::String*(*)(::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_OFFSET))(a1);
		}

		static ::System::String* ToString_1(::System::Object* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Object*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_1_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_2(::System::Boolean a1)
		{
			return ((::System::String*(*)(::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_2_OFFSET))(a1);
		}

		static ::System::String* ToString_3(::System::Boolean a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Boolean, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_3_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_4(::System::Char a1)
		{
			return ((::System::String*(*)(::System::Char))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_4_OFFSET))(a1);
		}

		static ::System::String* ToString_5(::System::Char a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Char, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_5_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_6(::System::SByte a1)
		{
			return ((::System::String*(*)(::System::SByte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_6_OFFSET))(a1);
		}

		static ::System::String* ToString_7(::System::SByte a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::SByte, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_7_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_8(::System::Byte a1)
		{
			return ((::System::String*(*)(::System::Byte))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_8_OFFSET))(a1);
		}

		static ::System::String* ToString_9(::System::Byte a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Byte, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_9_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_10(::System::Int16 a1)
		{
			return ((::System::String*(*)(::System::Int16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_10_OFFSET))(a1);
		}

		static ::System::String* ToString_11(::System::Int16 a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Int16, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_11_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_12(::System::UInt16 a1)
		{
			return ((::System::String*(*)(::System::UInt16))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_12_OFFSET))(a1);
		}

		static ::System::String* ToString_13(::System::UInt16 a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::UInt16, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_13_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_14(::System::Int32 a1)
		{
			return ((::System::String*(*)(::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_14_OFFSET))(a1);
		}

		static ::System::String* ToString_15(::System::Int32 a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Int32, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_15_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_16(::System::UInt32 a1)
		{
			return ((::System::String*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_16_OFFSET))(a1);
		}

		static ::System::String* ToString_17(::System::UInt32 a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::UInt32, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_17_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_18(::System::Int64 a1)
		{
			return ((::System::String*(*)(::System::Int64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_18_OFFSET))(a1);
		}

		static ::System::String* ToString_19(::System::Int64 a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Int64, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_19_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_20(::System::UInt64 a1)
		{
			return ((::System::String*(*)(::System::UInt64))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_20_OFFSET))(a1);
		}

		static ::System::String* ToString_21(::System::UInt64 a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::UInt64, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_21_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_22(::System::Single a1)
		{
			return ((::System::String*(*)(::System::Single))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_22_OFFSET))(a1);
		}

		static ::System::String* ToString_23(::System::Single a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Single, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_23_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_24(::System::Double a1)
		{
			return ((::System::String*(*)(::System::Double))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_24_OFFSET))(a1);
		}

		static ::System::String* ToString_25(::System::Double a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Double, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_25_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_26(::System::Decimal a1)
		{
			return ((::System::String*(*)(::System::Decimal))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_26_OFFSET))(a1);
		}

		static ::System::String* ToString_27(::System::Decimal a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::Decimal, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_27_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_28(::System::DateTime a1)
		{
			return ((::System::String*(*)(::System::DateTime))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_28_OFFSET))(a1);
		}

		static ::System::String* ToString_29(::System::DateTime a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::DateTime, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_29_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_30(::System::String* a1)
		{
			return ((::System::String*(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_30_OFFSET))(a1);
		}

		static ::System::String* ToString_31(::System::String* a1, ::System::IFormatProvider* a2)
		{
			return ((::System::String*(*)(::System::String*, ::System::IFormatProvider*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_31_OFFSET))(a1, a2);
		}

		static ::System::Byte ToByte_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::Byte(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBYTE_18_OFFSET))(a1, a2);
		}

		static ::System::SByte ToSByte_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::SByte(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSBYTE_18_OFFSET))(a1, a2);
		}

		static ::System::Int16 ToInt16_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::Int16(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT16_18_OFFSET))(a1, a2);
		}

		static ::System::UInt16 ToUInt16_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::UInt16(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT16_18_OFFSET))(a1, a2);
		}

		static ::System::Int32 ToInt32_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::Int32(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT32_18_OFFSET))(a1, a2);
		}

		static ::System::UInt32 ToUInt32_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::UInt32(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT32_18_OFFSET))(a1, a2);
		}

		static ::System::Int64 ToInt64_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::Int64(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOINT64_18_OFFSET))(a1, a2);
		}

		static ::System::UInt64 ToUInt64_18(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::UInt64(*)(::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOUINT64_18_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_32(::System::Byte a1, ::System::Int32 a2)
		{
			return ((::System::String*(*)(::System::Byte, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_32_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_33(::System::Int16 a1, ::System::Int32 a2)
		{
			return ((::System::String*(*)(::System::Int16, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_33_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_34(::System::Int32 a1, ::System::Int32 a2)
		{
			return ((::System::String*(*)(::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_34_OFFSET))(a1, a2);
		}

		static ::System::String* ToString_35(::System::Int64 a1, ::System::Int32 a2)
		{
			return ((::System::String*(*)(::System::Int64, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOSTRING_35_OFFSET))(a1, a2);
		}

		static ::System::String* ToBase64String(::Il2CppArray<::System::Byte>* a1)
		{
			return ((::System::String*(*)(::Il2CppArray<::System::Byte>*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64STRING_OFFSET))(a1);
		}

		static ::System::String* ToBase64String_1(::Il2CppArray<::System::Byte>* a1, ::System::Base64FormattingOptions a2)
		{
			return ((::System::String*(*)(::Il2CppArray<::System::Byte>*, ::System::Base64FormattingOptions))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64STRING_1_OFFSET))(a1, a2);
		}

		static ::System::String* ToBase64String_2(::Il2CppArray<::System::Byte>* a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::System::String*(*)(::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64STRING_2_OFFSET))(a1, a2, a3);
		}

		static ::System::String* ToBase64String_3(::Il2CppArray<::System::Byte>* a1, ::System::Int32 a2, ::System::Int32 a3, ::System::Base64FormattingOptions a4)
		{
			return ((::System::String*(*)(::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32, ::System::Base64FormattingOptions))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64STRING_3_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Int32 ToBase64CharArray(::Il2CppArray<::System::Byte>* a1, ::System::Int32 a2, ::System::Int32 a3, ::Il2CppArray<::System::Char>* a4, ::System::Int32 a5)
		{
			return ((::System::Int32(*)(::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32, ::Il2CppArray<::System::Char>*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64CHARARRAY_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Int32 ToBase64CharArray_1(::Il2CppArray<::System::Byte>* a1, ::System::Int32 a2, ::System::Int32 a3, ::Il2CppArray<::System::Char>* a4, ::System::Int32 a5, ::System::Base64FormattingOptions a6)
		{
			return ((::System::Int32(*)(::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32, ::Il2CppArray<::System::Char>*, ::System::Int32, ::System::Base64FormattingOptions))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64CHARARRAY_1_OFFSET))(a1, a2, a3, a4, a5, a6);
		}

		static ::System::Int32 ConvertToBase64Array(::System::Char* a1, ::System::Byte* a2, ::System::Int32 a3, ::System::Int32 a4, ::System::Boolean a5)
		{
			return ((::System::Int32(*)(::System::Char*, ::System::Byte*, ::System::Int32, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_CONVERTTOBASE64ARRAY_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Int32 ToBase64_CalculateAndValidateOutputLength(::System::Int32 a1, ::System::Boolean a2)
		{
			return ((::System::Int32(*)(::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_TOBASE64_CALCULATEANDVALIDATEOUTPUTLENGTH_OFFSET))(a1, a2);
		}

		static ::Il2CppArray<::System::Byte>* FromBase64String(::System::String* a1)
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_FROMBASE64STRING_OFFSET))(a1);
		}

		static ::Il2CppArray<::System::Byte>* FromBase64CharArray(::Il2CppArray<::System::Char>* a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::Il2CppArray<::System::Char>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_FROMBASE64CHARARRAY_OFFSET))(a1, a2, a3);
		}

		static ::Il2CppArray<::System::Byte>* FromBase64CharPtr(::System::Char* a1, ::System::Int32 a2)
		{
			return ((::Il2CppArray<::System::Byte>*(*)(::System::Char*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_FROMBASE64CHARPTR_OFFSET))(a1, a2);
		}

		static ::System::Int32 FromBase64_Decode(::System::Char* a1, ::System::Int32 a2, ::System::Byte* a3, ::System::Int32 a4)
		{
			return ((::System::Int32(*)(::System::Char*, ::System::Int32, ::System::Byte*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_FROMBASE64_DECODE_OFFSET))(a1, a2, a3, a4);
		}

		static ::System::Int32 FromBase64_ComputeResultLength(::System::Char* a1, ::System::Int32 a2)
		{
			return ((::System::Int32(*)(::System::Char*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_CONVERT_FROMBASE64_COMPUTERESULTLENGTH_OFFSET))(a1, a2);
		}
	};
}
