#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

class Class_1_9C0B4E74A45C3414;
namespace System { class String; }

#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_CREATE_OFFSET UNITYSDK_OFFSET(0xC286390)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_HEADICONPATH_OFFSET UNITYSDK_OFFSET(0xC285D80)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LARGEIMAGEMASKPATH_OFFSET UNITYSDK_OFFSET(0xC285F60)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LARGEIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xC285EC0)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LOGOICONINVERTCOLORPATH_OFFSET UNITYSDK_OFFSET(0xC286000)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LOGOICONPATH_OFFSET UNITYSDK_OFFSET(0xC2862E0)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_NAME_OFFSET UNITYSDK_OFFSET(0xC285CC0)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_SMALLIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xC285E20)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TALKONLOST_OFFSET UNITYSDK_OFFSET(0xC286160)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TALKONSTAGESELECT_OFFSET UNITYSDK_OFFSET(0xC286220)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TALKONWIN_OFFSET UNITYSDK_OFFSET(0xC2860A0)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TITLE_OFFSET UNITYSDK_OFFSET(0xC285C00)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET__ID_OFFSET UNITYSDK_OFFSET(0xC285B80)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET__ROW_OFFSET UNITYSDK_OFFSET(0xC285BA0)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_SET__ID_OFFSET UNITYSDK_OFFSET(0xC285B90)
#define RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xC286380)

namespace RPG::Client::DiceCombat
{
	inline static constexpr unsigned int DiceCombatV2OpponentData_TypeDefinitionIndex = 72240;

	class DiceCombatV2OpponentData : public ::System::Object
	{
	public:
		::System::UInt32 __ID_k__BackingField; // 0x10

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA__CTOR_OFFSET))(this);
		}

		::System::UInt32 get__ID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET__ID_OFFSET))(this);
		}

		::System::Void set__ID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_SET__ID_OFFSET))(this, a1);
		}

		::Class_1_9C0B4E74A45C3414* get__Row()
		{
			return ((::Class_1_9C0B4E74A45C3414*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET__ROW_OFFSET))(this);
		}

		::RPG::Client::TextID get_Title()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TITLE_OFFSET))(this);
		}

		::RPG::Client::TextID get_Name()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_NAME_OFFSET))(this);
		}

		::System::String* get_HeadIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_HEADICONPATH_OFFSET))(this);
		}

		::System::String* get_SmallImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_SMALLIMAGEPATH_OFFSET))(this);
		}

		::System::String* get_LargeImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LARGEIMAGEPATH_OFFSET))(this);
		}

		::System::String* get_LargeImageMaskPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LARGEIMAGEMASKPATH_OFFSET))(this);
		}

		::System::String* get_LogoIconInvertColorPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LOGOICONINVERTCOLORPATH_OFFSET))(this);
		}

		::RPG::Client::TextID get_TalkOnWin()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TALKONWIN_OFFSET))(this);
		}

		::RPG::Client::TextID get_TalkOnLost()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TALKONLOST_OFFSET))(this);
		}

		::RPG::Client::TextID get_TalkOnStageSelect()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_TALKONSTAGESELECT_OFFSET))(this);
		}

		::System::String* get_LogoIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_GET_LOGOICONPATH_OFFSET))(this);
		}

		static ::RPG::Client::DiceCombat::DiceCombatV2OpponentData* Create(::System::UInt32 a1)
		{
			return ((::RPG::Client::DiceCombat::DiceCombatV2OpponentData*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_DICECOMBAT_DICECOMBATV2OPPONENTDATA_CREATE_OFFSET))(a1);
		}
	};
}
