#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/FateRin/BaseViewModel.h"
#include "unitysdk/RPG/Client/FateRin/Battle/FateRinBattleEnemyHudHideType.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/RPG/GameCore/FateRinActionIntentType.h"
#include "unitysdk/RPG/GameCore/FixPoint.h"
#include "unitysdk/RPG/GameCore/MonsterRank.h"
#include "unitysdk/RPG/MVector3.h"
#include "unitysdk/UnityEngine/Vector3.h"

class Class_0_16E4307DCC419505_1287;
class Class_0_16E4307DCC419505_311;
class Class_1_0471857D35382E2E;
class Class_1_27B9ED3C765FAC5D;
class Class_1_5F4D64A4B97E38F9;
class Class_1_64EA8B4AB59D91C7_3;
class Class_1_64EA8B4AB59D91C7_4;
class Class_1_64EA8B4AB59D91C7_5;
class Class_1_6D8109111168D15F;
class Class_1_75C3EB54EC08BE44_2;
class Class_1_916A609943E0EE80_1;
class Class_1_B26E06FC40F846CD;
class Class_1_B9D6E7E76075C6E2_3;
class Class_1_E79EE3670D2EC49A;
class Class_1_F9FBCC956DFCF137_35;
class Class_1_F9FBCC956DFCF137_37;
namespace RPG::Client::FateRin { class ViewModelEventHandler; }
namespace RPG::Client::FateRin { template <typename T> class ViewModelEventHandler_1; }
namespace RPG::Client::FateRin::Battle { class IFateRinBattleEnemyEnergyBarViewModel; }
namespace RPG::Client::FateRin::Battle { class IFateRinBattleEnemySpecialMarkViewModel; }
namespace RPG::GameCore { class CharacterDataComponent; }
namespace RPG::GameCore { class CharacterModelComponent; }
namespace RPG::GameCore { class GameEntity; }
namespace System { class Object; }
namespace System { class String; }
namespace System { template <typename T1, typename T2, typename T3> class Action_3; }
namespace System::Collections::Generic { template <typename T> class List_1; }
namespace XLua { class LuaTable; }

#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADDMESSAGEHANDLER_OFFSET UNITYSDK_OFFSET(0xC47C0C0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADD_ONHPCHANGEWITHDELTA_OFFSET UNITYSDK_OFFSET(0xC47D910)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADD_ONPOSCHANGE_OFFSET UNITYSDK_OFFSET(0xC47DA90)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADD_ONSTATUSCHANGE_OFFSET UNITYSDK_OFFSET(0xC47D9D0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_DISPOSE_OFFSET UNITYSDK_OFFSET(0xC47B8B0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_BATTLEEVENTSPECIALMARKAREA_OFFSET UNITYSDK_OFFSET(0xC47D720)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CHARACTERDATACOMPONENT_OFFSET UNITYSDK_OFFSET(0xC47CD10)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CHARACTERHUDOFFSET_OFFSET UNITYSDK_OFFSET(0xC47CD90)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CHARACTERMODELCOMPONENT_OFFSET UNITYSDK_OFFSET(0xC47CC90)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CURHP_OFFSET UNITYSDK_OFFSET(0xC47CF40)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CURPHASE_OFFSET UNITYSDK_OFFSET(0xC47D3D0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ENERGYBARAREA_OFFSET UNITYSDK_OFFSET(0xC47D700)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ENTITY_OFFSET UNITYSDK_OFFSET(0xC47CC40)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_HEADROUNDICONPATH_OFFSET UNITYSDK_OFFSET(0xC47D4E0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_HPPERCENT_OFFSET UNITYSDK_OFFSET(0xC47CFB0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ID_OFFSET UNITYSDK_OFFSET(0xC47B9E0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_INTENTTYPELIST_OFFSET UNITYSDK_OFFSET(0xC47CBA0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_INTENTTYPEUISTATELIST_OFFSET UNITYSDK_OFFSET(0xC47CBF0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISALIVE_OFFSET UNITYSDK_OFFSET(0xC47D8F0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISBOSS_OFFSET UNITYSDK_OFFSET(0xC47D330)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISHAVEBLOCKSHIELD_OFFSET UNITYSDK_OFFSET(0xC47D530)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISHUDSHOW_OFFSET UNITYSDK_OFFSET(0xC47D6B0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISSHORTHPBAR_OFFSET UNITYSDK_OFFSET(0xC47D8A0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISSHOWINTENT_OFFSET UNITYSDK_OFFSET(0xC47D800)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_MAXPHASE_OFFSET UNITYSDK_OFFSET(0xC47D420)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_NAME_OFFSET UNITYSDK_OFFSET(0xC47D470)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_NAVIGATETOTEAMDETAIL_OFFSET UNITYSDK_OFFSET(0xC47D740)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_POSINDEX_OFFSET UNITYSDK_OFFSET(0xC47D7E0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_PREVIEWHPPERCENT_OFFSET UNITYSDK_OFFSET(0xC47D080)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_PREVIEWSHIELDPERCENT_OFFSET UNITYSDK_OFFSET(0xC47D240)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_RANK_OFFSET UNITYSDK_OFFSET(0xC47D380)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_SHIELDPERCENT_OFFSET UNITYSDK_OFFSET(0xC47D170)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_SPECIALMARKAREA_OFFSET UNITYSDK_OFFSET(0xC47D710)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_STATUSAREA_OFFSET UNITYSDK_OFFSET(0xC47D730)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_WORLDPOS_OFFSET UNITYSDK_OFFSET(0xC47D750)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_REMOVE_ONHPCHANGEWITHDELTA_OFFSET UNITYSDK_OFFSET(0xC47D970)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_REMOVE_ONPOSCHANGE_OFFSET UNITYSDK_OFFSET(0xC47DAF0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_REMOVE_ONSTATUSCHANGE_OFFSET UNITYSDK_OFFSET(0xC47DA30)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_SETPOSINDEX_OFFSET UNITYSDK_OFFSET(0xC47C040)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_SET_ISALIVE_OFFSET UNITYSDK_OFFSET(0xC47D900)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_SET_POSINDEX_OFFSET UNITYSDK_OFFSET(0xC47D7F0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xC47BA60)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__DOHUDSHOWCHANGE_OFFSET UNITYSDK_OFFSET(0xC47C680)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__NAVIGATETOTEAMDETAIL_OFFSET UNITYSDK_OFFSET(0xC47CAD0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYISHUDSHOWCHANGEBYENERGYBARMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C750)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYISHUDSHOWCHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C610)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELALIVESTATEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C9F0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELBOSSINFOCHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C850)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELHPCHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C1A0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELHPCHANGEWITHDELTAMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C2D0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELINTENTCHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C3B0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELPHASECHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C4E0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEGAMESTATEMODELCHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C930)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLESTATUSESMODELCHANGEMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C8A0)
#define RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__SENDMESSAGE_OFFSET UNITYSDK_OFFSET(0xC47C120)

namespace RPG::Client::FateRin::Battle
{
	inline static constexpr unsigned int FateRinBattleEnemyHudSingleViewModel_TypeDefinitionIndex = 75905;

	class FateRinBattleEnemyHudSingleViewModel : public ::RPG::Client::FateRin::BaseViewModel
	{
	public:
		::RPG::Client::FateRin::Battle::IFateRinBattleEnemySpecialMarkViewModel* _BattleEventSpecialMarkArea_k__BackingField; // 0x20
		::Class_1_B26E06FC40F846CD* _GameStateModel; // 0x28
		::RPG::Client::FateRin::Battle::IFateRinBattleEnemyEnergyBarViewModel* _EnergyBarArea_k__BackingField; // 0x30
		::RPG::Client::FateRin::Battle::IFateRinBattleEnemySpecialMarkViewModel* _SpecialMarkArea_k__BackingField; // 0x38
		::Class_1_0471857D35382E2E* _Model; // 0x40
		::System::Action_3<::XLua::LuaTable*, ::System::Int32, ::System::Object*>* _MessageHandler; // 0x48
		::XLua::LuaTable* _LuaTable; // 0x50
		::Class_0_16E4307DCC419505_1287* _StatusArea_k__BackingField; // 0x58
		::RPG::Client::FateRin::ViewModelEventHandler* OnStatusChange; // 0x60
		::RPG::Client::FateRin::ViewModelEventHandler_1<::RPG::GameCore::FixPoint>* OnHPChangeWithDelta; // 0x68
		::RPG::Client::FateRin::ViewModelEventHandler* OnPosChange; // 0x70
		::Class_0_16E4307DCC419505_311* _NavigateToTeamDetail_k__BackingField; // 0x78
		::Class_1_E79EE3670D2EC49A* _UIPresentService; // 0x80
		::System::Boolean _IsAlive_k__BackingField; // 0x88
		::RPG::Client::FateRin::Battle::FateRinBattleEnemyHudHideType _HudHideType; // 0x8C
		::System::UInt32 _PosIndex_k__BackingField; // 0x90

		::System::Void _ctor(::Class_1_0471857D35382E2E* a1, ::Class_1_B26E06FC40F846CD* a2, ::Class_1_5F4D64A4B97E38F9* a3, ::Class_1_E79EE3670D2EC49A* a4)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_0471857D35382E2E*, ::Class_1_B26E06FC40F846CD*, ::Class_1_5F4D64A4B97E38F9*, ::Class_1_E79EE3670D2EC49A*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__CTOR_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void Dispose()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_DISPOSE_OFFSET))(this);
		}

		::System::Void SetPosIndex(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_SETPOSINDEX_OFFSET))(this, a1);
		}

		::System::Void AddMessageHandler(::XLua::LuaTable* a1, ::System::Action_3<::XLua::LuaTable*, ::System::Int32, ::System::Object*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::XLua::LuaTable*, ::System::Action_3<::XLua::LuaTable*, ::System::Int32, ::System::Object*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADDMESSAGEHANDLER_OFFSET))(this, a1, a2);
		}

		::System::Void _SendMessage(::System::Int32 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__SENDMESSAGE_OFFSET))(this, a1, a2);
		}

		::System::Void _OnBattleEnemyStateModelHPChangeMessage(::Class_1_64EA8B4AB59D91C7_3* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_64EA8B4AB59D91C7_3*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELHPCHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyStateModelHPChangeWithDeltaMessage(::Class_1_6D8109111168D15F* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_6D8109111168D15F*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELHPCHANGEWITHDELTAMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyStateModelIntentChangeMessage(::Class_1_64EA8B4AB59D91C7_4* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_64EA8B4AB59D91C7_4*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELINTENTCHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyStateModelPhaseChangeMessage(::Class_1_64EA8B4AB59D91C7_5* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_64EA8B4AB59D91C7_5*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELPHASECHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyIsHudShowChangeMessage(::Class_1_27B9ED3C765FAC5D* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_27B9ED3C765FAC5D*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYISHUDSHOWCHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyIsHudShowChangeByEnergyBarMessage(::Class_1_916A609943E0EE80_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_916A609943E0EE80_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYISHUDSHOWCHANGEBYENERGYBARMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyStateModelBossInfoChangeMessage(::Class_1_F9FBCC956DFCF137_35* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_F9FBCC956DFCF137_35*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELBOSSINFOCHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleStatusesModelChangeMessage(::Class_1_B9D6E7E76075C6E2_3* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_B9D6E7E76075C6E2_3*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLESTATUSESMODELCHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleGameStateModelChangeMessage(::Class_1_F9FBCC956DFCF137_37* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_F9FBCC956DFCF137_37*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEGAMESTATEMODELCHANGEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _OnBattleEnemyStateModelAliveStateMessage(::Class_1_75C3EB54EC08BE44_2* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_75C3EB54EC08BE44_2*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__ONBATTLEENEMYSTATEMODELALIVESTATEMESSAGE_OFFSET))(this, a1);
		}

		::System::Void _NavigateToTeamDetail()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__NAVIGATETOTEAMDETAIL_OFFSET))(this);
		}

		::System::Void _DoHudShowChange(::System::Boolean a1, ::RPG::Client::FateRin::Battle::FateRinBattleEnemyHudHideType a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::RPG::Client::FateRin::Battle::FateRinBattleEnemyHudHideType))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL__DOHUDSHOWCHANGE_OFFSET))(this, a1, a2);
		}

		::System::UInt32 get_ID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ID_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::RPG::GameCore::FateRinActionIntentType>* get_IntentTypeList()
		{
			return ((::System::Collections::Generic::List_1<::RPG::GameCore::FateRinActionIntentType>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_INTENTTYPELIST_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::String*>* get_IntentTypeUIStateList()
		{
			return ((::System::Collections::Generic::List_1<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_INTENTTYPEUISTATELIST_OFFSET))(this);
		}

		::RPG::GameCore::GameEntity* get_Entity()
		{
			return ((::RPG::GameCore::GameEntity*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ENTITY_OFFSET))(this);
		}

		::RPG::GameCore::CharacterModelComponent* get_CharacterModelComponent()
		{
			return ((::RPG::GameCore::CharacterModelComponent*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CHARACTERMODELCOMPONENT_OFFSET))(this);
		}

		::RPG::GameCore::CharacterDataComponent* get_CharacterDataComponent()
		{
			return ((::RPG::GameCore::CharacterDataComponent*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CHARACTERDATACOMPONENT_OFFSET))(this);
		}

		::UnityEngine::Vector3 get_CharacterHUDOffset()
		{
			return ((::UnityEngine::Vector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CHARACTERHUDOFFSET_OFFSET))(this);
		}

		::System::Int64 get_CurHP()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CURHP_OFFSET))(this);
		}

		::System::Single get_HPPercent()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_HPPERCENT_OFFSET))(this);
		}

		::System::Single get_PreviewHPPercent()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_PREVIEWHPPERCENT_OFFSET))(this);
		}

		::System::Single get_ShieldPercent()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_SHIELDPERCENT_OFFSET))(this);
		}

		::System::Single get_PreviewShieldPercent()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_PREVIEWSHIELDPERCENT_OFFSET))(this);
		}

		::System::Boolean get_IsBoss()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISBOSS_OFFSET))(this);
		}

		::RPG::GameCore::MonsterRank get_Rank()
		{
			return ((::RPG::GameCore::MonsterRank(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_RANK_OFFSET))(this);
		}

		::System::UInt32 get_CurPhase()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_CURPHASE_OFFSET))(this);
		}

		::System::UInt32 get_MaxPhase()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_MAXPHASE_OFFSET))(this);
		}

		::RPG::Client::TextID get_Name()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_NAME_OFFSET))(this);
		}

		::System::String* get_HeadRoundIconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_HEADROUNDICONPATH_OFFSET))(this);
		}

		::System::Boolean get_IsHaveBlockShield()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISHAVEBLOCKSHIELD_OFFSET))(this);
		}

		::System::Boolean get_IsHudShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISHUDSHOW_OFFSET))(this);
		}

		::RPG::Client::FateRin::Battle::IFateRinBattleEnemyEnergyBarViewModel* get_EnergyBarArea()
		{
			return ((::RPG::Client::FateRin::Battle::IFateRinBattleEnemyEnergyBarViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ENERGYBARAREA_OFFSET))(this);
		}

		::RPG::Client::FateRin::Battle::IFateRinBattleEnemySpecialMarkViewModel* get_SpecialMarkArea()
		{
			return ((::RPG::Client::FateRin::Battle::IFateRinBattleEnemySpecialMarkViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_SPECIALMARKAREA_OFFSET))(this);
		}

		::RPG::Client::FateRin::Battle::IFateRinBattleEnemySpecialMarkViewModel* get_BattleEventSpecialMarkArea()
		{
			return ((::RPG::Client::FateRin::Battle::IFateRinBattleEnemySpecialMarkViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_BATTLEEVENTSPECIALMARKAREA_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_1287* get_StatusArea()
		{
			return ((::Class_0_16E4307DCC419505_1287*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_STATUSAREA_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_311* get_NavigateToTeamDetail()
		{
			return ((::Class_0_16E4307DCC419505_311*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_NAVIGATETOTEAMDETAIL_OFFSET))(this);
		}

		::RPG::MVector3 get_WorldPos()
		{
			return ((::RPG::MVector3(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_WORLDPOS_OFFSET))(this);
		}

		::System::UInt32 get_PosIndex()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_POSINDEX_OFFSET))(this);
		}

		::System::Void set_PosIndex(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_SET_POSINDEX_OFFSET))(this, a1);
		}

		::System::Boolean get_IsShowIntent()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISSHOWINTENT_OFFSET))(this);
		}

		::System::Boolean get_IsShortHPBar()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISSHORTHPBAR_OFFSET))(this);
		}

		::System::Boolean get_IsAlive()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_GET_ISALIVE_OFFSET))(this);
		}

		::System::Void set_IsAlive(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_SET_ISALIVE_OFFSET))(this, a1);
		}

		::System::Void add_OnHPChangeWithDelta(::RPG::Client::FateRin::ViewModelEventHandler_1<::RPG::GameCore::FixPoint>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler_1<::RPG::GameCore::FixPoint>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADD_ONHPCHANGEWITHDELTA_OFFSET))(this, a1);
		}

		::System::Void remove_OnHPChangeWithDelta(::RPG::Client::FateRin::ViewModelEventHandler_1<::RPG::GameCore::FixPoint>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler_1<::RPG::GameCore::FixPoint>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_REMOVE_ONHPCHANGEWITHDELTA_OFFSET))(this, a1);
		}

		::System::Void add_OnStatusChange(::RPG::Client::FateRin::ViewModelEventHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADD_ONSTATUSCHANGE_OFFSET))(this, a1);
		}

		::System::Void remove_OnStatusChange(::RPG::Client::FateRin::ViewModelEventHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_REMOVE_ONSTATUSCHANGE_OFFSET))(this, a1);
		}

		::System::Void add_OnPosChange(::RPG::Client::FateRin::ViewModelEventHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_ADD_ONPOSCHANGE_OFFSET))(this, a1);
		}

		::System::Void remove_OnPosChange(::RPG::Client::FateRin::ViewModelEventHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_BATTLE_FATERINBATTLEENEMYHUDSINGLEVIEWMODEL_REMOVE_ONPOSCHANGE_OFFSET))(this, a1);
		}
	};
}
