#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/FateRin/BaseViewModel.h"
#include "unitysdk/RPG/Client/TextID.h"

class Class_0_16E4307DCC419505_311;
class Class_1_96586C089CD5CA69;
class Class_1_F681AD6B57DC77A7;
namespace RPG::Client { class MonsterData; }
namespace RPG::Client::FateRin { class ViewModelEventHandler; }
namespace System { class Action; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class HashSet_1; }
namespace System::Collections::Generic { template <typename T> class IReadOnlyList_1; }
namespace System::Collections::Generic { template <typename T> class List_1; }
template <typename T> class Class_0_16E4307DCC419505_313;

#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_ADD_ONBUFFSELECTNUMCHANGE_OFFSET UNITYSDK_OFFSET(0xC4CBCE0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GETSELECTINGBUFFCOUNT_OFFSET UNITYSDK_OFFSET(0xC4CAD70)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GETSELECTINGDEEPBUFFCOUNT_OFFSET UNITYSDK_OFFSET(0xC4CAA30)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GETSELECTINGNORMALBUFFCOUNT_OFFSET UNITYSDK_OFFSET(0xC4CA790)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_BESTROUND_OFFSET UNITYSDK_OFFSET(0xC4CB8D0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_BUFFDESCLIST_OFFSET UNITYSDK_OFFSET(0xC4CB750)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_CLICKBUFF_OFFSET UNITYSDK_OFFSET(0xC4CBDA0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_DEEPBUFFUNLOCKLEVEL_OFFSET UNITYSDK_OFFSET(0xC4CB9A0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_DISPLAYTOTALBUFFCOUNT_OFFSET UNITYSDK_OFFSET(0xC4CBB00)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_FIGHTNAME_OFFSET UNITYSDK_OFFSET(0xC4CB770)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_FIRSTLISTBUFFCOUNT_OFFSET UNITYSDK_OFFSET(0xC4CA9A0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_HAVEPASSED_OFFSET UNITYSDK_OFFSET(0xC4CB920)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_ISBUFFSELECTING_OFFSET UNITYSDK_OFFSET(0xC4CA750)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_ISDEEPBUFFUNLOCKED_OFFSET UNITYSDK_OFFSET(0xC4CBA10)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_MONSTERDECOIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xC4CB830)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_MONSTERIMAGEPATH_OFFSET UNITYSDK_OFFSET(0xC4CB7D0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_PASSEDLEVEL_OFFSET UNITYSDK_OFFSET(0xC4CB880)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_TRIGGERBATTLE_OFFSET UNITYSDK_OFFSET(0xC4CBDB0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_REMOVE_ONBUFFSELECTNUMCHANGE_OFFSET UNITYSDK_OFFSET(0xC4CBD40)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_SAVESELECTEDBUFFINDEXES_OFFSET UNITYSDK_OFFSET(0xC4C9710)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_SET_BUFFDESCLIST_OFFSET UNITYSDK_OFFSET(0xC4CB760)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__BUILDBUFFINFO_OFFSET UNITYSDK_OFFSET(0xC4C9E20)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__BUILDINITSELECTION_OFFSET UNITYSDK_OFFSET(0xC4CA4B0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__CLICKBUFF_OFFSET UNITYSDK_OFFSET(0xC4CAFF0)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xC4C9130)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__GETSELECTINGBUFFIDS_OFFSET UNITYSDK_OFFSET(0xC4CB200)
#define RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__TRIGGERBATTLE_OFFSET UNITYSDK_OFFSET(0xC4CB170)

namespace RPG::Client::FateRin::Challenge
{
	inline static constexpr unsigned int FateRinChallengeLevelInfoViewModel_TypeDefinitionIndex = 76074;

	class FateRinChallengeLevelInfoViewModel : public ::RPG::Client::FateRin::BaseViewModel
	{
	public:
		::System::Action* _SaveSelectingBuffIndexesCallback; // 0x20
		::RPG::Client::MonsterData* _Monster; // 0x28
		::Class_1_F681AD6B57DC77A7* _Model; // 0x30
		::Class_0_16E4307DCC419505_313<::System::Int32>* _ClickBuff_k__BackingField; // 0x38
		::Class_1_96586C089CD5CA69* _Service; // 0x40
		::System::Collections::Generic::List_1<::System::Boolean>* _IsBuffSelecting; // 0x48
		::Class_0_16E4307DCC419505_311* _TriggerBattle_k__BackingField; // 0x50
		::RPG::Client::FateRin::ViewModelEventHandler* OnBuffSelectNumChange; // 0x58
		::System::Collections::Generic::IReadOnlyList_1<::System::String*>* _BuffDescList_k__BackingField; // 0x60

		::System::Void _ctor(::Class_1_F681AD6B57DC77A7* a1, ::System::Action* a2, ::Class_1_96586C089CD5CA69* a3)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_F681AD6B57DC77A7*, ::System::Action*, ::Class_1_96586C089CD5CA69*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__CTOR_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SaveSelectedBuffIndexes()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_SAVESELECTEDBUFFINDEXES_OFFSET))(this);
		}

		::System::UInt32 GetSelectingNormalBuffCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GETSELECTINGNORMALBUFFCOUNT_OFFSET))(this);
		}

		::System::UInt32 GetSelectingDeepBuffCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GETSELECTINGDEEPBUFFCOUNT_OFFSET))(this);
		}

		::System::UInt32 GetSelectingBuffCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GETSELECTINGBUFFCOUNT_OFFSET))(this);
		}

		::System::Void _BuildBuffInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__BUILDBUFFINFO_OFFSET))(this);
		}

		::System::Void _BuildInitSelection(::System::Collections::Generic::HashSet_1<::System::UInt32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::HashSet_1<::System::UInt32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__BUILDINITSELECTION_OFFSET))(this, a1);
		}

		::System::Void _ClickBuff(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__CLICKBUFF_OFFSET))(this, a1);
		}

		::System::Void _TriggerBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__TRIGGERBATTLE_OFFSET))(this);
		}

		::System::Collections::Generic::IReadOnlyList_1<::System::UInt32>* _GetSelectingBuffIDs()
		{
			return ((::System::Collections::Generic::IReadOnlyList_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL__GETSELECTINGBUFFIDS_OFFSET))(this);
		}

		::System::Collections::Generic::IReadOnlyList_1<::System::String*>* get_BuffDescList()
		{
			return ((::System::Collections::Generic::IReadOnlyList_1<::System::String*>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_BUFFDESCLIST_OFFSET))(this);
		}

		::System::Void set_BuffDescList(::System::Collections::Generic::IReadOnlyList_1<::System::String*>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Collections::Generic::IReadOnlyList_1<::System::String*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_SET_BUFFDESCLIST_OFFSET))(this, a1);
		}

		::System::Collections::Generic::IReadOnlyList_1<::System::Boolean>* get_IsBuffSelecting()
		{
			return ((::System::Collections::Generic::IReadOnlyList_1<::System::Boolean>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_ISBUFFSELECTING_OFFSET))(this);
		}

		::RPG::Client::TextID get_FightName()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_FIGHTNAME_OFFSET))(this);
		}

		::System::String* get_MonsterImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_MONSTERIMAGEPATH_OFFSET))(this);
		}

		::System::String* get_MonsterDecoImagePath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_MONSTERDECOIMAGEPATH_OFFSET))(this);
		}

		::System::UInt32 get_PassedLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_PASSEDLEVEL_OFFSET))(this);
		}

		::System::UInt32 get_BestRound()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_BESTROUND_OFFSET))(this);
		}

		::System::Boolean get_HavePassed()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_HAVEPASSED_OFFSET))(this);
		}

		::System::UInt32 get_DeepBuffUnlockLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_DEEPBUFFUNLOCKLEVEL_OFFSET))(this);
		}

		::System::Boolean get_IsDeepBuffUnlocked()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_ISDEEPBUFFUNLOCKED_OFFSET))(this);
		}

		::System::UInt32 get_DisplayTotalBuffCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_DISPLAYTOTALBUFFCOUNT_OFFSET))(this);
		}

		::System::UInt32 get_FirstListBuffCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_FIRSTLISTBUFFCOUNT_OFFSET))(this);
		}

		::System::Void add_OnBuffSelectNumChange(::RPG::Client::FateRin::ViewModelEventHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_ADD_ONBUFFSELECTNUMCHANGE_OFFSET))(this, a1);
		}

		::System::Void remove_OnBuffSelectNumChange(::RPG::Client::FateRin::ViewModelEventHandler* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::ViewModelEventHandler*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_REMOVE_ONBUFFSELECTNUMCHANGE_OFFSET))(this, a1);
		}

		::Class_0_16E4307DCC419505_313<::System::Int32>* get_ClickBuff()
		{
			return ((::Class_0_16E4307DCC419505_313<::System::Int32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_CLICKBUFF_OFFSET))(this);
		}

		::Class_0_16E4307DCC419505_311* get_TriggerBattle()
		{
			return ((::Class_0_16E4307DCC419505_311*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_CHALLENGE_FATERINCHALLENGELEVELINFOVIEWMODEL_GET_TRIGGERBATTLE_OFFSET))(this);
		}
	};
}
