#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/InControl/InputDeviceClass.h"
#include "unitysdk/RPG/Client/FateRin/Battle/FateRinBattleHudInputMode.h"
#include "unitysdk/System/Nullable_1.h"
#include "unitysdk/UnityEngine/MonoBehaviour.h"
#include "unitysdk/UnityEngine/Vector2.h"

class Class_0_16E4307DCC419505_1275;
namespace RPG::Client { class ScreenEventHandler; }
namespace RPG::Client::FateRin::Battle { class FateRinBattleHudFreeCardMoveHandler; }
namespace RPG::Client::FateRin::Battle { class IFateRinCardHitTestService; }
namespace System { class Action; }
namespace System { class Object; }
namespace System { template <typename T> class Action_1; }
namespace UnityEngine { class RectTransform; }

#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADCANCEL_OFFSET UNITYSDK_OFFSET(0xC59CEE0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADCONFIRM_OFFSET UNITYSDK_OFFSET(0xC59CE20)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADENEMYNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59CD60)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADFOCUSRESTOREREQUESTED_OFFSET UNITYSDK_OFFSET(0xC59CFC0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADHANDCARDNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59CCA0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADNAVIGATIONENTER_OFFSET UNITYSDK_OFFSET(0xC59CB20)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADNAVIGATIONEXIT_OFFSET UNITYSDK_OFFSET(0xC59CBE0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONINPUTDEVICECLASSSWITCH_OFFSET UNITYSDK_OFFSET(0xC59CA60)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONINPUTINTERRUPTED_OFFSET UNITYSDK_OFFSET(0xC59C9A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERCANCEL_OFFSET UNITYSDK_OFFSET(0xC59C8E0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERDRAG_OFFSET UNITYSDK_OFFSET(0xC59C760)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERHOVEREXIT_OFFSET UNITYSDK_OFFSET(0xC59C5E0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERHOVER_OFFSET UNITYSDK_OFFSET(0xC59C520)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERPRESS_OFFSET UNITYSDK_OFFSET(0xC59C6A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERRELEASE_OFFSET UNITYSDK_OFFSET(0xC59C820)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_CLEARFREECARDNAVIGATIONFOCUS_OFFSET UNITYSDK_OFFSET(0xC59E2B0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_GET_ISINPUTAVAILABLE_OFFSET UNITYSDK_OFFSET(0xC59E310)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_INIT_OFFSET UNITYSDK_OFFSET(0xC59D0A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ONDESTROY_OFFSET UNITYSDK_OFFSET(0xC59F0D0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ONDISABLE_OFFSET UNITYSDK_OFFSET(0xC59EBA0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ONENABLE_OFFSET UNITYSDK_OFFSET(0xC59EA50)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADCANCEL_OFFSET UNITYSDK_OFFSET(0xC59E100)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADCONFIRM_OFFSET UNITYSDK_OFFSET(0xC59E060)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADENEMYNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59DFF0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADFOCUSRESTOREREQUESTED_OFFSET UNITYSDK_OFFSET(0xC59E1A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADHANDCARDNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59DF80)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADNAVIGATIONENTER_OFFSET UNITYSDK_OFFSET(0xC59DDD0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADNAVIGATIONEXIT_OFFSET UNITYSDK_OFFSET(0xC59DEE0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEINPUTDEVICECLASSSWITCH_OFFSET UNITYSDK_OFFSET(0xC59DA00)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADCANCEL_OFFSET UNITYSDK_OFFSET(0xC59CF50)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADCONFIRM_OFFSET UNITYSDK_OFFSET(0xC59CE80)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADENEMYNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59CDC0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADFOCUSRESTOREREQUESTED_OFFSET UNITYSDK_OFFSET(0xC59D030)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADHANDCARDNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59CD00)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADNAVIGATIONENTER_OFFSET UNITYSDK_OFFSET(0xC59CB80)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADNAVIGATIONEXIT_OFFSET UNITYSDK_OFFSET(0xC59CC40)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONINPUTDEVICECLASSSWITCH_OFFSET UNITYSDK_OFFSET(0xC59CAC0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONINPUTINTERRUPTED_OFFSET UNITYSDK_OFFSET(0xC59CA00)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERCANCEL_OFFSET UNITYSDK_OFFSET(0xC59C940)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERDRAG_OFFSET UNITYSDK_OFFSET(0xC59C7C0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERHOVEREXIT_OFFSET UNITYSDK_OFFSET(0xC59C640)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERHOVER_OFFSET UNITYSDK_OFFSET(0xC59C580)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERPRESS_OFFSET UNITYSDK_OFFSET(0xC59C700)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERRELEASE_OFFSET UNITYSDK_OFFSET(0xC59C880)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REQUESTFREECARDNAVIGATIONFOCUS_OFFSET UNITYSDK_OFFSET(0xC59E240)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_GET_FREECARDMOVEHANDLER_OFFSET UNITYSDK_OFFSET(0xC59E450)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADCANCEL_OFFSET UNITYSDK_OFFSET(0xC59E9B0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADCONFIRM_OFFSET UNITYSDK_OFFSET(0xC59E960)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADENEMYNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59E8D0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADFOCUSRESTOREREQUESTED_OFFSET UNITYSDK_OFFSET(0xC59EA00)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADHANDCARDNAVIGATE_OFFSET UNITYSDK_OFFSET(0xC59E840)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADNAVIGATIONENTER_OFFSET UNITYSDK_OFFSET(0xC59E7A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADNAVIGATIONEXIT_OFFSET UNITYSDK_OFFSET(0xC59E7F0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_GET_CARDAREA_OFFSET UNITYSDK_OFFSET(0xC59E3B0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_GET_HITTESTSERVICE_OFFSET UNITYSDK_OFFSET(0xC59E400)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_GET_SCREENEVENT_OFFSET UNITYSDK_OFFSET(0xC59E360)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERCANCEL_OFFSET UNITYSDK_OFFSET(0xC59E700)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERDRAG_OFFSET UNITYSDK_OFFSET(0xC59E620)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERHOVEREXIT_OFFSET UNITYSDK_OFFSET(0xC59E510)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERHOVER_OFFSET UNITYSDK_OFFSET(0xC59E4A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERPRESS_OFFSET UNITYSDK_OFFSET(0xC59E5B0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERRELEASE_OFFSET UNITYSDK_OFFSET(0xC59E690)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_SETHITTESTSERVICE_OFFSET UNITYSDK_OFFSET(0xC59D330)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_SETSCREENEVENTACTIVE_OFFSET UNITYSDK_OFFSET(0xC59D2D0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_UPDATESCREENEVENTSIZE_OFFSET UNITYSDK_OFFSET(0xC59D380)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_UPDATE_OFFSET UNITYSDK_OFFSET(0xC59EE70)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__CLEARSCREENEVENTDELEGATES_OFFSET UNITYSDK_OFFSET(0xC59F490)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__CREATEDRIVERFORMODE_OFFSET UNITYSDK_OFFSET(0xC59F6C0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__CTOR_OFFSET UNITYSDK_OFFSET(0xC59F7C0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__ENSUREDRIVERFORCURRENTMODE_OFFSET UNITYSDK_OFFSET(0xC59F370)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__INTERRUPTINPUT_OFFSET UNITYSDK_OFFSET(0xC59ECE0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__NOTIFYCURRENTINPUTDEVICECLASSRESTORED_OFFSET UNITYSDK_OFFSET(0xC59F3E0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__ONAPPLICATIONFOCUSCHANGED_OFFSET UNITYSDK_OFFSET(0xC59F2A0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__POLLINPUTDEVICECLASSSWITCH_OFFSET UNITYSDK_OFFSET(0xC59EFE0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__RAISEINPUTEVENT_OFFSET UNITYSDK_OFFSET(0xC59DE70)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__REFRESHINPUTGATE_OFFSET UNITYSDK_OFFSET(0xC59D170)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__REGISTERNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0xC59EAE0)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__SHOULDINPUTGATEOPEN_OFFSET UNITYSDK_OFFSET(0xC59F310)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__SWITCHDRIVER_OFFSET UNITYSDK_OFFSET(0xC59DB20)
#define RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__UNREGISTERNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0xC59EC20)

namespace RPG::Client::FateRin::View::Battle
{
	inline static constexpr unsigned int FateRinBattleHudInputHandler_TypeDefinitionIndex = 75714;

	class FateRinBattleHudInputHandler : public ::UnityEngine::MonoBehaviour
	{
	public:
		::System::Action_1<::UnityEngine::Vector2>* OnPointerHover; // 0x18
		::System::Action* OnPointerHoverExit; // 0x20
		::System::Action_1<::UnityEngine::Vector2>* OnPointerPress; // 0x28
		::System::Action_1<::UnityEngine::Vector2>* OnPointerDrag; // 0x30
		::System::Action_1<::UnityEngine::Vector2>* OnPointerRelease; // 0x38
		::System::Action* OnPointerCancel; // 0x40
		::System::Action* OnInputInterrupted; // 0x48
		::System::Action_1<::InControl::InputDeviceClass>* OnInputDeviceClassSwitch; // 0x50
		::System::Action* OnGamepadNavigationEnter; // 0x58
		::System::Action* OnGamepadNavigationExit; // 0x60
		::System::Action_1<::System::Int32>* OnGamepadHandCardNavigate; // 0x68
		::System::Action_1<::System::Int32>* OnGamepadEnemyNavigate; // 0x70
		::System::Action* OnGamepadConfirm; // 0x78
		::System::Action* OnGamepadCancel; // 0x80
		::System::Action* OnGamepadFocusRestoreRequested; // 0x88
		::RPG::Client::ScreenEventHandler* _ScreenEvent; // 0x90
		::UnityEngine::RectTransform* _CardArea; // 0x98
		::RPG::Client::FateRin::Battle::FateRinBattleHudFreeCardMoveHandler* _FreeCardMoveHandler; // 0xA0
		::RPG::Client::FateRin::Battle::IFateRinCardHitTestService* _HitTestService; // 0xA8
		::Class_0_16E4307DCC419505_1275* _Driver; // 0xB0
		::System::Nullable_1<::RPG::Client::FateRin::Battle::FateRinBattleHudInputMode> _DriverMode; // 0xB8
		::System::Boolean _AreNotifyHandlersRegistered; // 0xC0
		::System::Boolean _IsInitialized; // 0xC1
		::System::Boolean _IsHudInputAllowed; // 0xC2
		::System::Boolean _IsApplicationFocused; // 0xC3
		::System::Boolean _IsInputGateOpen; // 0xC4

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__CTOR_OFFSET))(this);
		}

		::System::Void add_OnPointerHover(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERHOVER_OFFSET))(this, a1);
		}

		::System::Void remove_OnPointerHover(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERHOVER_OFFSET))(this, a1);
		}

		::System::Void add_OnPointerHoverExit(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERHOVEREXIT_OFFSET))(this, a1);
		}

		::System::Void remove_OnPointerHoverExit(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERHOVEREXIT_OFFSET))(this, a1);
		}

		::System::Void add_OnPointerPress(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERPRESS_OFFSET))(this, a1);
		}

		::System::Void remove_OnPointerPress(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERPRESS_OFFSET))(this, a1);
		}

		::System::Void add_OnPointerDrag(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERDRAG_OFFSET))(this, a1);
		}

		::System::Void remove_OnPointerDrag(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERDRAG_OFFSET))(this, a1);
		}

		::System::Void add_OnPointerRelease(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERRELEASE_OFFSET))(this, a1);
		}

		::System::Void remove_OnPointerRelease(::System::Action_1<::UnityEngine::Vector2>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::UnityEngine::Vector2>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERRELEASE_OFFSET))(this, a1);
		}

		::System::Void add_OnPointerCancel(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONPOINTERCANCEL_OFFSET))(this, a1);
		}

		::System::Void remove_OnPointerCancel(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONPOINTERCANCEL_OFFSET))(this, a1);
		}

		::System::Void add_OnInputInterrupted(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONINPUTINTERRUPTED_OFFSET))(this, a1);
		}

		::System::Void remove_OnInputInterrupted(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONINPUTINTERRUPTED_OFFSET))(this, a1);
		}

		::System::Void add_OnInputDeviceClassSwitch(::System::Action_1<::InControl::InputDeviceClass>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::InControl::InputDeviceClass>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONINPUTDEVICECLASSSWITCH_OFFSET))(this, a1);
		}

		::System::Void remove_OnInputDeviceClassSwitch(::System::Action_1<::InControl::InputDeviceClass>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::InControl::InputDeviceClass>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONINPUTDEVICECLASSSWITCH_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadNavigationEnter(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADNAVIGATIONENTER_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadNavigationEnter(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADNAVIGATIONENTER_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadNavigationExit(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADNAVIGATIONEXIT_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadNavigationExit(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADNAVIGATIONEXIT_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadHandCardNavigate(::System::Action_1<::System::Int32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Int32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADHANDCARDNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadHandCardNavigate(::System::Action_1<::System::Int32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Int32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADHANDCARDNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadEnemyNavigate(::System::Action_1<::System::Int32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Int32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADENEMYNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadEnemyNavigate(::System::Action_1<::System::Int32>* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action_1<::System::Int32>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADENEMYNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadConfirm(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADCONFIRM_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadConfirm(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADCONFIRM_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadCancel(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADCANCEL_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadCancel(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADCANCEL_OFFSET))(this, a1);
		}

		::System::Void add_OnGamepadFocusRestoreRequested(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ADD_ONGAMEPADFOCUSRESTOREREQUESTED_OFFSET))(this, a1);
		}

		::System::Void remove_OnGamepadFocusRestoreRequested(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REMOVE_ONGAMEPADFOCUSRESTOREREQUESTED_OFFSET))(this, a1);
		}

		::System::Void Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_INIT_OFFSET))(this);
		}

		::System::Void SetScreenEventActive(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_SETSCREENEVENTACTIVE_OFFSET))(this, a1);
		}

		::System::Void SetHitTestService(::RPG::Client::FateRin::Battle::IFateRinCardHitTestService* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::Battle::IFateRinCardHitTestService*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_SETHITTESTSERVICE_OFFSET))(this, a1);
		}

		::System::Void UpdateScreenEventSize(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_UPDATESCREENEVENTSIZE_OFFSET))(this, a1);
		}

		::System::Void RaiseInputDeviceClassSwitch(::InControl::InputDeviceClass a1)
		{
			return ((::System::Void(*)(::PVOID, ::InControl::InputDeviceClass))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEINPUTDEVICECLASSSWITCH_OFFSET))(this, a1);
		}

		::System::Void RaiseGamepadNavigationEnter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADNAVIGATIONENTER_OFFSET))(this);
		}

		::System::Void RaiseGamepadNavigationExit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADNAVIGATIONEXIT_OFFSET))(this);
		}

		::System::Void RaiseGamepadHandCardNavigate(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADHANDCARDNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void RaiseGamepadEnemyNavigate(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADENEMYNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void RaiseGamepadConfirm()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADCONFIRM_OFFSET))(this);
		}

		::System::Void RaiseGamepadCancel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADCANCEL_OFFSET))(this);
		}

		::System::Void RaiseGamepadFocusRestoreRequested()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RAISEGAMEPADFOCUSRESTOREREQUESTED_OFFSET))(this);
		}

		::System::Boolean RequestFreeCardNavigationFocus()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_REQUESTFREECARDNAVIGATIONFOCUS_OFFSET))(this);
		}

		::System::Void ClearFreeCardNavigationFocus()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_CLEARFREECARDNAVIGATIONFOCUS_OFFSET))(this);
		}

		::System::Boolean get_IsInputAvailable()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_GET_ISINPUTAVAILABLE_OFFSET))(this);
		}

		::RPG::Client::ScreenEventHandler* RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_get_ScreenEvent()
		{
			return ((::RPG::Client::ScreenEventHandler*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_GET_SCREENEVENT_OFFSET))(this);
		}

		::UnityEngine::RectTransform* RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_get_CardArea()
		{
			return ((::UnityEngine::RectTransform*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_GET_CARDAREA_OFFSET))(this);
		}

		::RPG::Client::FateRin::Battle::IFateRinCardHitTestService* RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_get_HitTestService()
		{
			return ((::RPG::Client::FateRin::Battle::IFateRinCardHitTestService*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_GET_HITTESTSERVICE_OFFSET))(this);
		}

		::RPG::Client::FateRin::Battle::FateRinBattleHudFreeCardMoveHandler* RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_get_FreeCardMoveHandler()
		{
			return ((::RPG::Client::FateRin::Battle::FateRinBattleHudFreeCardMoveHandler*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_GET_FREECARDMOVEHANDLER_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_RaisePointerHover(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERHOVER_OFFSET))(this, a1);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_RaisePointerHoverExit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERHOVEREXIT_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_RaisePointerPress(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERPRESS_OFFSET))(this, a1);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_RaisePointerDrag(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERDRAG_OFFSET))(this, a1);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_RaisePointerRelease(::UnityEngine::Vector2 a1)
		{
			return ((::System::Void(*)(::PVOID, ::UnityEngine::Vector2))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERRELEASE_OFFSET))(this, a1);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinPointerInputDriverHost_RaisePointerCancel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINPOINTERINPUTDRIVERHOST_RAISEPOINTERCANCEL_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadNavigationEnter()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADNAVIGATIONENTER_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadNavigationExit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADNAVIGATIONEXIT_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadHandCardNavigate(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADHANDCARDNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadEnemyNavigate(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADENEMYNAVIGATE_OFFSET))(this, a1);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadConfirm()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADCONFIRM_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadCancel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADCANCEL_OFFSET))(this);
		}

		::System::Void RPG_Client_FateRin_View_Battle_IFateRinGamepadInputDriverHost_RaiseGamepadFocusRestoreRequested()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_RPG_CLIENT_FATERIN_VIEW_BATTLE_IFATERINGAMEPADINPUTDRIVERHOST_RAISEGAMEPADFOCUSRESTOREREQUESTED_OFFSET))(this);
		}

		::System::Void OnEnable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ONENABLE_OFFSET))(this);
		}

		::System::Void OnDisable()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ONDISABLE_OFFSET))(this);
		}

		::System::Void Update()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_UPDATE_OFFSET))(this);
		}

		::System::Void OnDestroy()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER_ONDESTROY_OFFSET))(this);
		}

		::System::Void _RegisterNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__REGISTERNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _UnregisterNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__UNREGISTERNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _OnApplicationFocusChanged(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__ONAPPLICATIONFOCUSCHANGED_OFFSET))(this, a1);
		}

		::System::Void _RefreshInputGate()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__REFRESHINPUTGATE_OFFSET))(this);
		}

		::System::Boolean _ShouldInputGateOpen()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__SHOULDINPUTGATEOPEN_OFFSET))(this);
		}

		::System::Void _NotifyCurrentInputDeviceClassRestored()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__NOTIFYCURRENTINPUTDEVICECLASSRESTORED_OFFSET))(this);
		}

		::System::Void _PollInputDeviceClassSwitch()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__POLLINPUTDEVICECLASSSWITCH_OFFSET))(this);
		}

		::System::Void _EnsureDriverForCurrentMode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__ENSUREDRIVERFORCURRENTMODE_OFFSET))(this);
		}

		::System::Void _InterruptInput()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__INTERRUPTINPUT_OFFSET))(this);
		}

		::System::Void _RaiseInputEvent(::System::Action* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Action*))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__RAISEINPUTEVENT_OFFSET))(this, a1);
		}

		::System::Void _SwitchDriver(::RPG::Client::FateRin::Battle::FateRinBattleHudInputMode a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::FateRin::Battle::FateRinBattleHudInputMode))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__SWITCHDRIVER_OFFSET))(this, a1);
		}

		::System::Void _ClearScreenEventDelegates()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__CLEARSCREENEVENTDELEGATES_OFFSET))(this);
		}

		static ::Class_0_16E4307DCC419505_1275* _CreateDriverForMode(::RPG::Client::FateRin::Battle::FateRinBattleHudInputMode a1)
		{
			return ((::Class_0_16E4307DCC419505_1275*(*)(::RPG::Client::FateRin::Battle::FateRinBattleHudInputMode))((::PBYTE)hIl2Cpp + RPG_CLIENT_FATERIN_VIEW_BATTLE_FATERINBATTLEHUDINPUTHANDLER__CREATEDRIVERFORMODE_OFFSET))(a1);
		}
	};
}
