#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

class Class_1_463786FEF28056CE;
class Class_1_5092E2281751B550_1;
class Class_1_7EEA5E93C4D09894;
class Class_1_B13340E145F0BF93;
namespace RPG::Client { class PlayerPlatformInfo; }
namespace RPG::Client::TeamTowers { class TeamTowersPVPService; }
namespace RPG::Client::TeamTowers { class TeamTowersSettleExpInfoViewModel; }
namespace RPG::Client::TeamTowers { class TeamTowersStageData; }
namespace RPG::Client::TeamTowers { class TeamTowersStageDetailStarsViewModel; }
namespace RPG::Client::TeamTowers { class TeamTowersWindowService; }
namespace System { class String; }
namespace System::Collections::Generic { template <typename T> class List_1; }

#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_CHECKSHOULDEXITTOMAINPAGE_OFFSET UNITYSDK_OFFSET(0xD66C370)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_CHECKSHOULDEXITTOMAZEPAGE_OFFSET UNITYSDK_OFFSET(0xD66C100)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_EXITGAME_OFFSET UNITYSDK_OFFSET(0xD66C0B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_EXITPVP_OFFSET UNITYSDK_OFFSET(0xD66C640)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ACHIEVEDMAXLEVELBEFORESETTLEMENT_OFFSET UNITYSDK_OFFSET(0xD66CFA0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ACHIEVEDMAXLEVEL_OFFSET UNITYSDK_OFFSET(0xD66D2A0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ALLYOUTPUTNUM_OFFSET UNITYSDK_OFFSET(0xD66CC80)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ALLYOUTPUTPERCENTS_OFFSET UNITYSDK_OFFSET(0xD66CD60)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ALLYPLATFORMINFO_OFFSET UNITYSDK_OFFSET(0xD66E190)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_BREAKRECORD_OFFSET UNITYSDK_OFFSET(0xD66CDF0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_BREAKWAVECOUNTRECORD_OFFSET UNITYSDK_OFFSET(0xD66E760)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_BRICKCOUNT_OFFSET UNITYSDK_OFFSET(0xD66E6C0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DEADCOUNT_OFFSET UNITYSDK_OFFSET(0xD66CBE0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYEXPNUM_OFFSET UNITYSDK_OFFSET(0xD66E860)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYMAXTEXT_OFFSET UNITYSDK_OFFSET(0xD66E910)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYPREVLEVEL_OFFSET UNITYSDK_OFFSET(0xD66CEE0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYSTARCOUNT_OFFSET UNITYSDK_OFFSET(0xD66EC70)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYTARGETLEVEL_OFFSET UNITYSDK_OFFSET(0xD66D140)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_EXPOBTAINED_OFFSET UNITYSDK_OFFSET(0xD66CE40)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_FIRSTPASS_OFFSET UNITYSDK_OFFSET(0xD66C260)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISBOSSSTAGEFIRSTPASS_OFFSET UNITYSDK_OFFSET(0xD66C2B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISENDLESSMODE_OFFSET UNITYSDK_OFFSET(0xD66DA80)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISHARDSTAGE_OFFSET UNITYSDK_OFFSET(0xD66C4A0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISPVPMODE_OFFSET UNITYSDK_OFFSET(0xD66C210)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISRACEMODE_OFFSET UNITYSDK_OFFSET(0xD66DB80)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISSURVIVALMODE_OFFSET UNITYSDK_OFFSET(0xD66DB00)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISTUTORIALSTAGE_OFFSET UNITYSDK_OFFSET(0xD66CAE0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_LEVELTITLETEXT_OFFSET UNITYSDK_OFFSET(0xD66E1E0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_LEVELUP_OFFSET UNITYSDK_OFFSET(0xD66D4B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_MAXLEVEL_OFFSET UNITYSDK_OFFSET(0xD66D730)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_MODETITLETEXT_OFFSET UNITYSDK_OFFSET(0xD66E430)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_NEWMARKVISIBLE_OFFSET UNITYSDK_OFFSET(0xD66E340)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_OPENNEWDIFFICULTYLEVEL_OFFSET UNITYSDK_OFFSET(0xD66E7B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYAGAINBUTTONVISIBLE_OFFSET UNITYSDK_OFFSET(0xD66ECC0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYEROUTPUTNUM_OFFSET UNITYSDK_OFFSET(0xD66CC30)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYEROUTPUTPERCENTS_OFFSET UNITYSDK_OFFSET(0xD66CCD0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYERPLATFORMINFO_OFFSET UNITYSDK_OFFSET(0xD66E140)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYEXPSLIDERTWEEN_OFFSET UNITYSDK_OFFSET(0xD66E9B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PREVEXTRAEXP_OFFSET UNITYSDK_OFFSET(0xD66D040)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PREVLEVELTOTALEXP_OFFSET UNITYSDK_OFFSET(0xD66D090)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PREVLEVEL_OFFSET UNITYSDK_OFFSET(0xD66CE90)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PSPLATFORMPLAYERNAMESVISIBLE_OFFSET UNITYSDK_OFFSET(0xD66E000)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTFADEINANIMATIONNAME_OFFSET UNITYSDK_OFFSET(0xD66D790)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTSCOREPAGEUISTATE_OFFSET UNITYSDK_OFFSET(0xD66EA10)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTSCORETARGETINFOVISIBLE_OFFSET UNITYSDK_OFFSET(0xD66EAB0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTSCOREUI3DFADEINANIM_OFFSET UNITYSDK_OFFSET(0xD66ED40)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTTITLETEXT_OFFSET UNITYSDK_OFFSET(0xD66DE60)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SILVERWOLFEXTRAEXPVISIBLE_OFFSET UNITYSDK_OFFSET(0xD66EB60)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SILVERWOLFEXTRAEXP_OFFSET UNITYSDK_OFFSET(0xD66D660)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SKIPRESULTPAGE_OFFSET UNITYSDK_OFFSET(0xD66CA90)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STAGEID_OFFSET UNITYSDK_OFFSET(0xD66C9F0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STARCOUNT_OFFSET UNITYSDK_OFFSET(0xD66EBE0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STARIDLIST_OFFSET UNITYSDK_OFFSET(0xD66CA40)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STARSVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xD66E410)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SUCCESS_OFFSET UNITYSDK_OFFSET(0xD66C450)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SUMEXPVISIBLE_OFFSET UNITYSDK_OFFSET(0xD66EB10)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_TARGETEXTRAEXP_OFFSET UNITYSDK_OFFSET(0xD66D320)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_TARGETLEVELTOTALEXP_OFFSET UNITYSDK_OFFSET(0xD66D450)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_TARGETLEVEL_OFFSET UNITYSDK_OFFSET(0xD66D0E0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_UI3DPAGEUISTATE_OFFSET UNITYSDK_OFFSET(0xD66DC00)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_UI3DTORESULTANIMNAME_OFFSET UNITYSDK_OFFSET(0xD66DD30)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_UPGRADEANIMNAME_OFFSET UNITYSDK_OFFSET(0xD66EDC0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_WAVECOUNT_OFFSET UNITYSDK_OFFSET(0xD66E710)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ZEROEXPOBTAINED_OFFSET UNITYSDK_OFFSET(0xD66D590)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ZEROREGULAREXPOBTAINED_OFFSET UNITYSDK_OFFSET(0xD66D6B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_RESTARTCURRENTSTAGE_OFFSET UNITYSDK_OFFSET(0xD66C010)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_RETURNTOPVPLOBBY_OFFSET UNITYSDK_OFFSET(0xD66C520)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_SET_STARSVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xD66E420)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__CCTOR_OFFSET UNITYSDK_OFFSET(0xD66EED0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__CTOR_OFFSET UNITYSDK_OFFSET(0xD66BDB0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__INITSETTLEEXPINFO_OFFSET UNITYSDK_OFFSET(0xD66C690)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__INITSTARVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xD66C8B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__INITVIEWMODEL_OFFSET UNITYSDK_OFFSET(0xD66BE70)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__RETURNTOPVPLOBBY_B__5_0_OFFSET UNITYSDK_OFFSET(0xD66EEE0)

namespace RPG::Client::TeamTowers
{
	inline static constexpr unsigned int TeamTowersResultViewModel_TypeDefinitionIndex = 75106;

	class TeamTowersResultViewModel : public ::System::Object
	{
	public:
		static ::System::UInt32* StaticGet__SilverWolfMaxLevel()
		{
			return (::System::UInt32*)Il2CppClass::FromTypeDefinitionIndex(TeamTowersResultViewModel_TypeDefinitionIndex)->GetStaticField(0xA630);
		}
		::Class_1_7EEA5E93C4D09894* _Repository; // 0x10
		::RPG::Client::TeamTowers::TeamTowersStageDetailStarsViewModel* _StarsViewModel_k__BackingField; // 0x18
		::Class_1_5092E2281751B550_1* _ResultData; // 0x20
		::RPG::Client::TeamTowers::TeamTowersStageData* _StageData; // 0x28
		::RPG::Client::TeamTowers::TeamTowersWindowService* _WindowService; // 0x30
		::System::Collections::Generic::List_1<::RPG::Client::TeamTowers::TeamTowersSettleExpInfoViewModel*>* SettleExpInfoList; // 0x38
		::Class_1_B13340E145F0BF93* _GameflowService; // 0x40
		::Class_1_463786FEF28056CE* _StageService; // 0x48
		::RPG::Client::TeamTowers::TeamTowersPVPService* _PVPService; // 0x50

		::System::Void _ctor(::Class_1_5092E2281751B550_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_5092E2281751B550_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__CTOR_OFFSET))(this, a1);
		}

		static ::System::Void _cctor()
		{
			return ((::System::Void(*)())((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__CCTOR_OFFSET))();
		}

		::System::Void RestartCurrentStage()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_RESTARTCURRENTSTAGE_OFFSET))(this);
		}

		::System::Void ExitGame()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_EXITGAME_OFFSET))(this);
		}

		::System::Boolean CheckShouldExitToMazePage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_CHECKSHOULDEXITTOMAZEPAGE_OFFSET))(this);
		}

		::System::Boolean CheckShouldExitToMainPage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_CHECKSHOULDEXITTOMAINPAGE_OFFSET))(this);
		}

		::System::Void ReturnToPVPLobby()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_RETURNTOPVPLOBBY_OFFSET))(this);
		}

		::System::Void ExitPVP()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_EXITPVP_OFFSET))(this);
		}

		::System::Void _InitViewModel(::Class_1_5092E2281751B550_1* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_5092E2281751B550_1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__INITVIEWMODEL_OFFSET))(this, a1);
		}

		::System::Void _InitSettleExpInfo()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__INITSETTLEEXPINFO_OFFSET))(this);
		}

		::System::Void _InitStarViewModel()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__INITSTARVIEWMODEL_OFFSET))(this);
		}

		::System::Boolean get_SkipResultPage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SKIPRESULTPAGE_OFFSET))(this);
		}

		::System::Boolean get_IsTutorialStage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISTUTORIALSTAGE_OFFSET))(this);
		}

		::System::Boolean get_Success()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SUCCESS_OFFSET))(this);
		}

		::System::Boolean get_FirstPass()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_FIRSTPASS_OFFSET))(this);
		}

		::System::UInt32 get_StageID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STAGEID_OFFSET))(this);
		}

		::System::Boolean get_IsPvpMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISPVPMODE_OFFSET))(this);
		}

		::System::Boolean get_IsHardStage()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISHARDSTAGE_OFFSET))(this);
		}

		::System::UInt32 get_DeadCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DEADCOUNT_OFFSET))(this);
		}

		::System::Collections::Generic::List_1<::System::UInt32>* get_StarIDList()
		{
			return ((::System::Collections::Generic::List_1<::System::UInt32>*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STARIDLIST_OFFSET))(this);
		}

		::System::UInt32 get_PlayerOutputNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYEROUTPUTNUM_OFFSET))(this);
		}

		::System::UInt32 get_AllyOutputNum()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ALLYOUTPUTNUM_OFFSET))(this);
		}

		::System::Double get_PlayerOutputPercents()
		{
			return ((::System::Double(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYEROUTPUTPERCENTS_OFFSET))(this);
		}

		::System::Double get_AllyOutputPercents()
		{
			return ((::System::Double(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ALLYOUTPUTPERCENTS_OFFSET))(this);
		}

		::System::Boolean get_BreakRecord()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_BREAKRECORD_OFFSET))(this);
		}

		::System::UInt32 get_ExpObtained()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_EXPOBTAINED_OFFSET))(this);
		}

		::System::UInt32 get_PrevLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PREVLEVEL_OFFSET))(this);
		}

		::System::UInt32 get_DisplayPrevLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYPREVLEVEL_OFFSET))(this);
		}

		::System::UInt32 get_PrevExtraExp()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PREVEXTRAEXP_OFFSET))(this);
		}

		::System::UInt32 get_PrevLevelTotalExp()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PREVLEVELTOTALEXP_OFFSET))(this);
		}

		::System::UInt32 get_TargetLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_TARGETLEVEL_OFFSET))(this);
		}

		::System::UInt32 get_DisplayTargetLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYTARGETLEVEL_OFFSET))(this);
		}

		::System::UInt32 get_TargetExtraExp()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_TARGETEXTRAEXP_OFFSET))(this);
		}

		::System::UInt32 get_TargetLevelTotalExp()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_TARGETLEVELTOTALEXP_OFFSET))(this);
		}

		::System::Boolean get_LevelUp()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_LEVELUP_OFFSET))(this);
		}

		::System::Boolean get_ZeroExpObtained()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ZEROEXPOBTAINED_OFFSET))(this);
		}

		::System::Boolean get_ZeroRegularExpObtained()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ZEROREGULAREXPOBTAINED_OFFSET))(this);
		}

		::System::UInt32 get_MaxLevel()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_MAXLEVEL_OFFSET))(this);
		}

		::System::Boolean get_AchievedMaxLevel()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ACHIEVEDMAXLEVEL_OFFSET))(this);
		}

		::System::Boolean get_AchievedMaxLevelBeforeSettlement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ACHIEVEDMAXLEVELBEFORESETTLEMENT_OFFSET))(this);
		}

		::System::String* get_ResultFadeInAnimationName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTFADEINANIMATIONNAME_OFFSET))(this);
		}

		::System::String* get_UI3DPageUIState()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_UI3DPAGEUISTATE_OFFSET))(this);
		}

		::System::String* get_UI3DToResultAnimName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_UI3DTORESULTANIMNAME_OFFSET))(this);
		}

		::RPG::Client::TextID get_ResultTitleText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTTITLETEXT_OFFSET))(this);
		}

		::System::Boolean get_PSPlatformPlayerNamesVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PSPLATFORMPLAYERNAMESVISIBLE_OFFSET))(this);
		}

		::RPG::Client::PlayerPlatformInfo* get_PlayerPlatformInfo()
		{
			return ((::RPG::Client::PlayerPlatformInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYERPLATFORMINFO_OFFSET))(this);
		}

		::RPG::Client::PlayerPlatformInfo* get_AllyPlatformInfo()
		{
			return ((::RPG::Client::PlayerPlatformInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ALLYPLATFORMINFO_OFFSET))(this);
		}

		::RPG::Client::TextID get_LevelTitleText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_LEVELTITLETEXT_OFFSET))(this);
		}

		::System::Boolean get_NewMarkVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_NEWMARKVISIBLE_OFFSET))(this);
		}

		::RPG::Client::TeamTowers::TeamTowersStageDetailStarsViewModel* get_StarsViewModel()
		{
			return ((::RPG::Client::TeamTowers::TeamTowersStageDetailStarsViewModel*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STARSVIEWMODEL_OFFSET))(this);
		}

		::System::Void set_StarsViewModel(::RPG::Client::TeamTowers::TeamTowersStageDetailStarsViewModel* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TeamTowers::TeamTowersStageDetailStarsViewModel*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_SET_STARSVIEWMODEL_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_ModeTitleText()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_MODETITLETEXT_OFFSET))(this);
		}

		::System::UInt32 get_BrickCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_BRICKCOUNT_OFFSET))(this);
		}

		::System::UInt32 get_WaveCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_WAVECOUNT_OFFSET))(this);
		}

		::System::Boolean get_BreakWaveCountRecord()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_BREAKWAVECOUNTRECORD_OFFSET))(this);
		}

		::System::Boolean get_IsSurvivalMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISSURVIVALMODE_OFFSET))(this);
		}

		::System::Boolean get_IsRaceMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISRACEMODE_OFFSET))(this);
		}

		::System::Boolean get_IsEndlessMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISENDLESSMODE_OFFSET))(this);
		}

		::System::Boolean get_OpenNewDifficultyLevel()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_OPENNEWDIFFICULTYLEVEL_OFFSET))(this);
		}

		::System::Boolean get_DisplayExpNum()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYEXPNUM_OFFSET))(this);
		}

		::System::Boolean get_DisplayMaxText()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYMAXTEXT_OFFSET))(this);
		}

		::System::Boolean get_PlayExpSliderTween()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYEXPSLIDERTWEEN_OFFSET))(this);
		}

		::System::String* get_ResultScorePageUIState()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTSCOREPAGEUISTATE_OFFSET))(this);
		}

		::System::Boolean get_ResultScoreTargetInfoVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTSCORETARGETINFOVISIBLE_OFFSET))(this);
		}

		::System::Boolean get_SumExpVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SUMEXPVISIBLE_OFFSET))(this);
		}

		::System::UInt32 get_SilverWolfExtraExp()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SILVERWOLFEXTRAEXP_OFFSET))(this);
		}

		::System::Boolean get_SilverWolfExtraExpVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_SILVERWOLFEXTRAEXPVISIBLE_OFFSET))(this);
		}

		::System::UInt32 get_StarCount()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_STARCOUNT_OFFSET))(this);
		}

		::System::Boolean get_DisplayStarCount()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_DISPLAYSTARCOUNT_OFFSET))(this);
		}

		::System::Boolean get_PlayAgainButtonVisible()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_PLAYAGAINBUTTONVISIBLE_OFFSET))(this);
		}

		::System::Boolean get_IsBossStageFirstPass()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_ISBOSSSTAGEFIRSTPASS_OFFSET))(this);
		}

		::System::String* get_ResultScoreUI3DFadeInAnim()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_RESULTSCOREUI3DFADEINANIM_OFFSET))(this);
		}

		::System::String* get_UpgradeAnimName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL_GET_UPGRADEANIMNAME_OFFSET))(this);
		}

		::System::Void _ReturnToPVPLobby_b__5_0()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSRESULTVIEWMODEL__RETURNTOPVPLOBBY_B__5_0_OFFSET))(this);
		}
	};
}
