#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_CREATEBOSSBUBBLETALKMESSAGE_OFFSET UNITYSDK_OFFSET(0xD65C0B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_CREATEPLAYERBUBBLETALKMESSAGE_OFFSET UNITYSDK_OFFSET(0xD65BFE0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_AUTOHIDETIME_OFFSET UNITYSDK_OFFSET(0xD65C1A0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_FORCESHOW_OFFSET UNITYSDK_OFFSET(0xD65C1E0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_ISBOSSBUBBLE_OFFSET UNITYSDK_OFFSET(0xD65C220)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_PLAYERUID_OFFSET UNITYSDK_OFFSET(0xD65C200)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_PROTECTTIME_OFFSET UNITYSDK_OFFSET(0xD65C1C0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_TEXTID_OFFSET UNITYSDK_OFFSET(0xD65C180)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_AUTOHIDETIME_OFFSET UNITYSDK_OFFSET(0xD65C1B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_FORCESHOW_OFFSET UNITYSDK_OFFSET(0xD65C1F0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_PLAYERUID_OFFSET UNITYSDK_OFFSET(0xD65C210)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_PROTECTTIME_OFFSET UNITYSDK_OFFSET(0xD65C1D0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_TEXTID_OFFSET UNITYSDK_OFFSET(0xD65C190)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE__CTOR_OFFSET UNITYSDK_OFFSET(0xD65BF80)

namespace RPG::Client::TeamTowers
{
	inline static constexpr unsigned int TeamTowersGameBubbleTalkMessage_TypeDefinitionIndex = 75045;

	class TeamTowersGameBubbleTalkMessage : public ::System::Object
	{
	public:
		::System::Single _AutoHideTime_k__BackingField; // 0x10
		::System::Single _ProtectTime_k__BackingField; // 0x14
		::RPG::Client::TextID _TextID_k__BackingField; // 0x18
		::System::UInt32 _PlayerUID_k__BackingField; // 0x28
		::System::Boolean _ForceShow_k__BackingField; // 0x2C

		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE__CTOR_OFFSET))(this, a1);
		}

		static ::RPG::Client::TeamTowers::TeamTowersGameBubbleTalkMessage* CreatePlayerBubbleTalkMessage(::System::UInt32 a1, ::System::UInt32 a2)
		{
			return ((::RPG::Client::TeamTowers::TeamTowersGameBubbleTalkMessage*(*)(::System::UInt32, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_CREATEPLAYERBUBBLETALKMESSAGE_OFFSET))(a1, a2);
		}

		static ::RPG::Client::TeamTowers::TeamTowersGameBubbleTalkMessage* CreateBossBubbleTalkMessage(::System::UInt32 a1)
		{
			return ((::RPG::Client::TeamTowers::TeamTowersGameBubbleTalkMessage*(*)(::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_CREATEBOSSBUBBLETALKMESSAGE_OFFSET))(a1);
		}

		::RPG::Client::TextID get_TextID()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_TEXTID_OFFSET))(this);
		}

		::System::Void set_TextID(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_TEXTID_OFFSET))(this, a1);
		}

		::System::Single get_AutoHideTime()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_AUTOHIDETIME_OFFSET))(this);
		}

		::System::Void set_AutoHideTime(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_AUTOHIDETIME_OFFSET))(this, a1);
		}

		::System::Single get_ProtectTime()
		{
			return ((::System::Single(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_PROTECTTIME_OFFSET))(this);
		}

		::System::Void set_ProtectTime(::System::Single a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Single))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_PROTECTTIME_OFFSET))(this, a1);
		}

		::System::Boolean get_ForceShow()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_FORCESHOW_OFFSET))(this);
		}

		::System::Void set_ForceShow(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_FORCESHOW_OFFSET))(this, a1);
		}

		::System::UInt32 get_PlayerUID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_PLAYERUID_OFFSET))(this);
		}

		::System::Void set_PlayerUID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_SET_PLAYERUID_OFFSET))(this, a1);
		}

		::System::Boolean get_IsBossBubble()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBUBBLETALKMESSAGE_GET_ISBOSSBUBBLE_OFFSET))(this);
		}
	};
}
