#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/LittleGameShare/TeamTowersCore/BossSkillViewType.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

class Class_1_3B6C37FDA0C2C8C1;
class Class_1_5747B31C537024FC;
class Class_3_E7D29F43FB80184D;
namespace System { class String; }

#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_CURTIMEMS_OFFSET UNITYSDK_OFFSET(0xD65B8C0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ICONPATH_OFFSET UNITYSDK_OFFSET(0xD65B7A0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ISICE_OFFSET UNITYSDK_OFFSET(0xD65B9A0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ISTIMEPROGRESS_OFFSET UNITYSDK_OFFSET(0xD65B860)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ISWIND_OFFSET UNITYSDK_OFFSET(0xD65B950)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_MAXCOUNT_OFFSET UNITYSDK_OFFSET(0xD65B930)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_NAME_OFFSET UNITYSDK_OFFSET(0xD65B7F0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_REMAININGCOUNT_OFFSET UNITYSDK_OFFSET(0xD65B910)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_SKILLENDTIMEMS_OFFSET UNITYSDK_OFFSET(0xD65B8A0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_SKILLSTARTTIMEMS_OFFSET UNITYSDK_OFFSET(0xD65B880)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_ISTIMEPROGRESS_OFFSET UNITYSDK_OFFSET(0xD65B870)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_MAXCOUNT_OFFSET UNITYSDK_OFFSET(0xD65B940)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_REMAININGCOUNT_OFFSET UNITYSDK_OFFSET(0xD65B920)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_SKILLENDTIMEMS_OFFSET UNITYSDK_OFFSET(0xD65B8B0)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_SKILLSTARTTIMEMS_OFFSET UNITYSDK_OFFSET(0xD65B890)
#define RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE__CTOR_OFFSET UNITYSDK_OFFSET(0xD65B710)

namespace RPG::Client::TeamTowers
{
	inline static constexpr unsigned int TeamTowersGameBossSkillProgressChangedMessage_TypeDefinitionIndex = 75043;

	class TeamTowersGameBossSkillProgressChangedMessage : public ::System::Object
	{
	public:
		::Class_1_5747B31C537024FC* _SkillRow; // 0x10
		::Class_3_E7D29F43FB80184D* _OwnerGame; // 0x18
		::RPG::Client::LittleGameShare::TeamTowersCore::BossSkillViewType _ViewType; // 0x20
		::System::Boolean _IsTimeProgress_k__BackingField; // 0x21
		::System::UInt64 _SkillEndTimeMs_k__BackingField; // 0x28
		::System::Int32 _RemainingCount_k__BackingField; // 0x30
		::System::Int32 _MaxCount_k__BackingField; // 0x34
		::System::UInt64 _SkillStartTimeMs_k__BackingField; // 0x38

		::System::Void _ctor(::Class_3_E7D29F43FB80184D* a1, ::Class_1_3B6C37FDA0C2C8C1* a2)
		{
			return ((::System::Void(*)(::PVOID, ::Class_3_E7D29F43FB80184D*, ::Class_1_3B6C37FDA0C2C8C1*))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE__CTOR_OFFSET))(this, a1, a2);
		}

		::System::String* get_IconPath()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ICONPATH_OFFSET))(this);
		}

		::RPG::Client::TextID get_Name()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_NAME_OFFSET))(this);
		}

		::System::Boolean get_IsTimeProgress()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ISTIMEPROGRESS_OFFSET))(this);
		}

		::System::Void set_IsTimeProgress(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_ISTIMEPROGRESS_OFFSET))(this, a1);
		}

		::System::UInt64 get_SkillStartTimeMs()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_SKILLSTARTTIMEMS_OFFSET))(this);
		}

		::System::Void set_SkillStartTimeMs(::System::UInt64 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt64))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_SKILLSTARTTIMEMS_OFFSET))(this, a1);
		}

		::System::UInt64 get_SkillEndTimeMs()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_SKILLENDTIMEMS_OFFSET))(this);
		}

		::System::Void set_SkillEndTimeMs(::System::UInt64 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt64))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_SKILLENDTIMEMS_OFFSET))(this, a1);
		}

		::System::UInt64 get_CurTimeMs()
		{
			return ((::System::UInt64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_CURTIMEMS_OFFSET))(this);
		}

		::System::Int32 get_RemainingCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_REMAININGCOUNT_OFFSET))(this);
		}

		::System::Void set_RemainingCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_REMAININGCOUNT_OFFSET))(this, a1);
		}

		::System::Int32 get_MaxCount()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_MAXCOUNT_OFFSET))(this);
		}

		::System::Void set_MaxCount(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_SET_MAXCOUNT_OFFSET))(this, a1);
		}

		::System::Boolean get_IsWind()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ISWIND_OFFSET))(this);
		}

		::System::Boolean get_IsIce()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_TEAMTOWERS_TEAMTOWERSGAMEBOSSSKILLPROGRESSCHANGEDMESSAGE_GET_ISICE_OFFSET))(this);
		}
	};
}
