#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace RPG::Client::ActivityIdleLive { class IdleLiveDungeonAssistData; }

#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_CLEAR_OFFSET UNITYSDK_OFFSET(0xBB88160)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_GET_ISEMPTY_OFFSET UNITYSDK_OFFSET(0xBB89800)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_GET_PROGRESS_OFFSET UNITYSDK_OFFSET(0xBB89A50)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_GET_UID_OFFSET UNITYSDK_OFFSET(0xBB89A30)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_SETASSISTDATA_OFFSET UNITYSDK_OFFSET(0xBB884F0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_SET_PROGRESS_OFFSET UNITYSDK_OFFSET(0xBB89A60)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_SET_UID_OFFSET UNITYSDK_OFFSET(0xBB89A40)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xBB87E30)

namespace RPG::Client::ActivityIdleLive
{
	inline static constexpr unsigned int IdleLiveDungeonFriendSoltData_TypeDefinitionIndex = 71599;

	class IdleLiveDungeonFriendSoltData : public ::System::Object
	{
	public:
		::RPG::Client::ActivityIdleLive::IdleLiveDungeonAssistData* _AssistData; // 0x10
		::System::UInt32 _Progress_k__BackingField; // 0x18
		::System::UInt32 _UID_k__BackingField; // 0x1C

		::System::Void _ctor()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA__CTOR_OFFSET))(this);
		}

		::System::Void SetAssistData(::RPG::Client::ActivityIdleLive::IdleLiveDungeonAssistData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::IdleLiveDungeonAssistData*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_SETASSISTDATA_OFFSET))(this, a1);
		}

		::System::Void Clear()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_CLEAR_OFFSET))(this);
		}

		::System::UInt32 get_UID()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_GET_UID_OFFSET))(this);
		}

		::System::Void set_UID(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_SET_UID_OFFSET))(this, a1);
		}

		::System::UInt32 get_Progress()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_GET_PROGRESS_OFFSET))(this);
		}

		::System::Void set_Progress(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_SET_PROGRESS_OFFSET))(this, a1);
		}

		::System::Boolean get_IsEmpty()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDUNGEONFRIENDSOLTDATA_GET_ISEMPTY_OFFSET))(this);
		}
	};
}
