#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/BaseGameFlowContext.h"

class Class_1_4CFEF021C34E7902;
class Class_1_5E091DCE98E3035C;
class Class_1_BE764BAB439B58AC;
class Class_1_FFE5B8A52EC38E9C_5;
namespace RPG::Client { class BaseGameFlow; }
namespace RPG::Client::ActivityIdleLive { class NodeUIData; }
namespace RPG::Client::ActivityIdleLive { class StoryLine; }
namespace RPG::Client::Promises { class IPromise; }
namespace System { class Object; }
namespace System { class String; }
namespace System { template <typename T> class Func_1; }

#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_ASYNCENTERRECORDBATTLEIGNORINGFINALACT_OFFSET UNITYSDK_OFFSET(0xBBBFF40)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_CREATE_OFFSET UNITYSDK_OFFSET(0xBBBE030)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_FINISHCURBATTLENODEBYUSERQUIT_OFFSET UNITYSDK_OFFSET(0xBBC0DD0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETBTNCLICKACTION_OFFSET UNITYSDK_OFFSET(0xBBC1170)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETCURMAXSUBNODEPROGRESS_OFFSET UNITYSDK_OFFSET(0xBBC1750)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETCURNODEUIDATA_OFFSET UNITYSDK_OFFSET(0xBBC1420)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETCURSUBNODEPROGRESS_OFFSET UNITYSDK_OFFSET(0xBBC16C0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETNEXTNODEUIDATA_OFFSET UNITYSDK_OFFSET(0xBBC1660)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETSTAGESTATESTR_OFFSET UNITYSDK_OFFSET(0xBBC0E20)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GET_DEBUGSTATE_OFFSET UNITYSDK_OFFSET(0xBBBDF30)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GET_STORYLINE_OFFSET UNITYSDK_OFFSET(0xBBBDEF0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_RECEIVEMESSAGE_OFFSET UNITYSDK_OFFSET(0xBBC1860)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_SETSTORYLINE_OFFSET UNITYSDK_OFFSET(0xBBBDF90)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__CTOR_OFFSET UNITYSDK_OFFSET(0xBBBE1D0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ENTERRECORDBATTLEWITHOUTREQ_OFFSET UNITYSDK_OFFSET(0xBBBF650)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ENTERRECORDBATTLE_OFFSET UNITYSDK_OFFSET(0xBBC0020)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__FINISHBATTLEFAIL_OFFSET UNITYSDK_OFFSET(0xBBBEFC0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__FINISHBATTLEWIN_OFFSET UNITYSDK_OFFSET(0xBBBEEB0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__GOTONEXTNODE_OFFSET UNITYSDK_OFFSET(0xBBBEB80)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__INITMESSAGEHANDLERS_OFFSET UNITYSDK_OFFSET(0xBBBE2F0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__INITNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0xBBBE8A0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__INIT_OFFSET UNITYSDK_OFFSET(0xBBBE2A0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONBATTLEMODEFINISH_OFFSET UNITYSDK_OFFSET(0xBBBECC0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONDESTROYED_OFFSET UNITYSDK_OFFSET(0xBBBE960)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONFINISHCUREVENTNODE_OFFSET UNITYSDK_OFFSET(0xBBBEC70)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONGOTONEXTBATTLENODE_OFFSET UNITYSDK_OFFSET(0xBBBF5B0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONGOTONEXTNODE_OFFSET UNITYSDK_OFFSET(0xBBBEAB0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONGOTOPREVNODE_OFFSET UNITYSDK_OFFSET(0xBBBF550)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONLEAVEBATTLEWITHOUTREQ_OFFSET UNITYSDK_OFFSET(0xBBC0C90)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONLEAVEBATTLE_OFFSET UNITYSDK_OFFSET(0xBBC0AC0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONREENTERCURNODETOREPLACETEAM_OFFSET UNITYSDK_OFFSET(0xBBC1810)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONREENTERCURNODE_OFFSET UNITYSDK_OFFSET(0xBBBEC20)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONSHOWSTAGEPROGRESS_OFFSET UNITYSDK_OFFSET(0xBBBF3D0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONSUBNODEFIRSTWIN_OFFSET UNITYSDK_OFFSET(0xBBBF0E0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__PLAYFINALACT_OFFSET UNITYSDK_OFFSET(0xBBBFCD0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__SHOWSTAGEPROGRESS_OFFSET UNITYSDK_OFFSET(0xBBC0490)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__UNINITNOTIFYHANDLERS_OFFSET UNITYSDK_OFFSET(0xBBBE9F0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT___FINISHBATTLEFAIL_B__24_0_OFFSET UNITYSDK_OFFSET(0xBBC1EE0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT___FINISHBATTLEWIN_B__22_0_OFFSET UNITYSDK_OFFSET(0xBBC18D0)

namespace RPG::Client::ActivityIdleLive
{
	inline static constexpr unsigned int IdleLiveStoryLineGameContext_TypeDefinitionIndex = 71717;

	class IdleLiveStoryLineGameContext : public ::RPG::Client::BaseGameFlowContext
	{
	public:
		::Class_1_4CFEF021C34E7902* _MessageRegistry; // 0x20
		::RPG::Client::ActivityIdleLive::StoryLine* _StoryLineRef; // 0x28
		::Class_1_5E091DCE98E3035C* _NodeSwitchService; // 0x30
		::Class_1_BE764BAB439B58AC* _Service; // 0x38
		::System::UInt32 _DebugState; // 0x40

		::System::Void _ctor(::RPG::Client::BaseGameFlow* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::BaseGameFlow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__CTOR_OFFSET))(this, a1);
		}

		::RPG::Client::ActivityIdleLive::StoryLine* get_StoryLine()
		{
			return ((::RPG::Client::ActivityIdleLive::StoryLine*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GET_STORYLINE_OFFSET))(this);
		}

		::System::UInt32 get_DebugState()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GET_DEBUGSTATE_OFFSET))(this);
		}

		::System::Void SetStoryLine(::RPG::Client::ActivityIdleLive::StoryLine* a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::ActivityIdleLive::StoryLine*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_SETSTORYLINE_OFFSET))(this, a1);
		}

		static ::RPG::Client::ActivityIdleLive::IdleLiveStoryLineGameContext* Create(::RPG::Client::BaseGameFlow* a1)
		{
			return ((::RPG::Client::ActivityIdleLive::IdleLiveStoryLineGameContext*(*)(::RPG::Client::BaseGameFlow*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_CREATE_OFFSET))(a1);
		}

		::System::Void _Init()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__INIT_OFFSET))(this);
		}

		::System::Void _OnDestroyed()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONDESTROYED_OFFSET))(this);
		}

		::System::Void _InitMessageHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__INITMESSAGEHANDLERS_OFFSET))(this);
		}

		::System::Void _InitNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__INITNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _UninitNotifyHandlers()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__UNINITNOTIFYHANDLERS_OFFSET))(this);
		}

		::System::Void _OnGoToNextNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONGOTONEXTNODE_OFFSET))(this);
		}

		::RPG::Client::Promises::IPromise* _GoToNextNode()
		{
			return ((::RPG::Client::Promises::IPromise*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__GOTONEXTNODE_OFFSET))(this);
		}

		::System::Void _OnReEnterCurNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONREENTERCURNODE_OFFSET))(this);
		}

		::System::Void _OnFinishCurEventNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONFINISHCUREVENTNODE_OFFSET))(this);
		}

		::System::Void _OnBattleModeFinish(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONBATTLEMODEFINISH_OFFSET))(this, a1);
		}

		::System::Void _FinishBattleWin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__FINISHBATTLEWIN_OFFSET))(this);
		}

		::System::Void _OnSubNodeFirstWin()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONSUBNODEFIRSTWIN_OFFSET))(this);
		}

		::System::Void _FinishBattleFail()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__FINISHBATTLEFAIL_OFFSET))(this);
		}

		::System::Void _OnGoToPrevNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONGOTOPREVNODE_OFFSET))(this);
		}

		::System::Void _OnGotoNextBattleNode()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONGOTONEXTBATTLENODE_OFFSET))(this);
		}

		::System::Void _EnterRecordBattleWithoutReq(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ENTERRECORDBATTLEWITHOUTREQ_OFFSET))(this, a1);
		}

		::System::Void AsyncEnterRecordBattleIgnoringFinalAct(::System::Boolean a1, ::System::Func_1<::RPG::Client::Promises::IPromise*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean, ::System::Func_1<::RPG::Client::Promises::IPromise*>*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_ASYNCENTERRECORDBATTLEIGNORINGFINALACT_OFFSET))(this, a1, a2);
		}

		::System::Void _EnterRecordBattle(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ENTERRECORDBATTLE_OFFSET))(this, a1);
		}

		::System::Void _ShowStageProgress()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__SHOWSTAGEPROGRESS_OFFSET))(this);
		}

		::System::Void _PlayFinalAct()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__PLAYFINALACT_OFFSET))(this);
		}

		::System::Void _OnLeaveBattle()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONLEAVEBATTLE_OFFSET))(this);
		}

		::System::Void _OnLeaveBattleWithoutReq()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONLEAVEBATTLEWITHOUTREQ_OFFSET))(this);
		}

		::System::Void _OnShowStageProgress(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONSHOWSTAGEPROGRESS_OFFSET))(this, a1);
		}

		::RPG::Client::Promises::IPromise* FinishCurBattleNodeByUserQuit()
		{
			return ((::RPG::Client::Promises::IPromise*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_FINISHCURBATTLENODEBYUSERQUIT_OFFSET))(this);
		}

		::System::String* GetStageStateStr()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETSTAGESTATESTR_OFFSET))(this);
		}

		::System::String* GetBtnClickAction()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETBTNCLICKACTION_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::NodeUIData* GetCurNodeUIData()
		{
			return ((::RPG::Client::ActivityIdleLive::NodeUIData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETCURNODEUIDATA_OFFSET))(this);
		}

		::RPG::Client::ActivityIdleLive::NodeUIData* GetNextNodeUIData()
		{
			return ((::RPG::Client::ActivityIdleLive::NodeUIData*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETNEXTNODEUIDATA_OFFSET))(this);
		}

		::System::Int32 GetCurSubNodeProgress()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETCURSUBNODEPROGRESS_OFFSET))(this);
		}

		::System::Int32 GetCurMaxSubNodeProgress()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_GETCURMAXSUBNODEPROGRESS_OFFSET))(this);
		}

		::System::Void _OnReEnterCurNodeToReplaceTeam()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT__ONREENTERCURNODETOREPLACETEAM_OFFSET))(this);
		}

		::System::Void ReceiveMessage(::System::Int32 a1, ::System::Object* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Object*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT_RECEIVEMESSAGE_OFFSET))(this, a1, a2);
		}

		::System::Void __FinishBattleWin_b__22_0(::Class_1_FFE5B8A52EC38E9C_5* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FFE5B8A52EC38E9C_5*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT___FINISHBATTLEWIN_B__22_0_OFFSET))(this, a1);
		}

		::System::Void __FinishBattleFail_b__24_0(::Class_1_FFE5B8A52EC38E9C_5* a1)
		{
			return ((::System::Void(*)(::PVOID, ::Class_1_FFE5B8A52EC38E9C_5*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVESTORYLINEGAMECONTEXT___FINISHBATTLEFAIL_B__24_0_OFFSET))(this, a1);
		}
	};
}
