#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/RPG/Client/TextID.h"
#include "unitysdk/System/Object.h"

namespace System { class String; }

#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GETNAME_OFFSET UNITYSDK_OFFSET(0xBB867E0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GETSTAR_OFFSET UNITYSDK_OFFSET(0xBB866D0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_AVATARID_OFFSET UNITYSDK_OFFSET(0xBB86660)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_DMGSTR_OFFSET UNITYSDK_OFFSET(0xBB864E0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_DMGVALUE_OFFSET UNITYSDK_OFFSET(0xBB864C0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_ICON_OFFSET UNITYSDK_OFFSET(0xBB864A0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_NAME_OFFSET UNITYSDK_OFFSET(0xBB86480)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_RATIOTOHIGHESTDMGVALUE_OFFSET UNITYSDK_OFFSET(0xBB86680)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SETDMGVALUE_OFFSET UNITYSDK_OFFSET(0xBB86860)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_AVATARID_OFFSET UNITYSDK_OFFSET(0xBB86670)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_DMGVALUE_OFFSET UNITYSDK_OFFSET(0xBB864D0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_ICON_OFFSET UNITYSDK_OFFSET(0xBB864B0)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_NAME_OFFSET UNITYSDK_OFFSET(0xBB86490)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_RATIOTOHIGHESTDMGVALUE_OFFSET UNITYSDK_OFFSET(0xBB86690)
#define RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA__CTOR_OFFSET UNITYSDK_OFFSET(0xBB866A0)

namespace RPG::Client::ActivityIdleLive
{
	inline static constexpr unsigned int IdleLiveDmgStatisticsUiData_TypeDefinitionIndex = 71810;

	class IdleLiveDmgStatisticsUiData : public ::System::Object
	{
	public:
		::System::String* _Icon_k__BackingField; // 0x10
		::System::Double _RatioToHighestDmgValue_k__BackingField; // 0x18
		::RPG::Client::TextID _Name_k__BackingField; // 0x20
		::System::UInt32 _AvatarId_k__BackingField; // 0x30
		::System::Int64 _DmgValue_k__BackingField; // 0x38

		::System::Void _ctor(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA__CTOR_OFFSET))(this, a1);
		}

		::RPG::Client::TextID get_Name()
		{
			return ((::RPG::Client::TextID(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_NAME_OFFSET))(this);
		}

		::System::Void set_Name(::RPG::Client::TextID a1)
		{
			return ((::System::Void(*)(::PVOID, ::RPG::Client::TextID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_NAME_OFFSET))(this, a1);
		}

		::System::String* get_Icon()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_ICON_OFFSET))(this);
		}

		::System::Void set_Icon(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_ICON_OFFSET))(this, a1);
		}

		::System::Int64 get_DmgValue()
		{
			return ((::System::Int64(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_DMGVALUE_OFFSET))(this);
		}

		::System::Void set_DmgValue(::System::Int64 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_DMGVALUE_OFFSET))(this, a1);
		}

		::System::String* get_DmgStr()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_DMGSTR_OFFSET))(this);
		}

		::System::UInt32 get_AvatarId()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_AVATARID_OFFSET))(this);
		}

		::System::Void set_AvatarId(::System::UInt32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::UInt32))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_AVATARID_OFFSET))(this, a1);
		}

		::System::Double get_RatioToHighestDmgValue()
		{
			return ((::System::Double(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GET_RATIOTOHIGHESTDMGVALUE_OFFSET))(this);
		}

		::System::Void set_RatioToHighestDmgValue(::System::Double a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Double))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SET_RATIOTOHIGHESTDMGVALUE_OFFSET))(this, a1);
		}

		::System::UInt32 GetStar()
		{
			return ((::System::UInt32(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GETSTAR_OFFSET))(this);
		}

		::System::String* GetName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_GETNAME_OFFSET))(this);
		}

		::System::Void SetDmgValue(::System::Int64 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64))((::PBYTE)hIl2Cpp + RPG_CLIENT_ACTIVITYIDLELIVE_IDLELIVEDMGSTATISTICSUIDATA_SETDMGVALUE_OFFSET))(this, a1);
		}
	};
}
