#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Object.h"

namespace UnityEngine { class GameObject; }

#define HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_MOVENEXT_OFFSET UNITYSDK_OFFSET(0x14BD9210)
#define HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_OBJECT__GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x14BD9270)
#define HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET UNITYSDK_OFFSET(0x14BD92D0)
#define HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET UNITYSDK_OFFSET(0x14BD9280)
#define HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET UNITYSDK_OFFSET(0x14BD9200)
#define HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16__CTOR_OFFSET UNITYSDK_OFFSET(0x14BD91E0)

inline static constexpr unsigned int HipplenBuilderMiniGameController__DestroyRingAfter2Seconds_d__16_TypeDefinitionIndex = 45414;

class HipplenBuilderMiniGameController__DestroyRingAfter2Seconds_d__16 : public ::System::Object
{
public:
	::UnityEngine::GameObject* ringGO; // 0x10
	::System::Object* __2__current; // 0x18
	::System::Int32 __1__state; // 0x20

	::System::Void _ctor(::System::Int32 a1)
	{
		return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16__CTOR_OFFSET))(this, a1);
	}

	::System::Void System_IDisposable_Dispose()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_IDISPOSABLE_DISPOSE_OFFSET))(this);
	}

	::System::Boolean MoveNext()
	{
		return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_MOVENEXT_OFFSET))(this);
	}

	::System::Object* System_Collections_Generic_IEnumerator_System_Object__get_Current()
	{
		return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_COLLECTIONS_GENERIC_IENUMERATOR_SYSTEM_OBJECT__GET_CURRENT_OFFSET))(this);
	}

	::System::Void System_Collections_IEnumerator_Reset()
	{
		return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_COLLECTIONS_IENUMERATOR_RESET_OFFSET))(this);
	}

	::System::Object* System_Collections_IEnumerator_get_Current()
	{
		return ((::System::Object*(*)(::PVOID))((::PBYTE)hIl2Cpp + HIPPLENBUILDERMINIGAMECONTROLLER__DESTROYRINGAFTER2SECONDS_D__16_SYSTEM_COLLECTIONS_IENUMERATOR_GET_CURRENT_OFFSET))(this);
	}
};
