#pragma once
#include "unitysdk/unitysdk.h"
#include "unitysdk/System/Xml/DtdProcessing.h"
#include "unitysdk/System/Xml/EntityHandling.h"
#include "unitysdk/System/Xml/LineInfo.h"
#include "unitysdk/System/Xml/ReadState.h"
#include "unitysdk/System/Xml/Schema/XmlSeverityType.h"
#include "unitysdk/System/Xml/WhitespaceHandling.h"
#include "unitysdk/System/Xml/XmlCharType.h"
#include "unitysdk/System/Xml/XmlNodeType.h"
#include "unitysdk/System/Xml/XmlReader.h"
#include "unitysdk/System/Xml/XmlTextReaderImpl_EntityExpandType.h"
#include "unitysdk/System/Xml/XmlTextReaderImpl_EntityType.h"
#include "unitysdk/System/Xml/XmlTextReaderImpl_IncrementalReadState.h"
#include "unitysdk/System/Xml/XmlTextReaderImpl_ParsingFunction.h"
#include "unitysdk/System/Xml/XmlTextReaderImpl_ParsingMode.h"
#include "unitysdk/System/Xml/XmlTextReaderImpl_ParsingState.h"

namespace System { class Exception; }
namespace System { class Object; }
namespace System { class String; }
namespace System { class Uri; }
namespace System { template <typename T1, typename T2, typename T3, typename T4> class Tuple_4; }
namespace System::Collections::Generic { template <typename T1, typename T2> class Dictionary_2; }
namespace System::IO { class Stream; }
namespace System::IO { class TextReader; }
namespace System::Text { class Encoding; }
namespace System::Text { class StringBuilder; }
namespace System::Threading::Tasks { template <typename T> class Task_1; }
namespace System::Xml { class IDtdDefaultAttributeInfo; }
namespace System::Xml { class IDtdEntityInfo; }
namespace System::Xml { class IDtdInfo; }
namespace System::Xml { class IValidationEventHandling; }
namespace System::Xml { class IXmlNamespaceResolver; }
namespace System::Xml { class IncrementalReadDecoder; }
namespace System::Xml { class XmlNameTable; }
namespace System::Xml { class XmlNamespaceManager; }
namespace System::Xml { class XmlParserContext; }
namespace System::Xml { class XmlReaderSettings; }
namespace System::Xml { class XmlResolver; }
namespace System::Xml { class XmlTextReaderImpl_LaterInitParam; }
namespace System::Xml { class XmlTextReaderImpl_NodeData; }
namespace System::Xml { class XmlTextReaderImpl_OnDefaultAttributeUseDelegate; }
namespace System::Xml { class XmlTextReaderImpl_XmlContext; }
namespace System::Xml::Schema { class XmlSchemaException; }

#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTECHUNKTOLIST_OFFSET UNITYSDK_OFFSET(0x1CC27A40)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTENOCHECKS_OFFSET UNITYSDK_OFFSET(0x1CC1FEA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTE_1_OFFSET UNITYSDK_OFFSET(0x1CC2AAF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC25C40)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDDEFAULTATTRIBUTEDTD_OFFSET UNITYSDK_OFFSET(0x1CC2C190)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDDEFAULTATTRIBUTEINTERNAL_OFFSET UNITYSDK_OFFSET(0x1CC2C4C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDDEFAULTATTRIBUTESANDNORMALIZE_OFFSET UNITYSDK_OFFSET(0x1CC24EC0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDNAMESPACE_OFFSET UNITYSDK_OFFSET(0x1CC27780)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ADDNODE_OFFSET UNITYSDK_OFFSET(0x1CC1BA20)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ALLOCNODE_OFFSET UNITYSDK_OFFSET(0x1CC2A960)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ATTRIBUTEDUPLCHECK_OFFSET UNITYSDK_OFFSET(0x1CC27390)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ATTRIBUTENAMESPACELOOKUP_OFFSET UNITYSDK_OFFSET(0x1CC25960)
#define SYSTEM_XML_XMLTEXTREADERIMPL_BLOCKCOPYCHARS_OFFSET UNITYSDK_OFFSET(0x1CC2CCE0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_BLOCKCOPY_OFFSET UNITYSDK_OFFSET(0x1CC2CD00)
#define SYSTEM_XML_XMLTEXTREADERIMPL_CHECKENCODING_OFFSET UNITYSDK_OFFSET(0x1CC21C60)
#define SYSTEM_XML_XMLTEXTREADERIMPL_CLOSE_1_OFFSET UNITYSDK_OFFSET(0x1CC1C480)
#define SYSTEM_XML_XMLTEXTREADERIMPL_CLOSE_OFFSET UNITYSDK_OFFSET(0x1CC06CE0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DETECTENCODING_OFFSET UNITYSDK_OFFSET(0x1CC211F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_ONNEWLINE_OFFSET UNITYSDK_OFFSET(0x1CC1D580)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_ONPUBLICID_OFFSET UNITYSDK_OFFSET(0x1CC1FF70)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_ONSYSTEMID_OFFSET UNITYSDK_OFFSET(0x1CC1FE30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSECOMMENT_OFFSET UNITYSDK_OFFSET(0x1CC1E2A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSENAMEDCHARREF_OFFSET UNITYSDK_OFFSET(0x1CC1DD50)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSENUMERICCHARREF_OFFSET UNITYSDK_OFFSET(0x1CC1DBF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSEPI_OFFSET UNITYSDK_OFFSET(0x1CC1DE10)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_POPENTITY_OFFSET UNITYSDK_OFFSET(0x1CC1EC30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PUSHENTITY_OFFSET UNITYSDK_OFFSET(0x1CC1E7B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PUSHEXTERNALSUBSET_OFFSET UNITYSDK_OFFSET(0x1CC1EE30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PUSHINTERNALDTD_OFFSET UNITYSDK_OFFSET(0x1CC1F8A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_READDATA_OFFSET UNITYSDK_OFFSET(0x1CC1D5C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_THROW_OFFSET UNITYSDK_OFFSET(0x1CC1FCB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_EATWHITESPACES_OFFSET UNITYSDK_OFFSET(0x1CC1F340)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ELEMENTNAMESPACELOOKUP_OFFSET UNITYSDK_OFFSET(0x1CC25910)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHATTRIBUTEVALUEITERATOR_OFFSET UNITYSDK_OFFSET(0x1CC199C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINCREMENTALREAD_OFFSET UNITYSDK_OFFSET(0x1CC1BCA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINITSTREAM_OFFSET UNITYSDK_OFFSET(0x1CC18C70)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINITTEXTREADER_OFFSET UNITYSDK_OFFSET(0x1CC18DF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINITURISTRING_OFFSET UNITYSDK_OFFSET(0x1CC184A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINIT_OFFSET UNITYSDK_OFFSET(0x1CC19B60)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHOTHERVALUEITERATOR_OFFSET UNITYSDK_OFFSET(0x1CC19650)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHPARTIALVALUE_OFFSET UNITYSDK_OFFSET(0x1CC19500)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHREADCONTENTASBINARY_OFFSET UNITYSDK_OFFSET(0x1CC1C220)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHREADELEMENTCONTENTASBINARY_OFFSET UNITYSDK_OFFSET(0x1CC1C290)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FINISHREADVALUECHUNK_OFFSET UNITYSDK_OFFSET(0x1CC1C1E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_FULLATTRIBUTECLEANUP_OFFSET UNITYSDK_OFFSET(0x1CC2ACA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETATTRIBUTE_1_OFFSET UNITYSDK_OFFSET(0x1CC16500)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC16440)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETCHARS_OFFSET UNITYSDK_OFFSET(0x1CC22330)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETINDEXOFATTRIBUTEWITHOUTPREFIX_OFFSET UNITYSDK_OFFSET(0x1CC197F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETINDEXOFATTRIBUTEWITHPREFIX_OFFSET UNITYSDK_OFFSET(0x1CC198A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETTEMPRESOLVER_OFFSET UNITYSDK_OFFSET(0x1CC1E760)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETTEXTNODETYPE_OFFSET UNITYSDK_OFFSET(0x1CC28340)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GETWHITESPACETYPE_OFFSET UNITYSDK_OFFSET(0x1CC28640)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_BASEURI_OFFSET UNITYSDK_OFFSET(0x1CC197B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_CANRESOLVEENTITY_OFFSET UNITYSDK_OFFSET(0x1CC197E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DEPTH_OFFSET UNITYSDK_OFFSET(0x1CC16300)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDINFO_OFFSET UNITYSDK_OFFSET(0x1CC2C0A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_BASEURI_OFFSET UNITYSDK_OFFSET(0x1CC1D410)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_CURRENTPOSITION_OFFSET UNITYSDK_OFFSET(0x1CC1D530)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_DTDVALIDATION_OFFSET UNITYSDK_OFFSET(0x1CC1D3C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_ENTITYSTACKLENGTH_OFFSET UNITYSDK_OFFSET(0x1CC1D550)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_ISENTITYEOLNORMALIZED_OFFSET UNITYSDK_OFFSET(0x1CC1D560)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_ISEOF_OFFSET UNITYSDK_OFFSET(0x1CC1D500)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_LINENO_OFFSET UNITYSDK_OFFSET(0x1CC1D5A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_LINESTARTPOSITION_OFFSET UNITYSDK_OFFSET(0x1CC1D5B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NAMESPACERESOLVER_OFFSET UNITYSDK_OFFSET(0x1CC1D3B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NAMESPACES_OFFSET UNITYSDK_OFFSET(0x1CC1D3F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NAMETABLE_OFFSET UNITYSDK_OFFSET(0x1CC1D3A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NORMALIZATION_OFFSET UNITYSDK_OFFSET(0x1CC1D3E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_PARSINGBUFFERLENGTH_OFFSET UNITYSDK_OFFSET(0x1CC1D520)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_PARSINGBUFFER_OFFSET UNITYSDK_OFFSET(0x1CC1D510)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_V1COMPATIBILITYMODE_OFFSET UNITYSDK_OFFSET(0x1CC1D400)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_VALIDATIONEVENTHANDLING_OFFSET UNITYSDK_OFFSET(0x1CC1D570)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDVALIDATION_OFFSET UNITYSDK_OFFSET(0x1CC1D3D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_INATTRIBUTEVALUEITERATOR_OFFSET UNITYSDK_OFFSET(0x1CC199A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_INENTITY_OFFSET UNITYSDK_OFFSET(0x1CC22240)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_ISDEFAULT_OFFSET UNITYSDK_OFFSET(0x1CC163F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_ISEMPTYELEMENT_OFFSET UNITYSDK_OFFSET(0x1CC16380)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_ISRESOLVERNULL_OFFSET UNITYSDK_OFFSET(0x1CC1E750)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_LINENUMBER_OFFSET UNITYSDK_OFFSET(0x1CC174F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_LINEPOSITION_OFFSET UNITYSDK_OFFSET(0x1CC17540)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_LOCALNAME_OFFSET UNITYSDK_OFFSET(0x1CC16190)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_NAMESPACEURI_OFFSET UNITYSDK_OFFSET(0x1CC161E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_NAMETABLE_OFFSET UNITYSDK_OFFSET(0x1CC197D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_NAME_OFFSET UNITYSDK_OFFSET(0x1CC160E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_NODETYPE_OFFSET UNITYSDK_OFFSET(0x1CC16040)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_PREFIX_OFFSET UNITYSDK_OFFSET(0x1CC16230)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_READSTATE_OFFSET UNITYSDK_OFFSET(0x1CC197C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_SETTINGS_OFFSET UNITYSDK_OFFSET(0x1CC18FB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_GET_VALUE_OFFSET UNITYSDK_OFFSET(0x1CC06C70)
#define SYSTEM_XML_XMLTEXTREADERIMPL_HANDLEENTITYEND_OFFSET UNITYSDK_OFFSET(0x1CC21010)
#define SYSTEM_XML_XMLTEXTREADERIMPL_HANDLEENTITYREFERENCE_OFFSET UNITYSDK_OFFSET(0x1CC23380)
#define SYSTEM_XML_XMLTEXTREADERIMPL_HANDLEGENERALENTITYREFERENCE_OFFSET UNITYSDK_OFFSET(0x1CC1CD80)
#define SYSTEM_XML_XMLTEXTREADERIMPL_HASLINEINFO_OFFSET UNITYSDK_OFFSET(0x1CC1D240)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INCREMENTALREAD_OFFSET UNITYSDK_OFFSET(0x1CC2B250)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITFRAGMENTREADER_OFFSET UNITYSDK_OFFSET(0x1CC181B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITSTREAMINPUT_1_OFFSET UNITYSDK_OFFSET(0x1CC211C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITSTREAMINPUT_2_OFFSET UNITYSDK_OFFSET(0x1CC188A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITSTREAMINPUT_OFFSET UNITYSDK_OFFSET(0x1CC21160)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITSTRINGINPUT_OFFSET UNITYSDK_OFFSET(0x1CC18100)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITTEXTREADERINPUT_1_OFFSET UNITYSDK_OFFSET(0x1CC21640)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INITTEXTREADERINPUT_OFFSET UNITYSDK_OFFSET(0x1CC18070)
#define SYSTEM_XML_XMLTEXTREADERIMPL_INVALIDCHARRECOVERY_OFFSET UNITYSDK_OFFSET(0x1CC22510)
#define SYSTEM_XML_XMLTEXTREADERIMPL_LOOKUPNAMESPACE_1_OFFSET UNITYSDK_OFFSET(0x1CC27620)
#define SYSTEM_XML_XMLTEXTREADERIMPL_LOOKUPNAMESPACE_OFFSET UNITYSDK_OFFSET(0x1CC17220)
#define SYSTEM_XML_XMLTEXTREADERIMPL_LOOKUPPREFIX_OFFSET UNITYSDK_OFFSET(0x1CC176D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_MOVEOFFENTITYREFERENCE_OFFSET UNITYSDK_OFFSET(0x1CC17330)
#define SYSTEM_XML_XMLTEXTREADERIMPL_MOVETOATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC06BC0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_MOVETOELEMENT_OFFSET UNITYSDK_OFFSET(0x1CC168C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_MOVETOFIRSTATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC166B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_MOVETONEXTATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC167B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_MOVETONEXTCONTENTNODE_OFFSET UNITYSDK_OFFSET(0x1CC28470)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ONDEFAULTNAMESPACEDECL_OFFSET UNITYSDK_OFFSET(0x1CC26D30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ONEOF_OFFSET UNITYSDK_OFFSET(0x1CC1BF00)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ONNAMESPACEDECL_OFFSET UNITYSDK_OFFSET(0x1CC26EB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ONNEWLINE_OFFSET UNITYSDK_OFFSET(0x1CC1D590)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ONXMLRESERVEDATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC26F80)
#define SYSTEM_XML_XMLTEXTREADERIMPL_OPENANDPUSH_OFFSET UNITYSDK_OFFSET(0x1CC2AD20)
#define SYSTEM_XML_XMLTEXTREADERIMPL_OPENURLDELEGATE_OFFSET UNITYSDK_OFFSET(0x1CC21870)
#define SYSTEM_XML_XMLTEXTREADERIMPL_OPENURL_OFFSET UNITYSDK_OFFSET(0x1CC1A630)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEATTRIBUTES_OFFSET UNITYSDK_OFFSET(0x1CC24760)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEATTRIBUTEVALUECHUNK_OFFSET UNITYSDK_OFFSET(0x1CC1C6B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEATTRIBUTEVALUESLOW_OFFSET UNITYSDK_OFFSET(0x1CC25E00)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSECDATAORCOMMENT_1_OFFSET UNITYSDK_OFFSET(0x1CC28B70)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSECDATAORCOMMENT_OFFSET UNITYSDK_OFFSET(0x1CC1E4A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSECDATA_OFFSET UNITYSDK_OFFSET(0x1CC22A10)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSECHARREFINLINE_OFFSET UNITYSDK_OFFSET(0x1CC28390)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSECOMMENT_OFFSET UNITYSDK_OFFSET(0x1CC22990)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDOCTYPEDECL_OFFSET UNITYSDK_OFFSET(0x1CC22A20)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDOCUMENTCONTENT_OFFSET UNITYSDK_OFFSET(0x1CC19FA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDTDFROMPARSERCONTEXT_OFFSET UNITYSDK_OFFSET(0x1CC216D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDTD_OFFSET UNITYSDK_OFFSET(0x1CC290B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEELEMENTCONTENT_OFFSET UNITYSDK_OFFSET(0x1CC19BB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEELEMENT_OFFSET UNITYSDK_OFFSET(0x1CC22CE0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEENDELEMENT_OFFSET UNITYSDK_OFFSET(0x1CC23FF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEENTITYNAME_OFFSET UNITYSDK_OFFSET(0x1CC27A80)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEENTITYREFERENCE_OFFSET UNITYSDK_OFFSET(0x1CC1BB20)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEFRAGMENTATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC1BCF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSENAMEDCHARREFINLINE_OFFSET UNITYSDK_OFFSET(0x1CC2A370)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSENAMEDCHARREF_OFFSET UNITYSDK_OFFSET(0x1CC1DDB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSENAME_OFFSET UNITYSDK_OFFSET(0x1CC22860)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSENUMERICCHARREFINLINE_OFFSET UNITYSDK_OFFSET(0x1CC29D70)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSENUMERICCHARREF_OFFSET UNITYSDK_OFFSET(0x1CC1DCA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEPIVALUE_OFFSET UNITYSDK_OFFSET(0x1CC286F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEPI_1_OFFSET UNITYSDK_OFFSET(0x1CC1DE60)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEPI_OFFSET UNITYSDK_OFFSET(0x1CC22980)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEQNAME_1_OFFSET UNITYSDK_OFFSET(0x1CC2A670)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEQNAME_OFFSET UNITYSDK_OFFSET(0x1CC24750)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEROOTLEVELWHITESPACE_OFFSET UNITYSDK_OFFSET(0x1CC23D30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSETEXT_1_OFFSET UNITYSDK_OFFSET(0x1CC27BC0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSETEXT_OFFSET UNITYSDK_OFFSET(0x1CC23700)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEUNEXPECTEDTOKEN_1_OFFSET UNITYSDK_OFFSET(0x1CC2BFF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEUNEXPECTEDTOKEN_OFFSET UNITYSDK_OFFSET(0x1CC22CB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEXMLDECLARATIONFRAGMENT_OFFSET UNITYSDK_OFFSET(0x1CC1BE30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PARSEXMLDECLARATION_OFFSET UNITYSDK_OFFSET(0x1CC1A890)
#define SYSTEM_XML_XMLTEXTREADERIMPL_POPELEMENTCONTEXT_OFFSET UNITYSDK_OFFSET(0x1CC1BA60)
#define SYSTEM_XML_XMLTEXTREADERIMPL_POPENTITY_OFFSET UNITYSDK_OFFSET(0x1CC1EC80)
#define SYSTEM_XML_XMLTEXTREADERIMPL_POPPARSINGSTATE_OFFSET UNITYSDK_OFFSET(0x1CC22770)
#define SYSTEM_XML_XMLTEXTREADERIMPL_POPXMLCONTEXT_OFFSET UNITYSDK_OFFSET(0x1CC2AC60)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PROCESSDTDFROMPARSERCONTEXT_OFFSET UNITYSDK_OFFSET(0x1CC18C10)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PUSHEXTERNALENTITYORSUBSET_OFFSET UNITYSDK_OFFSET(0x1CC1EFB0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PUSHEXTERNALENTITY_OFFSET UNITYSDK_OFFSET(0x1CC1E800)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PUSHINTERNALENTITY_OFFSET UNITYSDK_OFFSET(0x1CC1EAD0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PUSHPARSINGSTATE_OFFSET UNITYSDK_OFFSET(0x1CC1F9F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_PUSHXMLCONTEXT_OFFSET UNITYSDK_OFFSET(0x1CC27710)
#define SYSTEM_XML_XMLTEXTREADERIMPL_READATTRIBUTEVALUE_OFFSET UNITYSDK_OFFSET(0x1CC16960)
#define SYSTEM_XML_XMLTEXTREADERIMPL_READDATAINNAME_OFFSET UNITYSDK_OFFSET(0x1CC2A930)
#define SYSTEM_XML_XMLTEXTREADERIMPL_READDATA_OFFSET UNITYSDK_OFFSET(0x1CC1D5D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_READSTRING_OFFSET UNITYSDK_OFFSET(0x1CC1D220)
#define SYSTEM_XML_XMLTEXTREADERIMPL_READ_OFFSET UNITYSDK_OFFSET(0x1CC05EF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_REGISTERCONSUMEDCHARACTERS_OFFSET UNITYSDK_OFFSET(0x1CC2C850)
#define SYSTEM_XML_XMLTEXTREADERIMPL_REGISTERENTITY_OFFSET UNITYSDK_OFFSET(0x1CC2AFE0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_RESETATTRIBUTES_OFFSET UNITYSDK_OFFSET(0x1CC1B970)
#define SYSTEM_XML_XMLTEXTREADERIMPL_RESOLVEENTITY_OFFSET UNITYSDK_OFFSET(0x1CC067F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_RETHROW_OFFSET UNITYSDK_OFFSET(0x1CC20960)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SENDVALIDATIONEVENT_1_OFFSET UNITYSDK_OFFSET(0x1CC20EE0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SENDVALIDATIONEVENT_OFFSET UNITYSDK_OFFSET(0x1CC1E6B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SETDTDINFO_OFFSET UNITYSDK_OFFSET(0x1CC2C0B0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SETERRORSTATE_OFFSET UNITYSDK_OFFSET(0x1CC20940)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SETUPENCODING_OFFSET UNITYSDK_OFFSET(0x1CC21460)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SETUPENDENTITYNODEINATTRIBUTE_OFFSET UNITYSDK_OFFSET(0x1CC28680)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SETUPENDENTITYNODEINCONTENT_OFFSET UNITYSDK_OFFSET(0x1CC1BBA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_DISABLEUNDECLAREDENTITYCHECK_OFFSET UNITYSDK_OFFSET(0x1CC2C840)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_DTDPARSERPROXY_CURRENTPOSITION_OFFSET UNITYSDK_OFFSET(0x1CC1D540)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_ENTITYHANDLING_OFFSET UNITYSDK_OFFSET(0x1CC17990)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_NAMESPACES_OFFSET UNITYSDK_OFFSET(0x1CC03EC0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_NORMALIZATION_OFFSET UNITYSDK_OFFSET(0x1CC17810)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_OUTERREADER_OFFSET UNITYSDK_OFFSET(0x1CC1D210)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_WHITESPACEHANDLING_OFFSET UNITYSDK_OFFSET(0x1CC178D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_XMLRESOLVER_OFFSET UNITYSDK_OFFSET(0x1CC040D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SET_XMLVALIDATINGREADERCOMPATIBILITYMODE_OFFSET UNITYSDK_OFFSET(0x1CC2C0F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SHIFTBUFFER_OFFSET UNITYSDK_OFFSET(0x1CC22820)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SKIPDTD_OFFSET UNITYSDK_OFFSET(0x1CC292C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SKIPPARTIALTEXTVALUE_OFFSET UNITYSDK_OFFSET(0x1CC1C190)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SKIPPUBLICORSYSTEMIDLITERAL_OFFSET UNITYSDK_OFFSET(0x1CC29770)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SKIPUNTIL_OFFSET UNITYSDK_OFFSET(0x1CC297D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SKIP_OFFSET UNITYSDK_OFFSET(0x1CC16D90)
#define SYSTEM_XML_XMLTEXTREADERIMPL_STRIPSPACES_1_OFFSET UNITYSDK_OFFSET(0x1CC2CBA0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_STRIPSPACES_OFFSET UNITYSDK_OFFSET(0x1CC2C900)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SWITCHENCODINGTOUTF8_OFFSET UNITYSDK_OFFSET(0x1CC22250)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SWITCHENCODING_OFFSET UNITYSDK_OFFSET(0x1CC21950)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SYSTEM_XML_IXMLNAMESPACERESOLVER_LOOKUPNAMESPACE_OFFSET UNITYSDK_OFFSET(0x1CC1D250)
#define SYSTEM_XML_XMLTEXTREADERIMPL_SYSTEM_XML_IXMLNAMESPACERESOLVER_LOOKUPPREFIX_OFFSET UNITYSDK_OFFSET(0x1CC1D300)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWEXPECTINGWHITESPACE_OFFSET UNITYSDK_OFFSET(0x1CC25BC0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWINVALIDCHAR_OFFSET UNITYSDK_OFFSET(0x1CC20E50)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWTAGMISMATCH_OFFSET UNITYSDK_OFFSET(0x1CC25A10)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNCLOSEDELEMENTS_OFFSET UNITYSDK_OFFSET(0x1CC243E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_1_OFFSET UNITYSDK_OFFSET(0x1CC22850)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_2_OFFSET UNITYSDK_OFFSET(0x1CC22CC0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_3_OFFSET UNITYSDK_OFFSET(0x1CC22880)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_OFFSET UNITYSDK_OFFSET(0x1CC229F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWWITHOUTLINEINFO_1_OFFSET UNITYSDK_OFFSET(0x1CC20B10)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWWITHOUTLINEINFO_2_OFFSET UNITYSDK_OFFSET(0x1CC20CD0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROWWITHOUTLINEINFO_OFFSET UNITYSDK_OFFSET(0x1CC1BFD0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_10_OFFSET UNITYSDK_OFFSET(0x1CC1FD70)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_1_OFFSET UNITYSDK_OFFSET(0x1CC201D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_2_OFFSET UNITYSDK_OFFSET(0x1CC20380)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_3_OFFSET UNITYSDK_OFFSET(0x1CC203A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_4_OFFSET UNITYSDK_OFFSET(0x1CC203C0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_5_OFFSET UNITYSDK_OFFSET(0x1CC20000)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_6_OFFSET UNITYSDK_OFFSET(0x1CC20580)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_7_OFFSET UNITYSDK_OFFSET(0x1CC201F0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_8_OFFSET UNITYSDK_OFFSET(0x1CC20740)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_9_OFFSET UNITYSDK_OFFSET(0x1CC207A0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_THROW_OFFSET UNITYSDK_OFFSET(0x1CC1FFE0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_UNDECODECHARS_OFFSET UNITYSDK_OFFSET(0x1CC21B30)
#define SYSTEM_XML_XMLTEXTREADERIMPL_UNREGISTERENTITY_OFFSET UNITYSDK_OFFSET(0x1CC2B1E0)
#define SYSTEM_XML_XMLTEXTREADERIMPL_ZEROENDINGSTREAM_OFFSET UNITYSDK_OFFSET(0x1CC28400)
#define SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_1_OFFSET UNITYSDK_OFFSET(0x1CC15F10)
#define SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_2_OFFSET UNITYSDK_OFFSET(0x1CC15FF0)
#define SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_3_OFFSET UNITYSDK_OFFSET(0x1CC17F60)
#define SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_4_OFFSET UNITYSDK_OFFSET(0x1CC03C10)
#define SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_5_OFFSET UNITYSDK_OFFSET(0x1CC069D0)
#define SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_OFFSET UNITYSDK_OFFSET(0x1CC17A40)

namespace System::Xml
{
	inline static constexpr unsigned int XmlTextReaderImpl_TypeDefinitionIndex = 1839;

	class XmlTextReaderImpl : public ::System::Xml::XmlReader
	{
	public:
		::Il2CppArray<::System::Xml::XmlTextReaderImpl_NodeData*>* attrDuplSortingArray; // 0x10
		::System::Xml::XmlReader* outerReader; // 0x18
		::System::Threading::Tasks::Task_1<::System::Tuple_4<::System::Int32, ::System::Int32, ::System::Int32, ::System::Boolean>*>* parseText_dummyTask; // 0x20
		::System::Xml::XmlResolver* xmlResolver; // 0x28
		::System::Xml::IDtdInfo* dtdInfo; // 0x30
		::System::Xml::XmlTextReaderImpl_NodeData* curNode; // 0x38
		::System::Xml::XmlTextReaderImpl_LaterInitParam* laterInitParam; // 0x40
		::System::String* url; // 0x48
		::System::Xml::XmlCharType xmlCharType; // 0x50
		::System::Xml::IncrementalReadDecoder* incReadDecoder; // 0x58
		::System::String* Xml; // 0x60
		::Il2CppArray<::System::Xml::XmlTextReaderImpl_NodeData*>* nodes; // 0x68
		::System::Text::Encoding* reportedEncoding; // 0x70
		::System::Xml::XmlTextReaderImpl_XmlContext* xmlContext; // 0x78
		::System::Text::StringBuilder* stringBuilder; // 0x80
		::System::String* lastPrefix; // 0x88
		::System::Xml::XmlNameTable* nameTable; // 0x90
		::System::Xml::XmlParserContext* fragmentParserContext; // 0x98
		::System::Xml::IValidationEventHandling* validationEventHandling; // 0xA0
		::Il2CppArray<::System::Xml::XmlTextReaderImpl_ParsingState>* parsingStatesStack; // 0xA8
		::System::Collections::Generic::Dictionary_2<::System::Xml::IDtdEntityInfo*, ::System::Xml::IDtdEntityInfo*>* currentEntities; // 0xB0
		::System::Xml::XmlTextReaderImpl_ParsingState ps; // 0xB8
		::System::Xml::XmlTextReaderImpl_OnDefaultAttributeUseDelegate* onDefaultAttributeUse; // 0x130
		::System::Xml::XmlNamespaceManager* namespaceManager; // 0x138
		::System::Xml::IDtdEntityInfo* lastEntity; // 0x140
		::System::String* reportedBaseUri; // 0x148
		::System::String* XmlNs; // 0x150
		::System::Int64 charactersInDocument; // 0x158
		::System::Boolean attrNeedNamespaceLookup; // 0x160
		::System::Boolean addDefaultAttributesAndNormalize; // 0x161
		::System::Boolean checkCharacters; // 0x162
		::System::Boolean xmlResolverIsSet; // 0x163
		::System::Xml::XmlTextReaderImpl_ParsingFunction nextParsingFunction; // 0x164
		::System::Xml::XmlNodeType fragmentType; // 0x168
		::System::Xml::LineInfo incReadLineInfo; // 0x16C
		::System::Xml::WhitespaceHandling whitespaceHandling; // 0x174
		::System::Boolean emptyEntityInAttributeResolved; // 0x178
		::System::Boolean validatingReaderCompatFlag; // 0x179
		::System::Boolean afterResetState; // 0x17A
		::System::Boolean v1Compat; // 0x17B
		::System::Int64 maxCharactersFromEntities; // 0x180
		::System::Xml::XmlTextReaderImpl_ParsingFunction nextNextParsingFunction; // 0x188
		::System::Int32 parsingStatesStackTop; // 0x18C
		::System::Int32 incReadLeftStartPos; // 0x190
		::System::Xml::XmlTextReaderImpl_ParsingMode parsingMode; // 0x194
		::System::Int64 charactersFromEntities; // 0x198
		::System::Int32 attrDuplWalkCount; // 0x1A0
		::System::Int32 nextEntityId; // 0x1A4
		::System::Int32 index; // 0x1A8
		::System::Boolean rootElementParsed; // 0x1AC
		::System::Boolean fragment; // 0x1AD
		::System::Boolean fullAttrCleanup; // 0x1AE
		::System::Boolean standalone; // 0x1AF
		::System::Boolean normalize; // 0x1B0
		::System::Boolean closeInput; // 0x1B1
		::System::Boolean disableUndeclaredEntityCheck; // 0x1B2
		::System::Boolean ignoreComments; // 0x1B3
		::System::Boolean ignorePIs; // 0x1B4
		::System::Boolean supportNamespaces; // 0x1B5
		::System::Boolean nameTableFromSettings; // 0x1B6
		::System::Int32 attrCount; // 0x1B8
		::System::Int32 attributeValueBaseEntityId; // 0x1BC
		::System::Int32 linePositionOffset; // 0x1C0
		::System::Int32 documentStartBytePos; // 0x1C4
		::System::Int32 attrHashtable; // 0x1C8
		::System::Xml::DtdProcessing dtdProcessing; // 0x1CC
		::System::Xml::XmlTextReaderImpl_ParsingFunction parsingFunction; // 0x1D0
		::System::Int32 incReadDepth; // 0x1D4
		::System::Int32 lineNumberOffset; // 0x1D8
		::System::Int32 readValueOffset; // 0x1DC
		::System::Int32 curAttrIndex; // 0x1E0
		::System::Int64 maxCharactersInDocument; // 0x1E8
		::System::Xml::XmlTextReaderImpl_IncrementalReadState incReadState; // 0x1F0
		::System::Xml::ReadState readState; // 0x1F4
		::System::Xml::EntityHandling entityHandling; // 0x1F8
		::System::Int32 incReadLeftEndPos; // 0x1FC

		::System::Void _ctor(::System::Xml::XmlNameTable* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlNameTable*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_OFFSET))(this, a1);
		}

		::System::Void _ctor_1(::System::IO::TextReader* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::IO::TextReader*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_1_OFFSET))(this, a1);
		}

		::System::Void _ctor_2(::System::IO::TextReader* a1, ::System::Xml::XmlNameTable* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::IO::TextReader*, ::System::Xml::XmlNameTable*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_2_OFFSET))(this, a1, a2);
		}

		::System::Void _ctor_3(::System::String* a1, ::System::IO::TextReader* a2, ::System::Xml::XmlNameTable* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::IO::TextReader*, ::System::Xml::XmlNameTable*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_3_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _ctor_4(::System::String* a1, ::System::Xml::XmlNodeType a2, ::System::Xml::XmlParserContext* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Xml::XmlNodeType, ::System::Xml::XmlParserContext*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_4_OFFSET))(this, a1, a2, a3);
		}

		::System::Void _ctor_5(::System::String* a1, ::System::Xml::XmlParserContext* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Xml::XmlParserContext*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL__CTOR_5_OFFSET))(this, a1, a2);
		}

		::System::Void FinishInitUriString()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINITURISTRING_OFFSET))(this);
		}

		::System::Void FinishInitStream()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINITSTREAM_OFFSET))(this);
		}

		::System::Void FinishInitTextReader()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINITTEXTREADER_OFFSET))(this);
		}

		::System::Xml::XmlReaderSettings* get_Settings()
		{
			return ((::System::Xml::XmlReaderSettings*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_SETTINGS_OFFSET))(this);
		}

		::System::Xml::XmlNodeType get_NodeType()
		{
			return ((::System::Xml::XmlNodeType(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_NODETYPE_OFFSET))(this);
		}

		::System::String* get_Name()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_NAME_OFFSET))(this);
		}

		::System::String* get_LocalName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_LOCALNAME_OFFSET))(this);
		}

		::System::String* get_NamespaceURI()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_NAMESPACEURI_OFFSET))(this);
		}

		::System::String* get_Prefix()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_PREFIX_OFFSET))(this);
		}

		::System::String* get_Value()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_VALUE_OFFSET))(this);
		}

		::System::Int32 get_Depth()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DEPTH_OFFSET))(this);
		}

		::System::String* get_BaseURI()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_BASEURI_OFFSET))(this);
		}

		::System::Boolean get_IsEmptyElement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_ISEMPTYELEMENT_OFFSET))(this);
		}

		::System::Boolean get_IsDefault()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_ISDEFAULT_OFFSET))(this);
		}

		::System::Xml::ReadState get_ReadState()
		{
			return ((::System::Xml::ReadState(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_READSTATE_OFFSET))(this);
		}

		::System::Xml::XmlNameTable* get_NameTable()
		{
			return ((::System::Xml::XmlNameTable*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_NAMETABLE_OFFSET))(this);
		}

		::System::Boolean get_CanResolveEntity()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_CANRESOLVEENTITY_OFFSET))(this);
		}

		::System::String* GetAttribute(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETATTRIBUTE_OFFSET))(this, a1);
		}

		::System::String* GetAttribute_1(::System::String* a1, ::System::String* a2)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETATTRIBUTE_1_OFFSET))(this, a1, a2);
		}

		::System::Boolean MoveToAttribute(::System::String* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_MOVETOATTRIBUTE_OFFSET))(this, a1);
		}

		::System::Boolean MoveToFirstAttribute()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_MOVETOFIRSTATTRIBUTE_OFFSET))(this);
		}

		::System::Boolean MoveToNextAttribute()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_MOVETONEXTATTRIBUTE_OFFSET))(this);
		}

		::System::Boolean MoveToElement()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_MOVETOELEMENT_OFFSET))(this);
		}

		::System::Void FinishInit()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINIT_OFFSET))(this);
		}

		::System::Boolean Read()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_READ_OFFSET))(this);
		}

		::System::Void Close()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_CLOSE_OFFSET))(this);
		}

		::System::Void Skip()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SKIP_OFFSET))(this);
		}

		::System::String* LookupNamespace(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_LOOKUPNAMESPACE_OFFSET))(this, a1);
		}

		::System::Boolean ReadAttributeValue()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_READATTRIBUTEVALUE_OFFSET))(this);
		}

		::System::Void ResolveEntity()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_RESOLVEENTITY_OFFSET))(this);
		}

		::System::Void set_OuterReader(::System::Xml::XmlReader* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlReader*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_OUTERREADER_OFFSET))(this, a1);
		}

		::System::Void MoveOffEntityReference()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_MOVEOFFENTITYREFERENCE_OFFSET))(this);
		}

		::System::String* ReadString()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_READSTRING_OFFSET))(this);
		}

		::System::Boolean HasLineInfo()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_HASLINEINFO_OFFSET))(this);
		}

		::System::Int32 get_LineNumber()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_LINENUMBER_OFFSET))(this);
		}

		::System::Int32 get_LinePosition()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_LINEPOSITION_OFFSET))(this);
		}

		::System::String* System_Xml_IXmlNamespaceResolver_LookupNamespace(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SYSTEM_XML_IXMLNAMESPACERESOLVER_LOOKUPNAMESPACE_OFFSET))(this, a1);
		}

		::System::String* System_Xml_IXmlNamespaceResolver_LookupPrefix(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SYSTEM_XML_IXMLNAMESPACERESOLVER_LOOKUPPREFIX_OFFSET))(this, a1);
		}

		::System::String* LookupPrefix(::System::String* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_LOOKUPPREFIX_OFFSET))(this, a1);
		}

		::System::Void set_Namespaces(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_NAMESPACES_OFFSET))(this, a1);
		}

		::System::Void set_Normalization(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_NORMALIZATION_OFFSET))(this, a1);
		}

		::System::Void set_WhitespaceHandling(::System::Xml::WhitespaceHandling a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::WhitespaceHandling))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_WHITESPACEHANDLING_OFFSET))(this, a1);
		}

		::System::Void set_EntityHandling(::System::Xml::EntityHandling a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::EntityHandling))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_ENTITYHANDLING_OFFSET))(this, a1);
		}

		::System::Void set_XmlResolver(::System::Xml::XmlResolver* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlResolver*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_XMLRESOLVER_OFFSET))(this, a1);
		}

		::System::Xml::XmlNameTable* get_DtdParserProxy_NameTable()
		{
			return ((::System::Xml::XmlNameTable*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NAMETABLE_OFFSET))(this);
		}

		::System::Xml::IXmlNamespaceResolver* get_DtdParserProxy_NamespaceResolver()
		{
			return ((::System::Xml::IXmlNamespaceResolver*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NAMESPACERESOLVER_OFFSET))(this);
		}

		::System::Boolean get_DtdParserProxy_DtdValidation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_DTDVALIDATION_OFFSET))(this);
		}

		::System::Boolean get_DtdParserProxy_Normalization()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NORMALIZATION_OFFSET))(this);
		}

		::System::Boolean get_DtdParserProxy_Namespaces()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_NAMESPACES_OFFSET))(this);
		}

		::System::Boolean get_DtdParserProxy_V1CompatibilityMode()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_V1COMPATIBILITYMODE_OFFSET))(this);
		}

		::System::Uri* get_DtdParserProxy_BaseUri()
		{
			return ((::System::Uri*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_BASEURI_OFFSET))(this);
		}

		::System::Boolean get_DtdParserProxy_IsEof()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_ISEOF_OFFSET))(this);
		}

		::Il2CppArray<::System::Char>* get_DtdParserProxy_ParsingBuffer()
		{
			return ((::Il2CppArray<::System::Char>*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_PARSINGBUFFER_OFFSET))(this);
		}

		::System::Int32 get_DtdParserProxy_ParsingBufferLength()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_PARSINGBUFFERLENGTH_OFFSET))(this);
		}

		::System::Int32 get_DtdParserProxy_CurrentPosition()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_CURRENTPOSITION_OFFSET))(this);
		}

		::System::Void set_DtdParserProxy_CurrentPosition(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_DTDPARSERPROXY_CURRENTPOSITION_OFFSET))(this, a1);
		}

		::System::Int32 get_DtdParserProxy_EntityStackLength()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_ENTITYSTACKLENGTH_OFFSET))(this);
		}

		::System::Boolean get_DtdParserProxy_IsEntityEolNormalized()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_ISENTITYEOLNORMALIZED_OFFSET))(this);
		}

		::System::Xml::IValidationEventHandling* get_DtdParserProxy_ValidationEventHandling()
		{
			return ((::System::Xml::IValidationEventHandling*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_VALIDATIONEVENTHANDLING_OFFSET))(this);
		}

		::System::Void DtdParserProxy_OnNewLine(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_ONNEWLINE_OFFSET))(this, a1);
		}

		::System::Int32 get_DtdParserProxy_LineNo()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_LINENO_OFFSET))(this);
		}

		::System::Int32 get_DtdParserProxy_LineStartPosition()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDPARSERPROXY_LINESTARTPOSITION_OFFSET))(this);
		}

		::System::Int32 DtdParserProxy_ReadData()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_READDATA_OFFSET))(this);
		}

		::System::Int32 DtdParserProxy_ParseNumericCharRef(::System::Text::StringBuilder* a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSENUMERICCHARREF_OFFSET))(this, a1);
		}

		::System::Int32 DtdParserProxy_ParseNamedCharRef(::System::Boolean a1, ::System::Text::StringBuilder* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Boolean, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSENAMEDCHARREF_OFFSET))(this, a1, a2);
		}

		::System::Void DtdParserProxy_ParsePI(::System::Text::StringBuilder* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSEPI_OFFSET))(this, a1);
		}

		::System::Void DtdParserProxy_ParseComment(::System::Text::StringBuilder* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PARSECOMMENT_OFFSET))(this, a1);
		}

		::System::Boolean get_IsResolverNull()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_ISRESOLVERNULL_OFFSET))(this);
		}

		::System::Xml::XmlResolver* GetTempResolver()
		{
			return ((::System::Xml::XmlResolver*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETTEMPRESOLVER_OFFSET))(this);
		}

		::System::Boolean DtdParserProxy_PushEntity(::System::Xml::IDtdEntityInfo* a1, ::System::Int32& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Xml::IDtdEntityInfo*, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PUSHENTITY_OFFSET))(this, a1, a2);
		}

		::System::Boolean DtdParserProxy_PopEntity(::System::Xml::IDtdEntityInfo*& a1, ::System::Int32& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Xml::IDtdEntityInfo*&, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_POPENTITY_OFFSET))(this, a1, a2);
		}

		::System::Boolean DtdParserProxy_PushExternalSubset(::System::String* a1, ::System::String* a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PUSHEXTERNALSUBSET_OFFSET))(this, a1, a2);
		}

		::System::Void DtdParserProxy_PushInternalDtd(::System::String* a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_PUSHINTERNALDTD_OFFSET))(this, a1, a2);
		}

		::System::Void DtdParserProxy_Throw(::System::Exception* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Exception*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_THROW_OFFSET))(this, a1);
		}

		::System::Void DtdParserProxy_OnSystemId(::System::String* a1, ::System::Xml::LineInfo a2, ::System::Xml::LineInfo a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Xml::LineInfo, ::System::Xml::LineInfo))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_ONSYSTEMID_OFFSET))(this, a1, a2, a3);
		}

		::System::Void DtdParserProxy_OnPublicId(::System::String* a1, ::System::Xml::LineInfo a2, ::System::Xml::LineInfo a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Xml::LineInfo, ::System::Xml::LineInfo))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DTDPARSERPROXY_ONPUBLICID_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Throw(::System::Int32 a1, ::System::String* a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Throw_1(::System::Int32 a1, ::System::String* a2, ::Il2CppArray<::System::String*>* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::String*, ::Il2CppArray<::System::String*>*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Throw_2(::System::Int32 a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_2_OFFSET))(this, a1, a2);
		}

		::System::Void Throw_3(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_3_OFFSET))(this, a1);
		}

		::System::Void Throw_4(::System::String* a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_4_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Throw_5(::System::String* a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_5_OFFSET))(this, a1, a2);
		}

		::System::Void Throw_6(::System::String* a1, ::System::String* a2, ::System::Int32 a3, ::System::Int32 a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_6_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void Throw_7(::System::String* a1, ::Il2CppArray<::System::String*>* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::Il2CppArray<::System::String*>*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_7_OFFSET))(this, a1, a2);
		}

		::System::Void Throw_8(::System::String* a1, ::System::String* a2, ::System::Exception* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::Exception*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_8_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Throw_9(::System::String* a1, ::Il2CppArray<::System::String*>* a2, ::System::Exception* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::Il2CppArray<::System::String*>*, ::System::Exception*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_9_OFFSET))(this, a1, a2, a3);
		}

		::System::Void Throw_10(::System::Exception* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Exception*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROW_10_OFFSET))(this, a1);
		}

		::System::Void ReThrow(::System::Exception* a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Exception*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_RETHROW_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ThrowWithoutLineInfo(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWWITHOUTLINEINFO_OFFSET))(this, a1);
		}

		::System::Void ThrowWithoutLineInfo_1(::System::String* a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWWITHOUTLINEINFO_1_OFFSET))(this, a1, a2);
		}

		::System::Void ThrowWithoutLineInfo_2(::System::String* a1, ::Il2CppArray<::System::String*>* a2, ::System::Exception* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::Il2CppArray<::System::String*>*, ::System::Exception*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWWITHOUTLINEINFO_2_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ThrowInvalidChar(::Il2CppArray<::System::Char>* a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::Il2CppArray<::System::Char>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWINVALIDCHAR_OFFSET))(this, a1, a2, a3);
		}

		::System::Void SetErrorState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SETERRORSTATE_OFFSET))(this);
		}

		::System::Void SendValidationEvent(::System::Xml::Schema::XmlSeverityType a1, ::System::String* a2, ::System::String* a3, ::System::Int32 a4, ::System::Int32 a5)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::Schema::XmlSeverityType, ::System::String*, ::System::String*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SENDVALIDATIONEVENT_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Void SendValidationEvent_1(::System::Xml::Schema::XmlSeverityType a1, ::System::Xml::Schema::XmlSchemaException* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::Schema::XmlSeverityType, ::System::Xml::Schema::XmlSchemaException*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SENDVALIDATIONEVENT_1_OFFSET))(this, a1, a2);
		}

		::System::Boolean get_InAttributeValueIterator()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_INATTRIBUTEVALUEITERATOR_OFFSET))(this);
		}

		::System::Void FinishAttributeValueIterator()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHATTRIBUTEVALUEITERATOR_OFFSET))(this);
		}

		::System::Boolean get_DtdValidation()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDVALIDATION_OFFSET))(this);
		}

		::System::Void InitStreamInput(::System::Uri* a1, ::System::IO::Stream* a2, ::System::Text::Encoding* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Uri*, ::System::IO::Stream*, ::System::Text::Encoding*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITSTREAMINPUT_OFFSET))(this, a1, a2, a3);
		}

		::System::Void InitStreamInput_1(::System::Uri* a1, ::System::String* a2, ::System::IO::Stream* a3, ::System::Text::Encoding* a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::Uri*, ::System::String*, ::System::IO::Stream*, ::System::Text::Encoding*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITSTREAMINPUT_1_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Void InitStreamInput_2(::System::Uri* a1, ::System::String* a2, ::System::IO::Stream* a3, ::Il2CppArray<::System::Byte>* a4, ::System::Int32 a5, ::System::Text::Encoding* a6)
		{
			return ((::System::Void(*)(::PVOID, ::System::Uri*, ::System::String*, ::System::IO::Stream*, ::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Text::Encoding*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITSTREAMINPUT_2_OFFSET))(this, a1, a2, a3, a4, a5, a6);
		}

		::System::Void InitTextReaderInput(::System::String* a1, ::System::IO::TextReader* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::IO::TextReader*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITTEXTREADERINPUT_OFFSET))(this, a1, a2);
		}

		::System::Void InitTextReaderInput_1(::System::String* a1, ::System::Uri* a2, ::System::IO::TextReader* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Uri*, ::System::IO::TextReader*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITTEXTREADERINPUT_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Void InitStringInput(::System::String* a1, ::System::Text::Encoding* a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::Text::Encoding*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITSTRINGINPUT_OFFSET))(this, a1, a2, a3);
		}

		::System::Void InitFragmentReader(::System::Xml::XmlNodeType a1, ::System::Xml::XmlParserContext* a2, ::System::Boolean a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlNodeType, ::System::Xml::XmlParserContext*, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INITFRAGMENTREADER_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ProcessDtdFromParserContext(::System::Xml::XmlParserContext* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlParserContext*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PROCESSDTDFROMPARSERCONTEXT_OFFSET))(this, a1);
		}

		::System::Void OpenUrl()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_OPENURL_OFFSET))(this);
		}

		::System::Void OpenUrlDelegate(::System::Object* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Object*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_OPENURLDELEGATE_OFFSET))(this, a1);
		}

		::System::Text::Encoding* DetectEncoding()
		{
			return ((::System::Text::Encoding*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_DETECTENCODING_OFFSET))(this);
		}

		::System::Void SetupEncoding(::System::Text::Encoding* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Text::Encoding*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SETUPENCODING_OFFSET))(this, a1);
		}

		::System::Void SwitchEncoding(::System::Text::Encoding* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Text::Encoding*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SWITCHENCODING_OFFSET))(this, a1);
		}

		::System::Text::Encoding* CheckEncoding(::System::String* a1)
		{
			return ((::System::Text::Encoding*(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_CHECKENCODING_OFFSET))(this, a1);
		}

		::System::Void UnDecodeChars()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_UNDECODECHARS_OFFSET))(this);
		}

		::System::Void SwitchEncodingToUTF8()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SWITCHENCODINGTOUTF8_OFFSET))(this);
		}

		::System::Int32 ReadData()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_READDATA_OFFSET))(this);
		}

		::System::Int32 GetChars(::System::Int32 a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETCHARS_OFFSET))(this, a1);
		}

		::System::Void InvalidCharRecovery(::System::Int32& a1, ::System::Int32& a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INVALIDCHARRECOVERY_OFFSET))(this, a1, a2);
		}

		::System::Void Close_1(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_CLOSE_1_OFFSET))(this, a1);
		}

		::System::Void ShiftBuffer(::System::Int32 a1, ::System::Int32 a2, ::System::Int32 a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SHIFTBUFFER_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean ParseXmlDeclaration(::System::Boolean a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEXMLDECLARATION_OFFSET))(this, a1);
		}

		::System::Boolean ParseDocumentContent()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDOCUMENTCONTENT_OFFSET))(this);
		}

		::System::Boolean ParseElementContent()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEELEMENTCONTENT_OFFSET))(this);
		}

		::System::Void ThrowUnclosedElements()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNCLOSEDELEMENTS_OFFSET))(this);
		}

		::System::Void ParseElement()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEELEMENT_OFFSET))(this);
		}

		::System::Void AddDefaultAttributesAndNormalize()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDDEFAULTATTRIBUTESANDNORMALIZE_OFFSET))(this);
		}

		::System::Void ParseEndElement()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEENDELEMENT_OFFSET))(this);
		}

		::System::Void ThrowTagMismatch(::System::Xml::XmlTextReaderImpl_NodeData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWTAGMISMATCH_OFFSET))(this, a1);
		}

		::System::Void ParseAttributes()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEATTRIBUTES_OFFSET))(this);
		}

		::System::Void ElementNamespaceLookup()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ELEMENTNAMESPACELOOKUP_OFFSET))(this);
		}

		::System::Void AttributeNamespaceLookup()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ATTRIBUTENAMESPACELOOKUP_OFFSET))(this);
		}

		::System::Void AttributeDuplCheck()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ATTRIBUTEDUPLCHECK_OFFSET))(this);
		}

		::System::Void OnDefaultNamespaceDecl(::System::Xml::XmlTextReaderImpl_NodeData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ONDEFAULTNAMESPACEDECL_OFFSET))(this, a1);
		}

		::System::Void OnNamespaceDecl(::System::Xml::XmlTextReaderImpl_NodeData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ONNAMESPACEDECL_OFFSET))(this, a1);
		}

		::System::Void OnXmlReservedAttribute(::System::Xml::XmlTextReaderImpl_NodeData* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ONXMLRESERVEDATTRIBUTE_OFFSET))(this, a1);
		}

		::System::Void ParseAttributeValueSlow(::System::Int32 a1, ::System::Char a2, ::System::Xml::XmlTextReaderImpl_NodeData* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::Char, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEATTRIBUTEVALUESLOW_OFFSET))(this, a1, a2, a3);
		}

		::System::Void AddAttributeChunkToList(::System::Xml::XmlTextReaderImpl_NodeData* a1, ::System::Xml::XmlTextReaderImpl_NodeData* a2, ::System::Xml::XmlTextReaderImpl_NodeData*& a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlTextReaderImpl_NodeData*, ::System::Xml::XmlTextReaderImpl_NodeData*, ::System::Xml::XmlTextReaderImpl_NodeData*&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTECHUNKTOLIST_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean ParseText()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSETEXT_OFFSET))(this);
		}

		::System::Boolean ParseText_1(::System::Int32& a1, ::System::Int32& a2, ::System::Int32& a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32&, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSETEXT_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Void FinishPartialValue()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHPARTIALVALUE_OFFSET))(this);
		}

		::System::Void FinishOtherValueIterator()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHOTHERVALUEITERATOR_OFFSET))(this);
		}

		::System::Void SkipPartialTextValue()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SKIPPARTIALTEXTVALUE_OFFSET))(this);
		}

		::System::Void FinishReadValueChunk()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHREADVALUECHUNK_OFFSET))(this);
		}

		::System::Void FinishReadContentAsBinary()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHREADCONTENTASBINARY_OFFSET))(this);
		}

		::System::Void FinishReadElementContentAsBinary()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHREADELEMENTCONTENTASBINARY_OFFSET))(this);
		}

		::System::Boolean ParseRootLevelWhitespace()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEROOTLEVELWHITESPACE_OFFSET))(this);
		}

		::System::Void ParseEntityReference()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEENTITYREFERENCE_OFFSET))(this);
		}

		::System::Xml::XmlTextReaderImpl_EntityType HandleEntityReference(::System::Boolean a1, ::System::Xml::XmlTextReaderImpl_EntityExpandType a2, ::System::Int32& a3)
		{
			return ((::System::Xml::XmlTextReaderImpl_EntityType(*)(::PVOID, ::System::Boolean, ::System::Xml::XmlTextReaderImpl_EntityExpandType, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_HANDLEENTITYREFERENCE_OFFSET))(this, a1, a2, a3);
		}

		::System::Xml::XmlTextReaderImpl_EntityType HandleGeneralEntityReference(::System::String* a1, ::System::Boolean a2, ::System::Boolean a3, ::System::Int32 a4)
		{
			return ((::System::Xml::XmlTextReaderImpl_EntityType(*)(::PVOID, ::System::String*, ::System::Boolean, ::System::Boolean, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_HANDLEGENERALENTITYREFERENCE_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Boolean get_InEntity()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_INENTITY_OFFSET))(this);
		}

		::System::Boolean HandleEntityEnd(::System::Boolean a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_HANDLEENTITYEND_OFFSET))(this, a1);
		}

		::System::Void SetupEndEntityNodeInContent()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SETUPENDENTITYNODEINCONTENT_OFFSET))(this);
		}

		::System::Void SetupEndEntityNodeInAttribute()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SETUPENDENTITYNODEINATTRIBUTE_OFFSET))(this);
		}

		::System::Boolean ParsePI()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEPI_OFFSET))(this);
		}

		::System::Boolean ParsePI_1(::System::Text::StringBuilder* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEPI_1_OFFSET))(this, a1);
		}

		::System::Boolean ParsePIValue(::System::Int32& a1, ::System::Int32& a2)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEPIVALUE_OFFSET))(this, a1, a2);
		}

		::System::Boolean ParseComment()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSECOMMENT_OFFSET))(this);
		}

		::System::Void ParseCData()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSECDATA_OFFSET))(this);
		}

		::System::Void ParseCDataOrComment(::System::Xml::XmlNodeType a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::XmlNodeType))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSECDATAORCOMMENT_OFFSET))(this, a1);
		}

		::System::Boolean ParseCDataOrComment_1(::System::Xml::XmlNodeType a1, ::System::Int32& a2, ::System::Int32& a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Xml::XmlNodeType, ::System::Int32&, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSECDATAORCOMMENT_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean ParseDoctypeDecl()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDOCTYPEDECL_OFFSET))(this);
		}

		::System::Void ParseDtd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDTD_OFFSET))(this);
		}

		::System::Void SkipDtd()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SKIPDTD_OFFSET))(this);
		}

		::System::Void SkipPublicOrSystemIdLiteral()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SKIPPUBLICORSYSTEMIDLITERAL_OFFSET))(this);
		}

		::System::Void SkipUntil(::System::Char a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Char, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SKIPUNTIL_OFFSET))(this, a1, a2);
		}

		::System::Int32 EatWhitespaces(::System::Text::StringBuilder* a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_EATWHITESPACES_OFFSET))(this, a1);
		}

		::System::Int32 ParseCharRefInline(::System::Int32 a1, ::System::Int32& a2, ::System::Xml::XmlTextReaderImpl_EntityType& a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::System::Int32&, ::System::Xml::XmlTextReaderImpl_EntityType&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSECHARREFINLINE_OFFSET))(this, a1, a2, a3);
		}

		::System::Int32 ParseNumericCharRef(::System::Boolean a1, ::System::Text::StringBuilder* a2, ::System::Xml::XmlTextReaderImpl_EntityType& a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Boolean, ::System::Text::StringBuilder*, ::System::Xml::XmlTextReaderImpl_EntityType&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSENUMERICCHARREF_OFFSET))(this, a1, a2, a3);
		}

		::System::Int32 ParseNumericCharRefInline(::System::Int32 a1, ::System::Boolean a2, ::System::Text::StringBuilder* a3, ::System::Int32& a4, ::System::Xml::XmlTextReaderImpl_EntityType& a5)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::System::Boolean, ::System::Text::StringBuilder*, ::System::Int32&, ::System::Xml::XmlTextReaderImpl_EntityType&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSENUMERICCHARREFINLINE_OFFSET))(this, a1, a2, a3, a4, a5);
		}

		::System::Int32 ParseNamedCharRef(::System::Boolean a1, ::System::Text::StringBuilder* a2)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Boolean, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSENAMEDCHARREF_OFFSET))(this, a1, a2);
		}

		::System::Int32 ParseNamedCharRefInline(::System::Int32 a1, ::System::Boolean a2, ::System::Text::StringBuilder* a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32, ::System::Boolean, ::System::Text::StringBuilder*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSENAMEDCHARREFINLINE_OFFSET))(this, a1, a2, a3);
		}

		::System::Int32 ParseName()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSENAME_OFFSET))(this);
		}

		::System::Int32 ParseQName(::System::Int32& a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEQNAME_OFFSET))(this, a1);
		}

		::System::Int32 ParseQName_1(::System::Boolean a1, ::System::Int32 a2, ::System::Int32& a3)
		{
			return ((::System::Int32(*)(::PVOID, ::System::Boolean, ::System::Int32, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEQNAME_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Boolean ReadDataInName(::System::Int32& a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_READDATAINNAME_OFFSET))(this, a1);
		}

		::System::String* ParseEntityName()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEENTITYNAME_OFFSET))(this);
		}

		::System::Xml::XmlTextReaderImpl_NodeData* AddNode(::System::Int32 a1, ::System::Int32 a2)
		{
			return ((::System::Xml::XmlTextReaderImpl_NodeData*(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDNODE_OFFSET))(this, a1, a2);
		}

		::System::Xml::XmlTextReaderImpl_NodeData* AllocNode(::System::Int32 a1, ::System::Int32 a2)
		{
			return ((::System::Xml::XmlTextReaderImpl_NodeData*(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ALLOCNODE_OFFSET))(this, a1, a2);
		}

		::System::Xml::XmlTextReaderImpl_NodeData* AddAttributeNoChecks(::System::String* a1, ::System::Int32 a2)
		{
			return ((::System::Xml::XmlTextReaderImpl_NodeData*(*)(::PVOID, ::System::String*, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTENOCHECKS_OFFSET))(this, a1, a2);
		}

		::System::Xml::XmlTextReaderImpl_NodeData* AddAttribute(::System::Int32 a1, ::System::Int32 a2)
		{
			return ((::System::Xml::XmlTextReaderImpl_NodeData*(*)(::PVOID, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTE_OFFSET))(this, a1, a2);
		}

		::System::Xml::XmlTextReaderImpl_NodeData* AddAttribute_1(::System::String* a1, ::System::String* a2, ::System::String* a3)
		{
			return ((::System::Xml::XmlTextReaderImpl_NodeData*(*)(::PVOID, ::System::String*, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDATTRIBUTE_1_OFFSET))(this, a1, a2, a3);
		}

		::System::Void PopElementContext()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_POPELEMENTCONTEXT_OFFSET))(this);
		}

		::System::Void OnNewLine(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ONNEWLINE_OFFSET))(this, a1);
		}

		::System::Void OnEof()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ONEOF_OFFSET))(this);
		}

		::System::String* LookupNamespace_1(::System::Xml::XmlTextReaderImpl_NodeData* a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_LOOKUPNAMESPACE_1_OFFSET))(this, a1);
		}

		::System::Void AddNamespace(::System::String* a1, ::System::String* a2, ::System::Xml::XmlTextReaderImpl_NodeData* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::Xml::XmlTextReaderImpl_NodeData*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDNAMESPACE_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ResetAttributes()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_RESETATTRIBUTES_OFFSET))(this);
		}

		::System::Void FullAttributeCleanup()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FULLATTRIBUTECLEANUP_OFFSET))(this);
		}

		::System::Void PushXmlContext()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PUSHXMLCONTEXT_OFFSET))(this);
		}

		::System::Void PopXmlContext()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_POPXMLCONTEXT_OFFSET))(this);
		}

		::System::Xml::XmlNodeType GetWhitespaceType()
		{
			return ((::System::Xml::XmlNodeType(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETWHITESPACETYPE_OFFSET))(this);
		}

		::System::Xml::XmlNodeType GetTextNodeType(::System::Int32 a1)
		{
			return ((::System::Xml::XmlNodeType(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETTEXTNODETYPE_OFFSET))(this, a1);
		}

		::System::Void PushExternalEntityOrSubset(::System::String* a1, ::System::String* a2, ::System::Uri* a3, ::System::String* a4)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*, ::System::Uri*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PUSHEXTERNALENTITYORSUBSET_OFFSET))(this, a1, a2, a3, a4);
		}

		::System::Boolean OpenAndPush(::System::Uri* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Uri*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_OPENANDPUSH_OFFSET))(this, a1);
		}

		::System::Boolean PushExternalEntity(::System::Xml::IDtdEntityInfo* a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Xml::IDtdEntityInfo*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PUSHEXTERNALENTITY_OFFSET))(this, a1);
		}

		::System::Void PushInternalEntity(::System::Xml::IDtdEntityInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::IDtdEntityInfo*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PUSHINTERNALENTITY_OFFSET))(this, a1);
		}

		::System::Void PopEntity()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_POPENTITY_OFFSET))(this);
		}

		::System::Void RegisterEntity(::System::Xml::IDtdEntityInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::IDtdEntityInfo*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_REGISTERENTITY_OFFSET))(this, a1);
		}

		::System::Void UnregisterEntity()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_UNREGISTERENTITY_OFFSET))(this);
		}

		::System::Void PushParsingState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PUSHPARSINGSTATE_OFFSET))(this);
		}

		::System::Void PopParsingState()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_POPPARSINGSTATE_OFFSET))(this);
		}

		::System::Int32 IncrementalRead()
		{
			return ((::System::Int32(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_INCREMENTALREAD_OFFSET))(this);
		}

		::System::Void FinishIncrementalRead()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_FINISHINCREMENTALREAD_OFFSET))(this);
		}

		::System::Boolean ParseFragmentAttribute()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEFRAGMENTATTRIBUTE_OFFSET))(this);
		}

		::System::Boolean ParseAttributeValueChunk()
		{
			return ((::System::Boolean(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEATTRIBUTEVALUECHUNK_OFFSET))(this);
		}

		::System::Void ParseXmlDeclarationFragment()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEXMLDECLARATIONFRAGMENT_OFFSET))(this);
		}

		::System::Void ThrowUnexpectedToken(::System::Int32 a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_OFFSET))(this, a1, a2);
		}

		::System::Void ThrowUnexpectedToken_1(::System::String* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_1_OFFSET))(this, a1);
		}

		::System::Void ThrowUnexpectedToken_2(::System::Int32 a1, ::System::String* a2, ::System::String* a3)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_2_OFFSET))(this, a1, a2, a3);
		}

		::System::Void ThrowUnexpectedToken_3(::System::String* a1, ::System::String* a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::String*, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWUNEXPECTEDTOKEN_3_OFFSET))(this, a1, a2);
		}

		::System::String* ParseUnexpectedToken(::System::Int32 a1)
		{
			return ((::System::String*(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEUNEXPECTEDTOKEN_OFFSET))(this, a1);
		}

		::System::String* ParseUnexpectedToken_1()
		{
			return ((::System::String*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEUNEXPECTEDTOKEN_1_OFFSET))(this);
		}

		::System::Void ThrowExpectingWhitespace(::System::Int32 a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_THROWEXPECTINGWHITESPACE_OFFSET))(this, a1);
		}

		::System::Int32 GetIndexOfAttributeWithoutPrefix(::System::String* a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETINDEXOFATTRIBUTEWITHOUTPREFIX_OFFSET))(this, a1);
		}

		::System::Int32 GetIndexOfAttributeWithPrefix(::System::String* a1)
		{
			return ((::System::Int32(*)(::PVOID, ::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GETINDEXOFATTRIBUTEWITHPREFIX_OFFSET))(this, a1);
		}

		::System::Boolean ZeroEndingStream(::System::Int32 a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ZEROENDINGSTREAM_OFFSET))(this, a1);
		}

		::System::Void ParseDtdFromParserContext()
		{
			return ((::System::Void(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_PARSEDTDFROMPARSERCONTEXT_OFFSET))(this);
		}

		::System::Boolean MoveToNextContentNode(::System::Boolean a1)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_MOVETONEXTCONTENTNODE_OFFSET))(this, a1);
		}

		::System::Xml::IDtdInfo* get_DtdInfo()
		{
			return ((::System::Xml::IDtdInfo*(*)(::PVOID))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_GET_DTDINFO_OFFSET))(this);
		}

		::System::Void SetDtdInfo(::System::Xml::IDtdInfo* a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Xml::IDtdInfo*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SETDTDINFO_OFFSET))(this, a1);
		}

		::System::Void set_XmlValidatingReaderCompatibilityMode(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_XMLVALIDATINGREADERCOMPATIBILITYMODE_OFFSET))(this, a1);
		}

		::System::Boolean AddDefaultAttributeDtd(::System::Xml::IDtdDefaultAttributeInfo* a1, ::System::Boolean a2, ::Il2CppArray<::System::Xml::XmlTextReaderImpl_NodeData*>* a3)
		{
			return ((::System::Boolean(*)(::PVOID, ::System::Xml::IDtdDefaultAttributeInfo*, ::System::Boolean, ::Il2CppArray<::System::Xml::XmlTextReaderImpl_NodeData*>*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDDEFAULTATTRIBUTEDTD_OFFSET))(this, a1, a2, a3);
		}

		::System::Xml::XmlTextReaderImpl_NodeData* AddDefaultAttributeInternal(::System::String* a1, ::System::String* a2, ::System::String* a3, ::System::String* a4, ::System::Int32 a5, ::System::Int32 a6, ::System::Int32 a7, ::System::Int32 a8, ::System::Boolean a9)
		{
			return ((::System::Xml::XmlTextReaderImpl_NodeData*(*)(::PVOID, ::System::String*, ::System::String*, ::System::String*, ::System::String*, ::System::Int32, ::System::Int32, ::System::Int32, ::System::Int32, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_ADDDEFAULTATTRIBUTEINTERNAL_OFFSET))(this, a1, a2, a3, a4, a5, a6, a7, a8, a9);
		}

		::System::Void set_DisableUndeclaredEntityCheck(::System::Boolean a1)
		{
			return ((::System::Void(*)(::PVOID, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_SET_DISABLEUNDECLAREDENTITYCHECK_OFFSET))(this, a1);
		}

		::System::Void RegisterConsumedCharacters(::System::Int64 a1, ::System::Boolean a2)
		{
			return ((::System::Void(*)(::PVOID, ::System::Int64, ::System::Boolean))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_REGISTERCONSUMEDCHARACTERS_OFFSET))(this, a1, a2);
		}

		static ::System::String* StripSpaces(::System::String* a1)
		{
			return ((::System::String*(*)(::System::String*))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_STRIPSPACES_OFFSET))(a1);
		}

		static ::System::Void StripSpaces_1(::Il2CppArray<::System::Char>* a1, ::System::Int32 a2, ::System::Int32& a3)
		{
			return ((::System::Void(*)(::Il2CppArray<::System::Char>*, ::System::Int32, ::System::Int32&))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_STRIPSPACES_1_OFFSET))(a1, a2, a3);
		}

		static ::System::Void BlockCopyChars(::Il2CppArray<::System::Char>* a1, ::System::Int32 a2, ::Il2CppArray<::System::Char>* a3, ::System::Int32 a4, ::System::Int32 a5)
		{
			return ((::System::Void(*)(::Il2CppArray<::System::Char>*, ::System::Int32, ::Il2CppArray<::System::Char>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_BLOCKCOPYCHARS_OFFSET))(a1, a2, a3, a4, a5);
		}

		static ::System::Void BlockCopy(::Il2CppArray<::System::Byte>* a1, ::System::Int32 a2, ::Il2CppArray<::System::Byte>* a3, ::System::Int32 a4, ::System::Int32 a5)
		{
			return ((::System::Void(*)(::Il2CppArray<::System::Byte>*, ::System::Int32, ::Il2CppArray<::System::Byte>*, ::System::Int32, ::System::Int32))((::PBYTE)hIl2Cpp + SYSTEM_XML_XMLTEXTREADERIMPL_BLOCKCOPY_OFFSET))(a1, a2, a3, a4, a5);
		}
	};
}
